### PR TITLE
ENH: Switch to new Slicer logo in module panel

### PR DESCRIPTION
**Pull request by lassoan**
This is a follow-up to https://github.com/Slicer/Slicer/pull/5820 (did not force-push to the same pull request to preserve the content of that branch).

If this pull request is merged then these pull requests can be closed:
- [ ] https://github.com/Slicer/Slicer/pull/5820
- [ ] https://github.com/Slicer/Slicer/pull/5366

---

Switch to the new Slicer logo: it is more compact than the old one and works with both dark and bright background (see #5367).

The logo was moved to the module panel dockable widget's header to save space. See discussion at https://github.com/Slicer/Slicer/pull/5820 for more details.

Welcome module before:

image

Welcome module after:

image

**Available height for module GUI increased by 18%:**

image

**Module panel can be still drag-and-dropped:**

https://user-images.githubusercontent.com/307929/133943218-8ce39c58-cfbe-4f25-a60d-91c22a8f8be8.mp4

---

For **crisp rendering of the new icon**, Qt::AA_UseHighDpiPixmaps application option is now enabled.
If higher-resolution variants of icons are provided by ...@2x.png, ...@3x.png, ... names then they are now used on high-DPI displays.

Before:

image

After:

image

Setting up high-resolution icons on high-DPI screens will come in a follow-up commit (basically we just need to rename our high-resolution icon versions to follow the basename@2x.png, basename@3x.png, ... naming convention).

### CODE REVIEW

**Review by jamesobutler — COMMENTED** [review]
Thanks for looking into the higher quality pixmaps for icons! I was still using the same resolution when replacing images for the new slicer logo as part of #5366. Do you think it will be ok to include the new logo here in the module panel title, but still have the old logo for the app icon? I know it would be great to include the saved space sooner but maybe it should be tied to the transition of the other logo updates?

**Comment by cpinter** [comment]
Thank you @lassoan for implementing this! It looks perfect to me, and a good compromise between branding and space.

**Comment by lassoan** [comment]
> Do you think it will be ok to include the new logo here in the module panel title, but still have the old logo for the app icon? I know it would be great to include the saved space sooner but maybe it should be tied to the transition of the other logo updates?

Makes sense. I'll add your other logo replacement commit to this pull request.

**Comment by lassoan** [comment]
Now all the Slicer logos are updated to the new one:

image

**Review by pieper — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
