### PR TITLE
ENH: adding test of DCMTK private dictionary

### PR DESCRIPTION
**Pull request by fedorov**
See issue 4013 and #299 

Philips phantom DWI dataset is included. The test runs dcmdump command, and looks
for the description of tag (2001,1003), which should be DiffusionBFactor, and can
only be recognized when private dictionary support is enabled in DCMTK.

@jcfr this test succeeds when I run --python-script from the binary install, but not from the build tree.

### CODE REVIEW

**Comment by fedorov** [comment]
The env variable is not set for the built Slicer, only for installed. Do you know what is wrong JC?

**Comment by jcfr** [comment]
@fedorov The variable set in the launcher settings is `DCMDICTHOME`. Should it be changed to `DCMDICTPATH` ?

**Comment by fedorov** [comment]
@jcfr that was wrong indeed. I committed a fix in r24507 = 4e54d1fc0ec7171cf2987bf1daac57c09a65ed92

**Comment by fedorov** [comment]
I rebuilt Slicer with this change, but now for unknown to me reason the test times out. No print statements other than this

```
[fedorov@beat] ctest -VVV -R DCMTK
Test project /Users/fedorov/local/builds/Slicer4-Debug/Slicer-build
    Start 545: py_nomainwindow_DCMTKPrivateDictionaryTest
```

**Comment by jcfr** [comment]
Closing this PR. It is superseded by #327 

@fedorov Let me know if I misunderstood something and if this PR should be re-opened and integrated.

**Comment by fedorov** [comment]
JC, I think this still might make sense to integrate. The test is verifying the private dictionary is enabled. This can get broken if the compile flags are not set correctly, or if there is a regression in DCMTK.

**Comment by jcfr** [comment]
@fedorov Very good point. I just re-open the PR.
Sorry for the noise.

**Comment by jcfr** [comment]
Integrated in [r24521](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24521)

@fedorov I tweaked the commit:
* now using `slicer_add_python_test` passing `SLICER_ARGS`
* also using `print()` function instead of the statement (forward compatible with python 3)
* and finally using exception instead of `exit()` .. otherwise Slicer is not exited cleanly and there are leaks

**Pull request closed without merging**
