### PR TITLE
COMP: Update Qt minimum required version

### PR DESCRIPTION
**Pull request by Connor-Bowley**
Updating to match factory build. This is a minimum recommended
version. Actual minimum usable version be less.

Update to Qt 5.15.0 after consultation with @sjh26 and @jcfr

### CODE REVIEW

**Review by lassoan — DISMISSED** [review]
Looks good to me.

**Comment by jcfr** [comment]
@Connor-Bowley  Well done on your first Slicer pull request :100: 

> nitpick

The contributors are not properly displayed in GitHub:

image


As you can see in https://github.com/Slicer/Slicer/commit/c7dd5c03c20089b992d5db96ddcb6e7cda75ce4c.patch, the email on your development workstation is set to `connor@KRS-7285.kitware.com`, consider setting up your email globally.

Once this is done, you should be able to amend the commit and push force the branch.

. See:
* https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git
* https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github

**Comment by Connor-Bowley** [comment]
@jcfr Thanks for the review. The username/email has been updated. Let me know if there is anything else.

https://github.com/Slicer/Slicer/commit/dfe167682ed687e0b845928bfbb27b2b05895a66.patch

**Comment by jcfr** [comment]
> Update to Qt 5.15.1 instead of Qt 5.15.0

The primary motivation to transition from `5.15.0` to `5.15.1` was to address https://github.com/Slicer/Slicer/issues/5106 discussed in https://discourse.slicer.org/t/dropdown-menus-spawn-on-other-monitor/13003/4. Issue was happening in at least macOS and Windows.

> commit message

Consider updating the message from:

```
COMP: Update Qt minimum required version

Updating to match factory build. This is a minimum recommended
version. Actual minimum usable version be less.
```

to

```
COMP: Update Qt minimum required version from 5.6.0 to 5.15.1

This commit updates the minimum required version to be consistent with the
major and minor Qt versions used on the build machine used to generate the
nightly builds.

To support building against older version of Qt, developer may configuring Slicer
passing the `Slicer_REQUIRED_QT_VERSION` option.

Qt version used on each build machines:

* computron / Qt 5.15.1. See https://github.com/Slicer/DashboardScripts/blob/0c8358850a8f16fb8aa38f921605720134522ac1/computron-slicer_preview_nightly.cmake#L32

* factory-south-macos / Qt 5.15.2. See https://github.com/Slicer/DashboardScripts/blob/0c8358850a8f16fb8aa38f921605720134522ac1/factory-south-macos-slicer_preview_nightly.cmake#L32

* metroplex / Qt 5.15.1: See
  - https://github.com/Slicer/DashboardScripts/blob/0c8358850a8f16fb8aa38f921605720134522ac1/metroplex-slicer_preview_nightly.cmake#L32
  - https://github.com/Slicer/SlicerBuildEnvironment/tree/eb8617d4bcaddda6687b63a9f16c92bce7b64706#supported-build-environments
  - https://github.com/Slicer/SlicerBuildEnvironment/blob/eb8617d4bcaddda6687b63a9f16c92bce7b64706/Docker/qt5-centos7/Dockerfile#L103-L109

* overload /  Qt 5.15.1. See https://github.com/Slicer/DashboardScripts/blob/0c8358850a8f16fb8aa38f921605720134522ac1/overload-vs2019-slicer_preview_nightly.cmake#L34
```

**Comment by jcfr** [comment]
> email

Consider using your work email instead of your personal address in your Git setup.

If you would like to support easy switch between personal/work email, considering this git alias. See https://github.com/jcfr/dotfiles/blob/a325e60558f8e8f7693e70d3dc23f2963a6ed5b4/.gitconfig#L35-L37

**Comment by jcfr** [comment]
> re: documentation

Update the documentation to be more explicit about the new requirement:
* https://github.com/Slicer/Slicer/blob/master/Docs/developer_guide/build_instructions/linux.md
* https://github.com/Slicer/Slicer/blob/master/Docs/developer_guide/build_instructions/macos.md
* https://github.com/Slicer/Slicer/blob/master/Docs/developer_guide/build_instructions/windows.md

**Review by jcfr — CHANGES_REQUESTED** [review]
See comments above.

**Comment by Connor-Bowley** [comment]
Updated commit message, author email to kitware email, and build instructions on all 3 platforms.

https://github.com/Slicer/Slicer/commit/3254799254fbc1102fd734944b861048807aa0b2.patch

**Comment by jcfr** [comment]
Thanks :pray: 

> https://github.com/Slicer/Slicer/commit/3254799254fbc1102fd734944b861048807aa0b2.patch

Moving forward, there is no need to explicitly reference the patch as it is available in the history:

image

**Comment by jcfr** [comment]
> last comment regarding your name

Should it be `Connor Bowley` instead of `Connor-Bowley` ?

**Comment by Connor-Bowley** [comment]
Yes, I had changed it to my github username for some reason, not sure why.

**Review by jcfr — APPROVED** [review]

**Comment by sjh26** [comment]
🎆

**Pull request merged**
