### PR TITLE
BUG: Update CTK to workaround slicer rendering issue when built against VTK9

### PR DESCRIPTION
**Pull request by jcfr**
Waiting issue Slicer/Slicer#5220 is resolved, accept that other actors
like corner annotations and crosshairs are occluded and ensure image
data is displayed.

List of changes:

```
$ git shortlog 03bf84789..2f164d767 --no-merges
Jean-Christophe Fillion-Robin (2):
      COMP: Fix build of CTKVisualizationVTK tests against VTK9
      BUG: Workaround slice viewer rendering issue when built against VTK9

Tobias Krähling (3):
      STYLE: Update CTKVisualizationVTK test requirements to be more specific
      BUG: Fix CTKVisualizationVTKWidgets tests updating QSurfaceFormat initialization
      ENH: Re-factor code centralizing setting of default surface format
```

### CODE REVIEW

**Comment by lassoan** [comment]
Do segmentations and markups show up above the image?

**Comment by jcfr** [comment]
> Do segmentations and markups show up above the image?

Sadly ... they do not.

**Comment by jcfr** [comment]
Let's wait for @sankhesh to address the issue as this workaround will not really improve things.

**Comment by adamrankin** [comment]
Just in case it matters, being able to see the slice would improve things for me. I don't need those features, but I do need to see the slice.

**Pull request closed without merging**
