### PR TITLE
COMP: add QtMultimedia Python wrapper from CTK

### PR DESCRIPTION
**Pull request by atracsys-sbt**
(This PR originates from [this discussion](https://github.com/Slicer/Slicer/pull/5909))

Support for the QtMultimedia component has been recently [added to CTK](https://github.com/commontk/CTK/pull/992).
This PR simply forward this support to Slicer.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution :pray: 

I will integrate after testing locally.

### Notes for integration

Squash and merge using this commit message:

```
ENH: Update CTK to include QtMultimedia Python wrappers

List of CTK changes:

$ git shortlog 34a390a4..ec9fcee5 --no-merges 
Sylvain Bernhardt (1):
      ENH: Add Python wrapping for Qt multimedia component (PR-992)

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
```

**Review by lassoan — APPROVED** [review]
I've tested this and it works perfectly.

This plays a sound:

```
effect = qt.QSoundEffect()
effect.setSource(qt.QUrl.fromLocalFile(r"c:\Windows\Media\chord.wav"))
effect.setLoopCount(qt.QSoundEffect.Infinite)
effect.setVolume(0.25)
effect.play()
```

**Comment by lassoan** [comment]
This is now merged. The way you figured out what's going on and fixed up everything in multiple upstream libraries were outstanding. Thank you very much for your contribution.

**Comment by atracsys-sbt** [comment]
> 
> 
> I've tested this and it works perfectly.
> 
> This plays a sound:
> 
> ```
> effect = qt.QSoundEffect()
> effect.setSource(qt.QUrl.fromLocalFile(r"c:\Windows\Media\chord.wav"))
> effect.setLoopCount(qt.QSoundEffect.Infinite)
> effect.setVolume(0.25)
> effect.play()
> ```

One can also use QSound:
```
sound = qt.QSound(r"C:\Windows\Media\chord.wav")
sound.play()
```

**Comment by lassoan** [comment]
Unfortunately, this change cause Slicer to fail to start:

image

To avoid rushing investigation and fix of this problem, I'll revert the commit and whenever the fix is ready we can merge the fixed version.

@atracsys-sbt Do you have time to investigate this issue?

**Comment by lassoan** [comment]
Reverted in https://github.com/Slicer/Slicer/commit/bd6021edf5414aaacb3b5d25a43b47e5b8443268

**Comment by jcfr** [comment]
For convenience, set of changes have been pushed in a new pull request: https://github.com/Slicer/Slicer/pull/5931

I will post additional commits in the PR to fix the problem.

**Comment by atracsys-sbt** [comment]
> 
> 
> Unfortunately, this change cause Slicer to fail to start:
> 
> image
> 
> To avoid rushing investigation and fix of this problem, I'll revert the commit and whenever the fix is ready we can merge the fixed version.
> 
> @atracsys-sbt Do you have time to investigate this issue?

That's odd... I installed the preview from yesterday and did not face this issue.
I don't have much time to try and debug this in the short term, but I will definitely try soon.

**Comment by jcfr** [comment]
> I installed the preview from yesterday and did not face this issue.

I am wondering if you have the Qt libraries in your PATH ? If yes, the issue wouldn't happen for you.

**Pull request merged**
