### PR TITLE
Update OpenSSL from 1.0.2n  to 1.1.1g

### PR DESCRIPTION
**Pull request by hjmjohnson**
Related to #4859 Tested on Ubuntu 18.04 Linux with Qt 5.15.0, and both debug and release builds work now, where previously they segfaulted almost immediately.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution :pray: 

Before we can integrate, few related tasks:

* [ ] Check that downloading sample data works. I anticipate this will help confirm that Python 3.6 works with the updated OpenSSL. 
* [ ] Generate binary archives for windows https://github.com/Slicer/Slicer-OpenSSL

**Comment by hjmjohnson** [comment]
@jcfr I did download sample data, and it worked smoothly. 

I can not make the windows openSSL (limited windows experience/access).

**Comment by jcfr** [comment]
> I did download sample data, and it worked smoothly.

Thanks for checking :+1: 

> make the windows openSSL 

I will take care of it.

**Comment by jcfr** [comment]
The project https://github.com/Slicer/Slicer-OpenSSL has been updated to support building OpenSSL >= 1.1.0 and binary archives have been uploaded at https://github.com/Slicer/Slicer-OpenSSL/releases/tag/1.1.1g

Since the library names have been updated, we will have to update the external  project and install rules.

**Comment by jcfr** [comment]
Update of curl is being integrated in its own pull request: https://github.com/Slicer/Slicer/pull/4997

**Comment by jcfr** [comment]
On windows, need to address this:

```
CMake Error at SuperBuild/External_OpenSSL.cmake:300 (message):
  There is no pre-compiled version of OpenSSL 1.1.1g available for

  this version of visual studio [1924].  You could either:

   (1) disable SSL support configuring with option Slicer_USE_PYTHONQT_WITH_OPENSSL:BOOL=OFF
   or
   (2) configure Slicer providing your own version of OpenSSL that matches the version
       of OpenSSL also used to compile Qt library.
       The options to specify are OPENSSL_INCLUDE_DIR, LIB_EAY_DEBUG, LIB_EAY_RELEASE,
       SSL_EAY_DEBUG and SSL_EAY_RELEASE.
Call Stack (most recent call first):
  CMake/ExternalProjectDependency.cmake:842 (include)
  SuperBuild/External_curl.cmake:15 (ExternalProject_Include_Dependencies)
  CMake/ExternalProjectDependency.cmake:842 (include)
  CMake/ExternalProjectDependency.cmake:916 (ExternalProject_Include_Dependencies)
  SuperBuild.cmake:489 (ExternalProject_Include_Dependencies)
  CMakeLists.txt:687 (include)
```

**Comment by jcfr** [comment]
On macOS, need to address this:

```
ar: creating archive test/libtestutil.a
Undefined symbols for architecture x86_64:
  "_slicer_zlib_deflate", referenced from:
      _zlib_stateful_compress_block in c_zlib.o
      _bio_zlib_write in c_zlib.o
      _bio_zlib_ctrl in c_zlib.o
  "_slicer_zlib_deflateEnd", referenced from:
      _zlib_stateful_finish in c_zlib.o
      _bio_zlib_free in c_zlib.o
  "_slicer_zlib_deflateInit_", referenced from:
      _zlib_stateful_init in c_zlib.o
      _bio_zlib_write in c_zlib.o
  "_slicer_zlib_inflate", referenced from:
      _zlib_stateful_expand_block in c_zlib.o
      _bio_zlib_read in c_zlib.o
  "_slicer_zlib_inflateEnd", referenced from:
      _zlib_stateful_finish in c_zlib.o
      _bio_zlib_free in c_zlib.o
  "_slicer_zlib_inflateInit_", referenced from:
      _zlib_stateful_init in c_zlib.o
      _bio_zlib_read in c_zlib.o
  "_slicer_zlib_zError", referenced from:
      _bio_zlib_write in c_zlib.o
      _bio_zlib_read in c_zlib.o
      _bio_zlib_ctrl in c_zlib.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by jcfr** [comment]
re: window install

It failed with the following error:

```
 CMake Error at D:/T/S-b/Slicer-build/CMake/LastConfigureStep/cmake_install.cmake:375 (file):
    file INSTALL cannot find "D:/T/S-b/OpenSSL-install/Release/bin/libssl.dll":
    File exists.
  Call Stack (most recent call first):
    D:/T/S-b/Slicer-build/cmake_install.cmake:59 (include)


  CMake Error at D:/T/S-b/Slicer-build/CMake/LastConfigureStep/cmake_install.cmake:379 (file):
    file INSTALL cannot find
    "D:/T/S-b/OpenSSL-install/Release/bin/libcrypto.dll": File exists.
  Call Stack (most recent call first):
    D:/T/S-b/Slicer-build/cmake_install.cmake:59 (include)
```

**Comment by jcfr** [comment]
> re: windows packaging failure

Fixed

> re: macOS failure

I submitted a fix in the upstream project as https://github.com/openssl/openssl/pull/12238

In the meantime, I will implement a workaround in our buildsystem

**Comment by jcfr** [comment]
* @jcfr:
  * overload (Windows 10, VS2019): build :heavy_check_mark:  packaging :heavy_check_mark: test: some failure



### overload (Windows 10, VS2019)

```
Test project D:/T/S-b/Slicer-build
      Start 275: qSlicerSslTest
 1/10 Test #275: qSlicerSslTest ...................................   Passed    0.46 sec
      Start 412: qSlicerSequencesModuleWidgetGenericTest
 2/10 Test #412: qSlicerSequencesModuleWidgetGenericTest ..........   Passed    2.97 sec
      Start 464: py_nomainwindow_qSlicerEditorModuleGenericTest
 3/10 Test #464: py_nomainwindow_qSlicerEditorModuleGenericTest ...***Failed    4.43 sec
      Start 465: py_ThresholdThreadingTest
 4/10 Test #465: py_ThresholdThreadingTest ........................***Failed    7.59 sec
      Start 466: py_StandaloneEditorWidgetTest
 5/10 Test #466: py_StandaloneEditorWidgetTest ....................***Failed   17.60 sec
      Start 627: py_nomainwindow_test_slicer_environment
 6/10 Test #627: py_nomainwindow_test_slicer_environment ..........***Failed    2.65 sec
      Start 630: py_SlicerSslTest
 7/10 Test #630: py_SlicerSslTest .................................   Passed    2.72 sec
      Start 631: py_PythonSslTest
 8/10 Test #631: py_PythonSslTest .................................   Passed    0.30 sec
      Start 646: py_WebEngine
 9/10 Test #646: py_WebEngine .....................................***Failed    7.07 sec
      Start 675: py_SurfaceToolbox
10/10 Test #675: py_SurfaceToolbox ................................***Failed   10.59 sec

40% tests passed, 6 tests failed out of 10

Label Time Summary:
qSlicerBaseQTCore         =   0.46 sec*proc (1 test)
qSlicerSequencesModule    =   2.97 sec*proc (1 test)

Total Test time (real) =  56.80 sec

The following tests FAILED:
        464 - py_nomainwindow_qSlicerEditorModuleGenericTest (Failed)
        465 - py_ThresholdThreadingTest (Failed)
        466 - py_StandaloneEditorWidgetTest (Failed)
        627 - py_nomainwindow_test_slicer_environment (Failed)
        646 - py_WebEngine (Failed)
        675 - py_SurfaceToolbox (Failed)
Errors while running CTest
```

**Comment by Leengit** [comment]
Building (detached) branch upstream/4859-fix-linux-crash (c666ad29d) with Qt-5.12.9 or Qt-5.15.0 on an Ubuntu 20.04 (focal) Linux system I get:

> /home/lee.newberg/git/Slicer-SuperBuild-Debug-5.12.9/curl/lib/warnless.c: At top level:
> cc1: warning: unrecognized command line option ‘-Wno-pedantic-ms-format’

**Comment by jcfr** [comment]
> re: https://github.com/Slicer/Slicer/pull/4992#issuecomment-648302425 (curl build on Ubuntu 20.04)

This is independent of this PR, it is now tracked in https://github.com/Slicer/Slicer/issues/5005

**Comment by jcfr** [comment]
macOS packaging failed reporting error like these:

```
[...]
libs_path=
  <Slicer_SUPERBUILD_DIR>/VTK-build/lib
  <Slicer_SUPERBUILD_DIR>/ITK-build/lib
  <Slicer_SUPERBUILD_DIR>/teem-build/bin
  <Slicer_SUPERBUILD_DIR>/CTK-build/CTK-build/bin
  <Slicer_SUPERBUILD_DIR>/SlicerExecutionModel-build/GenerateCLP/bin
  <Slicer_SUPERBUILD_DIR>/LibArchive-install/lib
  <Slicer_SUPERBUILD_DIR>/python-install/lib
  <Slicer_SUPERBUILD_DIR>/OpenSSL
  <Slicer_SUPERBUILD_DIR>/DCMTK-build/lib
  <Slicer_SUPERBUILD_DIR>/Slicer-build/bin
  <Slicer_SUPERBUILD_DIR>/Slicer-build/lib/Slicer-4.11
  <Slicer_SUPERBUILD_DIR>/Slicer-build/lib/Slicer-4.11/qt-loadable-modules
  <Slicer_SUPERBUILD_DIR>/Slicer-build/lib/Slicer-4.11/cli-modules
  <Slicer_SUPERBUILD_DIR>/Slicer-build/bin/designer
  <Slicer_SUPERBUILD_DIR>/Slicer-build/bin/iconengines
  <Slicer_SUPERBUILD_DIR>/Slicer-build/bin/styles
[...]
1 - fixing item /Volumes/D/T/S-b/Slicer-build/_CPack_Packages/macosx-amd64/DragNDrop/Slicer-4.11.0-2020-06-23-macosx-amd64/Slicer.app/Contents/lib/Python/lib/python3.6/lib-dynload/_hashlib.so with @rpath/
lib/Python/lib/python3.6/lib-dynload
warning: target '/Volumes/D/T/S-b/OpenSSL/lib/libcrypto.1.1.dylib' does not exist...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Volumes/D/T/S-b/OpenSSL/lib/libcrypto.1.1.dylib': No such file or directory
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Volumes/D/T/S-b/OpenSSL/lib/libcrypto.1.1.dylib': No such file or directory
warning: target '/Volumes/D/T/S-b/OpenSSL/lib/libssl.1.1.dylib' does not exist...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Volumes/D/T/S-b/OpenSSL/lib/libssl.1.1.dylib': No such file or directory
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Volumes/D/T/S-b/OpenSSL/lib/libssl.1.1.dylib': No such file or directory
2 - fixing item /Volumes/D/T/S-b/OpenSSL/lib/libcrypto.1.1.dylib with @rpath/lib/Slicer-4.11
3 - fixing item /Volumes/D/T/S-b/OpenSSL/lib/libssl.1.1.dylib with @rpath/lib/Slicer-4.11
4 - fixing item /Volumes/D/T/S-b/Slicer-build/_CPack_Packages/macosx-amd64/DragNDrop/Slicer-4.11.0-2020-06-23-macosx-amd64/Slicer.app/Contents/lib/Python/lib/python3.6/lib-dynload/_ssl.so with @rpath/lib/Python/lib/python3.6/lib-dynload
[...]
```

**Comment by jcfr** [comment]
We need to either revert https://github.com/Slicer/Slicer/pull/4992/commits/7a93b87aae68d716829c474e3885cb3f11727f23 or find a way to configure the lib directory

**Comment by jcfr** [comment]
It looks like passing the `--libdir` option doesn't have the intended effect
See https://github.com/openssl/openssl/blob/master/INSTALL.md#libdir

Headed on a :running_man: , will have an other look later ...

**Comment by RafaelPalomar** [comment]
> Related to #4859 Tested on Ubuntu 18.04 Linux with Qt 5.15.0, and both debug and release builds work now, where previously they segfaulted almost immediately.

I think the same happened pretty much in any modern Linux distribution. All I could trace pointed to the problem being the discrepancy between the pre-isntalled OpenSSL (>=1.1 for the most) and the version OpenSSL version coming with Slicer.

I'm glad this PR is on its way. I'll check it on my Linux setup and give feedback.

**Comment by RafaelPalomar** [comment]
I have just built 3D Slicer based on this PR and I confirm that I no longer get the crashes at startup.

Some more info on my build:

- Gentoo Linux (kernel 5.4.38)
- qt-core-5.14.2
- openssl-1.1.1g
- gcc-9.3.0

**Comment by jcfr** [comment]
>  have just built 3D Slicer based on this PR and I confirm that I no longer get the crashes at startup.

@RafaelPalomar Thanks for the update :pray: 

> It looks like passing the --libdir option doesn't have the intended effect

I was able to address this issue by passing `--libdir=${EP_SOURCE_DIR}` instead of `--libdir=`, macOS packaging issue should be fixed.

**Pull request merged**
