### PR TITLE
Legacy code is disabled for ITK, in preparation for version 5.0

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
It looks like yesterday's merge of [ITK update](https://github.com/Slicer/Slicer/pull/1013) introduced no new problems. Dashboard [yesterday](http://slicer.cdash.org/index.php?project=SlicerPreview&date=2018-09-10) and [today](http://slicer.cdash.org/index.php?project=SlicerPreview&date=2018-09-11). Can this be merged too?

**Comment by pieper** [comment]
@dzenanz did you see any regressions in extensions?  On the dev hangout earlier we saw ITK errors in an extension but we weren't sure if they were new.

**Comment by jcfr** [comment]
Thanks for checking, I will merge now.

**Comment by jcfr** [comment]
Before, I am doing a grep in all extension to see if `BSplineTransformType::ParametersType` is used anywhere

**Comment by jcfr** [comment]
Before we integrate, would it be possible to submit a PR to the following extensions:

* [ ] ABC
```
ABC/Engine/register/PairRegistrationMethod.txx
922:  typedef BSplineTransformType::ParametersType ParametersType;
1232:  BSplineTransformType::ParametersType p(numParams);
1291:  BSplineTransformType::ParametersType p = btrafo->GetParameters();
```

* [ ] DTIPrep
```
DTIPrep/src/itkMultiImageRegistrationFilter.cxx
233:  typedef BSplineTransformType::ParametersType BSplineParametersType;

```

* [ ] elastix 
  * https://github.com/SuperElastix/elastix
  * https://github.com/lassoan/SlicerElastix/blob/7d3deb3985d63344eb501892ae04a05e8bbbd253/SuperBuild/External_elastix.cmake#L34-L35
  * [search](https://github.com/SuperElastix/elastix/search?q=BSplineTransformType%3A%3AParametersType&unscoped_q=BSplineTransformType%3A%3AParametersType)
```
SlicerElastix-build/elastix/src/Testing/itkGPUResampleImageFilterTest.cxx
246:  typename BSplineTransformType::ParametersType & parameters,
383:  std::vector< typename BSplineTransformType::ParametersType > & bsplineParameters,
477:      typename BSplineTransformType::ParametersType parameters;
505:      typename AdvancedBSplineTransformType::ParametersType parameters;
824:  typedef BSplineTransformType::ParametersType BSplineParametersType;
```

**Comment by jcfr** [comment]
In the interest of time, I will merge the change but the deal is that we update these extensions asap :smile:

**Comment by jcfr** [comment]
Change integrated in [r27404](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27404).

Let's close this pull request after the extensions are updated.

**Comment by dzenanz** [comment]
I make a [PR](https://github.com/NIRALUser/DTIPrep/pull/55) for DTIPrep. Is that the right repository?

**Comment by jcfr** [comment]
Thanks :+1: 

Looking at the list of extension available [here](https://github.com/Slicer/ExtensionsIndex/), this is indeed the [correct](https://github.com/Slicer/ExtensionsIndex/blob/f10981214ed95d3c1e5bbf6818202cdef44b5baf/DTIPrep.s4ext#L9) repo.

**Comment by dzenanz** [comment]
PR for ABC is [here](https://github.com/NIRALUser/ABC/pull/1). I am even less sure about this being the right repository.

**Comment by dzenanz** [comment]
Elastix master builds with legacy OFF. No changes are needed.

**Comment by jcfr** [comment]
Thanks @dzenanz :+1: , since change for all impacted extensions have been proposed I am now closing this.

**Pull request closed without merging**
