### PR TITLE
ENH: Import vtkSegmentationCore to python by default. WIP

### PR DESCRIPTION
**Pull request by cpinter**
Attempt to implicitly import vtkSegmentationCorePython, based on what was in the code for vtkAddon. Unfortunately it does not work, so I'd appreciate any help. Thanks!

### CODE REVIEW

**Comment by cpinter** [comment]
To test whether importing implicitly was successful:
`segNode = slicer.vtkMRMLSegmentationNode()
slicer.mrmlScene.AddNode(segNode)
segNode.GetSegmentation()`

If the output is similar to this
`(vtkCommonCorePython.vtkObject)0000017BA6862EE8`
then it was unsuccessful. If it is like this
`(vtkCommonCorePython.vtkMRMLSegmentationNode)000002215A36E0A8`
then it was successful.

**Comment by cpinter** [comment]
@jcfr @pieper Do you know what's missing from this so that vtkSegmentationCorePython is imported when Slicer is started? Thanks!

**Comment by jcfr** [comment]
@cpinter Does it work when building against Qt5 + VTK8 ? 

Is yes, this it is related to VTK hierarchy files .. that became mandatory in VTK8 and not enable in the current build to avoid breaking anything.

Or you could remove the condition in `vtkMacroKitPythonWrap.cmake` and try with your current build .. 

See https://github.com/Slicer/Slicer/blob/ac3a3faba26e9536ce58a5832d5bf67cabf2d93a/CMake/vtkMacroKitPythonWrap.cmake#L112-L130

**Comment by cpinter** [comment]
@jcfr I haven't tried with Qt5 or VTK8, I just changed the current master.

Thanks, I'll try what you suggest. Although I don't understand how vtkAddon and the others work, as what you pointed to is not specific to any of these libraries. What makes vtkSegmentationCore different to vtkAddon?

**Comment by ihnorton** [comment]
@cpinter were you testing this on Windows? I just tried this PR (rebased to current trunk), and it seems to work correctly on Mac/Qt4/VTK7. If so, maybe that helps narrow down the issue...

```
>>> segNode = slicer.vtkMRMLSegmentationNode()
>>> slicer.mrmlScene.AddNode(segNode)
(vtkCommonCorePython.vtkMRMLSegmentationNode)0x14b257db8
>>> segNode.GetSegmentation()
(vtkCommonCorePython.vtkSegmentation)0x14b257ef0
>>> 
```

**Comment by lassoan** [comment]
I've found the missing piece, it works now on Windows as well.

https://github.com/Slicer/Slicer/commit/02f0812df1615de427aef5267d0d36a954aa7c28

**Comment by jcfr** [comment]
👍

**Comment by cpinter** [comment]
Thanks a lot to you both! I'll integrate this tomorrow or Friday if there are no objections.

**Comment by cpinter** [comment]
Oh I just see @lassoan integrated it. Thanks!

**Pull request closed without merging**
