### PR TITLE
ENH: Add "--hide-application-information" option

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @Slicer/slicer-core

**Comment by naucoin** [comment]
I'd suggest using information singular in all cases.

**Comment by jcfr** [comment]
> information rather than informations in all cases

Thanks for the review, I just updated the option to be `--hide-application-information`. Let me know if that is what you were thinking.

Later today, I will also add a test.

**Comment by lassoan** [comment]
Operating system, 32/64 bit, RAM, etc. information is essential for any kind of problem investigation, so it should always be written to the log file. On the other hand, this information is probably doesn't need to be printed on the console at all.

So, I would change the behavior to always write to file, don't write to console by default, and maybe add a switch to enable writing it to console.

I think the switch is not needed: we may just disable writing of system info on the console permanently. Writing it to the console is not really needed because although it may be useful for automatic tests, system information may be obtained by adding a test that specifically prints this info. It would simplify things if we didn't add yet another startup switch.

**Comment by naucoin** [comment]
@jcfr yes, that's what I meant, thanks.

**Comment by lassoan** [comment]
OK. Then the name of the switch should be --show-application-information (as the option is disabled by default).

**Comment by jcfr** [comment]
Thanks for the comments.

Updated behavior (logged to file but not to console), along with new option `--application-info` and tests have been integrated in [25149](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25149)

**Pull request closed without merging**
