### PR TITLE
ENH: Adding vtkMatrix4x4 to/from string methods to vtkAddonMathUtilities.

### PR DESCRIPTION
**Pull request by mholden8**
This pull request supersedes the pull request: #546.
Background on this issue at: SlicerRt/Sequences#16 (comment).
Factored out parallel implementation in the Transforms module's widget.

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks Matthew. There are build errors - see circleci report above.

**Comment by lassoan** [comment]
@jcfr CircleCI reported no errors - does it mean that Slicer compiled successfully (build log at https://circleci.com/gh/Slicer/Slicer/270 seem to be incomplete)?
Does CircleCI reportstest failures as errors?

**Comment by jcfr** [comment]
>  it mean that Slicer compiled successfully

Yes.

> seem to be incomplete

If  you expand the `$ docker run -e "BUILD_TOOL_FLAGS=-j5" --name slicer -v ~/Slicer:/usr/src/Slicer slicer/slicer-build-deps` section and download the full log .. you can confirm there are no error:

```

build/EMSegment/Testing/TestData -DDST=/usr/src/Slicer-build/Slicer-build/share/Slicer-4.5/qt-loadable-modules/EMSegment/Testing -P /usr/src/Slicer-build/EMSegment/CMake/EM_InstallTasksSubScript.cmake
[4/5] cd /usr/src/Slicer-build/Slicer-build/Modules/Remote/EMSegment && /usr/bin/cmake -DSRC=/usr/src/Slicer-build/EMSegment/Tcl -DDST=/usr/src/Slicer-build/Slicer-build/share/Slicer-4.5/qt-loadable-modules/EMSegment/ -P /usr/src/Slicer-build/EMSegment/CMake/EM_InstallTasksSubScript.cmake
-- Found Git: /usr/bin/git  
-- Configuring Slicer version [4.5.0-2016-07-22]
-- Configuring Slicer revision [4bf7757]
[5/5] Run CPack packaging tool...
CPack: Create package using TGZ
CPack: Install projects
CPack: - Install project: CTK
CPack: - Install project: CTK
CPack: - Install project: VTK
CPack: - Install project: ITK
CPack: - Install project: ITK
CPack: - Install project: ITK
CPack: - Install project: ITK
CPack: - Install project: ITK
CPack: - Install project: SlicerExecutionModel
CPack: - Install project: teem
CPack: - Install project: igtl
CPack: - Install project: CTK
CPack: - Install project: Slicer
CPack: - Install project: Slicer
CPack: - Install project: Slicer
CPack: Create package
CPack: - package: /usr/src/Slicer-build/Slicer-build/Slicer-4.5.0-2016-07-22-linux-amd64.tar.gz generated.
```

> Does CircleCI reports test failures as errors?

No. for now it only try to build and package

More details here: https://github.com/thewtex/SlicerDocker

**Comment by lassoan** [comment]
@jcfr Thanks for the info.

As build&test was successful on Windows and build was successful on Linux, I'll integrate this.

**Comment by lassoan** [comment]
@mholden8 I have these test failures:


7/647 Testing: vtkAddonMathUtilitiesTest1
7/647 Test: vtkAddonMathUtilitiesTest1
Command: "C:/D/S4R/Slicer-build/Slicer.exe" "--launcher-no-splash" "--launch" "C:/D/S4R/Slicer-build/bin/Release/vtkAddonCxxTests.exe" "vtkAddonMathUtilitiesTest1"
Directory: C:/D/S4R/Slicer-build/Libs/vtkAddon/Testing
"vtkAddonMathUtilitiesTest1" start time: Jul 22 14:41 Eastern Daylight Time
Output:
----------------------------------------------------------
vtkDebugLeaks has found no leaks.

Line 201 - resMat->GetElement(ii, jj) != mat->GetElement(ii, jj) : CheckDouble failed
	current :0
	expected:2

Line 51 - FromString_Test() != EXIT_SUCCESS : CheckInt failed
	current :1
	expected:0
<end of output>
Test time =   0.15 sec

**Comment by jcfr** [comment]
Great. Let s make sure to squash/reorganize the commits beforehand.

Thanks
Jc

**Comment by mholden8** [comment]
Thanks for verifying the tests. It looks like I inadvertently introduced these errors when switching to use ```vtksys::RegularExpression``` instead of ```std::regex```. I've fixed the issues, and the tests now pass on my machine.

@lassoan I elected to use strtod instead of stringstreams because it is significantly faster (almost two times) on my machine. I think this will be beneficial when reading long sequence metafiles, for example.

**Comment by lassoan** [comment]
Integrated into SVN rev 25246.

Thanks for all your work @mholden8 and @jcfr for the reviews.

**Pull request closed without merging**
