### PR TITLE
Fix support for installing extensions from file 

### PR DESCRIPTION
**Pull request by sobiny**
Fixes a regression introduced in e2ea8afa6 (BUG: Ensure extensions installed using "Girder_v1" serverAPI are enabled)

_Original  issue title and description edited by @jcfr_

### CODE REVIEW

**Comment by jamesobutler** [comment]
@jcfr can you take a look here? This PR by @sobiny is trying to address #5840 (also tracked as #5848)

**Comment by jcfr** [comment]
@sobiny Could you update the settings of your github profile adding your email ?

For more details, see https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github

That way, your contribution will be properly acknowledged.

Currently, it is not recognized:

image

**Comment by sobiny** [comment]
> 谢谢你🙏💯的贡献
> 
> @sobiny您能否更新添加电子邮件的 github 配置文件的设置？
> 
> 有关详细信息，请参[阅 https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github)
> 
> 这样，你的贡献将得到适当的承认。
> 
> 目前，它不被承认：
> 
> image

I have set it up, can you use it now?
This is a good start. I will submit to "slicer" if I encounter problems in the future, thank you

**Comment by jcfr** [comment]
Thanks for updating your settings.

>  can you use it now?

Indeed,  as  you can see your contribution is recognized:

image

**Comment by sobiny** [comment]
@jamesobutler thank you。a happy day。

**Pull request merged**
