### PR TITLE
ENH: New class DICOMStoreSCPProcess inherited from DICOMProcess:

### PR DESCRIPTION
**Pull request by che85**
- DICOMListener now inherited from DICOMStoreSCPProcess since DICOMListener is depends on storescp
- improved error handling and feedback for user

for reference see: http://slicer-devel.65872.n3.nabble.com/DICOMListener-with-optional-Indexing-td4036422.html

### CODE REVIEW

**Comment by pieper** [comment]
Looks good to me.

I know these are hard to thoroughly test because of the dependencies on other systems, but were you able to confirm that you can use storescu to put files into the database with this changed version of the code?

**Comment by che85** [comment]
Yes, I tested sending to the port and it was indexed into the dicom database

**Comment by jcfr** [comment]
Thanks for the patch.

If there is consensus. LGTM

Nitpicks: to facilitate review, you could even split 5533337 in two commits.

**Comment by lassoan** [comment]
Looks good in general. The class should be used carefully, as when you request to stop a store process, actually all of them are killed. It would be nice to store the pid when the process is started and kill the process corresponding to that pid (not needed in this pull request).

**Comment by che85** [comment]
Well, what I was thinking is, what if the DICOMListener has to get started and there is a other storescp process already running (maybe on another port) then the user is prompted with the question if running processes should be termintated. Clicking yes results in killing all storescp processes. 

It should better be checked if a storescp process is running that uses the same port as the DICOMListener uses and then specifically kills this process. 

Storescp processes that are listening to other ports should not stop DICOMListener from getting started.

**Comment by lassoan** [comment]
We shouldkill those processes that we started. In addition to that it could be nice to search for processes that listening on the port that we want to use to take care of processes that are hanging around due to any reason (netstat can tell which process uses a particular port; or you can parse the command-line of storescp processes).

**Comment by jcfr** [comment]
Related to netstat ... 

* A program with interesting part we could potentially re-use: http://qt-apps.org/content/show.php/QNetStatView?content=157088  Issue is that it is GPL, may be possible to contact the original author to ask to re-license. 

* An other one in python that is license under BSD: https://pypi.python.org/pypi/pynetstat

**Comment by che85** [comment]
Any news about when you are going to merge this PR?

**Comment by jcfr** [comment]
@che85 Thanks again for the patches

Commit squashed and integrated in [r25002](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25002)

**Pull request closed without merging**
