### PR TITLE
Two clis in a row issue

### PR DESCRIPTION
**Pull request by vovythevov**
There is an issue when running the same CLI twice in a row, the second CLI never completes.
This implements a test and a fix.

### CODE REVIEW

**Comment by pieper** [comment]
Nice fix :+1:

**Comment by lassoan** [comment]
Looks good to me.

Have you tested if CLI auto-run still works fine?

**Comment by vovythevov** [comment]
No actually, good call.
I'll test that tomorrow and report back.

On Tuesday, September 29, 2015, Andras Lasso <notifications@github.com>
wrote:

> Looks good to me.
>
> Have you tested if CLI auto-run still works fine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/358#issuecomment-144226420>.
>


-- 
Sent from Gmail Mobile

**Comment by vovythevov** [comment]
@lassoan,  @pieper :
Tested the CLI auto-run by hand and it seems to run to fine.
Thanks for the (very quick) feedback !

**Comment by jcfr** [comment]
Nitpicks: `VTKObservationMixin` could be used to observe events in the test. That said, it looks good the way it is and can definitively be integrated.
See http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Python_scripting#How_can_I_access_callData_argument_in_a_VTK_object_observer_callback_function

**Comment by vovythevov** [comment]
Actually, I think it would be even better if ScriptedLoadableModuleLogic ( https://github.com/Slicer/Slicer/blob/master/Base/Python/slicer/ScriptedLoadableModule.py#L130) inherited directly from VTKObservationMixin. We would get all those (very useful) methods in the CLIs.

What do you think ?

**Comment by jcfr** [comment]
Very good point. They will update the templates and existing code in a different commit.

**Comment by vovythevov** [comment]
Alexis Girault reported an issue when the same CLIs is ran twice in parallel. 

After looking at it with @jcfr, we suggest that the observations of the application logic should be made in the SetApplicationLogic() instead of everytime a CLI is executed.

@agirault: Would you mind looking into it ?

**Comment by jcfr** [comment]
More specifically, it seems the solution will be to add/remove the observation associated with `vtkSlicerApplicationLogic::RequestProcessedEvent` in the `SetApplicationLogic()` setter.

**Comment by vovythevov** [comment]
I'll close this pull request in favor of #458.

**Pull request closed without merging**
