### PR TITLE
Updating SimpleITK along 0.9beta

### PR DESCRIPTION
**Pull request by blowekamp**
This update includes:

d5b32be Merge topic 'SIMPLEITK-457_AddExhaustiveOptimizer'
2e4af8c Merge topic 'SIMPLEITK-622_LevelSetMotionFixImageNames'
a15c3f2 Merge topic 'SIMPLEITK-623_AddOptmizerWeights'

### CODE REVIEW

**Comment by blowekamp** [comment]
This update includes adding the Exhaustive Optimizers which was requested by Peter Behringer and Andriy Fedorov.

**Comment by jcfr** [comment]
Integrated in [r24107](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24107)

**Comment by jcfr** [comment]
Thanks for your contribution :+1:

**Comment by jcfr** [comment]
@fedorov @PeterBehringer Updated SimpleITK has been integrated in today's master. Nightly package that will be available on Thursday 26th should include these changes.

**Pull request closed without merging**
