### PR TITLE
ENH: adding extra units support 

### PR DESCRIPTION
**Pull request by Punzo**
As talked with Steve during the Summer Project week, It will be nice to add support for other units in Slicer. Attached there is a screenshot with a preview. Feedback will be very appreciated.

screenshot from 2015-07-10 16 19 36

tested on linux. 

see http://na-mic.org/Mantis/view.php?id=4017

### CODE REVIEW

**Comment by jcfr** [comment]
@Punzo Thanks for your contribution :+1: 

@finetjul Would you mind have a quick look at the contribution of @Punzo ?

**Comment by finetjul** [comment]
How is commit 097f62c related to issue #302 ?

**Comment by finetjul** [comment]
That looks fine to me. Not sure about the first commit. The next 2 commits should be squashed.

**Comment by jcfr** [comment]
Agreed. Thanks for your feedback. I was planning on squashing.

On Fri, Jul 10, 2015 at 5:50 PM, Julien Finet <notifications@github.com>
wrote:

> That looks fine to me. Not sure about the first commit. The next 2 commits
> should be squashed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/302#issuecomment-120537452>.
>



-- 
+1 919 869 8849

**Comment by Punzo** [comment]
Hi, yeah sorry for the first commit, still understanding how it works.

**Comment by Punzo** [comment]
I have found a kind of bug in the unit module:
as soon as a scene is closed the units settings are cleared.

here some screenshot using the current Slicer (fork without my modifications) 
screenshot

(left: before closing the scene; middle: after closing the scene; right: after toggling show advanced twice)

anyone can confirm it? @finetjul any thought how to fix it?

should I open a ticket in Mantis?

**Comment by jcfr** [comment]
Your first set of changes has been integrated in [r24411](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24411), [r24412](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24412) and [r24413](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24413)

I open an issue to keep track of https://github.com/Slicer/Slicer/pull/302#issuecomment-120957217

See http://www.na-mic.org/Bug/view.php?id=4021

**Pull request closed without merging**
