### PR TITLE
ENH: bump DMRI external module to 0402024

### PR DESCRIPTION
**Pull request by ihnorton**
```
Alex Yarmarkovich (4):
      ENH: Added test datasets for DiffusionTensorScalarMeasurements module.
      ENH: Added tests for DiffusionTensorScalarMeasurements CLI
      ENH: Added tests for DWIToDTIEstimation CLI
      BUG: 4238.Right click -> Edit Properties on Fiber Bundle nodes and Fiber Bundle Display nodes in the Data module should go to the Tractography Display module.

Isaiah (2):
      Merge pull request #37 from SlicerDMRI/fbm_stats_option
      Merge pull request #43 from SlicerDMRI/fbm_clamped_msrs

Isaiah Norton (22):
      ENH: FBTractMeasurement: by default, print only specified hierarchy.
      FBTractMsr: Introduce measurement range clamping, and count excluded points
      FBTractMsr: correctly fix #36: by default print top and cluster groups, but not fiberbundles
      FBTractMsr: refactor redundant code
      FBTractMsr: update to pass tests
      FBTractMsr: fix non-C++11 compile, and more refactoring.
      FBMsr: Print NAN when no measurement value exists.
      Remove obsolute DT scalar measures, update docs.
      Update DTMsr contributor list to match wiki
      Update DTMsr contributor institutions.
      More DTScalarMsr interface updates
      Update DWIToDTIEstim module description.
      More updates to DTEstim & ScalarMeasurements desc.
      Update DWMasking module description.
      Update more module description files
      Remove newlines from FBLabelSelect xml
      FBLabelSelect description updates
      FBLabelSelect description more updates
      FBTractMeasurements description update
      TractLMSeeding module description
      COMP: fix and simplify DTScalarMeasure tests
      COMP: fix FBTractMsr tests

Lauren O'Donnell (1):
      Update README.md

zhangfanmark (1):
      EHN: Measure name consistency
```

### CODE REVIEW

**Comment by msmolens** [comment]
This introduces some test failures: http://slicer.cdash.org/viewTest.php?onlyfailed&buildid=869169

**Comment by ihnorton** [comment]
Fixed, thanks.

(is there a general way to trigger a dashboard build from a pull request? useful...)

**Comment by ihnorton** [comment]
From what I can tell, the check "failure" is just a notice about dependencies not being rebuilt.

**Comment by msmolens** [comment]
@ihnorton That's correct, CircleCI indicates a failure because this changes the SuperBuild, but CircleCI uses a pre-built Docker image with the Slicer dependencies. See more details at: https://github.com/thewtex/SlicerDocker.

Integrated in [25260](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25260) and [25261](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25261).

**Comment by ihnorton** [comment]
Thanks. Can I trigger a dashboard build from a pull request?

> That's correct, CircleCI indicates a failure because this changes the SuperBuild

Maybe we should move the remotes out of `SuperBuild.cmake` to avoid this?

**Comment by msmolens** [comment]
> Can I trigger a dashboard build from a pull request?

Not currently, but clearly it would be beneficial if pull request CI could eventually run Slicer's tests.

> Maybe we should move the remote module sections out of `SuperBuild.cmake` to avoid this?

That seems reasonable. I'd like to hear what @jcfr or @thewtex think, or this could be discussed in the developer hangout.

**Comment by thewtex** [comment]
Would could run the tests, too, but there will likely be false positive failures; the VTK test suite has failures when using the CPU-rendering backend in the Docker image, which indicates more work is required in upstream VTK before rendering tests will be reliable.

**Comment by jcfr** [comment]
> move the remote module sections out of SuperBuild.cmake to avoid this?

Since, Source code of remote module is currently checked out during
superbuild, that is currently not possible.

To avoid this, we should check out the associated source code during the
inner build.

Thanks
Jc

On Aug 3, 2016 8:02 PM, "Max Smolens" <notifications@github.com> wrote:

Can I trigger a dashboard build from a pull request?

Not currently, but clearly it would be beneficial if pull request CI could
eventually run Slicer's tests.

Maybe we should move the remote module sections out of SuperBuild.cmake to
avoid this?

That seems reasonable. I'd like to hear what @jcfr <https://github.com/jcfr>
or @thewtex <https://github.com/thewtex> think, or this could be discussed
in the developer hangout.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Slicer/Slicer/pull/558#issuecomment-237311813>, or mute
the thread

**Comment by ihnorton** [comment]
> Would could run the tests, too, but there will likely be false positive failures; the VTK test suite has failures when using the CPU-rendering backend in the Docker image, which indicates more work is required in upstream VTK before rendering tests will be reliable.

As far as I can tell, CircleCI supports xvfb-run, so it may not be necessary to use the CPU-rendering backend.

**Comment by thewtex** [comment]
On Wed, Aug 3, 2016 at 3:37 PM, Isaiah <notifications@github.com> wrote:

> Would could run the tests, too, but there will likely be false positive
> failures; the VTK test suite has failures when using the CPU-rendering
> backend in the Docker image, which indicates more work is required in
> upstream VTK before rendering tests will be reliable.
>
> As far as I can tell, CircleCI supports xvfb-run, so it may not be
> necessary to use the CPU-rendering backend.
>
It is a challenge to get the graphical context of the host system into the
Docker container or to make the build tree in the Docker image usable on
the host.

**Comment by ihnorton** [comment]
> It is a challenge to get the graphical context of the host system into the
Docker container or to make the build tree in the Docker image usable on
the host.

See https://github.com/Slicer/Slicer/pull/561

**Pull request closed without merging**
