### PR TITLE
DOC: Fix spelling and grammar in linux.md

### PR DESCRIPTION
**Pull request by benzwick**

### CODE REVIEW

**Review by pieper — APPROVED** [review]
Looks good - thanks 👍

**Comment by pieper** [comment]
It's marked as work in progress, so we can wait to merge when you are ready.

**Comment by benzwick** [comment]
> It's marked as work in progress, so we can wait to merge when you are ready.

I made one more small change (Pre-requisites -> Prerequisites).

It's ready for review now.

**Comment by jcfr** [comment]
Thanks for your help improving the documentation 🙏

**Pull request merged**
