### PR TITLE
BUG: Fix vtkITKArchetypeImageSeriesReader::CanReadFile()

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
vtkITKArchetypeImageSeriesReader::CanReadFile previously returned true as long as the Archetype was set, and the file exists.
Now, CanReadFile will return true if, in addition to the archetype being set and the file existing, an itk::ImageFileReader can be instantiated for the specified file.

### CODE REVIEW

**Comment by pieper** [comment]
Makes sense to me.  Was there a specific issue that requires this change?  (I.e. wouldn't it just have failed later?).

**Comment by Sunderlandkyl** [comment]
It was causing some failing tests in SlicerRT. vtkMRMLSegmentationStorageNode would try to load polydata as an image and report an error. Everything still loaded fine, but the error messages caused the test to fail.

Probably there is some other way to work around the error messages, but I figured that the the better approach would be to determine if vtkITKArchetypeImageSeriesReader can actually read the file before attempting to use it.

**Comment by pieper** [comment]
Yes, makes sense.  Fine to merge from my point of view.

**Comment by jcfr** [comment]
I wonder if there is anyway to refactor the code used in both `RequestInformation` and `CanReadFile` ?

**Comment by pieper** [comment]
Yes, all that code is pretty messy.  Could make sense to take a fresh pass at the whole class.

**Comment by jcfr** [comment]
This could be done later of course and I would have no issue integrated this patch, just wanted to point it out.

@Sunderlandkyl  I will let you assess.

**Comment by Sunderlandkyl** [comment]
I agree, it makes sense to reduce the code duplication.
There's no hurry to integrate, so I'll make the necessary changes.

**Comment by jcfr** [comment]
> so I'll make the changes in this PR.
:pray:

**Comment by Sunderlandkyl** [comment]
I've added a GetImageIO function that is used by both RequestInformation and CanReadFile.

**Comment by Sunderlandkyl** [comment]
@jcfr @pieper @lassoan Let me know if there are any other necessary changes.

**Comment by lassoan** [comment]
The title of this PR is still "do not integrate" - can you confirm that it can be integrated now? Thank you!

**Comment by Sunderlandkyl** [comment]
@lassoan It should be ready to integrate.

**Comment by cpinter** [comment]
Thanks a lot, everyone! I integrated it (https://github.com/Slicer/Slicer/commit/8ea69453690690cee3de21e61e97122622c51e5d) so that we can see in the next nightly if the SlicerRT tests pass, to make progress with this [PR](https://github.com/SlicerRt/SlicerRT/pull/124).

**Pull request closed without merging**
