### PR TITLE
Fix SampleData module

### PR DESCRIPTION
**Pull request by jcfr**
Restore the passing of the following tests addressing regressions introduced in d3f49ed35 (BUG: Make more strings translatable) introduced through:
* https://github.com/Slicer/Slicer/pull/7243

Tests fixed:

* `py_Slicer4Minute`
* `py_ShaderProperties`
* `py_RSNA2012ProstateDemo`
* `py_VolumeRenderingSceneClose`
* `py_SubjectHierarchyGenericSelfTest`
* `py_SampleData`
* `py_SlicerRestoreSceneViewCrashIssue3445`
* `py_RSNAVisTutorial`
* `py_JRC2013Vis`
* `py_AtlasTests`

Tested on a local build generated on Ubuntu 20.04

### CODE REVIEW

**Review by pieper — APPROVED** [review]
That looks fine to me.  I don't know when BuiltIn was changed to General, but if that's the way it is then yes, this needs to be updated.

**Comment by jcfr** [comment]
>  I don't know when BuiltIn was changed to General,

Thanks for the review. This has done in the context of the pull request linked above. For convenience, see this direct link: https://github.com/Slicer/Slicer/commit/d3f49ed3540b8f9374d2e34227be5c0c1a060132#diff-fe7a3220b4dec268c9e7d101aefdfaef3e3ede882c9bbc148adf52fce2298f22R507

**Comment by pieper** [comment]
> This has done in the context of the pull request linked above

Ah, yes, I see, thanks.

**Review by jamesobutler — APPROVED** [review]
Changes make sense

**Comment by jcfr** [comment]
After the integration of this PR, we are now left with one failing test :ok_hand: 

image

**Comment by jcfr** [comment]
>  take a quick look at this last test.

Thanks for helping with this :pray: 

The following issue report should help understand how to fix the "problem":

* https://github.com/Slicer/Slicer/issues/7288

**Comment by cpinter** [comment]
Yes, it is most probable that it is related to the folder item visibility changes. It was a mistake I didn't run the tests to confirm. It seems that the failure is due to the fact that the `showEmptyHierarchyItems` flag is on in the proxy model. Trying to see why it is enabled.

**Pull request merged**
