### PR TITLE
WIP: Support qt5

### PR DESCRIPTION
**Pull request by jcfr**
This topic allows to compile Slicer against either Qt4 or Qt5.

* It supports version of Qt5 with/without webkit support.
* It was tested on Ubuntu with **CMake >= 3.4.2**
* When building with Qt5, a library named `Slicer/Libs/qtstyleplugins/` it basically includes the `QCleanlooksStyle` classes that were removed from Qt5 core. See http://code.qt.io/cgit/qt/qtstyleplugins.git/ and http://blog.qt.io/blog/2012/10/30/cleaning-up-styles-in-qt5-and-adding-fusion/

### How to configure Slicer with Qt5 ?

If not installed on your system, you should specify the option `-DQt5_DIR` (e.g `-DQt5_DIR:PATH=/home/jcfr/Software/Qt5.7.1/5.7/gcc_64/lib/cmake/Qt5`)

### Missing:

See https://www.slicer.org/wiki/Documentation/Labs/Qt5#To_Do_List

### Known issues:

See https://www.slicer.org/wiki/Documentation/Labs/Qt5#Known_Issues

### Update to dependent projects:
* CTK
* DataStore
* EMSegment
* MultiVolumeExporter
* OpenIGTLinkIF

### CODE REVIEW

**Comment by ClementMirabel** [comment]
I am trying to build Slicer with Qt5 support but while building I always have the following error:
```
[ 37%] Linking CXX executable ../../../bin/SlicerBaseLogicCxxTests
[ 37%] Built target SlicerBaseLogicCxxTests
[ 37%] Generating qrc_qSlicerBaseQTCoreExtra.cpp
Scanning dependencies of target qSlicerBaseQTCore
[ 37%] Building CXX object Base/QTCore/CMakeFiles/qSlicerBaseQTCore.dir/qSlicerCoreApplication.cxx.o
/Users/mirclem/Applications/Slicer/build/Slicer-Qt5/Base/QTCore/qSlicerCoreApplication.cxx:30:10: fatal error: 'QNetworkProxyFactory' file not found
#include <QNetworkProxyFactory>
         ^
1 error generated.
```

My config is MacOS El Capitan 10.11, Cmake 3.7.2, XCode 8.2.1 and Qt5.7.
Any ideas?

**Comment by pieper** [comment]
Maybe send the full build log using a command like

`make 2>&1 | tee /tmp/log.txt`

**Comment by jcfr** [comment]
Thanks for the report.  

For reference, here the line where the error  happens: [Base/QTCore/qSlicerCoreApplication.cxx#L30](https://github.com/jcfr/Slicer/blob/2cf3e550252c56345478e44824185c92b5ab2739/Base/QTCore/qSlicerCoreApplication.cxx#L30)

Also worth noting that the `QtNetwork` module is specified [here](https://github.com/jcfr/Slicer/blob/2cf3e550252c56345478e44824185c92b5ab2739/CMakeLists.txt#L603)

Finally, searching for that header in my local install of Qt 5.7, I am able to find the header:

```
$ cd /home/jcfr/Software/Qt5.7.1/5.7/gcc_64/include

$ find . | ack QNetworkProxyFactory
./QtNetwork/QNetworkProxyFactory
```

Could you also confirm that this header is available on your system ?

Last, it will be useful to report the last lines associated with the output of:

```
$ VERBOSE=1 make qSlicerBaseQTCore/fast
```

**Comment by ClementMirabel** [comment]
@pieper 
> Maybe send the full build log using a command like
make 2>&1 | tee /tmp/log.txt

You can find it [here](https://github.com/Slicer/Slicer/files/748028/log.txt).



@jcfr 
> Could you also confirm that this header is available on your system ?

I confirm, path is: 
`/Applications/Qt/5.7/Src/qtbase/include/QtNetwork/QNetworkProxyFactory`

> Last, it will be useful to report the last lines associated with the output of:
$ VERBOSE=1 make qSlicerBaseQTCore/fast

It was not a target rule for the makefile, so I did for the rule Slicer/fast and you can find the results [here](https://github.com/Slicer/Slicer/files/748062/verbose.txt).

**Comment by jcfr** [comment]
> full log [...] You can find it [here](https://github.com/Slicer/Slicer/files/748028/log.txt).

This confirm that the Network module is expected ...

```
[...]
-- Configuring Slicer with Qt .. (using modules: Core, Widgets, Network, OpenGL, PrintSupport, UiTools, Xml, XmlPatterns, Svg, Sql, WebEngine, WebEngineWidgets, Test, )
[...]
```


> I confirm, path is:
> /Applications/Qt/5.7/Src/qtbase/include/QtNetwork/QNetworkProxyFactory

This corresponds to the source tree.

As detailed below, the path of this form `/Applications/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers` are used on MacOSX.

Do you have a similar path in your install ?

> It was not a target rule for the makefile,

For this one you would have to go in the inner build directory (`cd /Users/mirclem/Applications/Slicer/build/Slicer-Qt5-build/Slicer-build`)

Otherwise, the interesting part of (https://github.com/Slicer/Slicer/files/748062/verbose.txt)  are:

```
[...]
/Users/mirclem/Applications/Slicer/build/Slicer-Qt5-build/VTKv7-build/ThirdParty/hdf5/vtkhdf5/src
-iframework
/Applications/Qt/5.7/clang_64/lib
-isystem
/Applications/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers
-isystem
/Applications/Qt/5.7/clang_64/lib/QtGui.framework/Headers
-isystem
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers
-isystem
/Applications/Qt/5.7/clang_64/lib/QtCore.framework/Headers
-isystem
/Applications/Qt/5.7/clang_64/./mkspecs/macx-clang
-isystem
/Users/mirclem/Applications/Slicer/build/Slicer-Qt5-build/ITKv4-build/Modules/ThirdParty/HDF5/src/itkhdf5/c++/src
-isystem
/Users/mirclem/Applications/Slicer/build/Slicer-Qt5-build/ITKv4/Modules/ThirdParty/HDF5/src/itkhdf5/c++/src
-isystem
/Users/mirclem/Applications/Slicer/build/Slicer-Qt5-build/ITKv4-build/Modules/ThirdParty/HDF5/src/itkhdf5/src
-isystem
/Users/mirclem/Applications/Slicer/build/Slicer-Qt5-build/ITKv4/Modules/ThirdParty/HDF5/src/itkhdf5/src
-isystem
/Applications/Qt/5.7/clang_64/lib/QtSql.framework/Headers

-g
-arch
x86_64
-isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
-mmacosx-version-min=10.9
-fPIC
[...]
```

I am also downloading Qt 5.7 on a MacOSx to have a look ...

**Comment by ClementMirabel** [comment]
>As detailed below, the path of this form /Applications/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers are used on MacOSX.
Do you have a similar path in your install ?

Makes sense, thank you for the clarification. `/Applications/Qt/5.7/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QNetworkProxyFactory` is the path to the header we were looking for.

**Comment by jcfr** [comment]
> the path to the header we were looking for

Good. We confirmed the header was available.

Short story: 

* `Qt5::Network` should be transitively included. I need to have an other look ... and also update the system to specify all Qt direct requirements.

* Conditionally adding `Qt5::Network` to the list `KIT_target_libraries` used in  [Base/QTCore/CMakeLists.txt#L244-L253](https://github.com/jcfr/Slicer/blob/2cf3e550252c56345478e44824185c92b5ab2739/Base/QTCore/CMakeLists.txt#L244-L253)  should be helpful.



Long story: See below .... 

Now, I would suggest the following:

* In [CMakeLists.txt#L629-L635](https://github.com/jcfr/Slicer/blob/2cf3e550252c56345478e44824185c92b5ab2739/CMakeLists.txt#L629-L635) after line 635, adds `message(STATUS "QT_LIBRARIES:${QT_LIBRARIES}")`

* After reconfiguring, the `Qt5::Network` is expected to be listed. Note, that you can simply re-run cmake from the inner build directory.

* Now, we need to check if the library built by `SlicerMacroBuildBaseQtLibrary` and defined in [Base/QTCore/CMakeLists.txt#L244-L253](https://github.com/jcfr/Slicer/blob/2cf3e550252c56345478e44824185c92b5ab2739/Base/QTCore/CMakeLists.txt#L244-L253) is linked against against `Qt5::Network`

 * To check this, you can display the value of the variables:

  * `SLICERQTBASELIB_TARGET_LIBRARIES` in [CMake/SlicerMacroBuildBaseQtLibrary.cmake#L230-L232](https://github.com/jcfr/Slicer/blob/2cf3e550252c56345478e44824185c92b5ab2739/CMake/SlicerMacroBuildBaseQtLibrary.cmake#L230-L232)

 
Look like, the `Qt5::Network` library should be transitively included ... it is writing this text I understood what is probably the problem ...

**Comment by ClementMirabel** [comment]
After the changes you advised to do, `Qt5::Network` is well listed

> --QT_LIBRARIES:Qt5::Core;Qt5::Widgets;Qt5::Network;Qt5::OpenGL;Qt5::PrintSupport;Qt5::UiTools;Qt5::Xml;Qt5::XmlPatterns;Qt5::Svg;Qt5::Sql;Qt5::WebEngine;Qt5::WebEngineWidgets;Qt5::Test
> -- Configuring Slicer with Qt .. (using modules: Core, Widgets, Network, OpenGL, PrintSupport, UiTools, Xml, XmlPatterns, Svg, Sql, WebEngine, WebEngineWidgets, Test, )

Here are the displays of `SLICERQTBASELIB_TARGET_LIBRARIES`

> -- Configuring Slicer Qt base library: qSlicerBaseQTCore
-- SLICERQTBASELIB_TARGET_LIBRARIES: SlicerBaseLogicMRMLDisplayableManagerCTKCoreCTKImageProcessingITKCoreCTKVisualizationVTKCoreITKCommonitksysitkvnl_algoitkvnlitkv3p_netlibitknetlibitkvclITKIOXMLITKIOImageBaseITKEXPATofstdoflogdcmdatai2ddcmimgledcmimagedcmjpegijg8ijg12ijg16dcmjplscharlsdcmtlsdcmnetdcmsrcmrdcmdsigdcmwlmdcmqrdbdcmpstatdcmrtdcmioddcmfgdcmsegdcmtractdcmpmapCTKDICOMCoreITKCommonitksysitkvnl_algoitkvnlitkv3p_netlibitknetlibitkvclITKIOXMLITKIOImageBaseITKEXPATModuleDescriptionParserCTKScriptingPythonCorevtkWrappingPythonCore
-- Looking for decorator header qSlicerBaseQTCorePythonQtDecorators.h
-- Looking for decorator header qSlicerBaseQTCorePythonQtDecorators.h - Found
-- Configuring Slicer Qt base library: qSlicerBaseQTGUI
-- SLICERQTBASELIB_TARGET_LIBRARIES: qSlicerBaseQTCoreqMRMLWidgetsCTKScriptingPythonWidgetsqtstyleplugins
-- Looking for decorator header qSlicerBaseQTGUIPythonQtDecorators.h
-- Looking for decorator header qSlicerBaseQTGUIPythonQtDecorators.h - Found
-- Configuring Slicer Qt base library: qSlicerBaseQTCLI
-- SLICERQTBASELIB_TARGET_LIBRARIES: qSlicerBaseQTCoreqSlicerBaseQTGUIModuleDescriptionParserITKCommonitksysitkvnl_algoitkvnlitkv3p_netlibitknetlibitkvclITKIOXMLITKIOImageBaseITKEXPATMRMLCLI
-- Looking for decorator header qSlicerBaseQTCLIPythonQtDecorators.h
-- Looking for decorator header qSlicerBaseQTCLIPythonQtDecorators.h - Not found
-- Configuring SEM CLI module: CLIModule4Test
-- Configuring Slicer Qt base library: qSlicerModulesCore
-- SLICERQTBASELIB_TARGET_LIBRARIES: qSlicerBaseQTGUI
-- Configuring Slicer Qt base library: qSlicerBaseQTApp
-- SLICERQTBASELIB_TARGET_LIBRARIES: qSlicerModulesCoreqSlicerBaseQTCLI

**Comment by jcfr** [comment]
Closing this PR.

@hina-shah  is currently working on finalizing the update of SlicerWebWidget to work with Qt5. On my side, I will tackle the remaining issue related to packaging.

We should push an new updated topic later next week.

**Pull request closed without merging**
