### PR TITLE
Update ITK to latest 4.13 release branch and update BRAINSTools

### PR DESCRIPTION
**Pull request by dzenanz**
Some tests are failing locally, but they are mostly overlapping with currently failing tests on the [dashboard](http://slicer.cdash.org/index.php?project=SlicerPreview). These are minor updates, and should be non-problematic.

Linux failures:
```text
	  9 - py_cmake_slicer_extensions_index_build_with_upload_using_ctest (Failed)
	 10 - py_cmake_slicer_extensions_index_build_without_upload_using_ctest (Failed)
	415 - qSlicerReformatModuleWidgetGenericTest (Failed)
	441 - vtkMRMLVolumeRenderingMultiVolumeTest (Failed)
	467 - py_nomainwindow_qSlicerDICOMModuleGenericTest (Failed)
	468 - py_nomainwindow_qSlicerDICOMPatcherModuleGenericTest (Failed)
	552 - qSlicerApplicationTpyclTest1 (Failed)
	612 - py_nomainwindow_DCMTKPrivateDictTest (Failed)
	621 - py_DICOMReaders (Failed)
	623 - py_sceneImport2428 (Failed)
	634 - py_RSNAVisTutorial (Failed)
	642 - py_JRC2013Vis (Failed)
	644 - py_SubjectHierarchyGenericSelfTest (Failed)
	658 - EMSegCL_RunDefaultNodes (Failed)
	659 - EMSegCL_RunSetEverything (Failed)
	666 - EMSegCL_IntermediateResults (Failed)
	668 - EMSegCL_Task_BRAINS_MRIHumanBrain_scalartype_float_very_small (Failed)
	669 - EMSegCL_Task_BRAINS_MRIHumanBrain_scalartype_uint_very_small (Failed)
	670 - EMSegCL_Task_MRIHumanBrain_2CH (Failed)
	671 - EMSegCL_Task_MRIHumanBrain_BRAINS_small (Failed)
	672 - EMSegCL_Task_HumanEye_BRAINS_small (Failed)
	673 - EMSegCL_Task_MRIHumanBrainExp_BRAINS_small (Failed)
	674 - EMSegCL_Task_MRIHumanBrainParcellation_BRAINS_small (Failed)
	675 - EMSegCL_Task_MRIHumanBrainFullParcellation_BRAINS_small (Failed)
	676 - EMSegCL_Task_NonHumanPrimate_BRAINS_small (Failed)
	684 - py_LandmarkRegistration (Failed)
```

MacOS failures:
```text
	  9 - py_cmake_slicer_extensions_index_build_with_upload_using_ctest (Failed)
	 10 - py_cmake_slicer_extensions_index_build_without_upload_using_ctest (Failed)
	415 - qSlicerReformatModuleWidgetGenericTest (Failed)
	467 - py_nomainwindow_qSlicerDICOMModuleGenericTest (Failed)
	468 - py_nomainwindow_qSlicerDICOMPatcherModuleGenericTest (Failed)
	594 - py_nomainwindow_SlicerOptionDisableSettingsTest (Failed)
	610 - py_nomainwindow_DCMTKPrivateDictTest (Failed)
	619 - py_DICOMReaders (Failed)
	621 - py_sceneImport2428 (Failed)
	625 - py_Slicer4Minute (Failed)
	626 - py_SlicerBoundsTest (Failed)
	632 - py_RSNAVisTutorial (Failed)
	633 - py_RSNAQuantTutorial (Failed)
	634 - py_slicerCloseCrashBug2590 (Failed)
	636 - py_SlicerTransformInteractionTest1 (Failed)
	639 - py_RSNA2012ProstateDemo (Failed)
	640 - py_JRC2013Vis (Failed)
	641 - py_FiducialLayoutSwitchBug1914 (Failed)
	642 - py_SubjectHierarchyGenericSelfTest (Failed)
	655 - py_LandmarkRegistration (Failed)
```

Windows failures:
```text
          6 - cmake_slicer_generate_extension_description_test (Failed)
          7 - py_cmake_slicer_extensions_index_build_without_upload (Failed)
          8 - py_cmake_slicer_extensions_index_build_with_upload (Failed)
        442 - py_VolumeRenderingSceneClose (Failed)
        454 - py_LabelStatistics (Failed)
        458 - py_ScreenCapture (Failed)
        461 - py_SegmentStatistics (Failed)
        467 - py_nomainwindow_qSlicerDICOMModuleGenericTest (Failed)
        468 - py_nomainwindow_qSlicerDICOMPatcherModuleGenericTest (Failed)
        508 - MergeModelsTestCompare (Failed)
        552 - qSlicerApplicationTpyclTest1 (Failed)
        597 - py_nomainwindow_SlicerOptionDisableSettingsTest (Failed)
        602 - py_nomainwindow_MRMLCreateNodeByClassWithoutSetReferenceCount (Failed)
        613 - py_nomainwindow_DCMTKPrivateDictTest (Failed)
        620 - py_AtlasTests (Timeout)
        622 - py_DICOMReaders (Failed)
        624 - py_sceneImport2428 (Failed)
        632 - py_ScenePerformance (Failed)
        634 - py_SlicerRestoreSceneViewCrashIssue3445 (Failed)
        635 - py_RSNAVisTutorial (Failed)
        643 - py_JRC2013Vis (Failed)
        644 - py_FiducialLayoutSwitchBug1914 (Failed)
        645 - py_SubjectHierarchyGenericSelfTest (Failed)
        661 - EMSegCL_RunDefaultNodes (Failed)
        662 - EMSegCL_RunSetEverything (Failed)
        669 - EMSegCL_IntermediateResults (Failed)
        671 - EMSegCL_Task_BRAINS_MRIHumanBrain_scalartype_float_very_small (Failed)
        672 - EMSegCL_Task_BRAINS_MRIHumanBrain_scalartype_uint_very_small (Failed)
        673 - EMSegCL_Task_MRIHumanBrain_2CH (Failed)
        674 - EMSegCL_Task_MRIHumanBrain_BRAINS_small (Failed)
        675 - EMSegCL_Task_HumanEye_BRAINS_small (Failed)
        676 - EMSegCL_Task_MRIHumanBrainExp_BRAINS_small (Failed)
        677 - EMSegCL_Task_MRIHumanBrainParcellation_BRAINS_small (Failed)
        678 - EMSegCL_Task_MRIHumanBrainFullParcellation_BRAINS_small (Failed)
        679 - EMSegCL_Task_NonHumanPrimate_BRAINS_small (Failed)
        687 - py_LandmarkRegistration (Failed)
```

### CODE REVIEW

**Comment by dzenanz** [comment]
My build tree on Linux was not fresh when I started working on the patch, that might be the reason for more test failures than on Mac. Automatic tests succeeded. Merge?

**Comment by dzenanz** [comment]
I haven't tested on Windows yet - will do. The reason for enabling `ITK_LEGACY_REMOVE` is preparation to switch to ITK 5.0 soon. All code which has been marked as legacy in 4.x is completely removed in 5.0.

**Comment by lassoan** [comment]
> The reason for enabling ITK_LEGACY_REMOVE is preparation to switch to ITK 5.0 soon

It may be better to upgrade ITK first and disable legacy code a few weeks later. In case of there were any regressions in any extensions or private custom Slicer applications, it would be easier to see if it's because of ITK update or due to removing legacy features.

**Comment by dzenanz** [comment]
This patch updates ITK from 4.13.0 to 4.13.1+a few more patches. All the added commits are strictly bug fixes. Updating BRAINSTools was not required, but I also updated it to the newest version I could. It also seems to contain only bug fixes and minor code changes.

ITK5's [migration guide](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md#legacy-code-removed) calls for first finishing migration to version 4.x, by building the application against ITK 4.x with legacy disabled. Then building against 5.0 with legacy enabled, and finally building against 5.0 with legacy disabled. The last step (5.0 with legacy off) is not realistic for Slicer soon. But this PR is the first step in this migration process.

**Comment by lassoan** [comment]
It makes sense to disable legacy for Slicer-4.10, I would just recommend to do the ITK update and legacy removal in two separate steps, to make any potential troubleshooting easier (e.g., have a nightly build with just ITK update but with legacy still enabled).

**Comment by dzenanz** [comment]
I edited the description of the PR to add local Windows test failures list.

**Comment by dzenanz** [comment]
Closing in favor of #1013 and #1014.

**Pull request closed without merging**
