### PR TITLE
STYLE: Remove unused DICOMStudyBrowser/DICOMStudyTable/DICOMSeriesTable

### PR DESCRIPTION
**Pull request by jcfr**
This commit removes part of experimental code added in r19454 (ENH: improvements
to DICOM Module) that was illustrating possible implementation during the
Slicer DICOM browser meeting of 2012-01-25.

See https://www.assembla.com/spaces/slicerrt/wiki/20120125_Slicer_DICOM_browser_meeting

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @pieper @lassoan @cpinter

**Comment by pieper** [comment]
+1

**Comment by jcfr** [comment]
Thanks for the review.

Integrated in [r24604](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24604)

**Comment by cpinter** [comment]
Makes sense. Thanks!

**Pull request closed without merging**
