### PR TITLE
BUG: Fix missing extension revision in extension package

### PR DESCRIPTION
**Pull request by jamesobutler**
This fixes what I think is a typo that was included in https://github.com/Slicer/Slicer/commit/3814f1af649d63a1737005304b0924a03393446a.

Extension packages used to have names like
28257-win-amd64-SegmentEditorExtraEffects-git5085c07-2020-03-23.zip

,but because of the typo they are missing the extension revision and are like
28879-win-amd64-SegmentEditorExtraEffects-git-2020-03-23.zip

### CODE REVIEW

**Comment by jamesobutler** [comment]
I've updated the commit message as requested.

**Comment by jcfr** [comment]
@jamesobutler  I added you to the [slicer-developer](https://github.com/orgs/Slicer/teams/slicer-developer/) team has write access.

After accepting the invite, let me know if you see the following button:

 
image

**Comment by jamesobutler** [comment]
I can see the button but I can’t merge as a the branch is restricted to “authorized users”.

**Comment by jcfr** [comment]
I updated the settings, you should now be able to merge.

**Pull request merged**
