### PR TITLE
Update python packages to latest

### PR DESCRIPTION
**Pull request by jamesobutler**
I noticed every so often all the python packages get an update to use latest versions.  I figured it was a good time to go ahead with this again. There are several packages receiving version updates from 2017/2018 to 2018/2019. For some of these packages(ie Numpy), these are the last feature release versions with full support for python2.
```terminal
C:\Program Files\Slicer 4.10.1\bin>SlicerPython.exe -m pip list --outdated
```

| Package        | Version | Latest | Release Date (version to Latest) |
| ------------- |----------|--------| -----:|
| gitdb2         | 2.0.3      | 2.0.5    |Sep 28, 2017 to Oct 13, 2018|
| GitPython   | 2.1.7      |  2.1.11 |Sep 28, 2017 to Jul 15, 2018 |
| numpy        | 1.13.1     | 1.16.2 |Jul 6, 2017 to Feb 26, 2019 |
| packaging   | 17.1        | 19.0    |Feb 28, 2018 to Jan 20, 2019 |
| pip               | 18.0       | 19.0.3 |Jul 22, 2018 to Feb 20, 2019|
| PyGithub     | 1.39        | 1.40(~~1.43.5~~) |Apr 9, 2018 to Jun 25, 2018 (~~Jan 29, 2019~~) |
| PyJWT          | 1.6.4      |  1.7.1   |May 23, 2018 to Dec 7, 2018 |
| pyparsing     | 2.2.0      |   2.3.1 |Mar 5, 2017 to Jan 13, 2019 |
| SimpleITK     | 1.1.0      |  1.2.0 (see #1074) |Mar 26, 2018 to Jan 8, 2019 |
| six                 | 1.11.0    | 1.12.0 |Sep 17, 2017 to Dec 9, 2018 |
| smmap2        | 2.0.3     |  2.0.5   |Jun 10, 2017 to Oct 13, 2018 |
| wheel            | 0.31.1   |  0.33.1  |May 13, 2018 to Feb 19, 2019 |

I've specified PyGithub to update only to 1.40 instead of 1.43.5 because there are a few more dependencies in the latest and one uses a c compiler to build, so I decided against doing that right now.

[setuptools](https://github.com/Slicer/setuptools) has a Slicer organization fork with a custom edit so I haven't updated that, but could if requested.

| Package        | Version | Latest | Release Date (version to Latest) |
| ------------- |----------|--------| -----:|
| setuptools    | 40.2.0.post20190115 | 40.8.0 |Aug 21, 2018 to Feb 5, 2019 |

### CODE REVIEW

**Comment by pieper** [comment]
Makes sense to me.   I'm sure we'll notice or hear if anything breaks.  Thanks for digging into this 👍

**Comment by jcfr** [comment]
Thanks @jamesobutler :+1: Well done.

> setuptools

Would be great to also update it. This could be done later by:
* creating a branch like [slicer-v40.2.0](https://github.com/Slicer/setuptools/commits/slicer-v40.2.0)
* cherry picking this two commits: https://github.com/Slicer/setuptools/commit/3dbad5dc19ccfb596e7e906ee2ecf4d30f644a55 and https://github.com/Slicer/setuptools/commit/1b48ec37eddeb39303bc32d217666cd1ba2b9c39
* You should now have push access to the fork

> PyGithub

You assessment makes sense

> numpy ...  last feature release versions with full support for python2.

:+1:

**Comment by jamesobutler** [comment]
Ok will update setuptools as well 👍

**Comment by jamesobutler** [comment]
[slicer-v40.8.0](https://github.com/Slicer/setuptools/commits/slicer-v40.8.0) has been created with those two commits on top.

**Comment by jcfr** [comment]
For, I will integrate all but the numpy update, it fails to apply the patches:

```
-- Applying 'numpy-01-system_info-fix-clang.patch' - failed
CMake Error at /home/jcfr/Projects/Slicer-Qt5-VTK9/CMake/SlicerPatch.cmake:68 (message):
  2 out of 2 hunks FAILED -- saving rejects to file
  numpy/distutils/system_info.py.rej
```

Patches are applied using this code: https://github.com/Slicer/Slicer/blob/6289b33445e6a0ee412476f3fb82cbe360238f0d/SuperBuild/External_NUMPY.cmake#L96-L114

Similarly to what you did with setuptools, patch for the updated numpy should be generated from a new branch push here: https://github.com/Slicer/numpy
You have been added as a collaborator to the numpy factor.

**Comment by jcfr** [comment]
All changes (expect numpy update) have been integrated in [r27975](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27975) to [r27986](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27986)

**Comment by jamesobutler** [comment]
@jcfr I created branch [slicer-v1.16.2-2019-02-26-0eeb158ea](https://github.com/Slicer/numpy/tree/slicer-v1.16.2-2019-02-26-0eeb158ea) in https://github.com/Slicer/numpy.  I believe I have merged conflicts appropriately when cherry picking those 3 custom slicer commits on top of the v1.16.2 numpy tag.

Please test to make sure the clang patch fixes work now. Thanks!

I have updated my Numpy commit in this PR.  Included is removing the .patch files since they are now incorporated into the branches within the Slicer organization's fork of numpy.

**Comment by jcfr** [comment]
>  Included is removing the .patch files since they are now incorporated into the branches within the Slicer 
organization's fork of numpy.

I suggest we keep the patch. Indeed, explicitly downloading the distribution is required as it contains already "cythonized" files.

**Comment by jamesobutler** [comment]
Got it. I'll change it back to downloading source from pypi and then update the patch files by generating them from [slicer-v1.16.2-2019-02-26-0eeb158ea](https://github.com/Slicer/numpy/tree/slicer-v1.16.2-2019-02-26-0eeb158ea)

**Comment by jcfr** [comment]
Thanks @jamesobutler :pray:

**Comment by jamesobutler** [comment]
Force pushed update to numpy commit with requested changes
```
Performing patch step for 'NUMPY'
-- Applying 'numpy-01-system_info-fix-clang.patch' - done
-- Applying 'numpy-02-fcompiler-optional-revert-4a3fd1f.patch' - done
-- Applying 'numpy-03-core-getlimits-ignore-warnings.patch' - done
```

**Comment by jcfr** [comment]
Et voila. Closing. NUMPY update integrated in [r27989](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27989)

**Comment by jamesobutler** [comment]
Merci! Thanks again for the review

**Comment by jcfr** [comment]
To follow up on this, there is a failure on macOS: http://slicer.cdash.org/viewBuildError.php?buildid=1530008

```
CMake Error at /Volumes/Dashboards/Preview/Slicer-0-build/python-pyparsing-prefix/src/python-pyparsing-stamp/python-pyparsing-install-Release.cmake:16 (message):
  Command failed: 1

   '/Volumes/Dashboards/Preview/Slicer-0-build/python-install/bin/PythonSlicer' 'setup.py' 'install'

  See also

    /Volumes/Dashboards/Preview/Slicer-0-build/python-pyparsing-prefix/src/python-pyparsing-stamp/python-pyparsing-install-*.log
```

I am looking into the details now

**Comment by jcfr** [comment]
Here is the content of `python-pyparsing-install-err.log `:

```
cat /Volumes/Dashboards/Preview/Slicer-0-build/python-pyparsing-prefix/src/python-pyparsing-stamp/python-pyparsing-install-err.log 
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ImportError: No module named setuptools

```

**Comment by jcfr** [comment]
To follow up, the macOS issue is now fixed in [r27995](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27995)

**Comment by jamesobutler** [comment]
I saw that issue on the dashboard today. Not sure why it didn't present itself on yesterdays build and only on one platform. Anyways, thanks for the fix!

**Comment by jcfr** [comment]
> not sure why it didn't present itself on yesterdays build and only on one platform

Since the build is parallel and build of targets depends on how fast some of them finish (in other word, depending on the machine load at that time) ... "luck" is part of it.

We also updated the version of CMake which is itself used in the build process and could be more efficient at performing some task ...

**Pull request closed without merging**
