### PR TITLE
STYLE: Upgrade python syntax to 3.6 and newer

### PR DESCRIPTION
**Pull request by jamesobutler**
This PR uses [`pyupgrade`](https://github.com/asottile/pyupgrade) to automatically upgrade python syntax to newer versions. This ultimately removes Python 2 compatibility. Slicer seemingly hasn't been trying to maintain Python 2 compatibility given that many libraries have already dropped Python 2 support since it went EOL on January 1st 2020. Slicer already includes some f-string formatting only supported by Python 3.6 and newer (See [usage](https://github.com/Slicer/Slicer/blob/master/Modules/Scripted/DICOMLib/DICOMUtils.py#L838) in DICOMUtils.py). Slicer's current Stable past couple of stable releases (4.11.20210226 and 4.11.20200930) have both included Python 3 as well.

Around early April 2019 @jcfr began using scripts, such as [`futurize`](https://python-future.org/futurize.html), provided by https://python-future.org/ to turn Python 2 code into valid Python 3 code. This was because Slicer was in a transition period and the Slicer nightly would begin using Python 3 while Slicer stable would still be using Python 2. This work was documented at https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide#Python_2_to_Python_3 and at https://discourse.slicer.org/t/updating-slicer-to-work-with-python-3/4662/9.

Notably, most of the changes in this PR are changes due to the following commits:
- `STYLE: Update python scripts to use print function for python 3.x`: https://github.com/Slicer/Slicer/commit/7df896e839dc03e1c2f3b5458590ea16e80fcbba
- `STYLE: Update python classes to follow new-style`: https://github.com/Slicer/Slicer/commit/d366e32491d13461c9c6316b3e4ed80fb4279d3f

## Using pyupgrade

- Install: `PythonSlicer -m pip install pyupgrade`
- Running:
  - On 1 file: `PythonSlicer -m pyupgrade --py36-plus MyPythonFile.py`
  - On multiple files: Here is my pyupgrade-script.py written to automate running pyupgrade across all python files in the Slicer repo. It was run by `PythonSlicer pyupgrade-script.py`.
```python
# pyupgrade-script.py
import os
import subprocess

search_directory = "C:/Users/JamesButler/Documents/GitHub/Slicer"
for root, _, files in os.walk(search_directory):
    for file_item in files:
        file_path = os.path.join(root, file_item)
        if os.path.isfile(file_path) and file_path.endswith(".py"):
            subprocess.call(["PythonSlicer", "-m", "pyupgrade", "--py36-plus", file_path])
```

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Thanks a lot for working on this. The changes look good to me. If all tests pass (except those few that already fails) then this should be ready to be merged.

**Comment by jcfr** [comment]
I corroborate with @lassoan, this is great and thanks for the detailed description in the PR :pray: 

Additionally, could you add a section called `Supporting only Python 3.6 and above` to https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide#Slicer_5.0:_API_changes_since_4.10 by copying the content of the PR description ?  

> If all tests pass (except those few that already fails) then this should be ready to be merged.

Makes sense

**Comment by jamesobutler** [comment]
@lassoan I pushed an update to fix a couple tests that had begun to fail due to an error fixing up a weird python print message. It was trying to fix up print messages such as `print("{index:04}\t".format(index="i"), "t\tdt\tt\tdt")`.

With latest changes the failed test cases are the same as the ones already failing on the factory nightly build
```
1>Total Test time (real) = 2358.90 sec
1>
1>The following tests FAILED:
1>	332 - vtkMRMLAnnotationLinesNodeTest1 (Failed)
1>	334 - vtkMRMLAnnotationLinesStorageNodeTest1 (Failed)
```

@jcfr I've added the new section to the migration guide. See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide#Supporting_only_Python_3.6_and_above

**Comment by jamesobutler** [comment]
I have rebased as the circleci is failing because this branch has superbuild items that are different from the latest nightly.

**Review by jcfr — APPROVED** [review]

**Comment by jcfr** [comment]
Suggested follow-up updates:
* [ ] https://github.com/fedorov/MultiVolumeExplorer
* [ ] https://github.com/fedorov/MultiVolumeImporter
* [ ] https://github.com/Slicer/LandmarkRegistration
* [ ] https://github.com/SimpleITK/SlicerSimpleFilters
* [ ] https://github.com/pieper/CompareVolumes

**Comment by jcfr** [comment]
🎉

**Pull request merged**
