### PR TITLE
BUG: Use Spline order for 3 template parameter

### PR DESCRIPTION
**Pull request by blowekamp**
Fix common mistake of using dimension for spline order.

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you, good catch. Could you please add a #define SPLINE_ORDER 3 or something similar and use that instead of magic number 3?

**Comment by lassoan** [comment]
Thanks! I've just noticed that static const int BSPLINE_TRANSFORM_ORDER = 3; is already defined along with static const unsigned int VTKDimension = 3; in vtkITKTransformConverter.h. So, we should just use BSPLINE_TRANSFORM_ORDER as this way both forward and inverse transforms use the same constant.

**Comment by blowekamp** [comment]
I ran into this after seeing some Transform registration warning. And working on this patch for ITK:
http://review.source.kitware.com/#/c/21677/2

**Comment by jcfr** [comment]
Great. Thanks for the patch.

I will test locally and integrate.

This will address http://na-mic.org/Mantis/view.php?id=4290

**Comment by jcfr** [comment]
Integrated in [r25485](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25485)

**Comment by blowekamp** [comment]
Neither of these patches address the warnings posted Slicer is having. The value of the b-spline order is not changed with this patch. It does address the conceptual conflating for the 3rd template parameter. 

The ITK patch http://review.source.kitware.com/#/c/21677/2 address warnings in SimpleITK related to duplicate registration of BSpline Transforms. And Bugs related to IO of BSplines with different orders.

**Pull request closed without merging**
