### PR TITLE
BUG: Update extensions build system to set dependency DIR with sub directory

### PR DESCRIPTION
**Pull request by jcfr**
Cc: @naucoin @fedorov

### CODE REVIEW

**Comment by fedorov** [comment]
:+1: !

**Comment by naucoin** [comment]
Merged: 
https://github.com/Slicer/Slicer/commit/bd066759d74456e56a06b358cac40d045a43b089

**Comment by naucoin** [comment]
@jcfr The SlicerPathology extension was added yesterday which also depends on SlicerOpenCV but it's failing on the find package step:
http://slicer.cdash.org/viewConfigure.php?buildid=818628

The OpenCVExample still has the FindSlicerOpenCV.cmake file included in it's repo and is configuring sucessfully on the dashboard, but I didn't add that file to SlicerPathology. I can add it to get SlicerPathology building quickly, but it seems that this fix isn't quite enough to get the dependent extensions building on the factory.
@fedorov

**Comment by fedorov** [comment]
@naucoin as discussed here https://github.com/SBU-BMI/SlicerOpenCV/issues/6#issuecomment-210730844, what is missing is the dependency subdirectory. 

If I understand correctly, in both of the following `inner-build` should be added in both of these places:

* https://github.com/SBU-BMI/OpenCVExample/blob/master/CMakeLists.txt#L13
* https://github.com/SBU-BMI/SlicerPathology/blob/master/CMakeLists.txt#L13

@jcfr can you please comment if my understanding is correct?

**Comment by naucoin** [comment]
@fedorov My understanding is that the patch that @jcfr  made should automatically add the inner-build subdirectory to the paths that are set by the find package instruction, but the find_package is still failing after that infrastructure change.

**Comment by fedorov** [comment]
My understanding is different, since JC specifically said

> the `FindSlicerOpenCV.cmake` is not needed

we can wait for JC to clarify

**Comment by naucoin** [comment]
@fedorov Agreed, it's not supposed to be necessary, I didn't test the patch thoroughly enough (aka without the FindSlicerOpenCV.cmake included), so I need to find out what is needed for SlicerPathology. I have a patch to add the find file to SlicerPathology if we want to patch it to get the dashboard building until @jcfr  has time to work on the patch.
https://github.com/naucoin/SlicerPathology/tree/Fix-dashboard-building

**Comment by fedorov** [comment]
Can you test specifying extension dependency with subdir and without find.cmake included?

**Comment by naucoin** [comment]
Trying to follow the instructions to build extensions locally like the dashboard does now...

**Comment by naucoin** [comment]
I have to head out soon, haven't been able to get my mini ExtensionsIndex to build (SlicerOpenCV, OpenCVExample, SlicerPathology) due to cmake issues (the compiler variables keep getting reset). I'll do the pull for the find patch with a disclaimer to not merge unless required.
https://github.com/SBU-BMI/SlicerPathology/pull/19

**Comment by jcfr** [comment]
@naucoin  Thanks for the report. I will address these issues shortly and report back.

**Comment by fedorov** [comment]
Guys, this patch does not appear to work - I realized the subdir is already set in SlicerOpenCV, but apparently has no effect to help find the dependency:

https://github.com/SBU-BMI/SlicerOpenCV/blob/master/CMakeLists.txt#L13

@naucoin your patch with FindSlicerOpenCV.cmake that I integrated yesterday does not work either.

http://slicer.cdash.org/viewConfigure.php?buildid=819907

**Comment by jcfr** [comment]
@fedorov I will tackle this today.

**Comment by jcfr** [comment]
Update 1: I was able to reproduce the problem locally.

**Comment by jcfr** [comment]
Update 2: Assuming extension `B` depends on extension 'A' where `A` is a superbuild extension with a subdirectory. These is a problem with having extension B  successfully looking up the subdirectory of extension `A`. Currently working on the problem.

Note: While working on the issue, I "paused" the current nightly build ... I will resume them once I address the issue.

**Comment by jcfr** [comment]
Update 3: Fix implemented locally and tested building an extensions index with only `SlicerOpenCV.s4ext`, `SlicerPathology.s4ext` and `OpenCVExample.s4ext`. Doing final review and testing on other platforms. 

Let's also note that module `FindSlicerOpenCV.cmake` is not needed anymore.

**Comment by jcfr** [comment]
Issue fixed in [r25039](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25039)

**Comment by fedorov** [comment]
Thanks a lot JC!! :+1:

Looking at the dashboard, we are past the configure errors for  both
SlicerPathology and OpenCVExample! Great job!!!

http://slicer.cdash.org/index.php?project=Slicer4&parentid=820563

**Comment by jcfr** [comment]
We are getting closer. Now looking into an other issue.

**Comment by jcfr** [comment]
Linux and MacOSX:
* SlicerOpenCV: Packages uploaded :+1: 
* OpenCVExample: Packages uploaded :+1: 

Linux: 
* SlicerPathology: Package uploaded :+1: 

MacOSX:
* SlicerPathology: Build error. See http://slicer.cdash.org/viewBuildError.php?buildid=820564

Windows:
* SlicerOpenCV failed:

```
opencv_core310.lib(stat.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(lapack.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(parallel.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(mathfuncs.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(umatrix.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(datastructs.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(algorithm.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(opencv_core_pch.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(persistence.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
opencv_core310.lib(tables.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in itkOpenCVVideoIO.obj [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV-build\src\ITKVideoBridgeOpenCV.vcxproj] [C:\D\N\S-1-E-b\SlicerOpenCV-build\ITKVideoBridgeOpenCV.vcxproj]
The maximum number of reported warnings or errors has been reached!!!
```

**Comment by fedorov** [comment]
👍 👍 👍 indeed!

**Comment by jcfr** [comment]
* MacOSX SlicerPathology error will be fixed by https://github.com/SBU-BMI/SlicerPathology/pull/22

* Now looking at windows error for SlicerOpenCV

**Comment by jcfr** [comment]
Re: windows.

Details about `MD` and `MT`: https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx

**Comment by jcfr** [comment]
Re: Windows

Most likely the following option needs to be set to `OFF`:

```
OCV_OPTION(BUILD_WITH_STATIC_CRT    "Enables use of staticaly linked CRT for staticaly linked OpenCV" ON IF MSVC )
```

**Comment by jcfr** [comment]
We should be in a good place now.

**Pull request closed without merging**
