### PR TITLE
COMP: Update FindVcvars with MSVC 1929 support

### PR DESCRIPTION
**Pull request by jamesobutler**
Based on https://github.com/scikit-build/cmake-FindVcvars/pull/1

Required to successfully build an extension such as SlicerRadiomics with latest version of Visual Studio.

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Thank you, it looks good to me.

**Review by lassoan — COMMENTED** [review]
I've just realized that we lost some granularity of the versions here. We don't know anymore the minor version  (in fact, the version is rounded down to the closest integer). How did you check that we did not need this information and rounding down does not cause a problem?

**Comment by jamesobutler** [comment]
> How did you check that we did not need this information and rounding down does not cause a problem?

I just tested it as the current logic of a MSVC_Version matching a Visual Studio version uniquely was no longer true. MSVC 1928 corresponds to both 16.8 AND 16.9 and MSVC 1929 corresponds to both 16.10 and 16.11. As seen in the code below it finds the same path as if you used the previous logic specifying a specific version. I would guess you can use the integer because I don't think it is possible to have install 2 different 16.X versions at the same time.

```cmake
  if(vs_version VERSION_GREATER_EQUAL "15.0")
    # Query the VS Installer tool for locations of VS 2017 and above.
    string(REGEX REPLACE "^([0-9]+)\.[0-9]+$" "\\1" vs_installer_version ${vs_version})
    # vs_installer_version can be "16" here
    cmake_host_system_information(RESULT _vs_dir QUERY VS_${vs_installer_version}_DIR)
    # which successfully returns "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community"
    if(_vs_dir)
      list(APPEND _vs_installer_paths "${_vs_dir}/VC/Auxiliary/Build")
      # which ultimately sets Vcvars as "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/vcvars64.bat"
    endif()
  else()
```
image

**Comment by jamesobutler** [comment]
Does the previous explanation make sense of why this change is appropriate?

**Comment by jamesobutler** [comment]
I will proceed with merging if no additional comments. This will allow for successful building of extensions that utilize this file when building with the latest versions of Visual Studio.

**Pull request merged**
