### PR TITLE
BUG: ExtensionBuildSystem: Update tests to illustrate #4247 failure

### PR DESCRIPTION
**Pull request by jcfr**
Issue report http://na-mic.org/Mantis/view.php?id=4247

```
$ ctest -C Release -R py_cmake_slicer_extensions
Test project /home/jcfr/Projects/Slicer-Release/Slicer-build
    Start  7: py_cmake_slicer_extensions_index_build_without_upload
1/4 Test  #7: py_cmake_slicer_extensions_index_build_without_upload ...............   Passed    7.05 sec
    Start  8: py_cmake_slicer_extensions_index_build_with_upload
2/4 Test  #8: py_cmake_slicer_extensions_index_build_with_upload ..................***Failed   12.53 sec
    Start  9: py_cmake_slicer_extensions_index_build_with_upload_using_ctest
3/4 Test  #9: py_cmake_slicer_extensions_index_build_with_upload_using_ctest ......   Passed   33.31 sec
    Start 10: py_cmake_slicer_extensions_index_build_without_upload_using_ctest
4/4 Test #10: py_cmake_slicer_extensions_index_build_without_upload_using_ctest ...   Passed    7.29 sec
```

To try to make sense of these test results, let's look at what is happening on the factory.

On windows, here are the steps

1. Every night "factory-south-win7.bat" [1] ends up invoking

         `ctest.exe -S "C:\D\DashboardScripts\factory-south-win7-vs2013-64bits_slicerextensions_release_nightly.cmake" -C Release`

2. Then `factory-south-win7-vs2013-64bits_slicerextensions_release_nightly.cmake` is a CTest
    script including [2] the generic driver:

       `SlicerExtensionsDashboardDriverScript.cmake`

  Note: that the test are also using that same generic driver.

3. Then, the driver script ends up invoking `ctest_start`, `ctest_configure`, `ctest_build`, .... [3]

4.  That  `ctest_build` calls end up building the "Regular" extension build project that is reported to fail above.

Still need to investigate ... to sort things out

______________

[1] https://github.com/Slicer/DashboardScripts/blob/41593b8ec76c7f0aacaf44f9057431e89ed0fa6b/factory-south-win7.bat#L58

[2] https://github.com/Slicer/DashboardScripts/blob/41593b8ec76c7f0aacaf44f9057431e89ed0fa6b/factory-south-win7-vs2013-64bits_slicerextensions_release_nightly.cmake#L105

[3] https://github.com/Slicer/Slicer/blob/22d0074d67c21fd8c0c3b68bb0c284289bf01b10/Extensions/CMake/SlicerExtensionsDashboardDriverScript.cmake#L384

### CODE REVIEW

**Comment by jcfr** [comment]
@lassoan  @cpinter @pieper @vovythevov @fedorov @ihnorton 

Could someone try this on windows too, to check if results (which still do  not make sense .. ) are consistent across platform. 

Thanks

**Comment by jcfr** [comment]
Here's the log from @pieper  build:

https://gist.github.com/anonymous/504371ae0c7aae880af676f2063b89de

**Comment by ihnorton** [comment]
Here's log from all tests and then test failure (Windows, x64, debug):

https://gist.github.com/ihnorton/58c9ed1d0dd87fb326407b51ca1f832a

2/3 pass, the issue is:
```
8:       Start 3: FailingTest
8:   Could not find executable invalid_test
8:   Looked in the following places:
8:   Unable to find executable: invalid_test
8:   invalid_test
8:   invalid_test.exe
8:   Debug/invalid_test
8:   Debug/invalid_test.exe
8:   Debug/invalid_test
8:   Debug/invalid_test.exe
8:
8:   3: Test command:
8:   3/3 Test #3: FailingTest ....................................***Not Run   0.00 sec
```

(maybe need a `WILL_FAIL` annotation?)

**Comment by jcfr** [comment]
Thanks.

 > maybe need a WILL_FAIL annotation?)

That test is on purpose failing. But the fact it fails should NOT prevent the extensions from building/packaging.  That is basically what we are testing here. 

Setting `WILL_FAIL` will cause the test to pass .. which is not desired here. See  http://na-mic.org/Mantis/view.php?id=4247

**Comment by ihnorton** [comment]
I'm not really following the cmake/python/cmake all the way down here, but from @lassoan's comment in 4274:

> How ctest.exe knows that ctest_test failed (from parsing XML output file)? How it could be prevented to return with error code?

I wonder if using `RETURN_VALUE` would allow to capture the result and avoid non-zero exit?

**Comment by jcfr** [comment]
@pieper @ihnorton @cpinter @lassoan @fedorov  Et voila, I think the mystery is solved and the problem fixed. 

Would be great if you could give it try on Windows and MacOSX.

I will then get started with the release process after dinner.

Thanks
Jc

**Comment by pieper** [comment]
All passed for me!

**Comment by jcfr** [comment]
Great Thanks for the update

**Comment by jcfr** [comment]
Now checking on windows to confirm it is fine there..

**Comment by jcfr** [comment]
Et voila. It now passes on Windows !

```
C:\D\N\Slicer-1-build\Slicer-build>C:\D\Support\CMake-3.5.0-rc3\bin\ctest.exe -C Release -R py_cmake_slicer_extensions
Test project C:/D/N/Slicer-1-build/Slicer-build
    Start  7: py_cmake_slicer_extensions_index_build_without_upload
1/4 Test  #7: py_cmake_slicer_extensions_index_build_without_upload ...............   Passed   52.57 sec
    Start  8: py_cmake_slicer_extensions_index_build_with_upload
2/4 Test  #8: py_cmake_slicer_extensions_index_build_with_upload ..................   Passed   94.87 sec
    Start  9: py_cmake_slicer_extensions_index_build_with_upload_using_ctest
3/4 Test  #9: py_cmake_slicer_extensions_index_build_with_upload_using_ctest ......   Passed   92.85 sec
    Start 10: py_cmake_slicer_extensions_index_build_without_upload_using_ctest
4/4 Test #10: py_cmake_slicer_extensions_index_build_without_upload_using_ctest ...   Passed   52.24 sec

100% tests passed, 0 tests failed out of 4

Label Time Summary:
CMake    = 292.53 sec (4 tests)

Total Test time (real) = 359.32 sec
```

**Comment by jcfr** [comment]
Gonna integrate now and move forward with da release. Finally

**Comment by jcfr** [comment]
Integrated in  [r25440](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25440), [r25439](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25439) and [r25438](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25438)

Thanks again everyone for helping sort this out. :tada:

**Comment by pieper** [comment]
👍

**Pull request closed without merging**
