### PR TITLE
COMP: fix qt warnings and c++11 errors Plot GUI

### PR DESCRIPTION
**Pull request by Punzo**
fix as reported by @lassoan  https://github.com/Slicer/Slicer/pull/797#issuecomment-333815222
tested on ubuntu 17.10 gcc6.4 qt5/VTK8 qt4/VTK8 (so this fix is not really tested. it needs to be tested on the build with VTK7).

if the fix can wait I'll try to test qt4/VTK7 version on mac El capitan

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks @Punzo , I will test on Linux and macOS and report back.

**Comment by Punzo** [comment]
ok perfect, thanks @jcfr !!

**Comment by Punzo** [comment]
compiled successfully and working on MAC/Qt4/VTK7

**Comment by jcfr** [comment]
Great. Linux is currently building. I will integrate once it completes

**Comment by jcfr** [comment]
Integrated in [r26414](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26414) and [r26415](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26415)

**Comment by Punzo** [comment]
perfect, thanks!

**Pull request closed without merging**
