### PR TITLE
BUG: fix loading multivolumes produced by CLIs

### PR DESCRIPTION
**Pull request by fedorov**
This addresses Slicer issue http://www.na-mic.org/Bug/view.php?id=3382.

The patch has been suggested by Jim Miller (see the Slicer issue).

@millerjv wants to add more comments before this is merged with the Slicer master.

### CODE REVIEW

**Comment by fedorov** [comment]
Forgot to mention - the patch has been tested with PkModeling extension, and the behavior observed is correct and desired.

**Comment by fedorov** [comment]
Thank you Jim! Will you merge, or is there anything else I need to do?

**Comment by millerjv** [comment]
I am not currently listed as a "project collaborator".  Can you merge into Slicer directly from the pull request on github?

**Comment by fedorov** [comment]
I am not a collaborator either. I can commit using SVN route. @jcfr or @pieper - can you advice how to proceed, or merge this pull request? Please let us know if anything else needs to be done before it can be merged.

**Comment by pieper** [comment]
We use the pull requests to organize things, but the final process is to
use git-svn.  Then github.com/Slicer/Slicer is synced back from svn.

That is, if you have your git-svn set up as described in [1] you can just
do:

git svn rebase
git svn dcommit --add-author-from


[1] http://www.slicer.org/slicerWiki/index.php/Slicer:git-svn

**Comment by fedorov** [comment]
@millerjv  let me know if you will do it, or if I should work on the merge.

@pieper so anyone who has permissions to write to svn can also do "git svn dcommit", right?

**Comment by pieper** [comment]
@fedorov yes, the svn commit looks like a normal one from the svn side, so
regular svn permissions apply.  Be aware that the svn commit hooks will
require the ENH:, BUG:, etc commit prefixes so be careful to use those on
your git commits for slicer too.

**Comment by fedorov** [comment]
@pieper as I review the myriad of steps needed for git svn commit, just curious - if I have a branch that has already been reviewed and is ready to commit, why is this git-svn workflow is preferred over just regular svn commit? Or is it?

**Comment by millerjv** [comment]
I think I have it all checked in to git-svn


Jim Miller
Principal Scientist
GE Research
Interventional and Therapy

GE imagination at work





On Jan 12, 2015, at 4:51 PM, Andrey Fedorov <notifications@github.com<mailto:notifications@github.com>> wrote:


@pieper<https://github.com/pieper> as I review the myriad of steps needed for git svn commit, just curious - if I have a branch that has already been reviewed and is ready to commit, why is this git-svn workflow is preferred over just regular svn commit? Or is it?

**Comment by pieper** [comment]
@fedorov - to be honest git svn is not hard at all.  Just a couple steps
and easy once you have done it a time or two.

But on the wish list for a long time has been migrating so that the github
repository is the actual home of slicer and not just a mirror of svn.  We
need to sort out all the steps to clean up old big data commits while
keeping the important history.  I suspect that @jcfr has had enough
practice now with git svn conversions that he knows pretty much exactly
what needs to be done.

**Comment by fedorov** [comment]
Steve, I am not saying it is hard - I just felt intimidated by the wiki page. I guess I would figure it out if I have to, but just tried to understand the logic why we are doing this instead of regular svn commit, what is the benefit.

In any case, postponing this again until the next time, thanks Jim for integrating! Will test tomorrow, and close the Mantis issue when confirmed the issue is resolved.

**Comment by jcfr** [comment]
@fedorov  "[...] why we are doing this instead of regular svn commit, what is the benefit. [...]": 

With svn proper, you have no way of organizing your commits and reviewing them before final integration. Waiting Slicer source code is solely hosted on Github, git-svn provide a very nice alternative.

That said, you could still apply the patches [1] and [2], one by one using directly svn. To do so, you would have to also carefully copy other the commit message. If you commit on behalf of somebody else, you would also have to add the `From: somebody@somewhere.org` field to give the appropriate credit. 

Using `git svn dcommit --add-from-author` provides a convenient way to commit on SVN one or multiple patches keeping track of the original author without doing the manual operation described above.

By also running `./Utilities/SetupForDevelopment.sh` as detailed on [3], local hook will also check that the commit message starts with `ENH:`, ... and have the expected kength. 

[1] https://github.com/fedorov/Slicer/commit/b19be99d9a9bba00219f2ffee29f429ea2b7fe1f.patch

[2] https://github.com/fedorov/Slicer/commit/2ba5ab732aada99948c90a3fa29b5809d3f7ff82.patch

[3] http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/DevelopmentWithGit

**Comment by jcfr** [comment]
Integrated in [r23876](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23876) and [r23877](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23877)

**Pull request closed without merging**
