### PR TITLE
Fix command line extension wizard issues

### PR DESCRIPTION
**Pull request by msmolens**
Fix issues using the command line extension wizard on Windows found when checking the status of http://na-mic.org/Mantis/view.php?id=4182.

Note that the AttributeError and path interpretation problems discussed in the bug are no longer issues with the latest Slicer and Git for Windows that reports the following version:

    $ git --version
    git version 2.12.2.windows.2

### CODE REVIEW

**Comment by vovythevov** [comment]
LGTM, thanks Max !

**Comment by lassoan** [comment]
LGTM

**Comment by jcfr** [comment]
Thanks @msmolens . Could you integrate ?

**Comment by msmolens** [comment]
Thanks, integrated in [r26012](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26012)..[r26013](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26013).

**Pull request closed without merging**
