### PR TITLE
BUG: Update BRAINSTools to BRAINSFit fix for centerOfROI initializer

### PR DESCRIPTION
**Pull request by jcfr**
Tested-by: Hans Johnson <hans-johnson@uiowa.edu>

```
$ git shortlog e257e62...29d203c --no-merges
Alexander Leinoff (5):
      COMP: BCD should only request VTK when building GUI
      COMP: CompareImageFilter should only use VTK when building GUI
      BUG: Replaces all baselines for BCDTests
      BUG: Fixes typo in previous commit
      BUG: Fixes version check in top level CMAKELists.txt

Ali Ghayoor (13):
      ENH: Upgrade vnl_powell to itkPowellOptimizerv4 in BCD
      ENH: Write the debug image based on requested debug level
      ENH: BCD can process input images with different dynamic range
      ENH: Change tolerance and step size for Powell optimizer
      BUG: Fixed a bug in BABC when a low debugLevel requested
      ENH: New parameters for multimodal segmentation in BABC
      ENH: Updated purePlugsThreshold value for AutoWorkup
      BUG: fixed a bug in BABC denoise filtering
      ENH: Initialize a matrix variable
      ENH: remove an intermediate variable to avoid extra memory usage
      BUG: defined an orderedmap class for BABC
      STYLE: Cleanup unnecessary if statement
      ENH: Prevent holes in created brain mask by ROIAutoFilter

Andrey Fedorov (2):
      BUG: fix centerOfROI initializer
      ENH: adjust restriction on the required registration phases

Hans J. Johnson (40):
      ENH: Update ITK, ANTS, and teem
      STYLE: Remove MinSizeRel option
      COMP: Resolve clang static analysis warnings
      BUG:  Compilation error fixed due to typo.
      ENH: Update external tools support.
      COMP: Improve coverage by using removeIntensityOutliers flag.
      COMP: Force C++11 compliance testing
      COMP: Added compatibility testing with apple and CXX11
      BUG: Nipype now reqires invert_initial_moving_transform to be set
      ENH: Selection of denoising filter improved.
      ENH: Changed options to reflect current processing
      ENH: Updated ANTs for improved DenoiseImage
      BUG: The Rician noise model fails for DenoiseImage
      ENH: Added key files for new denoised gaussian images.
      ENH: Use denoised images for atlas reference
      ENH: Add atlas images to reference atlas.
      ENH: Fine-tune denoising options in BAW.
      BUG: Need to work around nipype bug
      ENH: Use denoised t1 from atlas for registration
      ENH: Return to using Rician de-noising from ANTs
      BUG: Error in respecting the NSLOTS variable
      PERF:  Constrain memory usage for KNN phase
      PERF: Update ABC workflow to reflect memory with KNN
      BUG: Serialize printing from threaded sections
      STYLE: Print table consistently
      BUG: Need to pass all denoised images into BRAINSABC
      STYLE: Make usage of variable names consistent
      STYLE: Cleanup unsuded ComputeLabels references
      BUG: Internal ordering for dictionary missed first element
      BUG: This is an unsatisfactory solution
      BUG: Fix to allow all allocated slots to be used
      ENH: Consolidate and syncronize different ANTs run parameters
      BUG: Fix running of ANTs consistently
      ENH: Add N4 bias correction after denoising
      BUG: Missing ',' in python list.
      ENH: Improve error reporting for improper input
      STYLE: Uniformly describe registration parameters.
      PERF: New AntsJointFusion is well multithreaded
      ENH: Add automatic image unwrapping
      BUG: Fix mismatched function parameter calls.

Jean-Christophe Fillion-Robin (1):
      COMP: Force CMAKE_CONFIGURATION_TYPES only when using multi-config generator

Regina Kim (7):
      BUG: Fix Landmark Workflow
      ENH: Update antsDenoise IO specification
      ENH: Rewording to JointFusion from MALF
      ENH: Linear Regression Rescaling
      ENH: JointFusion Update for T2
      ENH: Add JointFusion masking option
      ENH: 1.5 Tesla T2-w excluded from JointFusion
```

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov @hjmjohnson

**Comment by fedorov** [comment]
Thank you @jcfr and@hjmjohnson!

**Comment by jcfr** [comment]
I confirmed it also build on Ubuntu 15.10

Integrated in [r24963](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24963)

**Comment by jcfr** [comment]
@fedorov The update is now causing EMSegment tests to fail.

See http://slicer.cdash.org/viewTest.php?onlyfailed&buildid=788537

```
TCL: Executing "/Users/kitware/Dashboards/Nightly/Slicer-0-build/Slicer-build/lib/Slicer-4.5/cli-modules/BRAINSFit" 
  --backgroundFillValue 0.0 --interpolationMode Linear --outputVolumePixelType short 
  --fixedVolume "/tmp/EMS1292024541eciUOv_vtkMRMLScalarVolumeNode13.nrrd" --movingVolume "/tmp/EMS1849305770hJ6aw4_vtkMRMLScalarVolumeNode1.nrrd" 
  --outputVolume "/tmp/EMS751253359MAH9Te_vtkMRMLScalarVolumeNode23.nrrd" 
  --outputTransform "/tmp/EMS1258844000MOUG9u_vtkMRMLLinearTransformNode1.h5" --useRigid 
  --useScaleSkewVersor3D --useAffine 
  --initializeTransformMode useCenterOfHeadAlign --minimumStepLength 0.005 
  --translationScale 1000 --reproportionScale 1 --skewScale 1 --maskProcessingMode NOMASK 
  --numberOfHistogramBins 40 --numberOfMatchPoints 10 --costMetric MMI 
  --fixedVolumeTimeIndex 0 --movingVolumeTimeIndex 0 --numberOfThreads -1 
  --debugLevel 0 --failureExitCode -1
Error executing __tpycl_result = slicer.NnttIqWZ.PrintText('TCL: Original Fixed image origin[119.531, 92.25, 119.531, 0]\n
TranformTypes: Rigid(1 of 3).\n\n
TranformTypes: ScaleSkewVersor3D(2 of 3).\n\n
TranformTypes: Affine(3 of 3).\n\n
Initializing transform with useCenterOfHeadAlign\n
terminate called after throwing an instance of 'itk::ExceptionObject'\n  what():  /Users/kitware/Dashboards/Nightly/Slicer-0-build/BRAINSTools/BRAINSCommonLib/BRAINSFitHelperTemplate.hxx:183:\n
itk::ERROR: FAILURE:  Improper mode for initializeTransformMode: useCenterOfHeadAlign')
(<type 'exceptions.SyntaxError'>, SyntaxError('invalid syntax', ('<string>', 1, 319, "__tpycl_result = slicer.NnttIqWZ.PrintText('TCL: Original Fixed image origin[119.531, 92.25, 119.531, 0]\\nTranformTypes: Rigid(1 of 3).\\n\\n
TranformTypes: ScaleSkewVersor3D(2 of 3).\\n\\n
TranformTypes: Affine(3 of 3).\\n\\n
Initializing transform with useCenterOfHeadAlign\\n
terminate called after throwing an instance of 'itk::ExceptionObject'\\n
  what():  /Users/kitware/Dashboards/Nightly/Slicer-0-build/BRAINSTools/BRAINSCommonLib/BRAINSFitHelperTemplate.hxx:183:\\n
itk::ERROR: FAILURE:  Improper mode for initializeTransformMode: useCenterOfHeadAlign')\n
")), <traceback object at 0x14e910998>)
```

Given the error message `Improper mode for initializeTransformMode: useCenterOfHeadAlign`, it seems to be related to https://github.com/BRAINSia/BRAINSTools/commit/12b796caac722863972c3d43d8502fffbab613f1 

I think that the [this](https://github.com/BRAINSia/BRAINSTools/blob/12b796caac722863972c3d43d8502fffbab613f1/BRAINSCommonLib/BRAINSFitHelperTemplate.hxx#L180-L184) snippet:

```
    if( movingMask.IsNull() || fixedMask.IsNull() )
      {
      itkGenericExceptionMacro(<< "FAILURE:  Improper mode for initializeTransformMode: "
                               << initializeTransformMode);
      }
```

needs to be moved inside the `if(initializeTransformMode == "useCenterOfROIAlign")` block.

Considering that the other block `else if( initializeTransformMode == "useCenterOfHeadAlign" )` account for null `moving` or `fixed` mask, that is most likely a valid fix.

**Comment by fedorov** [comment]
@jcfr yes, I think you are absolutely correct. I will submit a patch. Thank you.

**Pull request closed without merging**
