### PR TITLE
COMP: Fix debug build building curl library without "-d" postfix

### LINKED ISSUE #4998: mac build error with libcurl
```
make[5]: *** No rule to make target `/sr/curl-install/lib/libcurl.a', needed by `bin/libRemoteIO.dylib'.  Stop.
make[4]: *** [Libs/RemoteIO/CMakeFiles/RemoteIO.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [Slicer-prefix/src/Slicer-stamp/Slicer-build] Error 2
make[1]: *** [CMakeFiles/Slicer.dir/all] Error 2
make: *** [all] Error 2
```
## Steps to reproduce

Building current master 128fb86dd18040d9f7871d2276346e093d3248ae

Wiped out all curl and Slicer directories from the build tree.

## Environment
macOS 10.14.6
```
$ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### PR DESCRIPTION
**Pull request by jcfr**
Fixes #4998

### CODE REVIEW

**Comment by cpinter** [comment]
LGTM, thanks! How can I approve this?
(Btw what are you doing up this late? :) )

**Comment by cpinter** [comment]
Got it. Merging.

**Comment by jcfr** [comment]
> (Btw what are you doing up this late? :) )

Got "stuck" finalizing the update to OpenSSL 1.1.1g ... should be done shortly.

**Comment by pieper** [comment]
🙏 !!!

**Comment by cpinter** [comment]
Agreed, thank you so much @jcfr !

**Pull request merged**
