### PR TITLE
Added Tables support

### PR DESCRIPTION
**Pull request by lassoan**
* New module added: Tables. Create create/view/edit/delete tables, freeze column/row header, lock to read-only (vtkMRMLTableNode).
* Tables can be shown in the view layout (new layout added: Four-up table, more can be added as needed)
* Load/save csv, tsv, txt files as table nodes
* Copy-paste to/from Excel
* SubjectHierarchy plugin (show/hide, edit, clone tables)
* Use tables as input/output for CLI modules (PET Standard Uptake Value Computation module is updated to use tables; there was no need to change the Slicer Execution Model, the Table data type was already usable)
* Reusable widget added for viewing/editing tables in C++ and Python modules

Demo video: https://youtu.be/tNrAut6WD_k

This pull request is to facilitate testing and review, I'll squash all the commits and integrate when the trunk is not frozen anymore and other pull requests are merged.

### CODE REVIEW

**Comment by pieper** [comment]
Wow!!!

**Comment by fedorov** [comment]
+ one more wow!

On Tue, Nov 24, 2015, 17:06 Steve Pieper <notifications@github.com> wrote:

> Wow!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/422#issuecomment-159420266>.
>
-- 

Sent from on the go

**Comment by jcfr** [comment]
:8ball:

**Comment by jcfr** [comment]
@lassoan Is the commit of #409 the same as aeebc8e ?

**Comment by lassoan** [comment]
Yes, the commit of #409 is the same as  aeebc8e.

**Comment by jcfr** [comment]
Great I will review carefully #409 and look into splitting into smaller commits.

**Comment by lassoan** [comment]
#409 was a prerequisite for this, but I couldn't wait until it gets merged into the trunk, so I had to include it in this branch, too.

**Comment by jcfr** [comment]
Makes sense. That won't be a problem.

**Comment by agirault** [comment]
It looks awesome, I could really use this later on, thank you!

Just one thing that could be interesting : you could clear the selection after deleting rows/columns of the QTableWidget by using clearSelection inherited from QAbstractItemView [1]. I find it a little confusing when rows are selected after I delete some others, like I am not sure what was deleted.

Just the same I like to use selectRow() and selectColumn() after I add one of those, inherited by QTableView [2].

[1] http://doc.qt.io/qt-4.8/qabstractitemview.html#clearSelection
[2] http://doc.qt.io/qt-4.8/qtableview.html#selectColumn

**Comment by lassoan** [comment]
@agirault Thanks for the feedback. I'll implement removal of selection.

**Comment by lassoan** [comment]
Integrated in rev 24783

**Pull request closed without merging**
