### PR TITLE
ENH: Simplify single-image capture in ScreenCapture module

### PR DESCRIPTION
**Pull request by lassoan**
Instead of having an obscure "single" button next to the "number of frames" selector, add a "none" animation mode and make it the default. Options that are not relevant are not just disabled but hidden, to make it easier for the user to find the relevant options.

| Before | After |
|--|--|
| image | image |

### CODE REVIEW

**Review by pieper — DISMISSED** [review]
This is a great idea.  I'm not sure "Animation mode" of None will make sense to people.  How about just "Capture mode" of "Single Frame", "Sweep animation", "Rotate animation" etc to be explicit?

**Comment by jamesobutler** [comment]
I agree with Steve. User's likely don't expect to have to make a decision about anything Animation related when desiring a single capture. However if it was named "Capture Mode" then it being "Single Frame" makes sense with other options being different animation types. The question would be whether users who are looking for animation would be confused about it being in a Capture mode setting.

**Comment by pieper** [comment]
I'm thinking we might also want a mode that records a frame whenever a node is updated.  Like if you wanted to make a recording of a simulation.

**Comment by lassoan** [comment]
Good suggestions, I'll use "Capture mode".

For recording on node change: we already have a sequence mode that kind of does this. It is a bit complicated because you need to set what nodes are recorded. How would you simplify selection of the observed nodes? Would you record on real-time? How would it be different from a screen capture?

**Comment by pieper** [comment]
Regarding the triggering on a node change, I was thinking it could be just a node selector.  It would just trigger saving a frame whenever that node was modified.  

But now that I think about it maybe a better would be to record a frame every time a render completes.  That way, for example, you could be interacting with something that is slow to compute or render, but then playback in at whatever speed you want.  Or if it was an automated thing, like a simulation or iterative segmentation that takes a long time you could easily record the evolution of it to replay later.

**Comment by jcfr** [comment]
The changes have been rebased against current `main` to account for recent changes related to double-quotes[^1] and docstrings[^2]. 

[^1]: https://github.com/Slicer/Slicer/pull/7345
[^2]: https://github.com/Slicer/Slicer/pull/7387

**Comment by jcfr** [comment]
To follow-up, the last commit rename "Animation mode" to "Capture mode" and change the default "none" animation mode to "single frame".

**Comment by jcfr** [comment]
@lassoan @pieper @jamesobutler Now that the pull request was updated and that a new issue[^1] was created to capture the suggestion, any objection to move forward with integration ?

[^1]: https://github.com/Slicer/Slicer/issues/7405

**Review by lassoan — COMMENTED** [review]
Thank you very much, it all looks good. Since it was my own PR, I cannot submit a review or approve.

**Review by jcfr — APPROVED** [review]

**Pull request merged**
