### PR TITLE
COMP: Set the c++ standard version to 14

### PR DESCRIPTION
**Pull request by hjmjohnson**
Most current compilers default to c++14, and all
supported Slicer compilers support c++14 syntax.

C++ 14 is necessary for newer versions of ITK.

Qt 6.2 will require c++17 or greater support.

### CODE REVIEW

**Comment by ebrahimebrahim** [comment]
See also https://github.com/Slicer/Slicer/pull/5954

**Comment by jcfr** [comment]
Thanks @hjmjohnson :pray:

@jamesobutler what do you think of using `cmake_minimum_required(VERSION 3.16.3...3.19.7 FATAL_ERROR)` in #5954

**Comment by jamesobutler** [comment]
Sure I can update that commit in #5954 with that change. 

Also note @hjmjohnson there is currently https://github.com/Slicer/Slicer/pull/6108 with work towards C++17 to prep for Qt6.

**Comment by jamesobutler** [comment]
#5954 has now been officially updated with the `cmake_minimum_required(VERSION 3.16.3)` -> `cmake_minimum_required(VERSION 3.16.3...3.19.7 FATAL_ERROR)` change.

**Comment by hjmjohnson** [comment]
@jamesobutler   I love the idea of moving directly to C++17.  This PR looks redundant with your changes.  I'll close this and watch your PR more closely.   Thank you for doing the preliminary work.  I'm willing to put in some effort to get BRAINSTools working smoothly in Slicer if necessary.

I am a little concerned that there is a lot going on in the PR, and it seems to have been open for a long time.    Can I help to get it out of DRAFT mode?

Thanks,
Hans

**Comment by jamesobutler** [comment]
Hi @hjmjohnson a lot of it is draft mode because Slicer was planning to issue a new Stable release and these updates to CMake version, C++ version, other dependencies were all being held up until that release was going to cut. This being because we would be entering a new period of potential unstability with mass changes to the repo.

**Comment by hjmjohnson** [comment]
@jamesobutler  That makes a lot of sense. I thought the stable release was happening last month.  Sorry for my confusion.

Do you have an ETA on when the next stable release will be tagged?

Hans

**Comment by jamesobutler** [comment]
To follow up the update to C++14 will be proceeding instead of waiting for a new Slicer stable release to be cut. More details at https://github.com/Slicer/Slicer/pull/5954#issuecomment-1040636979.

**Pull request closed without merging**
