### PR TITLE
ENH: Removed legacy BSplineToDeformationField module

### PR DESCRIPTION
**Pull request by lassoan**
BSplineToDeformationField could convert certain bspline transform type to displacement field. The module was limited what transform types it can handle.

Conversion for all transform types was already available for users in the transforms module (and for other modules in the transforms module logic).

Remove BSplineToDeformationField module to reduce user confusion (see https://discourse.slicer.org/t/bspline-to-deformation-field-error/503) and reduce overall Slicer core size and maintenance workload.

### CODE REVIEW

**Comment by fedorov** [comment]
The reason this module was added was to support EMSegmenter needs. I don't know what is the current status of EMSegmenter and whether it is still used there.

**Comment by lassoan** [comment]
Thanks for the hint. I've checked the source code of all current extensions in the ExtensionIndex and none of them use this module.

EMSegmenter uses BRAINSTransformConvert now. BRAINSTransformConvert essentially does the same, converts transforms to displacement fields, but works for current bspline transform format.

**Comment by fedorov** [comment]
Great - sorry for the false alarm! I am glad this tool can finally be phased out.

**Comment by lassoan** [comment]
Committed as r26100

**Pull request closed without merging**
