### PR TITLE
DOC: Update operating system versions for recent Slicer stable

### PR DESCRIPTION
**Pull request by jamesobutler**
The recent slicer stable is referring to Slicer-4.11.20200930

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you, good catch!

Readthedocs is already versioned (I've just enabled building of stable tag):
https://slicer.readthedocs.io/en/stable/
https://slicer.readthedocs.io/en/latest/

Since the doc always refers to the "current" version (that users can choose in the readthedocs version selector), I think we can remove reference to stable/preview version and only write about what is applicable to the current version (remove the table and just list OS requirements for the current master version).

Could you update the pull request accordingly? Thank you!

**Comment by jamesobutler** [comment]
I've pushed an update to remove the Stable/Preview specification.  

I guess this means I'm unable to update the current stable documentation to fix the operating system version requirements because it has already been released and there is no maintenance branch for building the latest stable documentation.

**Comment by lassoan** [comment]
Good point. Although we don't plan to release not patches for 4.11, we can still create a branch from the 20200930 version and update the documentation. I've created a v4.11 for this purpose and enabled documentation generation for it: https://slicer.readthedocs.io/en/v4.11/ (and disabled documentation generation for the `stable` tag to keep things more clear).

You can send a pull request to the v4.11 branch.

**Review by lassoan — APPROVED** [review]
thank you, this looks good

**Pull request merged**
