### PR TITLE
Update VTK, vtkAdon and CTK to backport OpenXR and OpenXRRemoting updates 

### PR DESCRIPTION
**Pull request by jcfr**
To minimize changes prior to Slicer 5.2 release, this pull request attempts to backport the minimum set of VTK commits allowing to integrate OpenXR and OpenXRRemoting update.

## Build and testing

  * [ ] `metroplex` (linux) :question:
  * [ ] `computron` (macOS) :question:
  * [ ] `factory-south-macos` (macOS) :question: 
  * [ ] `overload` (Windows) :question:

### CODE REVIEW

**Comment by jcfr** [comment]
@lassoan @pieper @jamesobutler After finalizing testing on macOS and Windows, and also plan to move forward with integration.

**Comment by lassoan** [comment]
Sounds good. It's better to integrate sooner than later to have more time for testing.

**Comment by jcfr** [comment]
Since I had a chance to only perform minimal testing locally, I will move forward with the integration and monitor the dashboard.

**Comment by jcfr** [comment]
The error reported on the dashboard is due to me forgetting to push my local changes associated with the SurfaceToolbox project.

I will publish these later today and re trigger the builds for the sake of having installers to test.

**Comment by jcfr** [comment]
>  forgetting to push my local changes associated with the SurfaceToolbox project

Regression fixed in https://github.com/Slicer/Slicer/pull/6571

**Pull request merged**
