### PR TITLE
ENH: Enable gesture interactions in Slice and 3D views

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Adds Qt gesture interactions for pinch, rotate and pan gestures

Pinch:
- Slice view: Zoom in and out at mouse location
- 3D view: Zoom in and out at focal point

Rotate:
- Slice view: If slice intersection is visible, rotate parallel slices around current slice
- 3D view: Roll camera around current forward direction

Pan:
- Slice view: Translate slice plane
- 3D view: Translate camera position and focal point

___

Supersedes: https://github.com/Slicer/Slicer/pull/970

Requires a few changes in VTK to ensure that gestures are correctly captured:
https://github.com/Sunderlandkyl/VTK/commit/3ed40faaf3c785084f6eb13d562b30087d3010d6

Example video here:
https://www.dropbox.com/s/3zif5a4kvrad8xj/gesture_demo_2.mp4?dl=0

___

TODO:
- [x] Test gestures on touchscreen

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for updating the PR :+1: 

> Requires a few changes in VTK to ensure that gestures are correctly captured:
Sunderlandkyl/VTK@3ed40fa

Did you already created a MR to get these changes upstreamed into VTK ? See https://gitlab.kitware.com/vtk/vtk/blob/master/CONTRIBUTING.md

**Comment by Sunderlandkyl** [comment]
> Did you already created a MR to get these changes upstreamed into VTK ?

Not yet. There are already some changes integrated in VTK from the previous iteration of this pull request, but some more changes were required to re-enable support and for some of the gestures.

I'm going to set about making a merge request, and then post here once it's submitted.

**Comment by lassoan** [comment]
@Sunderlandkyl Before we send the VTK upstream merge request, check Windows touchscreen events as well.

**Comment by jcfr** [comment]
Closing. Corresponding changes integrated in [r28095](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28095)

**Comment by lassoan** [comment]
@Sunderlandkyl Can you remind me what's the status of this PR? Thanks!

**Comment by Sunderlandkyl** [comment]
@lassoan Several outstanding issues:
- Repeatedly zooming in and out with the pinch gesture causes a gradual pan towards the edge of the view
- Using the pinch gesture on a 3D view with perspective projection can cause the focal point to shift as the camera approaches the focal point

**Comment by Sunderlandkyl** [comment]
Alright, the dependencies for this pull request are now merged in VTK, albeit in the master branch.
https://gitlab.kitware.com/vtk/vtk/commit/6488ef5d38d2eae1ff79d78a0922a7f5b6af828f

@jcfr @lassoan Should I backport this commit and make a pull request for Slicer/VTK?

**Comment by jcfr** [comment]
@Sunderlandkyl I added as a collaborator to the Slicer/VTK repository, you should be able to backport the commit and publish them to the branch currently [used in Slicer](https://github.com/Slicer/Slicer/blob/ff55de1e20c7f5b1b1cd8fbb0e7e70e2f2568478/SuperBuild/External_VTK.cmake#L125).

See https://github.com/Slicer/VTK/tree/slicer-v8.2.0-2018-10-02-74d9488523

When backporting commits, considering:
* adding the prefix "[backport]" to the commit message title
* adding a string like `Cherry-picked commit ece6fe4 from main VTK repository.`

After cherry-picking each change, considering amending the commit using a command like `git commit --amend --no-verify`. This will allow you to update message title/body without having the VTK pre-commit hook complaining.

**Comment by Sunderlandkyl** [comment]
OK, I've backported the commit to the Slicer/VTK branch: https://github.com/Slicer/VTK/commit/c1898ef4f2732ad1cba034208f7293e5dac2e621

This should be ready now.

**Comment by jcfr** [comment]
Great. After you confirm it builds, consider create a PR for Slicer by updating this code:

https://github.com/Slicer/Slicer/blob/217c804931161aa0f75f0fd3ca08f6b980b432ea/SuperBuild/External_VTK.cmake#L124-L126

to be

```
if("${Slicer_VTK_VERSION_MAJOR}" STREQUAL "8")
  set(_git_tag "c1898ef4f2732ad1cba034208f7293e5dac2e621") # slicer-v8.2.0-2018-10-02-74d9488523
else()
```

Here is an example of commit message: https://github.com/Slicer/Slicer/commit/bc405ca57208886d7dae3200f08fee32cbfe4ad7

Adding this details help when we craft the release notes.

**Comment by Sunderlandkyl** [comment]
Moved the VTK tag change to separate pull request.

Previous build circleci:
https://circleci.com/gh/Slicer/Slicer/4172?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

VTK change pull request:
https://github.com/Slicer/Slicer/pull/1172

**Comment by jcfr** [comment]
Corresponding VTK changes have been integrated in #1172 

Now, should we move forward with integration of this topic ?

**Comment by lassoan** [comment]
Yes, please (I've asked @Sunderlandkyl this afternoon and he confirmed that it is ready to merge)

**Comment by jcfr** [comment]
Closing. I fixed few warnings and integrated in [r28385](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28385)

**Pull request closed without merging**
