### PR TITLE
ENH: Allow bundling superbuild-type extensions - WIP

### PR DESCRIPTION
**Pull request by lassoan**
Superbuild-type extension can be bundled to the Slicer package by adding it to Slicer_EXTENSION_SOURCE_DIRS.

Work in progress - do not merge it yet.

### CODE REVIEW

**Comment by lassoan** [comment]
@jcfr I've implemented what you recommended and tried to bundle SlicerVirtualReality extension to Slicer. Configuration was successful, required libraries are found, dependency added to Slicer, etc. 

However, while building VTKRenderingOpenVR I get this error:

```
1436: 32>------ Build started: Project: VTKRenderingOpenVR, Configuration: Release x64 ------
1484: 32>  Building Custom Rule C:/D/S4/CMakeLists.txt
1485: 32>  CMake does not need to re-run because C:/D/S4RVr/CMakeFiles/generate.stamp is up-to-date.
1486: 32>  Creating directories for 'VTKRenderingOpenVR'
1489: 32>  No download step for 'VTKRenderingOpenVR'
1490: 32>  No update step for 'VTKRenderingOpenVR'
1501: 32>  No patch step for 'VTKRenderingOpenVR'
1506: 32>  Performing configure step for 'VTKRenderingOpenVR'
1514: 32>  loading initial cache file C:/D/S4RVr/VTKRenderingOpenVR-prefix/tmp/VTKRenderingOpenVR-cache-Release.cmake
1709: 32>  -- The C compiler identification is MSVC 19.0.24215.1
1836: 32>  -- The CXX compiler identification is MSVC 19.0.24215.1
1854: 32>  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
2142: 32>  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
2145: 32>  -- Detecting C compiler ABI info
2296: 32>  -- Detecting C compiler ABI info - done
2297: 32>  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
2448: 32>  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
2450: 32>  -- Detecting CXX compiler ABI info
2733: 32>  -- Detecting CXX compiler ABI info - done
2734: 32>  -- Detecting CXX compile features
3757: 32>  -- Detecting CXX compile features - done
4116: 32>  -- Performing Test VTK_UNDEFINED_SYMBOLS_ALLOWED - Failed
4130: 32>  -- Found OpenVR: C:/D/S4RVr/OpenVR/headers
4136: 32>  -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
4206: 32>  -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
4208: 32>  -- Performing Test COMPILER_HAS_DEPRECATED
4342: 32>  -- Performing Test COMPILER_HAS_DEPRECATED - Success
4361: 32>  -- Found OpenGL: opengl32
4365: 32>  -- Configuring done
4399: 32>  -- Generating done
4402: 32>  -- Build files have been written to: C:/D/S4RVr/VTKRenderingOpenVR-build
4408: 32>  Performing build step for 'VTKRenderingOpenVR'
4416: 32>  Microsoft (R) Build Engine version 14.0.25420.1
4417: 32>  Copyright (C) Microsoft Corporation. All rights reserved.
4418: 32>
4419: 32>  Build started 3/7/2018 6:50:16 PM.
4456: 32>  Project "C:\D\S4RVr\VTKRenderingOpenVR-build\ALL_BUILD.vcxproj" on node 1 (default targets).
4457: 32>  Project "C:\D\S4RVr\VTKRenderingOpenVR-build\ALL_BUILD.vcxproj" (1) is building "C:\D\S4RVr\VTKRenderingOpenVR-build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
4458: 32>  PrepareForBuild:
4459: 32>    Creating directory "x64\Release\ZERO_CHECK\".
4460: 32>    Creating directory "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\".
4461: 32>  InitializeBuildStatus:
4462: 32>    Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
4468: 32>  CustomBuild:
4469: 32>    Checking Build System
4476: 32>    CMake does not need to re-run because C:/D/S4RVr/VTKRenderingOpenVR-build/CMakeFiles/generate.stamp is up-to-date.
4480: 32>  FinalizeBuildStatus:
4482: 32>    Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
4484: 32>    Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
4486: 32>  Done Building Project "C:\D\S4RVr\VTKRenderingOpenVR-build\ZERO_CHECK.vcxproj" (default targets).
4491: 32>  Project "C:\D\S4RVr\VTKRenderingOpenVR-build\ALL_BUILD.vcxproj" (1) is building "C:\D\S4RVr\VTKRenderingOpenVR-build\vtkRenderingOpenVR.vcxproj" (3) on node 1 (default targets).
4492: 32>  Project "C:\D\S4RVr\VTKRenderingOpenVR-build\vtkRenderingOpenVR.vcxproj" (3) is building "C:\D\S4RVr\VTKRenderingOpenVR-build\vtkRenderingOpenVRHierarchy.vcxproj" (4) on node 1 (default targets).
4493: 32>  PrepareForBuild:
4494: 32>    Creating directory "x64\Release\vtkRenderingOpenVRHierarchy\".
4495: 32>    Creating directory "x64\Release\vtkRenderingOpenVRHierarchy\vtkRende.26BE7FFC.tlog\".
4497: 32>  InitializeBuildStatus:
4498: 32>    Creating "x64\Release\vtkRenderingOpenVRHierarchy\vtkRende.26BE7FFC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
4502: 32>  CustomBuild:
4503: 32>    Building Custom Rule C:/D/S4RVr/VTKv9/Rendering/OpenVR/CMakeLists.txt
4509: 32>    CMake does not need to re-run because C:/D/S4RVr/VTKRenderingOpenVR-build/CMakeFiles/generate.stamp is up-to-date.
4511: 32>    For vtkRenderingOpenVR - updating vtkRenderingOpenVRHierarchy.txt
4631: 32>  FinalizeBuildStatus:
4632: 32>    Deleting file "x64\Release\vtkRenderingOpenVRHierarchy\vtkRende.26BE7FFC.tlog\unsuccessfulbuild".
4633: 32>    Touching "x64\Release\vtkRenderingOpenVRHierarchy\vtkRende.26BE7FFC.tlog\vtkRenderingOpenVRHierarchy.lastbuildstate".
4634: 32>  Done Building Project "C:\D\S4RVr\VTKRenderingOpenVR-build\vtkRenderingOpenVRHierarchy.vcxproj" (default targets).
4635: 32>  PrepareForBuild:
4636: 32>    Creating directory "vtkRenderingOpenVR.dir\Release\".
4637: 32>    Creating directory "C:\D\S4RVr\Release\".
4639: 32>    Creating directory "vtkRenderingOpenVR.dir\Release\vtkRende.0453B28D.tlog\".
4640: 32>  InitializeBuildStatus:
4641: 32>    Creating "vtkRenderingOpenVR.dir\Release\vtkRende.0453B28D.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
4642: 32>  CustomBuild:
4643: 32>    Building Custom Rule C:/D/S4RVr/VTKv9/Rendering/OpenVR/CMakeLists.txt
4644: 32>    CMake does not need to re-run because C:/D/S4RVr/VTKRenderingOpenVR-build/CMakeFiles/generate.stamp is up-to-date.
4645: 32>  ClCompile:
4646: 32>    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /I"C:\D\S4RVr\VTKRenderingOpenVR-build" /IC:\D\S4RVr\VTKv9\Rendering\OpenVR /I"C:\D\S4RVr\VTKv9-build\Common\Core" /IC:\D\S4RVr\VTKv9\Common\Core /I"C:\D\S4RVr\VTKv9-build\Utilities\KWIML" /IC:\D\S4RVr\VTKv9\Utilities\KWIML /I"C:\D\S4RVr\VTKv9-build\Utilities\KWSys" /IC:\D\S4RVr\VTKv9\Utilities\KWSys /I"C:\D\S4RVr\VTKv9-build\ThirdParty\utf8" /IC:\D\S4RVr\VTKv9\ThirdParty\utf8 /I"C:\D\S4RVr\VTKv9-build\Filters\Sources" /IC:\D\S4RVr\VTKv9\Filters\Sources /I"C:\D\S4RVr\VTKv9-build\Common\ComputationalGeometry" /IC:\D\S4RVr\VTKv9\Common\ComputationalGeometry /I"C:\D\S4RVr\VTKv9-build\Common\DataModel" /IC:\D\S4RVr\VTKv9\Common\DataModel /I"C:\D\S4RVr\VTKv9-build\Common\Math" /IC:\D\S4RVr\VTKv9\Common\Math /I"C:\D\S4RVr\VTKv9-build\Common\Misc" /IC:\D\S4RVr\VTKv9\Common\Misc /I"C:\D\S4RVr\VTKv9-build\Common\System" /IC:\D\S4RVr\VTKv9\Common\System /I"C:\D\S4RVr\VTKv9-build\Common\Transforms" /IC:\D\S4RVr\
4647: 32>    vtkOpenVRCamera.cxx
4661: 32>    vtkOpenVRControlsHelper.cxx
4662: 32>    vtkOpenVRDefaultOverlay.cxx
4663: 32>    vtkOpenVRFollower.cxx
4664: 32>    vtkOpenVRHardwarePicker.cxx
4665: 32>C:\D\S4RVr\VTKv9\Rendering\OpenVR\vtkOpenVRHardwarePicker.cxx(108): warning C4838: conversion from 'int' to 'unsigned int' requires a narrowing conversion [C:\D\S4RVr\VTKRenderingOpenVR-build\vtkRenderingOpenVR.vcxproj]
4683: 32>    vtkOpenVRInteractorStyle.cxx
4720: 32>    vtkOpenVRMenuRepresentation.cxx
4748: 32>    vtkOpenVRMenuWidget.cxx
4751: 32>    vtkOpenVRModel.cxx
4758: 32>    vtkOpenVROverlay.cxx
4763: 32>    vtkOpenVRPanelRepresentation.cxx
4764: 32>    vtkOpenVRPanelWidget.cxx
4765: 32>    vtkOpenVRPropPicker.cxx
4766: 32>    vtkOpenVRRenderer.cxx
4767: 32>    vtkOpenVRRenderWindow.cxx
4805: 32>    vtkOpenVRRenderWindowInteractor.cxx
5019: 32>    Generating Code...
5241: 32>  MakeDirsForLink:
5242: 32>    Creating directory "C:\D\S4RVr\VTKRenderingOpenVR-build\Release\".
5244: 32>  Link:
5246: 32>    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\D\S4RVr\Release\vtkRenderingOpenVR-9.0.dll" /INCREMENTAL:NO /NOLOGO C:\D\S4RVr\OpenVR\lib\win64\openvr_api.lib glu32.lib opengl32.lib "C:\D\S4RVr\VTKv9-build\lib\Release\vtkInteraction-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkOpenGL-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkglew-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkDomainsChemistry-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkRendering-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkIO-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkexodusII-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtktheora-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkogg-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtknetcdf-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkhdf5_src-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkhdf5_hl_src-9.0.lib" "C:\D\S4RVr\VTKv9-build\lib\Release\vtkfreetype-9.0.lib" "C:\D\S4RVr\zlib-i
5249: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRControlsHelper.obj
5250: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRDefaultOverlay.obj
5252: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRFollower.obj
5254: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRHardwarePicker.obj
5256: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRInteractorStyle.obj
5258: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRMenuRepresentation.obj
5260: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRMenuWidget.obj
5262: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRModel.obj
5264: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVROverlay.obj
5266: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRPanelRepresentation.obj
5267: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRPanelWidget.obj
5269: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRPropPicker.obj
5271: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRRenderer.obj
5273: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRRenderWindow.obj
5274: 32>    vtkRenderingOpenVR.dir\Release\vtkOpenVRRenderWindowInteractor.obj
5317: 32>       Creating library C:/D/S4RVr/VTKRenderingOpenVR-build/Release/vtkRenderingOpenVR-9.0.lib and object C:/D/S4RVr/VTKRenderingOpenVR-build/Release/vtkRenderingOpenVR-9.0.exp
5348: 32>    vtkRenderingOpenVR.vcxproj -> C:\D\S4RVr\Release\vtkRenderingOpenVR-9.0.dll
5349: 32>  FinalizeBuildStatus:
5350: 32>    Deleting file "vtkRenderingOpenVR.dir\Release\vtkRende.0453B28D.tlog\unsuccessfulbuild".
5351: 32>    Touching "vtkRenderingOpenVR.dir\Release\vtkRende.0453B28D.tlog\vtkRenderingOpenVR.lastbuildstate".
5352: 32>  Done Building Project "C:\D\S4RVr\VTKRenderingOpenVR-build\vtkRenderingOpenVR.vcxproj" (default targets).
5353: 32>  PrepareForBuild:
5354: 32>    Creating directory "x64\Release\ALL_BUILD\".
5355: 32>    Creating directory "x64\Release\ALL_BUILD\ALL_BUILD.tlog\".
5360: 32>  InitializeBuildStatus:
5361: 32>    Creating "x64\Release\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
5362: 32>  CustomBuild:
5363: 32>    Building Custom Rule C:/D/S4RVr/VTKv9/Rendering/OpenVR/CMakeLists.txt
5364: 32>    CMake is re-running because C:/D/S4RVr/VTKRenderingOpenVR-build/CMakeFiles/generate.stamp is out-of-date.
5365: 32>      the file 'C:/D/S4RVr/VTKv9-build/VTKTargets.cmake'
5366: 32>      is newer than 'C:/D/S4RVr/VTKRenderingOpenVR-build/CMakeFiles/generate.stamp.depend'
5367: 32>      result='-1'
5375: 32>    CMake Error at C:/D/S4RVr/VTKv9/CMake/vtkModuleAPI.cmake:140 (message):
5376: 32>      Requested modules not available:
5377: 32>
5378: 32>        vtkFiltersPython
5379: 32>        vtkInteractionStyle
5380: 32>        vtkGUISupportQt
5381: 32>        vtkGUISupportQtOpenGL
5382: 32>        vtkGUISupportQtSQL
5383: 32>        vtkImagingHybrid
5384: 32>        vtkInfovisLayout
5385: 32>        vtkInteractionWidgets
5386: 32>        vtkViewsCore
5387: 32>        vtklibproj4
5388: 32>        vtkGeovisCore
5389: 32>        vtkIOAMR
5390: 32>        vtkgl2ps
5391: 32>        vtkRenderingGL2PSOpenGL2
5392: 32>        vtklibharu
5393: 32>        vtkIOExport
5394: 32>        vtkIOExportOpenGL2
5395: 32>        vtkIOImport
5396: 32>        vtklibxml2
5397: 32>        vtkIOInfovis
5398: 32>        vtkIOMINC
5399: 32>        vtkjsoncpp
5400: 32>        vtkIOParallel
5401: 32>        vtkIOParallelXML
5402: 32>        vtkIOTecplotTable
5403: 32>        vtkInteractionImage
5404: 32>        vtkRenderingContextOpenGL2
5405: 32>        vtkRenderingQt
5406: 32>        vtkRenderingVolumeOpenGL2
5407: 32>        vtkTestingCore
5408: 32>        vtkTestingRendering
5409: 32>        vtkViewsContext2D
5410: 32>        vtkViewsInfovis
5411: 32>        vtkViewsQt
5412: 32>    Call Stack (most recent call first):
5413: 32>      C:/D/S4RVr/VTKv9-build/VTKConfig.cmake:130 (vtk_module_config)
5414: 32>      CMakeLists.txt:4 (find_package)
5415: 32>
5416: 32>
5417: 32>    -- Configuring incomplete, errors occurred!
5418: 32>    See also "C:/D/S4RVr/VTKRenderingOpenVR-build/CMakeFiles/CMakeOutput.log".
5419: 32>    See also "C:/D/S4RVr/VTKRenderingOpenVR-build/CMakeFiles/CMakeError.log".
5431: 32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\D\S4RVr\VTKRenderingOpenVR-build\ALL_BUILD.vcxproj]
5432: 32>  Done Building Project "C:\D\S4RVr\VTKRenderingOpenVR-build\ALL_BUILD.vcxproj" (default targets) -- FAILED.
5433: 32>
5434: 32>  Build FAILED.
5435: 32>
5436: 32>  "C:\D\S4RVr\VTKRenderingOpenVR-build\ALL_BUILD.vcxproj" (default target) (1) ->
5437: 32>  "C:\D\S4RVr\VTKRenderingOpenVR-build\vtkRenderingOpenVR.vcxproj" (default target) (3) ->
5438: 32>  (ClCompile target) ->
5439: 32>C:\D\S4RVr\VTKv9\Rendering\OpenVR\vtkOpenVRHardwarePicker.cxx(108): warning C4838: conversion from 'int' to 'unsigned int' requires a narrowing conversion [C:\D\S4RVr\VTKRenderingOpenVR-build\vtkRenderingOpenVR.vcxproj]
5440: 32>
5441: 32>
5442: 32>  "C:\D\S4RVr\VTKRenderingOpenVR-build\ALL_BUILD.vcxproj" (default target) (1) ->
5443: 32>  (CustomBuild target) ->
5444: 32>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\D\S4RVr\VTKRenderingOpenVR-build\ALL_BUILD.vcxproj]
5445: 32>
5446: 32>      1 Warning(s)
5447: 32>      1 Error(s)
5448: 32>
5449: 32>  Time Elapsed 00:00:19.38

```

**Comment by lassoan** [comment]
If I start building again, then the above error does not occur, but later this error comes up:

```
56>  -- Configuring Loadable module: VirtualReality [qSlicerVirtualRealityModuleExport.h]
56>  CMake Error at C:/D/SlicerVirtualReality/CMakeLists.txt:54 (install):
56>    install FILES given no DESTINATION!
56>
```

Probably additional files has to be installed differently when the extension is bundled with Slicer?

**Comment by cpinter** [comment]
@jcfr Is there anything I can try to help this move forward? Thanks!

**Comment by lassoan** [comment]
@jcfr I've implemented what you've suggested that would be needed but I have the error above. Could you have a look and recommend potential solutions? Thank you!

**Comment by jcfr** [comment]
Update 1: Support for `EXTERNAL_PROJECT_ADDITIONAL_DIRS` along with tests integrated in https://github.com/commontk/Artichoke/pull/31

**Comment by jcfr** [comment]
Update 2:  Add support for `ExternalProject_Add_Dependencies`. See https://github.com/commontk/Artichoke/pull/32

**Comment by jcfr** [comment]
@lassoan PTAL 
* Features (along with tests) have been integrated to [Artichoke](https://github.com/commontk/Artichoke). 
* A new macro was also added "ExternalProject_Add_Dependencies". This allows to ensure all project from extension are built after Slicer own dependencies are configured and built
*  message reported in the terminal have been tweaked

**Comment by jcfr** [comment]
This last commit is optional, it allows to simplify the summary displayed on the terminal:

```
[...]
-- SuperBuild - SlicerVirtualReality extension => OpenVR;VTKRenderingOpenVR
-- SuperBuild - First pass
-- SuperBuild - First pass - done
-- SuperBuild - Slicer => Requires SlicerDependencies, OpenVR, VTKRenderingOpenVR, 
-- SuperBuild -   SlicerDependencies => Requires curl, CTKAppLauncherLib, teem, VTKv9, ITKv4, CTK, LibArchive, RapidJSON, SimpleITK, SlicerExecutionModel, qRestAPI, DCMTK, python-pydicom, python-chardet, python-couchdb, python-GitPython, python-pip, python-PyGithub, CTKAPPLAUNCHER, python, NUMPY, incrTcl, 
-- SuperBuild -     curl => Requires zlib, OpenSSL, 
-- SuperBuild -       zlib[OK]
-- SuperBuild -       ZLIB_INCLUDE_DIR:/home/jcfr/Projects/Slicer-Qt5-VTK9-Release/zlib-install/include
-- SuperBuild -       ZLIB_LIBRARY:/home/jcfr/Projects/Slicer-Qt5-VTK9-Release/zlib-install/lib/libzlib.a
-- SuperBuild -       ZLIB_ROOT:/home/jcfr/Projects/Slicer-Qt5-VTK9-Release/zlib-install
[...]
-- SuperBuild -     NUMPY => Requires python[INCLUDED], python-setuptools[INCLUDED], python-nose, 
-- SuperBuild -       python-nose => Requires python[INCLUDED], python-setuptools[INCLUDED], 
-- SuperBuild -       python-nose[OK]
-- SuperBuild -     NUMPY[OK]
-- SuperBuild -     NUMPY - Building without Fortran compiler - Non-optimized code will be built !
-- SuperBuild -     incrTcl => Requires tcl[INCLUDED], tk[INCLUDED], 
-- SuperBuild -     incrTcl[OK]
-- SuperBuild -   SlicerDependencies[OK]
-- SuperBuild -   OpenVR => Requires SlicerDependencies[INCLUDED], 
-- SuperBuild -   OpenVR[OK]
-- SuperBuild -   OPENVR_INCLUDE_DIR:/home/jcfr/Projects/Slicer-Qt5-VTK9-Release/OpenVR/headers
-- SuperBuild -   OPENVR_LIBRARY:/home/jcfr/Projects/Slicer-Qt5-VTK9-Release/OpenVR/bin/linux64/libopenvr_api.so
-- SuperBuild -   VTKRenderingOpenVR => Requires OpenVR[INCLUDED], SlicerDependencies[INCLUDED], 
-- SuperBuild -   VTKRenderingOpenVR[OK]
-- SuperBuild -   VTK_SOURCE_DIR:/home/jcfr/Projects/Slicer-Qt5-VTK9-Release/VTKv9-build/../VTKv9
-- SuperBuild -   VTKRenderingOpenVR_SOURCE_DIR:/home/jcfr/Projects/Slicer-Qt5-VTK9-Release/VTKv9-build/../VTKv9/Rendering/OpenVR
-- SuperBuild -   VTKRenderingOpenVR_DIR:/home/jcfr/Projects/Slicer-Qt5-VTK9-Release/VTKRenderingOpenVR-build
-- SuperBuild - Slicer[OK]
-- Configuring done
-- Generating done
```

**Comment by lassoan** [comment]
Thanks a lot Jc, I've started a build.

**Comment by cpinter** [comment]
Me too. Thanks you!

**Comment by jcfr** [comment]
Also, instead of using `ExternalProject_Add_Dependencies` (and optionally introducing `SlicerDependencies`), we could update extensions to conditionally add dependency on Slicer project:
* https://github.com/KitwareMedical/SlicerVirtualReality/compare/support-extension-bundling-adding-slicer-dependencies

And here for the corresponding Slicer updates (revert of introduction of `SlicerDependencies` external project and remove of the call to `ExternalProject_Add_Dependencies`):
* https://github.com/lassoan/Slicer/compare/superbuild_extension_bundle...jcfr:superbuild_extension_bundle_approach2

**Comment by cpinter** [comment]
Build succeeded (after an initial error saying that markups logic wasn't able to find vtkSlicerVersionConfigure.h, but simply starting the superbuild once more worked), and packaging succeeded as well. SlicerVirtualReality was build and packaged with Slicer, as well as an extension depending on SlicerVirtualReality.

One issue is that vtkRenderingOpenVR-9.0.dll, which on my build ended up in c:\e\SvR\Release\vtkRenderingOpenVR-9.0.dll, wasn't included in the package. Once I copied it to "c:\Program Files\Slicer 4.9.0-2018-06-03-VR\lib\Slicer-4.9", everything worked. This is most likely related to https://github.com/KitwareMedical/SlicerVirtualReality/issues/2

**Comment by jcfr** [comment]
Thanks for the feedback.

@lassoan @cpinter Any strong feeling regarding https://github.com/Slicer/Slicer/pull/909#issuecomment-394358930 

I think updating the extension as suggested [here](https://github.com/KitwareMedical/SlicerVirtualReality/compare/support-extension-bundling-adding-slicer-dependencies) is a cleaner approach

**Comment by jcfr** [comment]
@lassoan Sounds good. I will go with updating the extension so that the dependencies are explicit.

**Comment by jcfr** [comment]
Closing. Integrated in [r27232](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27232)

An entry has also been added to the FAQ. See https://www.slicer.org/wiki/Documentation/Nightly/Developers/FAQ/Extensions#How_to_build_Slicer_bundling_extensions_.3F

**Comment by cpinter** [comment]
Thank you very much @jcfr for working on this!

**Pull request closed without merging**
