### PR TITLE
Use SimpleITK's SuperBuild for additional dependencies.

### PR DESCRIPTION
**Pull request by blowekamp**
Configure with SimpleITK's Superbuild CMake file, to allow additional
dependencies to be built. This is done by adding a second external
project just for the download step, so that the configuration can be
done in the Superbuild sub-directory as the source directory.

### CODE REVIEW

**Comment by blowekamp** [comment]
The latest development version of SimpleITK as added Lua and GTest to the as requirements, which can be build when the Superbuild CMake build is used.

The alternative is to add the Lua external project to Slicer's Superbuild. I was going to remove Swig and PCRE for Slicers Superbuild, but they are now used by WrapITK.

**Comment by jcfr** [comment]
@blowekamp Based on our discussion during the last dev hangout, let me know if you would me to start reviewing or if you would prefer I wait. Thanks

**Comment by blowekamp** [comment]
For reference this is the error I am getting from a clean build now:
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at /scratch/blowekamp/build/Slicer/download-SimpleITK-prefix/tmp/download-SimpleITK-gitupdate.cmake:12 (message):
  Failed to get the hash for HEAD


make[2]: *** [download-SimpleITK-prefix/src/download-SimpleITK-stamp/download-SimpleITK-update] Error 1
make[1]: *** [CMakeFiles/download-SimpleITK.dir/all] Error 2

**Comment by jcfr** [comment]
Could you try again after running:
```
rm -rf /scratch/blowekamp/build/Slicer/download-SimpleITK*
```

It is also possible that "download" is a reserved keyword and cannot be
used in a external project name.

On Thu, Jul 30, 2015 at 9:16 AM, Bradley Lowekamp <notifications@github.com>
wrote:

> For reference this is the error I am getting from a clean build now:
> fatal: Not a git repository (or any of the parent directories): .git
> CMake Error at
> /scratch/blowekamp/build/Slicer/download-SimpleITK-prefix/tmp/download-SimpleITK-gitupdate.cmake:12
> (message):
> Failed to get the hash for HEAD
>
> make[2]: ***
> [download-SimpleITK-prefix/src/download-SimpleITK-stamp/download-SimpleITK-update]
> Error 1
> make[1]: *** [CMakeFiles/download-SimpleITK.dir/all] Error 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/308#issuecomment-126319800>.
>



-- 
+1 919 869 8849

**Comment by blowekamp** [comment]
Update patch. Using:
 rm -rf /scratch/blowekamp/build/Slicer/SimpleITK

was part of my problem. Re-name the download project to work with that expectation.

**Comment by blowekamp** [comment]
What to just upgrade to SimpleITK master at the same time too?

There is new wrapping for this class:
http://www.itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1LabelIntensityStatisticsImageFilter.html
Which can be added to the IASEM LabelObject module.

**Comment by jcfr** [comment]
Update:
* Good news. Extensions packaging issues should now be fixed.
* Since I am travelling from August 12 to 19, I will be integrating this topic on my return.

**Comment by blowekamp** [comment]
Be sure to include the latest SimpleITK master. It contains a Superbuild bug fix:

https://github.com/SimpleITK/SimpleITK/commit/6acfc05c01c946316cac9bd8803d62a4e0cda5b9

**Comment by jcfr** [comment]
@blowekamp Doing a clean build on linux, I get the following:

```
[ 97%] Performing install step for 'SimpleITK'
-- SimpleITK: Removing 'install' log files
-- SimpleITK: SimpleITK_WORKING_DIR: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/Wrapping
-- SimpleITK: /home/jcfr/Projects/Slicer-Debug/python-install/bin/SlicerPython;PythonPackage/setup.py;install
CMake Error at /home/jcfr/Projects/Slicer/CMake/ExternalProjectForNonCMakeProject.cmake:58 (message):
  SimpleITK: Variable SimpleITK_WORKING_DIR is set to a non-existent
  directory !
Call Stack (most recent call first):
  /home/jcfr/Projects/Slicer-Debug/SimpleITK_install_step.cmake:3 (ExternalProject_Execute)


make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-install] Error 1
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
```

Now there is superbuild stucture, seems the `WORKING_DIR` associated with the install script needs to be updated.  After fixing this, build and install do not fail.
Could you check on your side that I am not missing anything ? 
See https://github.com/jcfr/Slicer/commits/jcfr-UseSimpleITKSuperbuild

I also notice that the include/cmake/libraries/.. are installer in the top-level SimpleITK folder:

```
-- Install configuration: "Debug"
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/lib/cmake/SimpleITK-0.10/SimpleITKConfig.cmake
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/lib/cmake/SimpleITK-0.10/SimpleITKConfigVersion.cmake
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/lib/cmake/SimpleITK-0.10/UseSimpleITK.cmake
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/lib/cmake/SimpleITK-0.10/SimpleITKTargets.cmake
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/lib/cmake/SimpleITK-0.10/SimpleITKTargets-debug.cmake
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/sitkBSplineTransformInitializerFilter.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/sitkCenteredVersorTransformInitializerFilter.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/sitkImageOperators.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/sitkAdditionalProcedures.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/sitkHashImageFilter.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/sitkCastImageFilter.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/itkHashImageFilter.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/itkUnaryMinusImageFilter.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/itkSliceImageFilter.h
[...]
 Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10//Ancillary/TypeList.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10//nsstd
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10//nsstd/unordered_map.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10//nsstd/functional.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10//nsstd/type_traits.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/share/doc/SimpleITK-0.10/LICENSE
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/share/doc/SimpleITK-0.10/NOTICE
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/share/doc/SimpleITK-0.10/Readme.md
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/share/doc/SimpleITK-0.10/ITK-4.8-NOTICE
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/share/doc/SimpleITK-0.10/ITK-4.8-README.txt
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/./lib/Slicer-4.4/libSimpleITKExplicit-0.10.so.1
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/./lib/Slicer-4.4/libSimpleITKExplicit-0.10.so
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/sitkConfigure.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/include/SimpleITK-0.10/sitkVersionConfig.h
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/./lib/Slicer-4.4/libSimpleITKCommon-0.10.so.1
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/./lib/Slicer-4.4/libSimpleITKCommon-0.10.so
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/./lib/Slicer-4.4/libSimpleITKBasicFilters0-0.10.so.1
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/./lib/Slicer-4.4/libSimpleITKBasicFilters0-0.10.so
-- Installing: /home/jcfr/Projects/Slicer-Debug/SimpleITK-build/./lib/Slicer-4.4/libSimpleITKBasicFilters1-0.10.so.1
[...]
```

Is this expected ? Would it make sense to install into `Slicer-SuperBuild/SimpleITK-install` ?



Last questions, should we remove the SWIG, PCRE, .. external projects ?

**Comment by blowekamp** [comment]
@jcfr 

Looking to to improving installation...

Getting the following error:

 Performing configure step for 'ITKv4'
 loading initial cache file /scratch/blowekamp/build/Slicer/ITKv4-prefix/tmp/ITKv4-cache.cmake 
CMake Error at CMakeLists.txt:14 (cmake_policy):
   Policy "CMP0042" is not known to this version of CMake.

Using CMake version 2.8.12.1. Slicer documentation does indicate that CMake >3 is required [1]. But this does not appear to be enforced [2].

Brad

[1] http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Build_Instructions
[2] https://github.com/Slicer/Slicer/blob/master/CMakeLists.txt#L2

**Comment by jcfr** [comment]
@blowekamp  Thanks

In the mean time, I fixed the configure error you reported.
See http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24521

Will update the minimum required CMake version at some later time.

**Comment by blowekamp** [comment]
These two line in the configuration of SimpleITK[1], I don't understand what they are suppose to do. The lines set SimpleITK_INSTALL_ARCHIVE_DIR to Slicer_INSTALL_LIB_DIR (relative path causes problems?). Before this patch the "install" target was not run on the SimpleITK project.  The static or shared libraries stayed in the build tree. For windows the shared libraries does get package up in the nightly distribution. Now the SimpleITK-Superbuild does not run its install target, but the SimpleITK sub-project now gets it's install target run.

Currently there is a separate script run to install the Python run-time, this works ok.

1) What should be done with installing the SimpleITK libraries/headers? Keep it in the build tree? Any point to installing it into SimpleITK-install?
2) It would be good to get SimpleITK bundled correctly for OSX when shared libraries are enabled. Would it be as simple as adding the missing libraries here [2]?

Thanks,
Brad

[1] https://github.com/Slicer/Slicer/blob/00ff318fbf5b93dd2e53aca9dfcc2c0f56f76aa0/SuperBuild/External_SimpleITK.cmake#L53-L54

[2] https://github.com/Slicer/Slicer/blob/00ff318fbf5b93dd2e53aca9dfcc2c0f56f76aa0/CMake/SlicerCPackBundleFixup.cmake.in#L85

**Comment by jcfr** [comment]
> These two line in the configuration of SimpleITK[1], I don't understand what they are suppose to do. 
> The lines set SimpleITK_INSTALL_ARCHIVE_DIR to Slicer_INSTALL_LIB_DIR (relative path causes 
> problems?). Before this patch the "install" target was not run on the SimpleITK project. The static or 
> shared libraries stayed in the build tree. For windows the shared libraries does get package up in the 
> nightly distribution. Now the SimpleITK-Superbuild does not run its install target, but the SimpleITK 
> sub-project now gets it's install target run.

`INSTALL` directory should be relative, they basically specify the relative location (for example relative location to `CMAKE_INSTALL_PREFIX`). More details [here](http://www.cmake.org/cmake/help/git-next/command/install.html?highlight=DESTINATION)

The  line `-DSimpleITK_INSTALL_ARCHIVE_DIR:PATH=${Slicer_INSTALL_LIB_DIR}` simply means that both shared and static library will be installed at the same location. This may change for Slicer moving forward. 


> 1) What should be done with installing the SimpleITK libraries/headers? Keep it in the build tree? Any 
> point to installing it into SimpleITK-install?

Ideally, all `install` rules within `SimpleITK` should be associated with a `COMPONENT`. That should allow to selectively install component. While there are no defined convention to named components, the following ones emerged: `Runtime`, `RuntimeLibraries` and `Development`.   

Looking at the top-level `SimpleITK/CMakeLists.txt`, I can see you are specifying component :+1: 

Now, to answer your original question, that means that, the python script install SimpleITK could select the `Runtime` / `RuntimeLibraries` components. See [here](https://github.com/Slicer/Slicer/blob/00ff318fbf5b93dd2e53aca9dfcc2c0f56f76aa0/CMake/SlicerBlockInstallCMakeProjects.cmake) for example of selective install.

You could also add a build option named `SimpleITK_INSTALL_DEVELOPMENT` that would be `ON` by default.  By turning that option `OFF` and running the current python install script ... no development files would be installed. 

> 2) It would be good to get SimpleITK bundled correctly for OSX when shared libraries are enabled. 
> Would it be as simple as adding the missing libraries here [2]?

For now, that is the way to go to integrate into  Slicer.

[1] https://github.com/Slicer/Slicer/blob/00ff318fbf5b93dd2e53aca9dfcc2c0f56f76aa0/SuperBuild/External_SimpleITK.cmake#L53-L54

[2] https://github.com/Slicer/Slicer/blob/00ff318fbf5b93dd2e53aca9dfcc2c0f56f76aa0/CMake/SlicerCPackBundleFixup.cmake.in#L85


Conclusion:

At some later point, to simplify things, bridging python package generation and CMake would be great. There are some effort in that direction ... solution like [PyCMake](https://github.com/PyCMake/PyCMake) (soon to be renamed to `scikit-build`) should help.

**Comment by blowekamp** [comment]
I am not sure there is a place for the fine grain control over the SimpleITK Superbuild that you describe. It may be best not to use SimpleITK's Super and just add Lua to Slicers Superbuild while keeping the current SimpleITK build the same?

**Comment by jcfr** [comment]
The advantage of using SimpleITK superbuild, is that we don't have to maintain the external projects in Slicer.

May be you could add the option `SimpleITK_INSTALL_DEVELOPMENT` in https://github.com/SimpleITK/SimpleITK/blob/1d7e62a66da5d39634d205f75c75cac1a763126f/SuperBuild/SuperBuild.cmake#L341-L375 ? 

nitpicks: I also notice that `CMAKE_INSTALL_PREFIX` is set to `${CMAKE_CURRENT_BINARY_DIR}`. May it could be set to using something like this:

```
set(CMAKE_INSTALL_PREFIX ${CMAKE_CURRENT_BINARY_DIR}/install-tree CACHE PATH "Where all the prerequisite libraries go" FORCE)
```

See https://github.com/SimpleITK/SimpleITK/blob/1d7e62a66da5d39634d205f75c75cac1a763126f/SuperBuild/SuperBuild.cmake#L68

That would allow to keep the installed files separated from the build tree artefacts.

**Comment by blowekamp** [comment]
The CMAKE_INSTALL_PREFIX has already been changed in this patch [1], to allow it to be customized when using the SimpleITK Superbuild.

Frankly I don't know what the official guidance is on what the install steps of external projects in a Superbuild should do. Everyone seems to have different expectations and request different things. And it is impossible to be able to customize all aspects of installation of ITK and SimpleITK from a top-level super build. The current installed SimpleITK is designed to support using SimpleITK from the C++ interface, and this is tested by having and an additional Superbuild project of SimpleITK examples. The other project: PCRE, SWIG, Lua, and ITK are installed in the EP_PREFIX default path[2] and prevent contamination as you suggest. The installation of the individual wrapped languages is handled outside of CMake install by the languages individual package management. If CMAKE_INSTALL_PREFIX is manual set to "/usr/local/" then SimpleITK libraries an headers will be installed there in a usable fashion if the super build is built static as is the default.

For Slicer what is suppose to happen for the installation of SimpleITK?

[1] https://github.com/SimpleITK/SimpleITK/commit/5a795e4ebc8b306a41363c7ee182bc82f27ad820
[2] http://www.cmake.org/cmake/help/v3.0/module/ExternalProject.html

**Comment by jcfr** [comment]
> Frankly I don't know what the official guidance is on what the install steps of external projects in a Superbuild should do.

Since it is project dependent. `ExternalProject` provide flexibility. Having some guide line for CMake/C++ project would be good.

> The current installed SimpleITK is designed to support using SimpleITK from the C++ interface, and this 
> is tested by having and an additional Superbuild project of SimpleITK examples. 

That is great.


> The other project: PCRE, SWIG, Lua, and ITK are installed in the EP_PREFIX default path[2] and 
> prevent contamination as you suggest. 

Great. 


> The installation of the individual wrapped languages is handled outside of CMake install by the 
> languages individual package management. 

> If CMAKE_INSTALL_PREFIX is manual set to "/usr/local/" then SimpleITK libraries an headers will be 
> installed there in a usable fashion if the super build is built static as is the default.

No need to change this. What I suggested in https://github.com/Slicer/Slicer/pull/308#issuecomment-139335447 was to add an option named `SimpleITK_INSTALL_DEVELOPMENT` 


> For Slicer what is suppose to happen for the installation of SimpleITK?

From Slicer perspective, SimpleITK is installed in the `site-packages` folder. That is the only things needed.

Now you have added a way to specify custom value for `CMAKE_INSTALL_PREFIX` in SimpleITK/SimpleITK@5a795e4, I guess you could update [SuperBuild.cmake](https://github.com/SimpleITK/SimpleITK/blob/master/SuperBuild/SuperBuild.cmake#L337-L371) adding:

```
-DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_BINARY_DIR}/SimpleITK-install
```

**Comment by jcfr** [comment]
@blowekamp As discussed during today's [developer hangout](http://wiki.slicer.org/slicerWiki/index.php/Developer_Meetings/20150915#Conclusion), I will wait for you to update the PR.

In the mean time, let me know if you have any other questions.

**Comment by jcfr** [comment]
Hi @blowekamp, 

Was wondering what was the status on this. Considering I will be travelling from Oct 10 to the 17, would be nice if we could finalize the SimpleITK update before end of this coming week.

Thanks
Jc

**Comment by blowekamp** [comment]
Thanks for the poke. I'll get this core part working on Monday.   I got side track with fixing the rpath issues.

**Comment by blowekamp** [comment]
Update patch with change to SimpleITK_DIR. Tested on OSX, and Linux in Debug (shared) and Release ( monolithic/static). Additionally, tested linux packaging and the IASEM module.

Shared library packaging maybe addressed later

**Comment by jcfr** [comment]
Thanks Brad.

Do you anticipate any issue on Windows ?  I will initiate a build to confirm.

**Comment by blowekamp** [comment]
With the changed SimpleITK_DIR, I think all install and run-time environments should work.

**Comment by jcfr** [comment]
@blowekamp Since I will be travelling next week, I will integrate your changes when I return. (after Oct 18th). In the mean time, if you can rebase the topic and do a clean Release build on windows, that be helpful. Thanks for your help.

**Comment by blowekamp** [comment]
My windows build is failing for a few reasons not related to the this change...

**Comment by jcfr** [comment]
@msmolens Do you know what could be the issue ?

**Comment by blowekamp** [comment]
Disabling numpy, I was able to continue to build Slicer. I was than able to successfully test the SimpleFilters module.

I tried packaging and got the following warning repeated many times then an error:
3>CMake Warning (dev) in C:/b/Slicer-build/CPackConfig.cmake:
3>  Syntax Warning in cmake code at
3>    C:/b/Slicer-build/CPackConfig.cmake:95:30
3>  Argument not separated from preceding token by whitespace.
3>This warning is for project developers.  Use -Wno-dev to suppress it.
3>CMake Error: Error in cmake code at
3>C:/b/Slicer-build/CPackConfig.cmake:96:
3>Parse error.  Function missing ending ")".  Instead found unterminated string with text ")
3>".
3>CPack Error: Problem reading CPack config file: "C:/b/Slicer-build/CPackConfig.cmake"
3>Project : error PRJ0019: A tool returned an error code from "Performing Post-Build Event..."
3>Build log was saved at "file://c:\b\Slicer-build\PACKAGE.dir\Release\BuildLog.htm"
3>PACKAGE - 1 error(s), 0 warning(s)

**Comment by msmolens** [comment]
@blowekamp @jcfr Based on the log above, somehow the NumPy build is using the "Gnu95FCompiler" Fortran compiler configuration even though we pass `--fcompiler=none`. Some things I would check to eliminate potential problems, if any of these apply, are:
- ensure a clean source tree and clean build directory
- build inside Visual Studio as opposed to from the command line
- ensure no system Python is in your path

The packaging error is likely what was fixed in https://github.com/Slicer/Slicer/commit/c087e5a1e8f073c76c3d8f8380d3a3137d1febe3.

**Comment by jcfr** [comment]
Thanks @blowekamp 

Integrated in [r24674](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24674)

**Comment by jcfr** [comment]
And thanks @msmolens for your feedback regarding the packaging and build errors reported above.

**Pull request closed without merging**
