### PR TITLE
Add patches to Slicer-5.2 branch

### PR DESCRIPTION
**Pull request by lassoan**
This pull requests adds fixes to the `5.2` maintanance branch by cherry-picking many small fixes made in the `main` branch since `5.2.1` was released. All the changes are small, without any expected side effect. Most changes are fixes (some of them fix very visible issues for the users). There are only a few small improvements that are included so that some projects can use the Slicer Stable Release.

Content of the 5.2 branch after this could be used to create a Slicer-5.2.2 patch release.

Backport changes associated with these pull-requests:
* https://github.com/Slicer/Slicer/pull/6682
* https://github.com/Slicer/Slicer/pull/6706
  * Only commit 052aa9448d878b8345a85f00e66a49cdf4a2a564 (`STYLE: Fix python linting issue`)
* https://github.com/Slicer/Slicer/pull/6715
* https://github.com/Slicer/Slicer/pull/6719
* https://github.com/Slicer/Slicer/pull/6720
* https://github.com/Slicer/Slicer/pull/6712
* https://github.com/Slicer/Slicer/pull/6729
* https://github.com/Slicer/Slicer/pull/6731
* https://github.com/Slicer/Slicer/pull/6743
* https://github.com/Slicer/Slicer/pull/6744
* https://github.com/Slicer/Slicer/pull/6747
* https://github.com/Slicer/Slicer/pull/6736
* https://github.com/Slicer/Slicer/pull/6752
* https://github.com/Slicer/Slicer/pull/6755 (3 commits)
  * `BUG: Fix qMRMLLayoutManagerTest2 failure`
  * `BUG: Fix py_SubjectHierarchyGenericSelfTest`
  * `BUG: Fix scene compatibility error message`
* https://github.com/Slicer/Slicer/pull/6759
* https://github.com/Slicer/Slicer/pull/6756 (4 commits)
  * `BUG: Fix exporting of display properties`
  * `ENH: Expose markups JSON reader/writer`
  * `ENH: Add vtkMRMLMarkupsROINode::GetObjectBounds convenience method`
  * `ENH: Expose some vtkMRMLMarkupsCurveNode features via static methods`
* https://github.com/Slicer/Slicer/pull/6762
  * Only commit 57da343cca5b98706aa54215b5365985108c2621 (`COMP: Fixed build warning in vtkCodedEntry::SetValueSchemeMeaning`)
* https://github.com/Slicer/Slicer/pull/6765
* https://github.com/Slicer/Slicer/pull/6767
* https://github.com/Slicer/Slicer/pull/6792
* https://github.com/Slicer/Slicer/pull/6791
* https://github.com/Slicer/Slicer/pull/6718
* https://github.com/Slicer/Slicer/pull/6775 (2 commits)
  * `ENH: Make table file reading/writing errors more visible to users`
  * `BUG: Fix table loading with default column type`
* https://github.com/Slicer/Slicer/pull/6781
* https://github.com/Slicer/Slicer/pull/6776
  * Selectively backport:
    * change to `SuperBuild/External_CTK.cmake` as `ENH: Backport CTK update adding support for dual-monitor layouts`. See https://github.com/commontk/CTK/compare/dec834fccffebdc3b0896c157d39e3c0031c4a0a...be0e1429e3fce605a49d08d6b94563920b019dff
    * update to `vtkMRMLMarkupsJsonElement::GetVectorProperty` to fix `ACPCTransformTest` (https://github.com/Slicer/Slicer/commit/a4bb78991da5bfedd37e67eafd8f3f6640d648b3)
* https://github.com/Slicer/Slicer/pull/6524
  * Selectively backport:
    * update to `vtkMRMLViewDisplayableManager::vtkInternal::UpdateRenderMode()` as `BUG: Backport MRMLViewDisplayableManager updates to fix qMRMLNavigationView tests`
* https://github.com/Slicer/Slicer/pull/6795
* https://github.com/Slicer/Slicer/pull/6797
* https://github.com/Slicer/Slicer/pull/6798
* https://github.com/Slicer/Slicer/pull/6799 (3 commits)
* https://github.com/Slicer/Slicer/pull/6805

Backport these commits that were directly integrated into `main`:
* https://github.com/Slicer/Slicer/commit/f9dcc53b560a5f1d3f933a81c514175aed65a127 (`BUG: Fix slicer.util.logProcessOutput`)
* a5af8205d5ff2d0d137c9abf6d28d987fc21afee (`BUG: Attempt to make Scissors effect more robust`)  related to #6705
* 52000cfa57efbd36f44e1ba6b3ac5a5eee8abe53 (`BUG: Add temporary code to debug Scissors effect crash on macOS`) related to #6705
* f6a911153ceaaef8b264beb4d943a14dcfc26958 (`BUG: Fix volume sequence support in CLI modules`)
* d838e31d2f3e554db83eaeb59d46658ceb6dd9cb (`BUG: Fix "Check for updates" checkbox in Welcome module`)
* b803ad48595c71a6e8768f920dab9f86c18be893 (`BUG: Fix "Apply to all visible segments" option in Segment Editor`)
* 6834c51215cd3217e01da622c4d4687255a92bea (`ENH: Make qMRMLTableWidget::mrmlTableViewNode accessible in Python`)
* 0eaffcfa2b0f330ead8943bcf49073e8f19410d3 (`ENH: Allow maximizing "Add data" and "Save data" dialog windows`)
* 5a3f3381d16c7151b695d2597695951869c9981d (`BUG: Fix arrayFromSegmentBinaryLabelmap leaving temporary node behind`)
* a943aa850467ba7b2425c236140f72f9d75ae686 (`BUG: Fix typo in Extensions Manager `)
* 822a50ba2a0da3c3aca995eeae5e869abbf6ff43 (`DOC: Fix typos in webserver.md`)
* 7f5f83e88120d75e6a5152b487626ffd9470921c (`ENH: Update CTK to latest version`) See https://github.com/commontk/CTK/compare/2c89539632e503e7cf9b7c53adccd8f1f71b2ead...dec834fccffebdc3b0896c157d39e3c0031c4a0a
  * Highlighted commits:
    * https://github.com/commontk/CTK/commit/dec834fccffebdc3b0896c157d39e3c0031c4a0a (`BUG: Fix ctk::vtkImageDataToQImage function`)
    * https://github.com/commontk/CTK/commit/d349b8750c220523cc124dd0be7bfdfeffe8cba7 (`BUG: Fix crash in ctkDICOMQueryRetrieveWidget`)
    * https://github.com/commontk/CTK/commit/8f349212143bf23469a7e4c4f08617423a23538c (`ENH: Expose removeCachedTags method in Python`)
* aa245559e6027c8bf568ff96365dff9aed5be773 (`BUG: Fix subject hierarchy tree in DICOM module `)
* 3ae750f4714cc38ab3c94600be1ce289e9b3c938 (`BUG: Avoid logging errors during Python auto-completion with CTK update`). See https://github.com/commontk/CTK/compare/be0e1429e3fce605a49d08d6b94563920b019dff...95dac75b80562b81db10555db5807648f4d17dee (1 commit)

### CODE REVIEW

**Comment by jamesobutler** [comment]
Slicer (5.2.0) 5.2.1 - represents code as of Nov 24th. Official release [announced](https://discourse.slicer.org/t/slicer-5-2-summary-highlights-and-changelog/26916) Dec 26th.

Based on the quarterly release of new code, Slicer 5.4.0 would represent code as of about February 24th which is just a little over a month away.

Releasing a 5.2.2 makes sense if it is released this week, though if it starts to creep into the planned Slicer 5.4.0 release (within a month) then it might make sense to just release 5.4.0. Bug fixes here can still be backported to the `5.2` branch even if a release isn't actually cut.

**Comment by pieper** [comment]
We discussed on the call today that 5.4 might be March/April so putting out a 5.2.2 seems like a good idea.

**Review by pieper — APPROVED** [review]
I didn't look at all the code in detail, but the list of commits looks good to me.

**Comment by jamesobutler** [comment]
Ok. Are we going to semi-annual releases? With April/May and November releases? 

With the previous mentions of quarterly releases for new features I was hoping to try and stick to that schedule instead of having to wait more than 3 months for new features to be present in a stable release. re https://discourse.slicer.org/t/slicer-quarterly-releases/24712

**Comment by pieper** [comment]
I understand the goal is to get to quarterly releases but the process is slowed by assembling release notes and signing mac binaries.  Probably we can get in the habit of writing the release notes as we go so it is less of a chore at release time.

**Comment by lassoan** [comment]
We still plan for quarterly releases. Currently we are about halfway between the last release (code freeze end of Nov 2022) and next release (code freeze end of Feb 2023), so it is a good time to initiate a patch release that probably contains all important fixes.

**Comment by jcfr** [comment]
I updated the description to reference backported pull-requests and commits, and I will soon force-push to rebase on top of current `5.2` branch

**Review by jcfr — APPROVED** [review]
After locally building and running the test, this should be good for integration on top of current 5.2 branch.

**Comment by jcfr** [comment]
Running tests reported the following:

```
$ ctest -j10
[...]
99% tests passed, 8 tests failed out of 663

Total Test time (real) = 2777.48 sec

The following tests FAILED:
	180 - qMRMLLayoutManagerVisibilityTest (Failed)
	189 - qMRMLNavigationViewTest1 (Failed)
	219 - qMRMLThreeDViewTest1 (Failed)
	220 - qMRMLThreeDWidgetTest1 (Failed)
	241 - qMRMLNavigationViewEventTranslatorPlayerTest1 (Failed)
	249 - qMRMLThreeDWidgetEventTranslatorPlayerTest1 (Failed)
	475 - ACPCTransformTest (Failed)
	637 - py_SlicerRestoreSceneViewCrashIssue3445 (Failed)
```

I suspect that only backporting the change to `SuperBuild/External_CTK.cmake` as `ENH: Backport CTK update adding support for dual-monitor layouts` is breaking the layout manager. It seems to require the full set of changes associated with https://github.com/Slicer/Slicer/pull/6776

Links:
* https://github.com/commontk/CTK/compare/dec834fccffebdc3b0896c157d39e3c0031c4a0a...be0e1429e3fce605a49d08d6b94563920b019dff
* https://github.com/Slicer/Slicer/pull/6776

**Comment by jcfr** [comment]
Next steps:
* [ ] Build & run test on windows @lassoan 
* [ ] Build & run test on macOS @RafaelPalomar

**Comment by jcfr** [comment]
For reference, here are the results of re-running the following command for both `main` and `lassoan:5.2` on @jcfr workstation (`Ubuntu 20.04.5 LTS`)

### `main`

```
$ ctest -R "qMRMLLayoutManagerVisibilityTest|qMRMLNavigationViewTest1|qMRMLThreeDViewTest1|qMRMLThreeDWidgetTest1|qMRMLNavigationViewEventTranslatorPlayerTest1|qMRMLThreeDWidgetEventTranslatorPlayerTest1|ACPCTransformTest|py_SlicerRestoreSceneViewCrashIssue3445"
Test project /home/jcfr/Projects/Slicer-Release/Slicer-build
    Start 180: qMRMLLayoutManagerVisibilityTest
1/8 Test #180: qMRMLLayoutManagerVisibilityTest ................***Failed    0.88 sec
    Start 189: qMRMLNavigationViewTest1
2/8 Test #189: qMRMLNavigationViewTest1 ........................   Passed    1.03 sec
    Start 219: qMRMLThreeDViewTest1
3/8 Test #219: qMRMLThreeDViewTest1 ............................   Passed    0.71 sec
    Start 220: qMRMLThreeDWidgetTest1
4/8 Test #220: qMRMLThreeDWidgetTest1 ..........................   Passed    0.87 sec
    Start 241: qMRMLNavigationViewEventTranslatorPlayerTest1
5/8 Test #241: qMRMLNavigationViewEventTranslatorPlayerTest1 ...   Passed    3.93 sec
    Start 249: qMRMLThreeDWidgetEventTranslatorPlayerTest1
6/8 Test #249: qMRMLThreeDWidgetEventTranslatorPlayerTest1 .....   Passed   11.50 sec
    Start 452: ACPCTransformTest
7/8 Test #452: ACPCTransformTest ...............................   Passed    0.49 sec
    Start 616: py_SlicerRestoreSceneViewCrashIssue3445
8/8 Test #616: py_SlicerRestoreSceneViewCrashIssue3445 .........   Passed  124.19 sec

[...]

Total Test time (real) = 143.63 sec

The following tests FAILED:
	180 - qMRMLLayoutManagerVisibilityTest (Failed)
```

### `lassoan:5.2`

```
ctest -R "qMRMLLayoutManagerVisibilityTest|qMRMLNavigationViewTest1|qMRMLThreeDViewTest1|qMRMLThreeDWidgetTest1|qMRMLNavigationViewEventTranslatorPlayerTest1|qMRMLThreeDWidgetEventTranslatorPlayerTest1|ACPCTransformTest|py_SlicerRestoreSceneViewCrashIssue3445"
Test project /home/jcfr/Projects/Slicer-2-Release/Slicer-build
    Start 180: qMRMLLayoutManagerVisibilityTest
1/8 Test #180: qMRMLLayoutManagerVisibilityTest ................***Failed    1.20 sec
    Start 189: qMRMLNavigationViewTest1
2/8 Test #189: qMRMLNavigationViewTest1 ........................***Failed    0.88 sec
    Start 219: qMRMLThreeDViewTest1
3/8 Test #219: qMRMLThreeDViewTest1 ............................***Failed    0.73 sec
    Start 220: qMRMLThreeDWidgetTest1
4/8 Test #220: qMRMLThreeDWidgetTest1 ..........................***Failed    1.08 sec
    Start 241: qMRMLNavigationViewEventTranslatorPlayerTest1
5/8 Test #241: qMRMLNavigationViewEventTranslatorPlayerTest1 ...***Failed    1.00 sec
    Start 249: qMRMLThreeDWidgetEventTranslatorPlayerTest1
6/8 Test #249: qMRMLThreeDWidgetEventTranslatorPlayerTest1 .....***Failed    0.95 sec
    Start 475: ACPCTransformTest
7/8 Test #475: ACPCTransformTest ...............................***Failed    0.67 sec
    Start 637: py_SlicerRestoreSceneViewCrashIssue3445

8/8 Test #637: py_SlicerRestoreSceneViewCrashIssue3445 .........***Failed  187.78 sec

0% tests passed, 8 tests failed out of 8

[...]

Total Test time (real) = 194.34 sec

The following tests FAILED:
	180 - qMRMLLayoutManagerVisibilityTest (Failed)
	189 - qMRMLNavigationViewTest1 (Failed)
	219 - qMRMLThreeDViewTest1 (Failed)
	220 - qMRMLThreeDWidgetTest1 (Failed)
	241 - qMRMLNavigationViewEventTranslatorPlayerTest1 (Failed)
	249 - qMRMLThreeDWidgetEventTranslatorPlayerTest1 (Failed)
	475 - ACPCTransformTest (Failed)
	637 - py_SlicerRestoreSceneViewCrashIssue3445 (Failed)
```

**Comment by RafaelPalomar** [comment]
> * 
> 
> * [ ]  Build & run tests on macOS @RafaelPalomar

Sorry, I don't have a Mac to do this. However I did a run on my Linux and here are the results:

```txt
xvfb-run ctest -R "qMRMLLayoutManagerVisibilityTest|qMRMLNavigationViewTest1|qMRMLThreeDViewTest1|qMRMLThreeDWidgetTest1|qMRMLNavigationViewEventTranslatorPlayerTest1|qMRMLThreeDWidgetEventTranslatorPlayerTest1|ACPCTransformTest|py_SlicerRestoreSceneViewCrashIssue3445"
Test project /home/rafael/src/Slicer/Slicer/Release/Slicer-build
    Start 180: qMRMLLayoutManagerVisibilityTest
1/8 Test #180: qMRMLLayoutManagerVisibilityTest ................   Passed    2.17 sec
    Start 189: qMRMLNavigationViewTest1
2/8 Test #189: qMRMLNavigationViewTest1 ........................   Passed    0.78 sec
    Start 219: qMRMLThreeDViewTest1
3/8 Test #219: qMRMLThreeDViewTest1 ............................   Passed    0.44 sec
    Start 220: qMRMLThreeDWidgetTest1
4/8 Test #220: qMRMLThreeDWidgetTest1 ..........................   Passed    0.69 sec
    Start 241: qMRMLNavigationViewEventTranslatorPlayerTest1
5/8 Test #241: qMRMLNavigationViewEventTranslatorPlayerTest1 ...   Passed    3.58 sec
    Start 249: qMRMLThreeDWidgetEventTranslatorPlayerTest1
6/8 Test #249: qMRMLThreeDWidgetEventTranslatorPlayerTest1 .....   Passed   11.06 sec
    Start 475: ACPCTransformTest
7/8 Test #475: ACPCTransformTest ...............................   Passed    0.28 sec
    Start 637: py_SlicerRestoreSceneViewCrashIssue3445
8/8 Test #637: py_SlicerRestoreSceneViewCrashIssue3445 .........   Passed  107.87 sec

100% tests passed, 0 tests failed out of 8

Label Time Summary:
ACPCTransform    =   0.28 sec*proc (1 test)
qMRMLWidgets     =  18.71 sec*proc (6 tests)

Total Test time (real) = 126.90 sec
```

**Comment by jcfr** [comment]
> re: macOS

This was an oversight, I meant to write Linux. Thanks for testing, it is great to see the test passing on your workstation.

**Comment by jcfr** [comment]
> how does the log for Test#180 look like?

```
$ ctest -R qMRMLLayoutManagerVisibilityTest -VV
[...]
Checking test dependency graph...
Checking test dependency graph end
test 180
    Start 180: qMRMLLayoutManagerVisibilityTest

180: Test command: /home/jcfr/Projects/Slicer-2-Release/Slicer-build/Slicer "--launch" "/home/jcfr/Projects/Slicer-2-Release/Slicer-build/bin/qMRMLWidgetsCxxTests" "qMRMLLayoutManagerVisibilityTest"
180: Test timeout computed to be: 1500
180: Line 201 - Problem with widget visibility associated with node vtkMRMLSliceNodeGreen
180:   widgetVisibility: 0
180:   expectedWidgetVisibility: 1
```

**Comment by jcfr** [comment]
The following three tests are now fixed after backporting selected changes:
* `ACPCTransformTest`
* `qMRMLNavigationViewTest1`
* `qMRMLNavigationViewEventTranslatorPlayerTest1`

**Comment by jcfr** [comment]
Failures of the following tests were due to the fact the build was in `Debug` [^1]:

```
qMRMLThreeDViewTest1
qMRMLThreeDWidgetTest1
qMRMLThreeDWidgetEventTranslatorPlayerTest1
```

[^1]: The fact the local build directory was named `Slicer-2-Release` misled me in thinking that it matched the build type of `Slicer-Release` (effectively being in `Release`).

**Comment by jcfr** [comment]
Et voila, the last failing test (`qMRMLLayoutManagerVisibilityTest`) is expected to be fixed by https://github.com/Slicer/Slicer/pull/6797. 

Once it is merged into `main` it will be backported.

**Comment by jcfr** [comment]
@lassoan After we backport https://github.com/Slicer/Slicer/pull/6798, I think we will be in good shape to tag & release.

How does that sound ?

cc: @jamesobutler @sjh26 @pieper

**Comment by jamesobutler** [comment]
I will begin a local build on Windows with this branch + those 2 additional PRs of commits locally cherry-picked over. I will run tests and post results in the morning

**Comment by jamesobutler** [comment]
Windows build/package/tests were all successful.

> 1>100% tests passed, 0 tests failed out of 661

This is without the additional upcoming change regarding https://github.com/Slicer/Slicer/pull/6799#issuecomment-1406472244.

**Comment by jcfr** [comment]
Thanks everyone for testing, I just backported the additional commits.

After we perform additional testing, here is the proposed timeline:

- week of Feb 14: Release of Slicer 5.2.2  (will be done on macOS 10.13 with deployment target set to 10.13)

- week of Feb 20: Update of Slicer Preview build (aka nightly) to happen on macOS 13.x with deployment target set to 11.0. See https://github.com/Slicer/DashboardScripts/pull/53

- afterward, we will get started on addressing arm64 support:
  * https://github.com/Slicer/Slicer/issues/5944
  * https://github.com/Slicer/slicer_download/issues/22
  * https://github.com/Slicer/slicer_download_stats/issues/6

**Comment by jcfr** [comment]
Associated patch release issue:
* https://github.com/Slicer/Slicer/issues/6832

**Pull request merged**
