### PR TITLE
BUG: Update SimpleITK to fix import adding missing use of custom namespace

### PR DESCRIPTION
**Pull request by jcfr**
### BUG: Update SimpleITK to fix import adding missing use of custom namespace

Update remaining use of `itk::simple` introduced after Slicer/SimpleITK@f95590f7 and omitted when updating SimpleITK in the context of Slicer/Slicer@acf3dd47 (ENH: Update ITK to 5.4.0)

List of SimpleITK changes:

```
$ git shortlog 4328a91a..441c59aa --no-merges
Jean-Christophe Fillion-Robin (2):
      COMP: Update remaining Swig interface files to use "slicer_itk" namespace
      COMP: Revert namespace changes in "sitkPathType.i" to fix build issues
```

-----------

###  COMP: Ensure SimpleITK is built using Slicer Python environment

Ensure SimpleITK is built using the Slicer Python environment by fixing the configuration to account for changes introduced in SimpleITK/SimpleITK@1b7d670b2, which uses the new CMake FindPython module.

This commit addresses the following warning:

```
CMake Warning at /path/to/SimpleITK/CMake/sitkLanguageOptions.cmake:110 (message):
  Use Python_EXECUTABLE! Ignoring PYTHON_EXECUTABLE:
```

Additionally, it resolves the error encountered when using CMake versions earlier than 3.24:

```
CMake Error at /path/to/cmake-3.22.2-linux-x86_64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Interpreter Development.Module)
Call Stack (most recent call first):
  /path/to/cmake-3.22.2-linux-x86_64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /path/to/cmake-3.22.2-linux-x86_64/share/cmake-3.22/Modules/FindPython.cmake:561 (find_package_handle_standard_args)
  Wrapping/Python/CMakeLists.txt:7 (find_package)
```

To support CMake versions earlier than 3.24, the _Python_VERSION variables are explicitly passed.
This workaround is necessary because the fix introduced in kitware/cmake@ece3bedbf (FindPython: fix error on multiple queries with different COMPONENTS) is not available in older CMake versions.

List of SimpleITK changes:

```
$ git shortlog 236005d4..4328a91af --no-merges
Jean-Christophe Fillion-Robin (2):
      COMP: Ensure Python_* variables are passed to SimpleITK inner-build
      COMP: Support CMake < 3.24 passing _Python_VERSION vars to inner-build
```

----------

This pull request supersedes https://github.com/Slicer/Slicer/pull/7810

Related pull requests and issues:
* https://github.com/Slicer/Slicer/pull/7771
* https://github.com/Slicer/Slicer/issues/7799
* https://github.com/Slicer/Slicer/pull/7810

### CODE REVIEW

**Comment by jcfr** [comment]
Local testing in progress :hourglass_flowing_sand:

**Comment by jcfr** [comment]
Local build of the changes in progress :hourglass_flowing_sand:

**Comment by jcfr** [comment]
Considering that building the branch on Windows[^1], macOS[^2] and Linux[^3] ("bluestreak") succeeds and allow to successfully  import SimpleITK (tested on Windows and Linux, macOS was not yet completed), I am moving forward with the integration :rocket: 

[^1]: "bluestreak" Windows factory
[^2]: "computron" macOS factory
[^3]: Ubuntu 20.04

**Comment by dzenanz** [comment]
Thank you for following up JC!

**Comment by lassoan** [comment]
I've tested this and I can confirm that SimpleITK in the latest Slicer Preview Release works well!
Thank you @jcfr!

**Pull request merged**
