### PR TITLE
ENH: Update icon for create markup fiducial node

### PR DESCRIPTION
**Pull request by smrolfe**
This commit updates the 'Create Fiducial Markup' icon in the Markups module. The single fiducial is replaced by a set of three points and the arrow is removed. The goal is to help users distinguish between the function of this button and the place fiducial point button.

This update was suggested by @lassoan in the forum discussion:
https://discourse.slicer.org/t/surface-semilandmarks-created-inadequately/13704/4?u=smrolfe

This pull request replaces [an earlier one](https://github.com/Slicer/Slicer/pull/5226) with an improved icon.

### CODE REVIEW

**Comment by smrolfe** [comment]
@pieper @lassoan @jamesobutler 
Please let me know if you have any further suggestions on this icon, I think the appearance is much improved with the reduced number of points.

**Review by pieper — APPROVED** [review]
This one looks nicer 👍

**Review by jamesobutler — COMMENTED** [review]
For reference:

Previous Proposal: image
Current Proposal: image
Current Icon: image

Yes, this new proposal looks good to me.

**Comment by lassoan** [comment]
@smrolfe Thank you, this new icon looks very nice. To preserve consistency of the icons, please remove the arrow from all the create markup node icons.

**Comment by SlicerMorph** [comment]
> 
> 
> @smrolfe Thank you, this new icon looks very nice. To preserve consistency of the icons, please remove the arrow from all the create markup node icons.

I want to take a look at this request, but is there a place where the vector images of original icons stored? Also would it be possible to incorporate these changes to the current stable too?

**Comment by lassoan** [comment]
> I want to take a look at this request, but is there a place where the vector images of original icons stored?

There are no vector originals. Icons of this small size are handcrafted, painted pixel by pixel, not converted from vector graphics.

> Also would it be possible to incorporate these changes to the current stable too?

This was a snapshot release, a separate branch was not created, so I'm not sure if it is possible to backport any changes. Maybe @sjh26 or @jcfr knows more what is feasible.

**Pull request merged**
