### PR TITLE
BUG: Small fixes 20231005

### PR DESCRIPTION
**Pull request by lassoan**
Fix of 3 small issues.

### CODE REVIEW

**Review by jcfr — APPROVED** [review]

**Review by pieper — APPROVED** [review]
LGTM 👍

**Comment by jcfr** [comment]
Since the three commits were carefully crafted, I think this should have been integrated through `rebase + merge` (instead of `squash + merge`)

@pieper Out of curiosity, was this intentional or was the "default" proposed through the GitHub UI misleading ?

**Comment by pieper** [comment]
I just did the default since it seemed logical, but I guess rebasing and merging would make sense.  It didn't seem like a big deal, but I see your point.

**Comment by lassoan** [comment]
I can remove the squashed commit and merge+rebase, unless @jcfr or @pieper you want to do it.

**Comment by jcfr** [comment]
> I can remove the squashed commit and merge+rebase

Since I raised this, I will take care of it then ...


And definitely a nitpick. I just help when reviewing the history. For example, I do so once a week to communicate internally about recent changes.

**Comment by jcfr** [comment]
@lassoan  @pieper Consider approving:
* https://github.com/Slicer/Slicer/pull/7263

**Pull request merged**
