### PR TITLE
BUG: Fix condition for customization in qSlicerTerminologyItemDelegate

### PR DESCRIPTION
**Pull request by Punzo**
@cpinter @lassoan 

Issue: color picker not working for any node in the Data or Markups module (i.e., any widget using `qMRMLSubjectHierarchyTreeView`)

https://github.com/user-attachments/assets/a140ecc8-a411-4e29-aa42-8b73cdc2e56a

Fix: use terminology color picker as default. Csaba, I am not sure this small change breaks anything else or if I am missing something. Your input will be very welcome!

Ref: https://github.com/Slicer/Slicer/commit/ab918265234155a72044a21e7a4e4653cd975927

### CODE REVIEW

**Comment by cpinter** [comment]
The line in question is from the refactoring of my code by @lassoan so I defer to him.

**Comment by lassoan** [comment]
Changing the default does not address the root cause of the problem but it may effectively mask it. I may have time for looking into it early next week. If @cpinter you can get to it sooner that's great.

**Comment by Punzo** [comment]
@lassoan @cpinter I had a look at the class qSlicerTerminologyItemDelegate, and fixed the underlying issue. i.e. I changed the QLineEdit widget used as editor with a ctkColorPickerButton.

**Comment by Punzo** [comment]
> @lassoan @cpinter I had a look at the class qSlicerTerminologyItemDelegate, and fixed the underlying issue. i.e. I changed the QLineEdit widget used as editor with a ctkColorPickerButton.

P.S.1: it would be nide to add a `cancel` signal at `ctkColorPickerButton` and connect it to `close` slot as the one for `qSlicerTerminologySelectorButton`, but I don;t have time for it.
P.S.2: I discriminate between nodes by using the default color, see https://github.com/Slicer/Slicer/pull/8059/files#diff-6c0329496f9e1e52921d60a5363b23b64c84e9c6a552996ff838ffa783eaa28cR71-R80. Not sure if there is a more optimal way.

**Comment by cpinter** [comment]
I think these changes are breaking other things (thinking about changing the ColorRole to DecorationRole, but there might be more). @Punzo have you tested every part of the feature?

**Comment by Punzo** [comment]
> I think these changes are breaking other things (thinking about changing the ColorRole to DecorationRole, but there might be more). @Punzo have you tested every part of the feature?

I have tested with volumes, markups, segmentations and models in the data module tree and in the segmentation editor. Both with the option UseTerminologySelectorCallback to false and true

UseTerminologySelectorCallback true:

https://github.com/user-attachments/assets/0ae15c65-98c0-442b-b119-d664ceae0c5b


https://github.com/user-attachments/assets/cb9aa200-9e45-4352-9fc3-e8430a7a84fc


UseTerminologySelectorCallback false (the default):

https://github.com/user-attachments/assets/2f6405cd-7ca6-4ae5-9c9a-2d10b91e2000

**Comment by Punzo** [comment]
@cpinter if you can do a round of testing it would be very apprecciated. I’m in no rush to have this merged on my end.

**Comment by Punzo** [comment]
> > I think these changes are breaking other things (thinking about changing the ColorRole to DecorationRole, but there might be more). @Punzo have you tested every part of the feature?
> 
> I have tested with volumes, markups, segmentations and models in the data module tree and in the segmentation editor. Both with the option UseTerminologySelectorCallback to false and true
> 
> UseTerminologySelectorCallback true:
> 
>  2024-11-22.15-10-15.mp4 
>  2024-11-22.15-11-22.mp4 
> UseTerminologySelectorCallback false (the default):
> 
>  2024-11-22.15-12-01.mp4

**Comment by lassoan** [comment]
I tested and it all works correctly for me, too. I don't know why chaning the role did not cause any problems, as at a few places still the qSlicerTerminologyItemDelegate::ColorRole is used. @Punzo do you remember why the role had to be changed?

**Comment by Punzo** [comment]
> I tested and it all works correctly for me, too. I don't know why chaning the role did not cause any problems, as at a few places still the qSlicerTerminologyItemDelegate::ColorRole is used. @Punzo do you remember why the role had to be changed?

simply using the `ColorRole` instead of `DecorationRole` was not working, so I changed to `DecorationRole`. But I did not investigated why (I hadn't the time).

**Review by lassoan — APPROVED** [review]
This commit fixes the issue, let's merge it and we can review the design later.

**Pull request merged**
