### PR TITLE
ENH: Update CTK to include QtMultimedia Python wrappers

### PR DESCRIPTION
**Pull request by jcfr**
List of CTK changes:

```
$ git shortlog 34a390a4..ec9fcee5 --no-merges
Sylvain Bernhardt (1):
      ENH: Add Python wrapping for Qt multimedia component (PR-992)
```

Co-authored-by: Andras Lasso <lasso@queensu.ca>
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>

### CODE REVIEW

**Comment by lassoan** [comment]
@jcfr this looks like the change that I've just reverted (https://github.com/Slicer/Slicer/pull/5923) because it [breaks the install package](https://discourse.slicer.org/t/slicer-wont-start/20017/4?u=lassoan). Have you managed to fix this problem?

**Comment by jcfr** [comment]
On windows, here is the call to `windeployqt.exe` configured in `cmake_install.cmake`:

```
execute_process(COMMAND "D:/Support/Qt2/5.15.2/msvc2019_64/bin/windeployqt.exe" --release --no-compiler-runtime --no-translations --no-plugins -core -widgets -multimedia -network -opengl -printsupport -xml -xmlpatterns -svg -sql -webengine -webenginewidgets -webchannel -script -test -gui -qml -quick -quickwidgets -webenginecore -positioning -designercomponents "${CMAKE_INSTALL_PREFIX}/bin/SlicerApp-real.exe")
```

References:

* list of libraries for initializing list of components passed to `windeployqt.exe`

https://github.com/Slicer/Slicer/blob/bd6021edf5414aaacb3b5d25a43b47e5b8443268/CMake/SlicerBlockInstallQt.cmake#L6-L35

* call to `windeployqt.exe`

https://github.com/Slicer/Slicer/blob/bd6021edf5414aaacb3b5d25a43b47e5b8443268/CMake/SlicerBlockInstallQt.cmake#L154-L181

**Comment by lassoan** [comment]
It seems that `multimediawidgets` library is missing. I guess only `multimedia` library is specified because PythonQt uses a single flag to enable both `multimedia` and `multimediawidgets` Qt libraries.

**Comment by jcfr** [comment]
This is now ready for review. The latest commit is expected to fix the packaging issue.

**Comment by jcfr** [comment]
Alternatively, we could introduce an option called `Slicer_BUILD_AUDIO_SUPPORT` and then list `Qt5::MultimediaWidgets` here: 

https://github.com/Slicer/Slicer/blob/1a6186cde4676f9935bf2668cc0c78954ce4db21/CMakeLists.txt#L580-L588

Doing something like this:

```diff
  set(Slicer_REQUIRED_QT_MODULES
    Core Widgets
-    Multimedia
    Network OpenGL
    PrintSupport # Required by "Annotations" module
    UiTools #no dll
    Xml XmlPatterns
    Svg Sql
    )
+if(Slicer_BUILD_AUDIO_SUPPORT)
+  list(APPEND Slicer_REQUIRED_QT_MODULES
+    Multimedia
+    MultimediaWidgets
+    )
+endif()
```

**Comment by atracsys-sbt** [comment]
While testing the new sound inclusion in slicer, I realized something weird: in the python terminal, I can play sound no problem. However, running the exact same code (with an absolute path to a .wav file) in a scripted module does nothing (no sound, no error)...

**Comment by lassoan** [comment]
> While testing the new sound inclusion in slicer, I realized something weird: in the python terminal, I can play sound no problem. However, running the exact same code (with an absolute path to a .wav file) in a scripted module does nothing (no sound, no error)...

Maybe you need to pump the event loop. Try adding `slicer.app.processEvents()` to see if it solves the issue. If you can upload a minimal example that reproduces the issue then I can have a look.

**Comment by atracsys-sbt** [comment]
> 
> 
> > While testing the new sound inclusion in slicer, I realized something weird: in the python terminal, I can play sound no problem. However, running the exact same code (with an absolute path to a .wav file) in a scripted module does nothing (no sound, no error)...
> 
> Maybe you need to pump the event loop. Try adding `slicer.app.processEvents()` to see if it solves the issue. If you can upload a minimal example that reproduces the issue then I can have a look.

I tried, but it didn't seem to work. Here is the [scripted module](https://github.com/Slicer/Slicer/files/7294749/module1.zip) I use to test this problem.

**Comment by lassoan** [comment]
Thanks for the example it made things very clear. Since you create the QSound object as a local variable, it gets immediately deleted when you exit the method. You need to keep the object alive, for example by storing it in a member variable.

**Review by lassoan — DISMISSED** [review]
This looks perfect to me.

**Comment by jcfr** [comment]
Note that including `Qt5::Multimedia` only if `Slicer_BUILD_MULTIMEDIA_SUPPORT ` is `ON` is valid since it was originally introduced to support use of `QSound`. See https://github.com/Slicer/Slicer/commit/6a2af8e4c2a95497d5962335b9bfc7fa75a2641f

**Pull request merged**
