### PR TITLE
ENH: Update SimpleITK to v1.1.0 release

### PR DESCRIPTION
**Pull request by blowekamp**
Release Notes:
https://github.com/SimpleITK/SimpleITK/releases/tag/v1.1.0

### CODE REVIEW

**Comment by lassoan** [comment]
After updating the git hash to use latest SimpleITK, there seem to be some new errors in SimpleFilters test (see details below). Could you check if these are related and if SimpleFilters module would need to be updated along with SimpleITK?

```
649/684 Testing: py_SimpleFiltersModuleTest
649/684 Test: py_SimpleFiltersModuleTest
Command: "C:/D/S4R/Slicer-build/Slicer.exe" "--no-splash" "--testing" "--additional-module-paths" "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules" "C:/D/S4R/Slicer-build/lib/Slicer-4.9/cli-modules" "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-loadable-modules" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['C:/D/S4R/Slicer-build/E/SimpleFilters/SimpleFilters/Testing/Python', 'C:/D/S4R/SimpleFilters/SimpleFilters/Testing/Python'], 'SimpleFiltersModuleTest')"
Directory: C:/D/S4R/Slicer-build/E/SimpleFilters/SimpleFilters/Testing/Python
"py_SimpleFiltersModuleTest" start time: Apr 17 23:05 Eastern Daylight Time
Output:
----------------------------------------------------------
libpng warning: iCCP: known incorrect sRGB profile
Switch to module:  "Welcome"
-------------------------------------------
path: ['C:/D/S4R/Slicer-build/E/SimpleFilters/SimpleFilters/Testing/Python', 'C:/D/S4R/SimpleFilters/SimpleFilters/Testing/Python']
testname: SimpleFiltersModuleTest
-------------------------------------------
Switch to module:  "SimpleFilters"
testing my test....
Testing filter "AbsImageFilter" (0 of 258).
Testing filter "AbsoluteValueDifferenceImageFilter" (1 of 258).
Testing filter "AcosImageFilter" (2 of 258).
Testing filter "AdaptiveHistogramEqualizationImageFilter" (3 of 258).
test_SimpleFilters1 (SimpleFiltersModuleTest.SimpleFiltersTest) ... Traceback (most recent call last):
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 260, in onFilterSelect
    self.filterParameters.create(json)
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 805, in create
    w = self.createBoolWidget(member["name"])
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 963, in createBoolWidget
    exec('default = self.filter.Get{0}()'.format(name)) in globals(), locals()
  File "<string>", line 1, in <module>
  File "C:\D\S4R\python-install\Lib\site-packages\SimpleITK\SimpleITK.py", line 10934, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, AdaptiveHistogramEqualizationImageFilter, name)
  File "C:\D\S4R\python-install\Lib\site-packages\SimpleITK\SimpleITK.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'AdaptiveHistogramEqualizationImageFilter' object has no attribute 'GetUseLookupTable'
Testing filter "AddImageFilter" (4 of 258).
Testing filter "AdditiveGaussianNoiseImageFilter" (5 of 258).
Testing filter "AndImageFilter" (6 of 258).
Testing filter "AntiAliasBinaryImageFilter" (7 of 258).
Testing filter "ApproximateSignedDistanceMapImageFilter" (8 of 258).
Testing filter "AsinImageFilter" (9 of 258).
Testing filter "Atan2ImageFilter" (10 of 258).
Testing filter "AtanImageFilter" (11 of 258).
Testing filter "BilateralImageFilter" (12 of 258).
Testing filter "BinShrinkImageFilter" (13 of 258).
Testing filter "BinaryClosingByReconstructionImageFilter" (14 of 258).
Testing filter "BinaryContourImageFilter" (15 of 258).
Testing filter "BinaryDilateImageFilter" (16 of 258).
Testing filter "BinaryErodeImageFilter" (17 of 258).
Testing filter "BinaryFillholeImageFilter" (18 of 258).
Testing filter "BinaryGrindPeakImageFilter" (19 of 258).
Testing filter "BinaryMagnitudeImageFilter" (20 of 258).
Testing filter "BinaryMedianImageFilter" (21 of 258).
Testing filter "BinaryMinMaxCurvatureFlowImageFilter" (22 of 258).
Testing filter "BinaryMorphologicalClosingImageFilter" (23 of 258).
Testing filter "BinaryMorphologicalOpeningImageFilter" (24 of 258).
Testing filter "BinaryNotImageFilter" (25 of 258).
Testing filter "BinaryOpeningByReconstructionImageFilter" (26 of 258).
Testing filter "BinaryProjectionImageFilter" (27 of 258).
Testing filter "BinaryReconstructionByDilationImageFilter" (28 of 258).
Testing filter "BinaryReconstructionByErosionImageFilter" (29 of 258).
Testing filter "BinaryThinningImageFilter" (30 of 258).
Testing filter "BinaryThresholdImageFilter" (31 of 258).
Testing filter "BinaryThresholdProjectionImageFilter" (32 of 258).
Testing filter "BinomialBlurImageFilter" (33 of 258).
Testing filter "BitwiseNotImageFilter" (34 of 258).
Testing filter "BlackTopHatImageFilter" (35 of 258).
Testing filter "BoundedReciprocalImageFilter" (36 of 258).
Testing filter "BoxMeanImageFilter" (37 of 258).
Testing filter "BoxSigmaImageFilter" (38 of 258).
Testing filter "CannyEdgeDetectionImageFilter" (39 of 258).
Testing filter "CastImageFilter" (40 of 258).
Testing filter "CheckerBoardImageFilter" (41 of 258).
Testing filter "ClampImageFilter" (42 of 258).
Testing filter "ClosingByReconstructionImageFilter" (43 of 258).
Testing filter "CollidingFrontsImageFilter" (44 of 258).
Testing filter "ComplexToImaginaryImageFilter" (45 of 258).
Testing filter "ComplexToModulusImageFilter" (46 of 258).
Testing filter "ComplexToPhaseImageFilter" (47 of 258).
Testing filter "ComplexToRealImageFilter" (48 of 258).
Testing filter "ComposeImageFilter" (49 of 258).
Testing filter "ConfidenceConnectedImageFilter" (50 of 258).
Testing filter "ConnectedComponentImageFilter" (51 of 258).
Testing filter "ConnectedThresholdImageFilter" (52 of 258).
Testing filter "ConstantPadImageFilter" (53 of 258).
Testing filter "ConvolutionImageFilter" (54 of 258).
Testing filter "CosImageFilter" (55 of 258).
Testing filter "CropImageFilter" (56 of 258).
Testing filter "CurvatureAnisotropicDiffusionImageFilter" (57 of 258).
Testing filter "CurvatureFlowImageFilter" (58 of 258).
Testing filter "CyclicShiftImageFilter" (59 of 258).
Testing filter "DanielssonDistanceMapImageFilter" (60 of 258).
adding 0: Input FixedVolume: 
adding 1: Input MovingVolume: 
adding 2: Input InitialDisplacementField: 
Testing filter "DemonsRegistrationFilter" (61 of 258).
Testing filter "DerivativeImageFilter" (62 of 258).
adding 0: Input FixedVolume: 
adding 1: Input MovingVolume: 
adding 2: Input InitialDisplacementField: 
Testing filter "DiffeomorphicDemonsRegistrationFilter" (63 of 258).
Testing filter "DilateObjectMorphologyImageFilter" (64 of 258).
Testing filter "DiscreteGaussianDerivativeImageFilter" (65 of 258).
Testing filter "DiscreteGaussianImageFilter" (66 of 258).
Traceback (most recent call last):
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 260, in onFilterSelect
    self.filterParameters.create(json)
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 803, in create
    w = self.createDoubleWidget(member["name"])
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 982, in createDoubleWidget
    w.setValue(default)
ValueError: Called setValue(double val) -> void with wrong arguments: ((1.0, 1.0, 1.0),)
Testing filter "DisplacementFieldJacobianDeterminantFilter" (67 of 258).
Testing filter "DivideFloorImageFilter" (68 of 258).
Testing filter "DivideImageFilter" (69 of 258).
Testing filter "DivideRealImageFilter" (70 of 258).
Testing filter "DoubleThresholdImageFilter" (71 of 258).
Testing filter "EdgePotentialImageFilter" (72 of 258).
Testing filter "EqualImageFilter" (73 of 258).
Testing filter "ErodeObjectMorphologyImageFilter" (74 of 258).
Testing filter "ExpImageFilter" (75 of 258).
Testing filter "ExpNegativeImageFilter" (76 of 258).
Testing filter "ExpandImageFilter" (77 of 258).
Testing filter "ExtractImageFilter" (78 of 258).
Testing filter "FFTConvolutionImageFilter" (79 of 258).
Testing filter "FFTNormalizedCorrelationImageFilter" (80 of 258).
Testing filter "FFTShiftImageFilter" (81 of 258).
Testing filter "FastApproximateRankImageFilter" (82 of 258).
Testing filter "FastMarchingBaseImageFilter" (83 of 258).
Testing filter "FastMarchingImageFilter" (84 of 258).
Testing filter "FastMarchingUpwindGradientImageFilter" (85 of 258).
adding 0: Input FixedVolume: 
adding 1: Input MovingVolume: 
adding 2: Input InitialDisplacementField: 
Testing filter "FastSymmetricForcesDemonsRegistrationFilter" (86 of 258).
Testing filter "FlipImageFilter" (87 of 258).
Testing filter "ForwardFFTImageFilter" (88 of 258).
Testing filter "GaborImageSource" (89 of 258).
Testing filter "GaussianImageSource" (90 of 258).
Testing filter "GeodesicActiveContourLevelSetImageFilter" (91 of 258).
Testing filter "GradientAnisotropicDiffusionImageFilter" (92 of 258).
Testing filter "GradientImageFilter" (93 of 258).
Testing filter "GradientMagnitudeImageFilter" (94 of 258).
Testing filter "GradientMagnitudeRecursiveGaussianImageFilter" (95 of 258).
Testing filter "GradientRecursiveGaussianImageFilter" (96 of 258).
Testing filter "GrayscaleConnectedClosingImageFilter" (97 of 258).
Testing filter "GrayscaleConnectedOpeningImageFilter" (98 of 258).
Testing filter "GrayscaleDilateImageFilter" (99 of 258).
Testing filter "GrayscaleErodeImageFilter" (100 of 258).
Testing filter "GrayscaleFillholeImageFilter" (101 of 258).
Testing filter "GrayscaleGeodesicDilateImageFilter" (102 of 258).
Testing filter "GrayscaleGeodesicErodeImageFilter" (103 of 258).
Testing filter "GrayscaleGrindPeakImageFilter" (104 of 258).
Testing filter "GrayscaleMorphologicalClosingImageFilter" (105 of 258).
Testing filter "GrayscaleMorphologicalOpeningImageFilter" (106 of 258).
Testing filter "GreaterEqualImageFilter" (107 of 258).
Testing filter "GreaterImageFilter" (108 of 258).
Testing filter "GridImageSource" (109 of 258).
Testing filter "HConcaveImageFilter" (110 of 258).
Testing filter "HConvexImageFilter" (111 of 258).
Testing filter "HMaximaImageFilter" (112 of 258).
Testing filter "HMinimaImageFilter" (113 of 258).
Testing filter "HalfHermitianToRealInverseFFTImageFilter" (114 of 258).
Testing filter "HausdorffDistanceImageFilter" (115 of 258).
Testing filter "HistogramMatchingImageFilter" (116 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "HuangThresholdImageFilter" (117 of 258).
Testing filter "IntensityWindowingImageFilter" (118 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "IntermodesThresholdImageFilter" (119 of 258).
Testing filter "InverseDeconvolutionImageFilter" (120 of 258).
Testing filter "InverseDisplacementFieldImageFilter" (121 of 258).
Testing filter "InverseFFTImageFilter" (122 of 258).
Testing filter "InvertDisplacementFieldImageFilter" (123 of 258).
Testing filter "InvertIntensityImageFilter" (124 of 258).
Testing filter "IsoContourDistanceImageFilter" (125 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "IsoDataThresholdImageFilter" (126 of 258).
Testing filter "IsolatedConnectedImageFilter" (127 of 258).
Testing filter "IsolatedWatershedImageFilter" (128 of 258).
Testing filter "JoinSeriesImageFilter" (129 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "KittlerIllingworthThresholdImageFilter" (130 of 258).
Testing filter "LabelContourImageFilter" (131 of 258).
adding 0: Input Volume: 
adding 1: Input LabelVolume: 
Testing filter "LabelOverlayImageFilter" (132 of 258).
Testing filter "LabelToRGBImageFilter" (133 of 258).
Testing filter "LabelVotingImageFilter" (134 of 258).
Testing filter "LandweberDeconvolutionImageFilter" (135 of 258).
Testing filter "LaplacianImageFilter" (136 of 258).
Testing filter "LaplacianRecursiveGaussianImageFilter" (137 of 258).
Testing filter "LaplacianSegmentationLevelSetImageFilter" (138 of 258).
Testing filter "LaplacianSharpeningImageFilter" (139 of 258).
Testing filter "LessEqualImageFilter" (140 of 258).
Testing filter "LessImageFilter" (141 of 258).
Testing filter "LevelSetMotionRegistrationFilter" (142 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "LiThresholdImageFilter" (143 of 258).
Testing filter "Log10ImageFilter" (144 of 258).
Testing filter "LogImageFilter" (145 of 258).
Testing filter "MagnitudeAndPhaseToComplexImageFilter" (146 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "MaskImageFilter" (147 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "MaskNegatedImageFilter" (148 of 258).
Testing filter "MaskedFFTNormalizedCorrelationImageFilter" (149 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "MaximumEntropyThresholdImageFilter" (150 of 258).
Testing filter "MaximumImageFilter" (151 of 258).
Testing filter "MaximumProjectionImageFilter" (152 of 258).
Testing filter "MeanImageFilter" (153 of 258).
Testing filter "MeanProjectionImageFilter" (154 of 258).
Testing filter "MedianImageFilter" (155 of 258).
Testing filter "MedianProjectionImageFilter" (156 of 258).
Testing filter "MinMaxCurvatureFlowImageFilter" (157 of 258).
Testing filter "MinimumImageFilter" (158 of 258).
Testing filter "MinimumMaximumImageFilter" (159 of 258).
Testing filter "MinimumProjectionImageFilter" (160 of 258).
Testing filter "MirrorPadImageFilter" (161 of 258).
Testing filter "ModulusImageFilter" (162 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "MomentsThresholdImageFilter" (163 of 258).
Testing filter "MorphologicalGradientImageFilter" (164 of 258).
adding 0: Input Volume: 
adding 1: Input MarkerVolume: 
Testing filter "MorphologicalWatershedFromMarkersImageFilter" (165 of 258).
Testing filter "MorphologicalWatershedImageFilter" (166 of 258).
Testing filter "MultiplyImageFilter" (167 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "N4BiasFieldCorrectionImageFilter" (168 of 258).
Unknown member "MaximumNumberOfIterations" of type "std::vector<uint32_t>"
Testing filter "NaryAddImageFilter" (169 of 258).
Testing filter "NaryMaximumImageFilter" (170 of 258).
Testing filter "NeighborhoodConnectedImageFilter" (171 of 258).
Testing filter "NoiseImageFilter" (172 of 258).
Testing filter "NormalizeImageFilter" (173 of 258).
Testing filter "NormalizeToConstantImageFilter" (174 of 258).
Testing filter "NormalizedCorrelationImageFilter" (175 of 258).
Testing filter "NotEqualImageFilter" (176 of 258).
Testing filter "NotImageFilter" (177 of 258).
Testing filter "OpeningByReconstructionImageFilter" (178 of 258).
Testing filter "OrImageFilter" (179 of 258).
Testing filter "OtsuMultipleThresholdsImageFilter" (180 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "OtsuThresholdImageFilter" (181 of 258).
Testing filter "PasteImageFilter" (182 of 258).
Testing filter "PatchBasedDenoisingImageFilter" (183 of 258).
Testing filter "PermuteAxesImageFilter" (184 of 258).
Testing filter "PhysicalPointImageSource" (185 of 258).
Testing filter "PowImageFilter" (186 of 258).
Testing filter "ProjectedLandweberDeconvolutionImageFilter" (187 of 258).
Testing filter "RankImageFilter" (188 of 258).
Testing filter "RealAndImaginaryToComplexImageFilter" (189 of 258).
Testing filter "RealToHalfHermitianForwardFFTImageFilter" (190 of 258).
Testing filter "ReconstructionByDilationImageFilter" (191 of 258).
Testing filter "ReconstructionByErosionImageFilter" (192 of 258).
Testing filter "RecursiveGaussianImageFilter" (193 of 258).
Testing filter "RegionOfInterestImageFilter" (194 of 258).
Testing filter "RegionalMaximaImageFilter" (195 of 258).
Testing filter "RegionalMinimaImageFilter" (196 of 258).
Testing filter "RelabelComponentImageFilter" (197 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "RenyiEntropyThresholdImageFilter" (198 of 258).
Testing filter "ResampleImageFilter" (199 of 258).
Unknown member "Transform" of type "Transform"
Testing filter "RescaleIntensityImageFilter" (200 of 258).
Testing filter "RichardsonLucyDeconvolutionImageFilter" (201 of 258).
Testing filter "SaltAndPepperNoiseImageFilter" (202 of 258).
Testing filter "ScalarChanAndVeseDenseLevelSetImageFilter" (203 of 258).
Testing filter "ScalarConnectedComponentImageFilter" (204 of 258).
Testing filter "ScalarImageKmeansImageFilter" (205 of 258).
Unknown member "ClassWithInitialMean" of type "std::vector<double>"
Testing filter "ScalarToRGBColormapImageFilter" (206 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "ShanbhagThresholdImageFilter" (207 of 258).
Testing filter "ShapeDetectionLevelSetImageFilter" (208 of 258).
Testing filter "ShiftScaleImageFilter" (209 of 258).
Testing filter "ShotNoiseImageFilter" (210 of 258).
Testing filter "ShrinkImageFilter" (211 of 258).
Testing filter "SigmoidImageFilter" (212 of 258).
Testing filter "SignedDanielssonDistanceMapImageFilter" (213 of 258).
Testing filter "SignedMaurerDistanceMapImageFilter" (214 of 258).
Testing filter "SimilarityIndexImageFilter" (215 of 258).
Testing filter "SimpleContourExtractorImageFilter" (216 of 258).
Testing filter "SinImageFilter" (217 of 258).
Testing filter "SliceImageFilter" (218 of 258).
Testing filter "SmoothingRecursiveGaussianImageFilter" (219 of 258).
Traceback (most recent call last):
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 260, in onFilterSelect
    self.filterParameters.create(json)
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 803, in create
    w = self.createDoubleWidget(member["name"])
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 982, in createDoubleWidget
    w.setValue(default)
ValueError: Called setValue(double val) -> void with wrong arguments: ((1.0, 1.0, 1.0),)
Testing filter "SobelEdgeDetectionImageFilter" (220 of 258).
Testing filter "SpeckleNoiseImageFilter" (221 of 258).
Testing filter "SqrtImageFilter" (222 of 258).
Testing filter "SquareImageFilter" (223 of 258).
Testing filter "SquaredDifferenceImageFilter" (224 of 258).
Testing filter "StandardDeviationProjectionImageFilter" (225 of 258).
Testing filter "SubtractImageFilter" (226 of 258).
Testing filter "SumProjectionImageFilter" (227 of 258).
adding 0: Input FixedVolume: 
adding 1: Input MovingVolume: 
adding 2: Input InitialDisplacementField: 
Testing filter "SymmetricForcesDemonsRegistrationFilter" (228 of 258).
Testing filter "TanImageFilter" (229 of 258).
Testing filter "TernaryAddImageFilter" (230 of 258).
Testing filter "TernaryMagnitudeImageFilter" (231 of 258).
Testing filter "TernaryMagnitudeSquaredImageFilter" (232 of 258).
Testing filter "ThresholdImageFilter" (233 of 258).
Testing filter "ThresholdMaximumConnectedComponentsImageFilter" (234 of 258).
Testing filter "ThresholdSegmentationLevelSetImageFilter" (235 of 258).
Testing filter "TikhonovDeconvolutionImageFilter" (236 of 258).
Testing filter "TileImageFilter" (237 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "TriangleThresholdImageFilter" (238 of 258).
Testing filter "UnaryMinusImageFilter" (239 of 258).
Testing filter "ValuedRegionalMaximaImageFilter" (240 of 258).
Testing filter "ValuedRegionalMinimaImageFilter" (241 of 258).
Testing filter "VectorConfidenceConnectedImageFilter" (242 of 258).
Testing filter "VectorConnectedComponentImageFilter" (243 of 258).
Testing filter "VectorIndexSelectionCastImageFilter" (244 of 258).
Testing filter "VectorMagnitudeImageFilter" (245 of 258).
Testing filter "VotingBinaryHoleFillingImageFilter" (246 of 258).
Testing filter "VotingBinaryImageFilter" (247 of 258).
Testing filter "VotingBinaryIterativeHoleFillingImageFilter" (248 of 258).
Testing filter "WarpImageFilter" (249 of 258).
Testing filter "WhiteTopHatImageFilter" (250 of 258).
Testing filter "WienerDeconvolutionImageFilter" (251 of 258).
Testing filter "WrapPadImageFilter" (252 of 258).
Testing filter "XorImageFilter" (253 of 258).
adding 0: Input Volume: 
adding 1: Input MaskVolume: 
Testing filter "YenThresholdImageFilter" (254 of 258).
Testing filter "ZeroCrossingBasedEdgeDetectionImageFilter" (255 of 258).
Testing filter "ZeroCrossingImageFilter" (256 of 258).
Testing filter "ZeroFluxNeumannPadImageFilter" (257 of 258).
ok

----------------------------------------------------------------------
Ran 1 test in 31.979s

```

**Comment by blowekamp** [comment]
There errors are related to the following two changes in the SimpleITK filter descriptions:
SimpleITK/SimpleITK@701c7b909e3ad371b966e2bb87fc23a7de346d0d
SimpleITK/SimpleITK@810ad19944dbe10c39e2b2778e9a4b74fcb1466d

The SimpleFilters Slicer modules should be updated with the latest SimpleITK JSON. I'll try to get to it shortly.

Thanks

**Comment by blowekamp** [comment]
@lassoan This issues should be fixed now.

**Comment by lassoan** [comment]
Now there are only two issues:

1. 

```
Testing filter "MultiLabelSTAPLEImageFilter" (170 of 264).
Traceback (most recent call last):
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 260, in onFilterSelect
    self.filterParameters.create(json)
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 811, in create
    w = self.createIntWidget(member["name"],t)
  File "C:/D/S4R/Slicer-build/lib/Slicer-4.9/qt-scripted-modules/SimpleFilters.py", line 957, in createIntWidget
    w.setValue(int(default))
ValueError: Called setValue(int val) -> void with wrong arguments: (4294967295L,)
```

2.

```
Switch to module:  ""
Exception ValueError: "Trying to call 'disconnect' on a destroyed qMRMLNodeComboBox object" in <bound method FilterParameters.__del__ of <SimpleFilters.FilterParameters object at 0x000002495423B208>> ignored
vtkDebugLeaks has found no leaks.
```

This one is probably a side effect of the fix for the widget destroy crash and could be fixed by catching ValueError exceptions.

**Comment by blowekamp** [comment]
This first failure is cause by an out of range conversion error from the following value:
https://github.com/SimpleITK/SlicerSimpleFilters/blob/master/SimpleFilters/Resources/json/MultiLabelSTAPLEImageFilter.json#L12

**Comment by blowekamp** [comment]
*bump*

**Comment by jcfr** [comment]
Thanks for the reminder, we will integrate Friday or Monday

**Comment by jcfr** [comment]
Closing. Integrated in [r27229](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27229)

Note that similarly to `STAPLEImageFilter` (removed in https://github.com/SimpleITK/SlicerSimpleFilters/commit/77eeae334bef866318ed923e786d4af508b994ac#diff-fca0453372a4306b46cf28de484b3dbf),  `MultiLabelSTAPLEImageFilter` as been removed in https://github.com/SimpleITK/SlicerSimpleFilters/commit/92cbe91774350aca201b01de91ec1fa265173789

**Comment by blowekamp** [comment]
Thanks JC! Are there any followup needed for this update?

**Pull request closed without merging**
