### PR TITLE
Add vtk addon math utilities

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@lassoan:
* I introduced `vtkAddonTestingUtilities` and `vtkAddonTestingMacros` to facilitate testing of classes in vtkAddon
* I was also thinking to introduce `Matrix4x4AreStrictlyEqual()` .. that would have a tolerance set to '0' ?

@Punzo Consider adding some test to `vtkAddonMathUtilitiesTest1`, you can now use macros from `vtkAddonTestingMacros`

**Comment by Punzo** [comment]
@jcfr  added PR for test on your branch https://github.com/jcfr/Slicer/pull/2

**Comment by jcfr** [comment]
Integrated in [r25097](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25097)

**Comment by Punzo** [comment]
thanks!

**Pull request closed without merging**
