### PR TITLE
STYLE: Update python scripts with whitespace fixes

### PR DESCRIPTION
**Pull request by jamesobutler**
This is part of #6271 and the commit here is in the style of https://github.com/Slicer/Slicer/commit/a4adeff2e8f6f93a7ea4d465226cc3c4de3f200a. These changes were almost all completed through local automation. This commit once merged should be added to https://github.com/Slicer/Slicer/blob/master/.git-blame-ignore-revs.

This fixes all remaining pycodestyle E2 whitespace error codes.

Bulk of updates performed using autopep8 CLI
with the following command:

  autopep8 --in-place --select E201,E202,E203,E211,E221,E222,E225,E226,E227,E228,E231,E241,E251,E261,E262,E265,E266,E271 $(git ls-files '*.py')

See https://github.com/hhatto/autopep8#readme

References:

* Whitespace after '('
  See https://www.flake8rules.com/rules/E201.html

* Whitespace before ')'
  See https://www.flake8rules.com/rules/E202.html

* Whitespace before ':'
  See https://www.flake8rules.com/rules/E203.html

* Whitespace before '('
  See https://www.flake8rules.com/rules/E211.html

* Multiple spaces before operator
  See https://www.flake8rules.com/rules/E221.html

* Multiple spaces after operator
  See https://www.flake8rules.com/rules/E222.html

* Missing whitespace around operator
  See https://www.flake8rules.com/rules/E225.html

* Missing whitespace around arithmetic operator
  See https://www.flake8rules.com/rules/E226.html

* Missing whitespace around bitwise or shift operator
  See https://www.flake8rules.com/rules/E227.html

* Missing whitespace around modulo operator
  See https://www.flake8rules.com/rules/E228.html

* Missing whitespace after ',', ';', or ':'
  See https://www.flake8rules.com/rules/E231.html

* Multiple spaces after ','
  See https://www.flake8rules.com/rules/E241.html

* Unexpected spaces around keyword / parameter equals
  See https://www.flake8rules.com/rules/E251.html

* At least two spaces before inline comment
  See https://www.flake8rules.com/rules/E261.html

* Inline comment should start with '# '
  See https://www.flake8rules.com/rules/E262.html

* Block comment should start with '# '
  See https://www.flake8rules.com/rules/E265.html

* Too many leading '#' for block comment
  See https://www.flake8rules.com/rules/E266.html

* Multiple spaces after keyword
  See https://www.flake8rules.com/rules/E271.html

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
All these changes look good to me. They make the code look nicer and more consistent. A lot of files are affected but there are no pull requests with many .py file changes, so hopefully it won't cause much disruption.

One significant consequence would be that it would make it really hard to backport any .py fixes to the 5.0 branch. However, usually we only backport very few changes, so even if it is very hard then it may be manageable.

**Comment by lassoan** [comment]
@jamesobutler @jcfr @pieper @cpinter @Sunderlandkyl What do you think about switching to 4 spaces for .py file indentation?

I find it a waste of space, but using 4 spaces would make Slicer code feel more natural for Python developers, so overall I think it could worth it. If we all agree then it could be a good time to do it along with this change.

**Comment by jamesobutler** [comment]
I’m good with 4 spaces for indentation. This would then help address the E1 error codes which are all indentation related.

We would need to update the following to remove the current mention of using 2 spaces. https://github.com/Slicer/Slicer/blob/1bdfefe4e275c9b5713503077930fe387aa8a324/Docs/developer_guide/style_guide.md#python. I think most everything python linting related can be enforced automatically so consistency is easy to achieve when following the linters commonly agreed upon rules.

**Comment by pieper** [comment]
4 spaces would also be fine with me.  It's what I usually use for non-slicer python code.  I agree now would be a good time to do it.

**Comment by jamesobutler** [comment]
> it could be a good time to do it along with this change.

@lassoan You wanting this change added to this PR? Just thinking about maintenance of the branch if the PR stays open for a longer period of time that very likely would need some rebasing to fix merge conflicts. I could do it but the added diff would mean the merging of it would need to happen soon after.

**Comment by lassoan** [comment]
Yes, if possible please add to this pull request as a separate commit. These two commits touch a lot of files and it will cause less trouble if they are merged at about the same time.

It would be nice if these commits would be clearly separated from functional changes. @jcfr what is the best way to achieve this? Use a special prefix (STYLE:?) or a special author (slicerbot),...?

**Comment by jamesobutler** [comment]
@lassoan I've completed the documentation and running of the autopep8 fixes for the E1 pycodestyle indentation error codes. Since this touches nearly all python code any new python code changes will likely introduce merge conflicts here.

**Comment by jamesobutler** [comment]
Once merged, the final git hash of each commit will be perfect candidates to be added to https://github.com/Slicer/Slicer/blob/master/.git-blame-ignore-revs.

**Comment by jcfr** [comment]
As suggested, using `STYLE:` along with adding the commit to `.git-blame-ignore-revs` will work well.

I suggest we wait May 30th to integrate these changes, it will make eventual backport of fixes for `maintenance/5.0` easier.

Anticipating compatibility with `black`, I suggest we continue ignoring `E203`:
* https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices
* https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length

**Comment by jamesobutler** [comment]
Rebased to fix some merge conflicts

**Comment by jamesobutler** [comment]
Rebased to fix some merge conflicts

**Comment by lassoan** [comment]
Never mind, I'll resolve the conflicts.

**Comment by jamesobutler** [comment]
Thanks! I am off on vacation so have limited access to my computer.

**Pull request merged**
