### PR TITLE
ENH: Change organization name and domain to Slicer from NA-MIC

### LINKED ISSUE #6722: CPack always uses NA-MIC as the vendor for extension packages
## Summary

https://github.com/Slicer/Slicer/blob/53625c29ec8c212a91ba34750e01ea2a4b25272e/CMake/SlicerExtensionCPack.cmake#L126
CPack's NuGet generator, for example, uses this value for the `<authors>` property in the resulting package. Since `CPackConfig.cmake` is also written from that file, this setting can't be easily replaced.

## Expected behavior

Either `${EXTENSION_CONTRIBUTORS}` or the replaceable `${Slicer_ORGANIZATION_NAME}` seem to make more sense in this context.

### PR DESCRIPTION
**Pull request by jamesobutler**
See discussion at https://discourse.slicer.org/t/inconsistency-between-organization-name-used-for-settings-files-and-for-macos-bundle-identifier/26547

This also closes #6722

### CODE REVIEW

**Comment by jamesobutler** [comment]
Installed programs list:
image
Installed to user location:
image
Installed user settings location:
image

**Comment by jamesobutler** [comment]
Would migration of user settings being required from the NA-MIC location to the new Slicer organization location?

**Review by lassoan — APPROVED** [review]
I don't think it is a big issue if we don't bring over the settings from the old location, and it is a bit simpler and cleaner. The main problem I see with copying the old settings that it would be complicated to reset the application settings to the default (deleting Slicer.ini would not actually reset to the application default but it would reset to the content in the NA-MIC folder).

Since we recently released a new patch release (Slicer-5.2.2) I think this is a good time to make this change.

@jamesobutler Please update the migration guide and write a post on the Slicer forum after this is integrated (people may need to update their scripts).

**Comment by jcfr** [comment]
> deleting Slicer.ini would not actually reset to the application default but it would reset to the content in the NA-MIC folde

If we want to support this, after a first import, the original settings in NA-MIC folder would be:
1. updated to indicate that the settings have already been migrated (e.g writing in the application revision)
2. or deleted if the user choose to delete these after the first import

This would address the issue outlined by @lassoan 

That said, this would make the settings logic more complex so moving forward with approach suggested above is sensible.

**Comment by jamesobutler** [comment]
You all still want to have the Migration Guide on the slicer.org/wiki (https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide) or should it be migrated to the GitHub repository like https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md considering developers are likely the individuals writing the updates?

Based on the ordering, would a new Slicer 5.3 prefixed entry be placed at position 1.2 as the most recent 5.3 change? Is the 1.1 Slicer 5 changes since 4.10 section still needing to be first entry instead of chronologically mentioned?
image

**Comment by jcfr** [comment]
> re: migration

See https://github.com/Slicer/Slicer/issues/6207

**Comment by jamesobutler** [comment]
Migration guide updated: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/Slicer#Slicer_5.3:_Organization_name_and_domain_changed_from_NA-MIC_to_Slicer

Discourse post:
https://discourse.slicer.org/t/organization-name-and-domain-changed-from-na-mic-to-slicer/28173

**Pull request merged**
