### PR TITLE
ENH: Update vtkAddon to include vtkImageLabelDilate3D filter

### PR DESCRIPTION
**Pull request by lassoan**
Adds one commit:

Revision: 8bdd3d7bf0b81a947c5ed82754387b76c2bfd3f5
Author: Andras Lasso <lasso@queensu.ca>
Date: 2023-10-25 5:35:17 PM
Message:
ENH: Add vtkImageLabelDilate3D filter (#41)

Used when coloring a scalar volume using segmentation and we want to make sure that labels cover the underlying structure and a bit further (to color also the transition of the masked voxels). ----
Modified: CMakeLists.txt
Added: vtkImageLabelDilate3D.cxx
Added: vtkImageLabelDilate3D.h

### CODE REVIEW

**Comment by lassoan** [comment]
@jcfr If this gets merged then we don't need the "[ENH: Add background masking mode to vtkImageMedian3D](https://github.com/Slicer/VTK/commit/50d4bdd2cac3274d22f929d9a49ddf9dadf1ed7a)" commit from this branch: https://github.com/Slicer/VTK/commits/slicer-v9.2.20230607-1ff325c54

We could also squash the "BUG: use alpha to calculate RGBA lighting" commit with your regexp fix "[BUG: Fix generation of volume rendering shader](https://github.com/Slicer/VTK/commit/97965bba9e1d8f49482ffc61c464b11287cd19e2)" to make the commit history more clear.

Could we do this cleanup in the current branch (thereby invalidating some commits that were used by a few Preview Releases); or we should rather do this cleanup in a separate branch; or we should leave this branch as is and clean things up when we create a new branch?

**Comment by jcfr** [comment]
> or we should leave this branch as is and clean things up when we create a new branch?

Let's do that, I am creating a branch called `slicer-v9.2.20230607-1ff325c54-2` and I am also opening a merge request with the change @pieper added that way we will have commit all prefixed with `[MR-NNNN] `

**Comment by lassoan** [comment]
Sounds good. Has @pieper submitted a PR to upstream VTK? I don't see it in the [list of PRs under his name](https://gitlab.kitware.com/vtk/vtk/-/merge_requests?scope=all&state=all&author_username=pieper).

**Comment by jcfr** [comment]
Closing. Superseded by https://github.com/Slicer/Slicer/pull/7305

**Pull request closed without merging**
