### PR TITLE
Upgrade to Python 2.7.10

### PR DESCRIPTION
**Pull request by msmolens**
This PR incorporates feedback from and supersedes #331.

This change upgrades Slicer's Python from version 2.7.3 to version 2.7.10. The newer Python version fixes a number of build warnings seen when building Slicer with Python 2.7.3 in Visual Studio 2013, like:

    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xtgmath.h(190): warning C4273: '_hypot' : inconsistent dll linkage [C:\dev\SN\VTKv6-build\Wrapping\PythonCore\vtkWrappingPythonCore.vcxproj]
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\math.h(538) : see previous definition of '_hypot'

and:

    C:\dev\SN\python-2.7.3\include\pymath.h(22): warning C4273: 'round' : inconsistent dll linkage [C:\dev\SN\python-build\CMakeBuild\libpython\libpython-shared.vcxproj]
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\math.h(516) : see previous definition of 'round'

This change also updates the following external packages:

- python-cmake-buildsystem: to support building Python 2.7.10 on all platforms
- CTK/PythonQt: to fix crashes on exit in Python/PythonQt with Python >2.7.3

This change has been manually tested on:
- Windows (Visual Studio 2008, Visual Studio 2013)
- Ubuntu 14.04.3
- Mac OS X 10.6.8

### CODE REVIEW

**Comment by jcfr** [comment]
:+1:  Great news.

Looks good. Please integrate into the trunk.

**Comment by jcfr** [comment]
If not too late, 

1) in commit 07cc594 could you mention that it will fix tests like `py_ColorsScalarBarSelfTest`
See http://slicer.cdash.org/testDetails.php?test=6704371&build=625689

2) in 44a60d7898b5fb16 could you mention if you did a Debug or Release build, and mention which tests were failing (if any). I will expect at least `vtkMRMLSceneImportIDModelHierarchyConflictTest` to fail

**Comment by msmolens** [comment]
Commits integrated in:
[r24524](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24524)
[r24525](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24525)
[r24526](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24526)

**Comment by jcfr** [comment]
@msmolens Good news. Build on all platforms succeeded  :+1: 

That said, it seems there is still a small glitch. For example, here is the backtrace associated with `py_nomainwindow_DCMTKPrivateDictTest`.

python-finalization-issue

Could you have a look ?

**Comment by msmolens** [comment]
@jcfr after investigating, I have the following pull requests that will fix the crash when used with Slicer:
https://github.com/commontk/PythonQt/pull/31
https://github.com/commontk/CTK/pull/600

It's a bit ugly that I revert my earlier change to ctkAbstractPythonManager, but based on what I see in py_nomainwindow_DCMTKPrivateDictTest this is a better solution overall.

I'm running the full test suite overnight.

**Comment by jcfr** [comment]
>  have the following pull requests that will fix the crash

:8ball: 

> It's a bit ugly 

No worry :)   Great that you made progress and that my original patch from 2011 https://github.com/commontk/PythonQt/commit/e7860427ddb0da2ff269d46431217aa02ccd1a90 is useful after all

> I'm running the full test suite overnight.

Excellent :+1:

**Pull request closed without merging**
