### PR TITLE
COMP: Update SimpleITK to v2.1.0

### PR DESCRIPTION
**Pull request by jamesobutler**
This updates SimpleITK to a tagged release. Should be tested across the platforms to confirm none of these final updates from the pre-release version to the tagged release cause issues.

```
$ git shortlog --topo-order --no-merges 1062acf..v2.1.0
Bradley Lowekamp (25):
      Use https://simpleitk.org
      CircleCI fix typo in anchor name
      Wrap the ComposeScaleSkewVersor3DTransform
      Document ComposeScaleSkewVersorTransform in Sphinx overviews
      Add ComposeScaleSkewVersor3DTransform header to wrapping interface
      Add another baseline image for the SLICImageFilter "default" case
      Release tolerance for SLICImageFilter.default measurement
      Add alternative baseline for ImageRegistrationMethodDisplacement1
      Add Image GetBufferAsNativePointer and GetBufferAsBuffer methods
      Ignore constant Image::GetBufferAs.. methods
      Add testing for Java GetBufferAsBuffer interface
      Remove debugging code from ComposeScaleSkewVersor3DTransform test
      Add registration of ComposeScaleSkewVersor3DTransform
      Update SWIG to 4 require in CMake find_package
      Remove filename from sha512 has file
      Add example demonstration Java Image buffer interface
      Update HistogramMatchingImageFilter to use name referenceImage input
      Remove explicit instantiating of Image of deque of LabelObjectLine
      Add StopRegistration method to DemonsRegistrationFilter
      Adding testing for StopRegistration
      Add StopRegistration method to other Demons based registration fitlers
      Update to C++14 for ITK master build
      Add ImageRegistrationMethod::StopRegistration method
      Add Testing for ImageRegistrationMethod::StopRegistration
      Fix comparison between signed and unsigned integer warning

Dave Chen (7):
      Sphinx add_stylesheet -> add_css_file
      Added a Windows build page
      removed { in Cpp examples
      include all langs in the docs
      Changed type from UInt32 to Int32
      initial checkin of MacARM scripts
      don't overwrite SIMPLEITK_GIT_TAG if set in env

Dave Mackey (2):
      Spelling correction
      Minor grammar change to gettingStarted

Richard Beare (1):
      BUG: Calls to nonexistent methods weren't handled gracefully

Ziv Yaniv (6):
      DOC: Registration initialization and center of rotation docs.
      DOC: Adding details on naming conventions and OO, procedural interfaces.
      STYLE: Renamed variables to meaningful names.
      Adding example illustrating usage of optimizer weights.
      DOC: Improve documentation for registration sampling strategies.
      DOC: Additional information on registration sampling strategies.
```

### CODE REVIEW

**Comment by lassoan** [comment]
Upgrade to Swig4 and requiring C++14 might cause some trouble, but otherwise the changelog looks quite harmless.

Do we require C++14 already due to current ITK version that we use?

**Comment by jamesobutler** [comment]
`Update to C++14 for ITK master build` -> https://github.com/SimpleITK/SimpleITK/commit/f61023d70b7a6648707f0b2dd26af4f2f1c07fb6 appears to have just been for their testing and not necessarily a requirement for SimpleITK. The ITK requirement to go to C++14 happened after the ITK 5.2 release and we are still using the official v5.2.0 tag. Since SimpleITK v2.1.0 is also targeting ITK 5.2.0, they didn't necessarily need to switch to C++14 testing, but only if they were building against latest ITK.

https://github.com/Slicer/Slicer/blob/9920f81ac9524e5e56eb9f43a397e6a7ae29be3f/SuperBuild/External_ITK.cmake#L37-L39

I know for the Slicer superbuild we are using SWIG 4 if not defining a local version. We updated to SWIG 4 because SimpleITK v2.0rc3 needed it.
https://github.com/Slicer/Slicer/blob/9920f81ac9524e5e56eb9f43a397e6a7ae29be3f/SuperBuild/External_Swig.cmake#L13-L17

**Review by lassoan — APPROVED** [review]
Thanks for the responses, based on them it seems safe to try this upgrade.

**Comment by lassoan** [comment]
There was no objection from anyone, so I'll merge this later in this afternoon unless I hear from anyone.

**Pull request merged**
