### PR TITLE
BUG: Fix markups cannot be placed after loading a scene

### LINKED ISSUE #4748: Markups cannot be placed after a scene is loaded
When loading a scene markup points cannot be placed in viewers.

## Steps to reproduce

- Load this scene: https://www.dropbox.com/s/pzoetx9i6t6a8se/2020-03-18-Scene.mrb?dl=0
- Click on place button on toolbar (markups fiducial mode is selected by default)
- Move the mouse over a viewer => ERROR: markup preview point does not appear, clicking has no effect.

## Expected behavior

After the place button is activated, preview points should show up and clicking should place a point.

## Environment
- Slicer version: Slicer-4.11.0-2020-03-15 (revision 5266433)
- Operating system: Windows

### PR DESCRIPTION
**Pull request by lassoan**
After loading certain scenes, users could not place markups when clicking on the toolbar because active place node class in Selection node was set to "NULL" and this was not detected as an empty (default) class.

Fixed by changing all classes that wrote nullptr as "NULL" (vtkMRMLSelectionNode, vtkMRMLSegmentationDisplayNode, vtkMRMLSubjectHierarchyLegacyNode, vtkSegment, and qMRMLPlotSeriesPropertiesWidget) to write it as "" (empty string). This makes application code simpler (empty string can be recognized by checking for nullptr or "", no need to check also for the special "NULL" value, which is actually missed at most places).

Fixes #4748.

### CODE REVIEW

**Comment by lassoan** [comment]
If there is no comment, I'll merge this tomorrow.

**Comment by jcfr** [comment]
Should any the following files be updated as well:

```
Modules/Loadable/VolumeRendering/MRMLDM/vtkMRMLVolumeRenderingDisplayableManager.cxx
1071:        << (currentDisplayNode->GetDisplayableNode() ? currentDisplayNode->GetDisplayableNode()->GetName() : "NULL"));

Modules/Loadable/Annotations/MRMLDM/vtkMRMLAnnotationDisplayableManager.cxx
1660:    vtkDebugMacro("associatedNodeID set to " << (associatedNodeID ? associatedNodeID : "NULL"));

Modules/Loadable/Annotations/Logic/vtkSlicerAnnotationModuleLogic.cxx
100:  os << indent << "MeasurementFormat = " << (this->m_MeasurementFormat ? this->m_MeasurementFormat : "NULL") << std::endl;
101:  os << indent << "CoordinateFormat = " << (this->m_CoordinateFormat ? this->m_CoordinateFormat : "NULL") << std::endl;
102:  os << indent << "ActiveHierarchyNodeID = " << (this->ActiveHierarchyNodeID ? this->ActiveHierarchyNodeID : "NULL") << std::endl;
105:    os << indent << "LastAddedAnnotationNode: " << (this->m_LastAddedAnnotationNode->GetID() ? this->m_LastAddedAnnotationNode->GetID() : "NULL ID") << std::endl;

Modules/Loadable/Terminologies/Widgets/qSlicerTerminologyNavigatorWidget.cxx
764:    qCritical() << Q_FUNC_INFO << ": Failed to find category with name " << (categoryObject->GetCodeMeaning()?categoryObject->GetCodeMeaning():"NULL");
777:    qCritical() << Q_FUNC_INFO << ": Failed to find type with name " << (typeObject->GetCodeMeaning()?typeObject->GetCodeMeaning():"NULL");
787:      qCritical() << Q_FUNC_INFO << ": Failed to find type modifier with name " << (typeModifierObject->GetCodeMeaning()?typeModifierObject->GetCodeMeaning():"NULL");

Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologyType.cxx
80:  os << indent << "SlicerLabel:   " << (this->SlicerLabel?this->SlicerLabel:"NULL") << "\n";
81:  os << indent << "SNOMEDCTConceptID:   " << (this->SNOMEDCTConceptID?this->SNOMEDCTConceptID:"NULL") << "\n";
82:  os << indent << "UMLSConceptUID:   " << (this->UMLSConceptUID?this->UMLSConceptUID:"NULL") << "\n";
83:  os << indent << "Cid:   " << (this->Cid?this->Cid:"NULL") << "\n";
84:  os << indent << "ContextGroupName:   " << (this->ContextGroupName?this->ContextGroupName:"NULL") << "\n";

Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologyEntry.cxx
81:  os << indent << "TerminologyContextName:   " << (this->TerminologyContextName?this->TerminologyContextName:"NULL") << "\n";
90:    os << indent.GetNextIndent() << "NULL\n";
99:    os << indent.GetNextIndent() << "NULL\n";
108:    os << indent.GetNextIndent() << "NULL\n";
111:  os << indent << "AnatomicContextName:   " << (this->AnatomicContextName?this->AnatomicContextName:"NULL") << "\n";
119:    os << indent.GetNextIndent() << "NULL\n";
128:    os << indent.GetNextIndent() << "NULL\n";

Modules/Loadable/Terminologies/Logic/vtkSlicerTerminologyCategory.cxx
65:  os << indent << "SNOMEDCTConceptID:   " << (this->SNOMEDCTConceptID?this->SNOMEDCTConceptID:"NULL") << "\n";
66:  os << indent << "UMLSConceptUID:   " << (this->UMLSConceptUID?this->UMLSConceptUID:"NULL") << "\n";
67:  os << indent << "Cid:   " << (this->Cid?this->Cid:"NULL") << "\n";
68:  os << indent << "ContextGroupName:   " << (this->ContextGroupName?this->ContextGroupName:"NULL") << "\n";

Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginHandler.cxx
305:                                    dataNode?dataNode->GetName():"NULL").arg(dataNode?dataNode->GetNodeTagName():"None");

Modules/Loadable/Segmentations/Widgets/qMRMLSegmentEditorWidget.cxx
123:static const char NULL_EFFECT_NAME[] = "NULL";

Modules/Loadable/Segmentations/Logic/vtkSlicerSegmentationsModuleLogic.cxx
1477:      << (segmentationNode->GetName() ? segmentationNode->GetName() : "NULL") << " is not binary labelmap");

Modules/Scripted/DICOMLib/Logic/vtkSlicerDICOMLoadable.cxx
65:  os << indent << "Name:   " << (this->Name?this->Name:"NULL") << "\n";
66:  os << indent << "Tooltip:   " << (this->Tooltip?this->Tooltip:"NULL") << "\n";
67:  os << indent << "Warning:   " << (this->Warning?this->Warning:"NULL") << "\n";
68:  os << indent << "Files:   " << (this->Files?"":"NULL") << "\n";
78:  os << indent << "ReferencedInstanceUIDs:   " << (this->ReferencedInstanceUIDs?"":"NULL") << "\n";

Modules/Scripted/DICOMLib/Logic/vtkSlicerDICOMExportable.cxx
58:  os << indent << "Name:   " << (this->Name?this->Name:"NULL") << "\n";
59:  os << indent << "Tooltip:   " << (this->Tooltip?this->Tooltip:"NULL") << "\n";
61:  os << indent << "PluginClass:   " << (this->PluginClass?this->PluginClass:"NULL") << "\n";
62:  os << indent << "Directory:   " << (this->Directory?this->Directory:"NULL") << "\n";

Libs/vtkSegmentationCore/vtkSegment.cxx
93:  os << indent << "Name: " << (this->Name ? this->Name : "NULL") << "\n";
145:  of << "Name=\"" << (this->Name ? this->Name : "NULL") << "\"";

Libs/vtkSegmentationCore/vtkSegmentationConverter.cxx
69:    os << indent << "Rule:   " << (rule->GetSourceRepresentationName() ? rule->GetSourceRepresentationName() : "NULL") << " -> " << (rule->GetTargetRepresentationName() ? rule->GetTargetRepresentationName() : "NULL") << "\n";

Libs/MRML/Core/vtkMRMLSubjectHierarchyNode.cxx
2872:    vtkErrorMacro("GetParentDataNode: Given data node (" << (dataNode ? dataNode->GetName() : "NULL")

Libs/MRML/Core/vtkMRMLDisplayableHierarchyNode.cxx
151:      os << indent.GetNextIndent() << i << "th child id = " << (child->GetID() ? child->GetID() : "NULL") << "\n";

Libs/MRML/Core/vtkMRMLCameraNode.cxx
474:        vtkWarningMacro("SetActiveTag: " << (this->GetID() ? this->GetID() : "NULL ID") << " found another node " << node->GetID() << " with the tag " << _arg);
482:                    << ", input arg = " << (_arg == nullptr ? "NULL" : _arg));

Libs/MRML/Core/Testing/vtkMRMLSceneTest1.cxx
403:                (changedIDFromPrivateScene?changedIDFromPrivateScene:"NULL") << "\n"
405:                (nodeAddedFromPrivateSceneID?nodeAddedFromPrivateSceneID:"NULL")
432:                (importedNodeID?importedNodeID:"NULL") << "\n"
434:                (changedIDFromImportedScene?changedIDFromImportedScene:"NULL")

Libs/MRML/Core/Testing/vtkMRMLDisplayableHierarchyNodeTest1.cxx
83:                "NULL" : node1->GetDisplayNodeID())
101:            << (pnode1 == nullptr ? "NULL" : "not null")
156:            << (hnode3 == nullptr ? "NULL" : hnode3->GetID())
161:            << (hnode3 == nullptr ? "NULL" : hnode3->GetID())

Libs/MRML/Core/Testing/vtkMRMLDisplayableHierarchyNodeTest3.cxx
33:      std::cout << "\t" << i << " name = " << (kids[i]->GetName() != nullptr ? kids[i]->GetName() : "NULL") << std::endl;

Libs/MRML/Core/vtkMRMLSelectionNode.cxx
148:  of << " activeVolumeID=\"" << (this->ActiveVolumeID ? this->ActiveVolumeID : "NULL") << "\"";
149:  of << " secondaryVolumeID=\"" << (this->SecondaryVolumeID ? this->SecondaryVolumeID : "NULL") << "\"";
150:  of << " activeLabelVolumeID=\"" << (this->ActiveLabelVolumeID ? this->ActiveLabelVolumeID : "NULL") << "\"";
151:  of << " activeFiducialListID=\"" << (this->ActiveFiducialListID ? this->ActiveFiducialListID : "NULL") << "\"";
152:  of << " activePlaceNodeID=\"" << (this->ActivePlaceNodeID ? this->ActivePlaceNodeID : "NULL") << "\"";
153:  of << " activePlaceNodeClassName=\"" << (this->ActivePlaceNodeClassName ? this->ActivePlaceNodeClassName : "NULL") << "\"";
154:  of << " activeROIListID=\"" << (this->ActiveROIListID ? this->ActiveROIListID : "NULL") << "\"";
155:  of << " activeCameraID=\"" << (this->ActiveCameraID ? this->ActiveCameraID : "NULL") << "\"";
156:  of << " activeTableID=\"" << (this->ActiveTableID ? this->ActiveTableID : "NULL") << "\"";
157:  of << " activeViewID=\"" << (this->ActiveViewID ? this->ActiveViewID : "NULL") << "\"";
158:  of << " activeLayoutID=\"" << (this->ActiveLayoutID ? this->ActiveLayoutID : "NULL") << "\"";
159:  of << " activePlotChartID=\"" << (this->ActivePlotChartID ? this->ActivePlotChartID : "NULL") << "\"";

Libs/MRML/Core/vtkTagTable.cxx
77:      value = "NULL";
109:      value = "NULL";
173:      value = "NULL";

Libs/MRML/Core/vtkMRMLScene.cxx
2155:  os << indent << "Version = " << (this->GetVersion() ? this->GetVersion() : "NULL") << "\n";
2156:  os << indent << "LastLoadedVersion = " << (this->GetLastLoadedVersion() ? this->GetLastLoadedVersion() : "NULL") << "\n";
2184:      os << indent.GetNextIndent().GetNextIndent() << "Default write extension = " << (exts != nullptr ? exts : "NULL") << endl;

Libs/MRML/Core/vtkUserTagTable.cxx
62:      value = "NULL";
97:      ss << "NULL";

Libs/MRML/Core/vtkMRMLSegmentationDisplayNode.cxx
90:    << (this->PreferredDisplayRepresentationName2D ? this->PreferredDisplayRepresentationName2D : "NULL") << "\"";
92:    << (this->PreferredDisplayRepresentationName3D ? this->PreferredDisplayRepresentationName3D : "NULL") << "\"";
257:  os << indent << " PreferredDisplayRepresentationName2D:   " << (this->PreferredDisplayRepresentationName2D ? this->PreferredDisplayRepresentationName2D : "NULL") << "\n";
258:  os << indent << " PreferredDisplayRepresentationName3D:   " << (this->PreferredDisplayRepresentationName3D ? this->PreferredDisplayRepresentationName3D : "NULL") << "\n";

Libs/MRML/Core/vtkMRMLStorageNode.cxx
370:    os << indent << "FileListMember: " << (this->GetNthFileName(i) == nullptr ? "NULL" : this->GetNthFileName(i)) << "\n";
889:  vtkDebugMacro("SetDataDirectory: from FileName " << (this->GetFileName() ? this->GetFileName() : "NULL") << ", got filePath = " << filePath.c_str());

Libs/MRML/Core/vtkMRMLSubjectHierarchyLegacyNode.cxx
72:    << (this->Level ? this->Level : "NULL" ) << "\n";
75:    << (this->OwnerPluginName ? this->OwnerPluginName : "NULL" ) << "\n";
153:  of << " Level=\"" << (this->Level ? this->Level : "NULL" ) << "\"";
156:    << (this->OwnerPluginName ? this->OwnerPluginName : "NULL" ) << "\"";

Libs/MRML/Core/vtkMRMLCoreTestingUtilities.cxx
365:  std::cout << "Filename 0 = " << (f0 == nullptr ? "NULL" : f0) << std::endl;

Libs/MRML/DisplayableManager/vtkMRMLCameraDisplayableManager.cxx
387:            vtkDebugMacro("UpdateCamera: found a camera pointing to me with id = " << (node->GetID() ? node->GetID() : "NULL"));
```

**Comment by lassoan** [comment]
I've checked all the other occurrences and they only print null pointers (in printself method, log messages, or tests).

**Comment by jcfr** [comment]
We may have to upload additional mrb files to https://github.com/Slicer/SlicerTestingData/releases

**Comment by lassoan** [comment]
@jcfr Thanks for the review.

**Pull request merged**
