### PR TITLE
Add Fedora information

### PR DESCRIPTION
**Pull request by numas**
Included Fedora version

### CODE REVIEW

**Comment by numas** [comment]
Feel free to close/remove this PR

**Comment by pieper** [comment]
Is it superseded by another one?  Is there a reason you don't want to close it yourself?

**Comment by jamesobutler** [comment]
@pieper This is a PR to update documentation for the https://github.com/Slicer/Slicer/tree/v4.11 branch to update documentation for the stable release (4.11.20210226)

**Comment by pieper** [comment]
> @pieper This is a PR to update documentation for the https://github.com/Slicer/Slicer/tree/v4.11 branch to update documentation for the stable release (4.11.20210226)

Yes, so why close it instead of just merging it?

**Comment by jamesobutler** [comment]
@numas might be frustrated that the PR was posted 20 days ago and nothing has proceeded to merge this. I have no Linux usage  experience to reflect on this documentation.

**Comment by pieper** [comment]
I don't know anything about Fedora so I can't really comment either.

@numas can you comment on whether the PR should be closed or merged?  I see no downside of it but with no active Fedora users on the core team we'll just follow your lead here.

**Comment by lassoan** [comment]
I agree, this information should be useful for those who want to use Slicer-4.11 on Fedora. I'll fix the commit message and merge it.

**Comment by lassoan** [comment]
Thank you @numas the pull request is now merged.
Sorry it took a long time, we are just busy finalizing the new Slicer5 release and as you could see we are battling with many pull requests.

**Comment by numas** [comment]
@pieper I'm still not super used to GitHub, so didn't know I could close it myself! I just wondered if you didn't care about it since the latest docs was updated with nearly identical text, I didn't want to clutter the PR list, since you are busy as it is.

@lassoan Thanks and thank you all for what you do. Maybe I can contribute again in the future, even if it isn't important such as real code.

**Comment by pieper** [comment]
Thanks for the contribution 👍

**Pull request merged**
