### PR TITLE
STYLE: Update python scripts to not import from __main__

### PR DESCRIPTION
**Pull request by jcfr**
This commit simplifies the scripts removing extra `from __main__`
statements and improve the integration with Python IDE ensuring python
package like `slicer` can simply be imported.

The `from __main__` statement most likely became obsolete since
r24155 (ENH: Fixes #3549. Import scripted module as python module).

Remarks:

A global replace of `from __main__ import` into `import` as been done
except in:
 * EditOptions: `from __main__ getNodes` changed into `from slicer.util import getNodes`
 * slicer/module[dm|logic|mrml|widget]/__init__.py where it makes sense to keep it.

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @Slicer/slicer-core-team

**Comment by jcfr** [comment]
I tested on Linux by:
* ensuring Slicer loaded all modules
* using the editor module
* importing DICOM
* running all python tests

I also generated package and confirmed Slicer was loading all modules, editor and DICOM import were working.

**Comment by jcfr** [comment]
```
$ ctest -R py_nomainwindow_
[...]
The following tests passed:
	py_nomainwindow_qSlicerDataProbeModuleGenericTest
	py_nomainwindow_qSlicerEditorModuleGenericTest
	py_nomainwindow_qSlicerLabelStatisticsModuleGenericTest
	py_nomainwindow_qSlicerPerformanceTestsModuleGenericTest
	py_nomainwindow_qSlicerSampleDataModuleGenericTest
	py_nomainwindow_qSlicerSelfTestsModuleGenericTest
	py_nomainwindow_qSlicerSurfaceToolboxModuleGenericTest
	py_nomainwindow_qSlicerVectorToScalarVolumeModuleGenericTest
	py_nomainwindow_qSlicerExtensionWizardModuleGenericTest
	py_nomainwindow_qSlicerEndoscopyModuleGenericTest
	py_nomainwindow_qSlicerDICOMModuleGenericTest
	py_nomainwindow_qSlicerDICOM2FullBrainTractographyModuleGenericTest
	py_nomainwindow_qSlicerFiberBundleToLabelMapModuleGenericTest
	py_nomainwindow_SlicerPythonCodeTest1
	py_nomainwindow_SlicerPythonCodeTest2
	py_nomainwindow_SlicerPythonCodeTest3
	py_nomainwindow_SlicerPythonCodeTest4
	py_nomainwindow_SlicerPythonCodeTest5
	py_nomainwindow_SlicerTestingExitSuccessTest
	py_nomainwindow_SlicerTestingExitFailureTest
	py_nomainwindow_SlicerUnitTestTest
	py_nomainwindow_SlicerUnitTestWithErrorsTest
	py_nomainwindow_ScriptedModuleDiscoveryTest
	py_nomainwindow_SlicerSceneObserverTest
	py_nomainwindow_MRMLCreateNodeByClassWithoutSetReferenceCount
	py_nomainwindow_MRMLCreateNodeByClassWithSetReferenceCountMinusOne
	py_nomainwindow_MRMLCreateNodeByClassWithSetReferenceCountToOne
	py_nomainwindow_test_saferef
	py_nomainwindow_test_slicer_util_save
	py_nomainwindow_test_slicer_mgh
	py_nomainwindow_test_slicer_util_VTKObservationMixin
	py_nomainwindow_DCMTKPrivateDictTest
	py_nomainwindow_qSlicerMultiVolumeImporterModuleGenericTest
	py_nomainwindow_qSlicerLandmarkRegistrationModuleGenericTest

100% tests passed, 0 tests failed out of 34
```

**Comment by jcfr** [comment]
```
$ ctest -R py_[^n] 
Test project /home/jcfr/Projects/Slicer-Debug/Slicer-build
      Start   6: py_vtkITKArchetypeDiffusionTensorReaderFile
 1/53 Test   #6: py_vtkITKArchetypeDiffusionTensorReaderFile .........   Passed   50.11 sec
      Start   7: py_vtkITKArchetypeScalarReaderFile
 2/53 Test   #7: py_vtkITKArchetypeScalarReaderFile ..................   Passed   29.62 sec
      Start 279: py_ColorsScalarBarSelfTest
 3/53 Test #279: py_ColorsScalarBarSelfTest ..........................   Passed   89.71 sec
      Start 314: py_AnnotationsTestingAddManyFiducials
 4/53 Test #314: py_AnnotationsTestingAddManyFiducials ...............   Passed    8.13 sec
      Start 315: py_AnnotationsTestingAddManyRulers
 5/53 Test #315: py_AnnotationsTestingAddManyRulers ..................   Passed    9.16 sec
      Start 316: py_AnnotationsTestingAddManyROIs
 6/53 Test #316: py_AnnotationsTestingAddManyROIs ....................   Passed    8.54 sec
      Start 317: py_RemoveAnnotationsIDFromSelectionNode
 7/53 Test #317: py_RemoveAnnotationsIDFromSelectionNode .............   Passed    7.10 sec
      Start 318: py_LoadAnnotationRulerScene
 8/53 Test #318: py_LoadAnnotationRulerScene .........................   Passed    8.12 sec
      Start 319: py_AnnotationsTestingFiducialWithSceneViewRestore
 9/53 Test #319: py_AnnotationsTestingFiducialWithSceneViewRestore ...   Passed   11.38 sec
      Start 341: py_AddManyMarkupsFiducialTest
10/53 Test #341: py_AddManyMarkupsFiducialTest .......................   Passed   46.98 sec
      Start 342: py_MarkupsSceneViewRestoreTestSimple
11/53 Test #342: py_MarkupsSceneViewRestoreTestSimple ................   Passed    7.07 sec
      Start 343: py_MarkupsSceneViewRestoreTestManyLists
12/53 Test #343: py_MarkupsSceneViewRestoreTestManyLists .............   Passed    7.35 sec
      Start 344: py_NeurosurgicalPlanningTutorialMarkupsSelfTest
13/53 Test #344: py_NeurosurgicalPlanningTutorialMarkupsSelfTest .....   Passed  282.79 sec
      Start 345: py_MarkupsInCompareViewersSelfTest
14/53 Test #345: py_MarkupsInCompareViewersSelfTest ..................   Passed   99.15 sec
      Start 346: py_MarkupsInViewsSelfTest
15/53 Test #346: py_MarkupsInViewsSelfTest ...........................   Passed   19.87 sec
      Start 358: py_mainwindow_RestoreSceneViewWithoutCamera
16/53 Test #358: py_mainwindow_RestoreSceneViewWithoutCamera .........   Passed    6.83 sec
      Start 359: py_AddStorableDataAfterSceneViewTest
17/53 Test #359: py_AddStorableDataAfterSceneViewTest ................   Passed   19.28 sec
      Start 375: py_LoadVolumeDisplaybleSceneModelClose
18/53 Test #375: py_LoadVolumeDisplaybleSceneModelClose ..............   Passed   45.97 sec
      Start 376: py_VolumesLogicCompareVolumeGeometry
19/53 Test #376: py_VolumesLogicCompareVolumeGeometry ................   Passed    8.82 sec
      Start 389: py_VolumeRenderingSceneClose
20/53 Test #389: py_VolumeRenderingSceneClose ........................   Passed   95.57 sec
      Start 393: py_CropVolumeSelfTest
21/53 Test #393: py_CropVolumeSelfTest ...............................   Passed   28.62 sec
      Start 403: py_ThresholdThreadingTest
22/53 Test #403: py_ThresholdThreadingTest ...........................   Passed   70.84 sec
      Start 404: py_StandaloneEditorWidgetTest
23/53 Test #404: py_StandaloneEditorWidgetTest .......................   Passed   22.73 sec
      Start 406: py_LabelStatistics
24/53 Test #406: py_LabelStatistics ..................................   Passed   55.70 sec
      Start 515: py_SlicerTestingExitSuccessTest
25/53 Test #515: py_SlicerTestingExitSuccessTest .....................   Passed   30.86 sec
      Start 516: py_SlicerTestingExitFailureTest
26/53 Test #516: py_SlicerTestingExitFailureTest .....................   Passed   30.30 sec
      Start 542: py_mainwindow_MRMLSceneImportAndExport
27/53 Test #542: py_mainwindow_MRMLSceneImportAndExport ..............   Passed   25.06 sec
      Start 549: py_AtlasTests
28/53 Test #549: py_AtlasTests .......................................   Passed  929.83 sec
      Start 550: py_AbdominalAtlasTest
29/53 Test #550: py_AbdominalAtlasTest ...............................   Passed   72.01 sec
      Start 551: py_DTINotReproducibleIssue3977
30/53 Test #551: py_DTINotReproducibleIssue3977 ......................   Passed  165.48 sec
      Start 552: py_KneeAtlasTest
31/53 Test #552: py_KneeAtlasTest ....................................   Passed   90.66 sec
      Start 553: py_fiber_visibility_crash2438
32/53 Test #553: py_fiber_visibility_crash2438 .......................   Passed   33.23 sec
      Start 554: py_test_tractography_display
33/53 Test #554: py_test_tractography_display ........................   Passed   43.99 sec
      Start 555: py_sceneImport2428
34/53 Test #555: py_sceneImport2428 ..................................   Passed   41.59 sec
      Start 556: py_SlicerMRBTest
35/53 Test #556: py_SlicerMRBTest ....................................   Passed  136.35 sec
      Start 557: py_SlicerMRBMultipleSaveRestoreLoopTest
36/53 Test #557: py_SlicerMRBMultipleSaveRestoreLoopTest .............   Passed  101.77 sec
      Start 558: py_SlicerMRBMultipleSaveRestoreTest
37/53 Test #558: py_SlicerMRBMultipleSaveRestoreTest .................   Passed   73.15 sec
      Start 559: py_SlicerMRBSaveRestoreCheckPathsTest
38/53 Test #559: py_SlicerMRBSaveRestoreCheckPathsTest ...............   Passed   74.86 sec
      Start 560: py_Slicer4Minute
39/53 Test #560: py_Slicer4Minute ....................................   Passed   55.05 sec
      Start 561: py_Charting
40/53 Test #561: py_Charting .........................................   Passed   30.32 sec
      Start 562: py_SliceLinkLogic
41/53 Test #562: py_SliceLinkLogic ...................................   Passed   35.94 sec
      Start 563: py_ScenePerformance
42/53 Test #563: py_ScenePerformance .................................   Passed  153.72 sec
      Start 564: py_RSNAVisTutorial
43/53 Test #564: py_RSNAVisTutorial ..................................   Passed  556.01 sec
      Start 565: py_RSNAQuantTutorial
44/53 Test #565: py_RSNAQuantTutorial ................................   Passed  304.95 sec
      Start 566: py_slicerCloseCrashBug2590
45/53 Test #566: py_slicerCloseCrashBug2590 ..........................   Passed   40.70 sec
      Start 567: py_ViewControllersSliceInterpolationBug1926
46/53 Test #567: py_ViewControllersSliceInterpolationBug1926 .........   Passed   32.22 sec
      Start 568: py_RSNA2012ProstateDemo
47/53 Test #568: py_RSNA2012ProstateDemo .............................   Passed  268.18 sec
      Start 569: py_JRC2013Vis
48/53 Test #569: py_JRC2013Vis .......................................   Passed  433.75 sec
      Start 570: py_FiducialLayoutSwitchBug1914
49/53 Test #570: py_FiducialLayoutSwitchBug1914 ......................   Passed   30.63 sec
      Start 571: py_SubjectHierarchyGenericSelfTest
50/53 Test #571: py_SubjectHierarchyGenericSelfTest ..................   Passed   35.88 sec
      Start 572: py_SubjectHierarchyCorePluginsSelfTest
51/53 Test #572: py_SubjectHierarchyCorePluginsSelfTest ..............   Passed   48.05 sec
      Start 609: py_CompareVolumes
52/53 Test #609: py_CompareVolumes ...................................   Passed  113.97 sec
      Start 611: py_LandmarkRegistration
53/53 Test #611: py_LandmarkRegistration .............................   Passed  412.75 sec

100% tests passed, 0 tests failed out of 53

Label Time Summary:
SceneViews    =  26.11 sec

Total Test time (real) = 5440.86 sec

```

**Comment by pieper** [comment]
In the past this behavior varied a lot in debug vs release builds so we
should keep an eye on how this change behaves.

Thanks for the fix!

**Comment by jcfr** [comment]
Integrated in [r24622](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24622)

**Pull request closed without merging**
