### PR TITLE
COMP: Fix Slicer extension VTK wrapping ensuring availability of hierarchy files

### PR DESCRIPTION
**Pull request by jcfr**
This commit updates the configuration of both Slicer application and Slicer
extension config files so that paths to dependent hierarchy files are
available.

See https://issues.slicer.org/view.php?id=4462

### CODE REVIEW

**Comment by jcfr** [comment]
Closing. Integrated in [r26649](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26649)

**Comment by jcfr** [comment]
@Punzo This should also address wrapping issues for SlicerAstro build against VTK8-9 and Qt5

**Comment by Punzo** [comment]
Great! I'll test right now.

**Comment by Punzo** [comment]
It works for MRML classes, thanks! but now the wrapping of MRMLDM classes fails, I reported the error in the issue tracker https://issues.slicer.org/view.php?id=4462

**Pull request closed without merging**
