### PR TITLE
 add lang+region qm file support and simplified/transitional Chinese language in Slicer_LANGUAGES

### PR DESCRIPTION
**Pull request by u8621011**
we remove the qm file filter resizer because Chinese Language have area differences.

### CODE REVIEW

**Comment by pieper** [comment]
Seems reasonable to me

**Comment by jcfr** [comment]
Issue related with filter to discover file with `.qm` extension is fixed in [r26944](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26944)

**Comment by jcfr** [comment]
Changes explicitly adding chinese translations and enabling the option will be done in a different commit.

**Comment by jcfr** [comment]
Closing. This is superseded by https://github.com/Slicer/Slicer/pull/898

**Pull request closed without merging**
