### PR TITLE
Several small fixes

### PR DESCRIPTION
**Pull request by lassoan**
This pull request contains 4 unrelated fixes, lumped together to reduce overhead in creating and reviewing the pull request.

### CODE REVIEW

**Review by pieper — APPROVED** [review]
LGTM.

**Comment by lassoan** [comment]
This .vtk file format incompatibility is really ugly (caused us some embarrassment today when a SlicerHeart tool that has been used successfully clinically suddenly created a file that did not work with their EP guidance system).

The change of file format must be reverted in vtk master, too (at least, by default the old, compatible format should be use), before the reputation of this file format get tainted. I've added a comment on [VTK forum](https://discourse.vtk.org/t/legacy-polydata-file-compatibility/5354/4).

**Comment by pieper** [comment]
Yes, I was following the story on the SlicerHeart notifications.  This kind of backwards compatibility breakage is very bad practice and I agree it needs to be reverted in VTK.

**Comment by jcfr** [comment]
> I agree it needs to be reverted in VTK.

We are currently discussing this, I will follow up when I have more details.

**Pull request merged**
