### PR TITLE
ENH: switch to teem-1.10.0 release branch

### PR DESCRIPTION
**Pull request by ayarmarkovich**
Please see if new teem release version works for packaging of slicer

### CODE REVIEW

**Comment by jcfr** [comment]
@pieper Let me know if you would like me to look at this now or if you would prefer me to wait you are done testing & patching alex topic.

**Comment by pieper** [comment]
I'm packaging a mac release build of this now and will post it for testing.

**Comment by jcfr** [comment]
:+1:  

@hjmjohnson Is also working on addressing CMake warning / error happening with teem.

**Comment by jcfr** [comment]
Closing this Pull request. External project will be updated using github.com/Slicer/teem

**Pull request closed without merging**
