### PR TITLE
ENH: Update EMSegment to include compilation fixes for VTK 7.1

### PR DESCRIPTION
**Pull request by msmolens**
This commit updates EMSegment to include compilation fixes for the current VTK
master (upcoming VTK 7.1).

### CODE REVIEW

**Comment by jcfr** [comment]
Nice 

Please go head and integrate. 

The CI will not turn green because `SuperBuild.cmake` has been updated.

Next step will be to update https://github.com/thewtex/SlicerDocker/commit/df31cc0f1688e04eb35d800109e0e7fcdf02609c

Then:

```
cd slicer-build-base
./build.sh

cd slicer-build-deps
./build.sh

docker push slicer/slicer-build-deps
```

I am granting you access.

**Comment by jcfr** [comment]
If you don't have docker installer locally .. let me know and I will proceed to the update.

**Comment by msmolens** [comment]
@jcfr The builds succeeded but I'm unable to push the image:

    $ docker login
    Username (msmolens): 
    Password: 
    WARNING: login credentials saved in /home/msmolens/.docker/config.json
    Login Succeeded

    $ docker push slicer/slicer-build-deps
    The push refers to a repository [docker.io/slicer/slicer-build-deps]
    ac9f4e0eb151: Preparing 
    c637b21b1beb: Preparing 
    70194128caab: Preparing 
    488277f5d19a: Preparing 
    f3709f53eff6: Preparing 
    cfe97695ab24: Waiting 
    a83a991d4883: Waiting 
    61d4e4e2d27c: Waiting 
    5f70bf18a086: Waiting 
    46cedcc01e1f: Waiting 
    85a9072761cb: Waiting 
    19b04b5c259e: Waiting 
    59b23fc5a308: Waiting 
    28fff06e0d11: Waiting 
    bad4e40ad2f4: Waiting 
    b3467aac0e99: Waiting 
    73739fb20d9e: Waiting 
    unauthorized: authentication required

**Comment by jcfr** [comment]
Great. What is your dockerhub userid ?

**Comment by jcfr** [comment]
I guess it is `msmolens` :p

**Comment by jcfr** [comment]
@msmolens All set. You have now need added to the [slicer](https://hub.docker.com/u/slicer/dashboard/teams/?team=owners) team

**Comment by msmolens** [comment]
@jcfr Thanks! I pushed the image:

    latest: digest: sha256:d1e0db1073191fe1a6bb92f2c6eee2d5e7f880ad407ca30457bad4e64b8f082d size: 6352

**Comment by msmolens** [comment]
Integrated in [r25188](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25188)

**Pull request closed without merging**
