### PR TITLE
Fix source typo 

### PR DESCRIPTION
**Pull request by luzpaz**
Typo in `typeDisplayNameCollison` should be `typeDisplayNameCollision`

### CODE REVIEW

**Review by jamesobutler — COMMENTED** [review]
@luzpaz You mentioned in https://github.com/Slicer/Slicer/pull/6483#issuecomment-1198822243 that you are using a different dictionary to discover these typos. Based on your success can you provide information about the dictionary you are using?

**Comment by luzpaz** [comment]
@jamesobutler I will x-ref https://github.com/orbitcowboy/codespell_dictionary and I'll also use code editor search functions with regex to search the codebase. So it's a mixture of approaches.

**Comment by jcfr** [comment]
> I also use the HEAD version of codespell

We are not doing so thanks to https://github.com/Slicer/Slicer/pull/6483/commits

See also:
* https://github.com/Slicer/actions-codespell#readme
* https://github.com/Slicer/actions-codespell/commit/a2c8557d8abf83ee46629088c3e110ca04bf16dd


> updated dictionary

What do you think of contributing the following entries:

```
abot->about
afther->after
apperarance->appearance
cleares->clears
creteria->criteria
inactivate->deactivate
individuall->individual
inpection->inspection
requrested->requested
tabl->table
wen->when
```
Source: https://github.com/Slicer/Slicer/pull/6483/commits/e6ef991d2d0c54db3442fea2685ae63e48577f30

```
malformatted->malformed
```

Source: https://github.com/Slicer/Slicer/pull/6483/commits/2a6971e83a7dd0833fdde03434d3dab9d0e80bc8

**Comment by luzpaz** [comment]
> What do you think of contributing the following entries:

Most of those are in a PR already under review https://github.com/codespell-project/codespell/pull/2432 :wink: Thank you nonetheless!

**Review by jamesobutler — DISMISSED** [review]

**Comment by jcfr** [comment]
> Most of those are in a PR already under review

This is great. I now updating https://github.com/Slicer/actions-codespell accordingly and will follow up here.

**Pull request merged**
