### PR TITLE
ENH: Avoid tansform context menu if transform plugin is disabled

### PR DESCRIPTION
**Pull request by riep**
Fix https://github.com/Slicer/Slicer/issues/6621

### CODE REVIEW

**Review by lassoan — CHANGES_REQUESTED** [review]
Thanks for the pull request. I can see that it can be useful to configure menu items of the transform column's context menu and thank you for providing a potential implementation.

As you can see, the current actions in the transform context menu are not associated with the qSlicerSubjectHierarchyTransformsPlugin. Therefore, disabling that plugin does not hide the items. This is correct and consistent behavior and should not be changed.

To allow hiding the transform context menu items that are currently provided by qMRMLSubjectHierarchyTreeView by disabling the transforms plugin, creation and showing/hiding of those menu items must be moved into the qSlicerSubjectHierarchyTransformsPlugin class.

**Comment by lassoan** [comment]
@riep Do you think you'll have time to move creation and showing/hiding of transforms related menu items into the qSlicerSubjectHierarchyTransformsPlugin class?

**Comment by riep** [comment]
> @riep Do you think you'll have time to move creation and showing/hiding of transforms related menu items into the qSlicerSubjectHierarchyTransformsPlugin class?

Hi Andras, I will do that by the end of the month.
Best regards,
Pierre

**Comment by lassoan** [comment]
Thank you. Probably it will be included in the Slicer-5.6 release then.

**Comment by jcfr** [comment]
@riep Did you have a chance to work on this ? Let us know if you have any questions. Thanks again for your time and contribution :pray:

**Comment by jcfr** [comment]
@riep We moved this to Backlog, if you have a chance to work on this we can revisit and have the improvement included in an upcoming release.

**Comment by riep** [comment]
New PR https://github.com/Slicer/Slicer/pull/7997

**Comment by lassoan** [comment]
Thank you for the new PR, I'm closing this one then.

**Pull request closed without merging**
