### PR TITLE
Multishell DWI i/o improvements

### PR DESCRIPTION
**Pull request by ihnorton**
Adds several tests, improves round-trip-ability of gradient vectors by using DoubleConversion to write the gradients losslessly, and improves internal consistency of DWI NRRD nodes by enforcing expected invariants in the node setters.

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you, it looks good to me. It could make sense to squash the commits.

**Comment by pieper** [comment]
LGTM 👍

**Comment by jcfr** [comment]
Thanks @ihnorton

**Comment by ihnorton** [comment]
Thanks for the review. I will squash down to fewer commits, and merge.

**Comment by ihnorton** [comment]
Committed in r27382-r27386.

**Pull request closed without merging**
