### PR TITLE
BUG: Interaction handler visibility is updated when changing displayed slice

### PR DESCRIPTION
**Pull request by malbi**
This is a proposal to fix issue #6922

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
Thanks, lgtm!

**Comment by lassoan** [comment]
Thank you @malbi, you've found the root cause of the issue. @Sunderlandkyl is looking into this now, trying to find a fix that does not require manually calling `UpdateInteractionPipeline()` again (it is already called in `Superclass::UpdateFromMRML(caller, event, callData);` but that is probably done too early, before doing).

**Comment by malbi** [comment]
Hi
Do you have an update? Let me know if I can be of any help.

**Comment by lassoan** [comment]
@Sunderlandkyl I remember you worked on it, did we end up getting a fix integrated for this?

**Comment by lassoan** [comment]
@malbi could you please check if the problem is fixed in the latest Slicer Preview Release?

**Comment by malbi** [comment]
@lassoan thanks for the update, I have tried with Slicer-5.3.0-2023-05-21-linux-amd64 and I still encounter the same behaviour.

**Comment by lassoan** [comment]
Superseded by https://github.com/Slicer/Slicer/pull/6992

**Pull request closed without merging**
