### PR TITLE
DOC: Adding funding grant list

### PR DESCRIPTION
**Pull request by lassoan**
Move list of funding grants from the old wiki (https://www.slicer.org/wiki/Documentation/4.x/Acknowledgments#Grants)

This pull request is to test how the documentation page would look like if we included the funding grant list. Motivated by question raised in https://github.com/Slicer/Slicer/issues/5835.

### CODE REVIEW

**Review by jamesobutler — COMMENTED** [review]
At first I thought some text in the table was getting cutoff, but realized you have to scroll down the long list to be able to see the horizontal scroll bar. The Wiki table word wraps long text in cells.
image
image

**Comment by jcfr** [comment]
> but realized you have to scroll down the long list to be able to see the horizontal scroll bar.

I made a similar observation and initially thought the dates and PIs were dropped from the new listing.

Alternatively, we could list the grants and have them listed on the landing page. This would give us more flexibility to present the list.

**Comment by cpinter** [comment]
Once the format is finalized I can add the Spanish grant we have received partially for infrastructure - if you think it's appropriate to add that is.

**Comment by lassoan** [comment]
@cpinter this PR is merged, you can now add the Spanish grant.

**Pull request merged**
