### PR TITLE
ENH: Remove VolumeRenderingReplacements fixed point raycaster override

### PR DESCRIPTION
**Pull request by jcfr**
This specialized implementation was first introduced in r4673 (ENH: Integrated
VTK ray cast classes, started with modifications for incremental update) by
copying the VTK implementation of the FixedPoint volume caster.

Since then, the VTK implementation has matured a lot and fixes can easily
be contributed upstream, this commit removes the Slicer specific implementation.

### CODE REVIEW

**Comment by pieper** [comment]
+1

**Comment by lassoan** [comment]
:+1: Reducing code size without losing functionality is one of the best things that we can do.

How did you compare Slicer's implementation with current VTK implementation? Reviewed the code changes and/or compared results visually?

**Comment by jcfr** [comment]
@pieper Thanks for reviewing, out of curiosity do you know what was the original motivation to integrate a custom version of the mapper ? 

> How did you compare Slicer's implementation with current VTK implementation? 

Didn't do any thorough comparison yet ...  

> Reviewed the code changes and/or compared results visually?

quick visual inspection.

I would like this PR to trigger the discussion so that we can understand the original motivation, I will then check with the VTK team if all requirement are fulfilled.

**Comment by lassoan** [comment]
What I heard from Ron that they worked a lot on volume rendering compositing with polygonal data. 

I've just checked and it seems that development of both Slicer's and VTK's CPU raycast mapper essentially stopped 10 years ago, so probably comparing them is not worth the time. We should just drop them when we switch to OpenGL2, test it thoroughly and fix any issues that come up.

**Comment by pieper** [comment]
We discussed this on the developer hangout and the best seems to be to test
the proposed changes (dropping the Slicer custom classes) and debug in the
context of the OpenGL2 transition.  If we find any issues we can compare
the implementation details.

https://www.slicer.org/wiki/Developer_Meetings/20170425

**Comment by jcfr** [comment]
@lassoan @pieper I added a print statement  in the constructor of all the classes found in VolumeRenderingReplacements library and no classes are instantiated (assuming the string would have been displayed otherwise).

I will then proceed to the removal of this library.

These could have become obsolete after the clean up done in one of these revisions:
* [r23887](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23887) ENH: Remove unused Texture based volume rendering classes  (VTK OpenGL 3D Texture Mapping).
  * -> Previously disabled in [r23026](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23026)
* [r23888](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23888) ENH: Remove unused NCI volume rendering classes (NCI volume rendering).
  * -> Previously disabled in [r23026](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23026)
* [r23889 ](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23889) ENH: Remove unused NCI MultiVolume rendering classes (NCI GPU MultiVolume Ray Casting).
  * -> Previously disabled in [r20474](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=20474)


For future reference, here is the patch I applied:

```diff
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointRayCastImage.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointRayCastImage.cxx
index 7b381ec..9814997 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointRayCastImage.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointRayCastImage.cxx
@@ -20,6 +20,7 @@ vtkStandardNewMacro(vtkSlicerFixedPointRayCastImage);
 // Construct a new vtkSlicerFixedPointRayCastImage with default values
 vtkSlicerFixedPointRayCastImage::vtkSlicerFixedPointRayCastImage()
 {
+  std::cout << "vtkSlicerFixedPointRayCastImage" << std::endl;
   this->ImageViewportSize[0] = 0;
   this->ImageViewportSize[1] = 0;
 
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeGOHelper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeGOHelper.cxx
index a59b7ed..df863f1 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeGOHelper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeGOHelper.cxx
@@ -32,6 +32,7 @@ vtkStandardNewMacro(vtkSlicerFixedPointVolumeRayCastCompositeGOHelper);
 // Construct a new vtkSlicerFixedPointVolumeRayCastCompositeGOHelper with default values
 vtkSlicerFixedPointVolumeRayCastCompositeGOHelper::vtkSlicerFixedPointVolumeRayCastCompositeGOHelper()
 {
+  std::cout << "vtkSlicerFixedPointVolumeRayCastCompositeGOHelper" << std::endl;
 }
 
 // Destruct a vtkSlicerFixedPointVolumeRayCastCompositeGOHelper - clean up any memory used
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper.cxx
index 7c3ccf8..f7d4ed5 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper.cxx
@@ -32,6 +32,7 @@ vtkStandardNewMacro(vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper);
 // Construct a new vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper with default values
 vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper::vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper()
 {
+  std::cout << "vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper" << std::endl;
 }
 
 // Destruct a vtkSlicerFixedPointVolumeRayCastCompositeGOShadeHelper - clean up any memory used
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeHelper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeHelper.cxx
index 1d1bb8d..ec46378 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeHelper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeHelper.cxx
@@ -32,6 +32,7 @@ vtkStandardNewMacro(vtkSlicerFixedPointVolumeRayCastCompositeHelper);
 // Construct a new vtkSlicerFixedPointVolumeRayCastCompositeHelper with default values
 vtkSlicerFixedPointVolumeRayCastCompositeHelper::vtkSlicerFixedPointVolumeRayCastCompositeHelper()
 {
+  std::cout << "vtkSlicerFixedPointVolumeRayCastCompositeHelper" << std::endl;
 }
 
 // Destruct a vtkSlicerFixedPointVolumeRayCastCompositeHelper - clean up any memory used
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper.cxx
index 9a39402..706c28e 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper.cxx
@@ -32,6 +32,7 @@ vtkStandardNewMacro(vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper);
 // Construct a new vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper with default values
 vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper::vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper()
 {
+  std::cout << "vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper" << std::endl;
 }
 
 // Destruct a vtkSlicerFixedPointVolumeRayCastCompositeShadeHelper - clean up any memory used
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastHelper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastHelper.cxx
index b76eab3..aa24055 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastHelper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastHelper.cxx
@@ -20,6 +20,7 @@ vtkStandardNewMacro(vtkSlicerFixedPointVolumeRayCastHelper);
 
 vtkSlicerFixedPointVolumeRayCastHelper::vtkSlicerFixedPointVolumeRayCastHelper()
 {
+  std::cout << "vtkSlicerFixedPointVolumeRayCastHelper" << std::endl;
 }
 
 vtkSlicerFixedPointVolumeRayCastHelper::~vtkSlicerFixedPointVolumeRayCastHelper()
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastMIPHelper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastMIPHelper.cxx
index 9f2b364..eb6df72 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastMIPHelper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastMIPHelper.cxx
@@ -29,6 +29,7 @@ vtkStandardNewMacro(vtkSlicerFixedPointVolumeRayCastMIPHelper);
 // Construct a new vtkSlicerFixedPointVolumeRayCastMIPHelper with default values
 vtkSlicerFixedPointVolumeRayCastMIPHelper::vtkSlicerFixedPointVolumeRayCastMIPHelper()
 {
+  std::cout << "vtkSlicerFixedPointVolumeRayCastMIPHelper" << std::endl;
 }
 
 // Destruct a vtkSlicerFixedPointVolumeRayCastMIPHelper - clean up any memory used
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastMapper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastMapper.cxx
index a48e011..93c3b6b 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastMapper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerFixedPointVolumeRayCastMapper.cxx
@@ -400,6 +400,7 @@ void vtkSlicerFixedPointVolumeRayCastMapperComputeGradients( T *dataPtr,
 // Construct a new vtkSlicerFixedPointVolumeRayCastMapper with default values
 vtkSlicerFixedPointVolumeRayCastMapper::vtkSlicerFixedPointVolumeRayCastMapper()
 {
+  std::cout << "vtkSlicerFixedPointVolumeRayCastMapper" << std::endl;
     this->SampleDistance             =  1.0;
     this->InteractiveSampleDistance  =  2.0;
     this->ImageSampleDistance        =  1.0;
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerOpenGLRayCastImageDisplayHelper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerOpenGLRayCastImageDisplayHelper.cxx
index 621b8f3..a02e9ae 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerOpenGLRayCastImageDisplayHelper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerOpenGLRayCastImageDisplayHelper.cxx
@@ -30,6 +30,7 @@ vtkStandardNewMacro(vtkSlicerOpenGLRayCastImageDisplayHelper);
 // Construct a new vtkSlicerOpenGLRayCastImageDisplayHelper with default values
 vtkSlicerOpenGLRayCastImageDisplayHelper::vtkSlicerOpenGLRayCastImageDisplayHelper()
 {
+  std::cout << "vtkSlicerOpenGLRayCastImageDisplayHelper" << std::endl;
   this->PreviousImage = NULL;
 }
 
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerRayCastImageDisplayHelper.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerRayCastImageDisplayHelper.cxx
index 03eef20..bd70aba 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerRayCastImageDisplayHelper.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerRayCastImageDisplayHelper.cxx
@@ -21,6 +21,7 @@ vtkAbstractObjectFactoryNewMacro(vtkSlicerRayCastImageDisplayHelper);
 // Construct a new vtkSlicerRayCastImageDisplayHelper with default values
 vtkSlicerRayCastImageDisplayHelper::vtkSlicerRayCastImageDisplayHelper()
 {
+  std::cout << "vtkSlicerRayCastImageDisplayHelper" << std::endl;
   this->PreMultipliedColors = 0;
   this->PixelScale = 1.0;
 }
diff --git a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerVolumeRenderingFactory.cxx b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerVolumeRenderingFactory.cxx
index cc15e10..f0ee3a9 100644
--- a/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerVolumeRenderingFactory.cxx
+++ b/Modules/Loadable/VolumeRendering/VolumeRenderingReplacements/vtkSlicerVolumeRenderingFactory.cxx
@@ -34,6 +34,7 @@ vtkObject* vtkSlicerVolumeRenderingFactory::CreateInstance(const char* vtkclassn
   vtkObject *ret = vtkObjectFactory::CreateInstance(vtkclassname);
   if (ret)
     {
+    std::cout << "vtkSlicerVolumeRenderingFactory::CreateInstance:" << vtkclassname << std::endl;
     return ret;
     }
   // if the factory failed to create the object,

```

**Comment by jcfr** [comment]
Integrated in [r25972](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25972)

**Pull request closed without merging**
