### PR TITLE
Default cleanups with scripts used to modernize ITK

### PR DESCRIPTION
**Pull request by hjmjohnson**
This applies a set of standard scripts that were created to update many ITK packages to make them consistent
with modern programming recommendations.

### CODE REVIEW

**Review by pieper — DISMISSED** [review]
Looks fine to me - thanks for this @hjmjohnson 

Anyone else have an opinion?

**Review by lassoan — CHANGES_REQUESTED** [review]
std::stod/std::stoi are dangerous. If they encounter an error then they throw an exception and crash the entire application. For the same input, atof/atod return 0, and no crash.

Error checking has value, so I'm not against switching, but everywhere outside tests the exception has to be handled right there where the conversion is done. Annotation module classes can be left as they are, as they will be removed soon.

It seems that blanket replacement like this was done in entire ITK, without adding exception handling for these issues. Most occurrences are in tests, which don't matter (they can crash, that's good, it makes errors more visible), but there are dozens of classes (mainly IO) that now crash the application if they encounter unexpected input. We could fence around all ITK calls  with handlers for these new exceptions, but it would be much better if ITK would take care of it (the minimum would be to wrap it into itk::ExceptionObject that we already catch at risky places).

**Comment by lassoan** [comment]
For example:
- `std::atoi("")` and `std::atof("")` return 0
- `std::stoi("")` and `std::stod("")` make the application crash

**Comment by jcfr** [comment]
@hjmjohnson  Thanks for working on this :pray:

To help more forward, could you submit another PR with the commit associated with :heavy_check_mark: and update this one to only have the one :x: ? 

| Status | Commit |
|--|--|
| :heavy_check_mark:  | [COMP: Deprecate use itkGetObjectMacro](https://github.com/Slicer/Slicer/pull/6200/commits/543eaa84bf1bed84fc50ab7045ea11d86e0888d1)|
| :heavy_check_mark:  | [STYLE: Replace itkStaticConstMacro with static constexpr](https://github.com/Slicer/Slicer/pull/6200/commits/482f73840ebaa929e5b15adbb5ffd8090eb4b511) |
| :x:  | [STYLE: Prefer error checked std::sto[id] over ato[if]](https://github.com/Slicer/Slicer/pull/6200/commits/1706ffd0ad07d58a99d1ee3985eb4294e31d8b22) [1706ffd](https://github.com/Slicer/Slicer/pull/6200/commits/1706ffd0ad07d58a99d1ee3985eb4294e31d8b22) |
| :heavy_check_mark:  | [COMP: Future proof vnl_math_XXX function usage.](https://github.com/Slicer/Slicer/pull/6200/commits/29aaabdc6828b406bb978713992eee172cb6adad) |

**Comment by hjmjohnson** [comment]
My 2 cents.

The worst type of error for a medical imaging software is 
WORST:  Silently produce the wrong or ambiguous result for invalid inputs.
REALLY BAD: Crash the program if an invalid result would be produced.
BEST: catch exceptional cases and due something with those cases.

IMHO going from worst to really bad is a small step in the right direction.  I agree with @lassoan that the next step should be to evaluate all those exceptions and determine what the correct course of action should be.

I'll make a separate PR for this more controversial set of changes.

**Comment by jcfr** [comment]
Thanks @hjmjohnson 

To keep the discussion about the "controversial" patchset in one location, could you instead keep it in this PR and submit new one with the other patches associated with :heavy_check_mark:  ?  

Thanks for your patience while we finalize the discussions :pray:

**Comment by jcfr** [comment]
@hjmjohnson Could you add few entries to https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide ?

**Comment by hjmjohnson** [comment]
@jcfr Here are the scripts! 

[code_modernization_scripts.zip](https://github.com/Slicer/Slicer/files/8100340/code_modernization_scripts.zip)

Is there a directory in Slicer that would be a good place to share these and similar items?

Note: ITK has several of these scripts as well: ITK/Utilities/Maintenance

**Comment by hjmjohnson** [comment]
@pieper A point of clarification regarding "Slicer catches unhandled exceptions at the highest level".  That is good, but the current usage of atof/atod does not throw exceptions, they return valid values of 0 or 0.0 which are indistinguishable from valid conversions from the string "0".  

```c++
#include <iostream>
#include <stdlib.h>  

int main()
{
  int a=atoi("0");
  int b=atoi("2f");
  int c=atoi("7 ");

  std::cout << "a" << " = " << a << std::endl;
  std::cout << "b" << " = " << a << std::endl;
  std::cout << "c" << " = " << a << std::endl;

  return 0;
}
```

results in:
```txt
a = 0
b = 0
c = 0
```

I would argue that the use of "std::stod/std::stoi", which do throw exceptions, would allow the current slicer handling at the highest level to take effect.

**Comment by pieper** [comment]
Yes, I agree Hans, I think I'm on your side on this one.  @lassoan these exceptions would be caught be Slicer, right?  The user would have a hard time knowing exactly what triggered the error, but at least they wouldn't lose data.

**Comment by jcfr** [comment]
Looks like this introduced errors:

* Windows / Visual Studio

```
D:\D\P\Slicer-0\Modules\CLI\ExpertAutomatedRegistration\ITKRegistrationHelper\itkImageToImageRegistrationMethod.h(141,1): error C2535: 'const itk::Transform<double,itk::ImageToImageRegistrationMethod<TImage>::ImageDimension,itk::ImageToImageRegistrationMethod<TImage>::ImageDimension> *itk::ImageToImageRegistrationMethod<TImage>::GetTransform(void) const': member function already defined or declared [D:\D\P\Slicer-0-build\Slicer-build\Modules\CLI\ExpertAutomatedRegistration\ExpertAutomatedRegistrationLib.vcxproj] [D:\D\P\Slicer-0-build\Slicer.vcxproj]
```
Source: https://slicer.cdash.org/viewBuildError.php?buildid=2597175

* Linux / gcc 

```
error: ‘virtual const TransformType* itk::ImageToImageRegistrationMethod<TImage>::GetTransform() const’ cannot be overloaded
```

Source: https://slicer.cdash.org/viewBuildError.php?buildid=2597173

**Comment by lassoan** [comment]
ExpertAutomatedRegistration module was a very simple ITK registration demo. Since we have BRAINS, Elastix, and ANTs, this could be a good time to remove this module instead of fixing it.

**Comment by hjmjohnson** [comment]
@lassoan I am not sure I fully understand what to do with making ITK better.

Is the following refactoring what you are desiring?

```c++
      try
      {
        record.m_Tokens["Size"] =
          static_cast<itk::SizeValueType>(std::stoi(bracket.substr(1, bracket.length() - 3).c_str()));
      }
      catch (const std::invalid_argument & ia)
      {
        itkGenericExceptionMacro(<< "Invalid argument: " << ia.what() << '\n');
      }
      catch (const std::out_of_range & oor)
      {
        itkGenericExceptionMacro(<< "Out of Range error: " << oor.what() << '\n');
      }
```

To me both the old and new code throw exceptions, but the new version is known to be an ITK exception rather than one of the std exceptions.  Is this the type of solution that you think would improve Slicer's behavior in the event of a corrupt file reading?

Or were you thinking:

```c++
      try
      {
        record.m_Tokens["Size"] =
          static_cast<itk::SizeValueType>(std::stoi(bracket.substr(1, bracket.length() - 3).c_str()));
      }
      catch (const std::invalid_argument & ia)
      {
        record.m_Tokens["Size"] = std::numeric_traits<itk::SizeValueType>::max;
      }
      catch (const std::out_of_range & oor)
      {
        record.m_Tokens["Size"] = std::numeric_traits<itk::SizeValueType>::max;
      }
```

I am willing to make a patch set for ITK if I can better understand how the implementation can be made better.

**Comment by hjmjohnson** [comment]
NOTES:

```bash
#NOTE: 39 examples exist in ITK
git grep "\<sto[idf]\>"|fgrep -v ThirdParty|fgrep -v Test.cxx |fgrep -v Examples |fgrep -v Utilities |fgrep -v "test"|fgrep -v Document     
Modules/Core/Common/src/itkSmapsFileParser.cxx:          static_cast<itk::SizeValueType>(std::stoi(bracket.substr(1, bracket.length() - 3).c_str()));
Modules/Core/TestKernel/src/itkTestDriverInclude.cxx:      itk::MultiThreaderBase::SetGlobalDefaultNumberOfThreads(std::stoi((*argv)[i + 1]));
Modules/Core/TestKernel/src/itkTestDriverInclude.cxx:      regressionTestParameters.numberOfPixelsTolerance = std::stoi((*argv)[i + 1]);
Modules/Core/TestKernel/src/itkTestDriverInclude.cxx:      regressionTestParameters.radiusTolerance = std::stoi((*argv)[i + 1]);
Modules/Core/TestKernel/src/itkTestDriverInclude.cxx:      regressionTestParameters.intensityTolerance = std::stod((*argv)[i + 1]);
Modules/Core/TestKernel/src/itkTestDriverInclude.cxx:      regressionTestParameters.coordinateTolerance = std::stod((*argv)[i + 1]);
Modules/Core/TestKernel/src/itkTestDriverInclude.cxx:      regressionTestParameters.directionTolerance = std::stod((*argv)[i + 1]);
Modules/IO/Bruker/src/itkBruker2dseqImageIO.cxx:        sizeToSwap *= std::stoi(i[0].c_str());
Modules/IO/Bruker/src/itkBruker2dseqImageIO.cxx:            sizeT *= std::stoi(i[0].c_str());
Modules/IO/GDCM/src/itkGDCMImageIO.cxx:      outpixeltype.SetBitsAllocated(static_cast<unsigned short int>(std::stoi(bitsAllocated.c_str())));
Modules/IO/GDCM/src/itkGDCMImageIO.cxx:      outpixeltype.SetBitsStored(static_cast<unsigned short int>(std::stoi(bitsStored.c_str())));
Modules/IO/GDCM/src/itkGDCMImageIO.cxx:      outpixeltype.SetHighBit(static_cast<unsigned short int>(std::stoi(highBit.c_str())));
Modules/IO/GDCM/src/itkGDCMImageIO.cxx:      outpixeltype.SetPixelRepresentation(static_cast<unsigned short int>(std::stoi(pixelRep.c_str())));
Modules/IO/GE/src/itkGE4ImageIO.cxx:  hdr->seriesNumber = std::stoi(tmpStr);
Modules/IO/GE/src/itkGE4ImageIO.cxx:  hdr->imageNumber = std::stoi(tmpStr);
Modules/IO/GE/src/itkGE4ImageIO.cxx:    hdr->imagesPerSlice = static_cast<short>(std::stoi(tmpStr));
Modules/IO/ImageBase/src/itkRegularExpressionSeriesFileNames.cxx:    return std::stod(s1.second.c_str()) < std::stod(s2.second.c_str());
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:    return std::stoi(temp.c_str());
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:    return std::stoi(temp.c_str());
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->seriesNumber = std::stoi(tmpStr);
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->imageNumber = std::stoi(tmpStr);
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->sliceThickness = std::stoi(tmpStr);
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->acqXsize = std::stoi(tmpStr);
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->acqYsize = std::stoi(tmpStr);
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->xFOV = static_cast<float>(std::stod(tmpStr));
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->yFOV = static_cast<float>(std::stod(tmpStr));
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:    if (text_angle_len.empty() || itk::Math::abs(std::stod(text_angle_len)) <= 45.0)
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:    if (text_angle_len.empty() || itk::Math::abs(std::stod(text_angle_len)) <= 45.0)
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:    if (text_angle_len.empty() || itk::Math::abs(std::stod(text_angle_len)) <= 45.0)
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->sliceLocation = static_cast<float>(std::stod(tmpStr));
Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx:  hdr->echoNumber = (int)std::stoi(tmpStr);
Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx:    int size = std::stoi(m_CurCharacterData.c_str());
Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx:    int size = std::stoi(m_CurCharacterData.c_str());
Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx:    int size = std::stoi(m_CurCharacterData.c_str());
Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx:    float res = std::stod(m_CurCharacterData.c_str());
Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx:    float res = std::stod(m_CurCharacterData.c_str());
Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx:    float res = std::stod(m_CurCharacterData.c_str());
Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx:    int size = std::stoi(m_CurCharacterData.c_str());
Modules/Video/IO/src/itkVideoIOFactory.cxx:      int cameraIndex = std::stoi(arg);
```

**Comment by lassoan** [comment]
> @lassoan I am not sure I fully understand what to do with making ITK better.
> 
> Is the following refactoring what you are desiring?
> 
> ```c++
>       try
>       {
>         record.m_Tokens["Size"] =
>           static_cast<itk::SizeValueType>(std::stoi(bracket.substr(1, bracket.length() - 3).c_str()));
>       }
>       catch (const std::invalid_argument & ia)
>       {
>         itkGenericExceptionMacro(<< "Invalid argument: " << ia.what() << '\n');
>       }
>       catch (const std::out_of_range & oor)
>       {
>         itkGenericExceptionMacro(<< "Out of Range error: " << oor.what() << '\n');
>       }
> ```

Yes, exactly. We already catch ITK exceptions around most ITK calls (especially IO), so if ITK does not start to throw low-level C++ exceptions then it should be all good.

Ideally, ITK should do more than just changing the exception type, but it should give more context to the problem. For example, instead of getting this description from ITK exception:

    Invalid argument: 63,90812

I would except something like this:

    Reading of file /path/to/myfile.nrrd failed. Syntax error in line 12: "63,90812" is not a valid value for "space origin" [0].

Note that stoi/stod does not actually check validity of the input (`63,90812` would be simply accepted as `63` no error would be detected), so if you want to check validity of string inputs then you need to look elsewhere. For example, `std::strtol` and `std::strtod` can actually check for residual non-converted string fragments (and does not throw exceptions, so you don't need to catch and re-throw).

@hjmjohnson Thank you for working on these. I really appreciate that you take the effort to improve code quality of not just ITK but also Slicer.

**Comment by hjmjohnson** [comment]
@lassoan Thank you for your response.  I did not appreciate the value of the exception error class change until you pointed out that only ITK exceptions are caught.

I have made an issue in ITK https://github.com/InsightSoftwareConsortium/ITK/issues/3213.  

I am working on another big project for ITK at the momement, so I wont get to this ASAP, but I'll try to fix this in the next few months.

**Pull request merged**
