### PR TITLE
Upgrade to NumPy 1.9.2

### PR DESCRIPTION
**Pull request by msmolens**
This PR upgrades from NumPy 1.4.1 to NumPy 1.9.2. This allows compiling Slicer with NumPy enabled in Visual Studio 2013. (However, beware the NumPy test failures with Visual Studio 2013 listed in 722397a.)

Additionally, the Python package 'nose' is now installed into Slicer's embedded Python. Including nose allows running NumPy unit tests inside Slicer's Python environment.

Finally, a Python build configuration problem that prevented building NumPy 1.9.2 on Windows in Debug configuration is fixed.

### CODE REVIEW

**Comment by jcfr** [comment]
Very nice :+1: 

Few nitpicks / remarks:

1. Could you mention in the commit message that it still work with VS2008 and VS2010
2. Regarding the numpy tests, do you have the results for `Windows (Visual Studio 2008, Release)`
3. For sake of comparison, how many python tests are failing using numpy 1.4.1.

**Comment by msmolens** [comment]
Updated the commit message to show NumPy test results for 1.4.1 and 1.9.2 on Mac, Linux, VS2008, and VS2013.

**Comment by jcfr** [comment]
:+1: :8ball:  LGTM   :fireworks:

**Comment by msmolens** [comment]
Great! Integrated in:
[24559](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24559)
[24560](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24560)
[24561](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24561)

**Pull request closed without merging**
