### PR TITLE
Update minimum supported macOS versions

### PR DESCRIPTION
**Pull request by jamesobutler**
This PR aims to update the minimum supported platform versions for Slicer on macOS to be versions of macOS that they themselves are supported by Apple.

This will support the following macOS versions:
- 13.x: Ventura (2022)
- 12.x: Monterey (2021)
- 11.x: Big Sur (2020)

This is a follow-up to https://github.com/Slicer/Slicer/pull/6314 where the macOS minimum was updated from 10.13 to 10.15. The change was reverted in https://github.com/Slicer/Slicer/pull/6582 to put off the change until after Slicer 5.2.0 was released. This PR updates the minimum to macOS 11 (Big Sur) now that macOS 13 (Ventura) is out and Apple is no longer supporting macOS 10.15 (Catalina).

See https://github.com/Slicer/Slicer/pull/6582#issuecomment-1276838014 regarding the latest about the "computron" Slicer factory machine being updated to macOS Monterey.

### CODE REVIEW

**Comment by jcfr** [comment]
The update of `computron` from macOS 10.15 (Catalina) to macOS 12 (Monterrey) has been added to  @Kitware sysadmins queue. Tentative completion date is December 15th 2022.

**Comment by jamesobutler** [comment]
@jcfr Has `computron` been updated to macOS 12 based on the previously mentioned tentative date?

**Comment by jcfr** [comment]
IT turns out `computron` has been updated to Ventura (macOS 13), I was able to log in to the system and triggered the update of Xcode.

Once this is done, I will (1) update the Dashboard script and (2) test building this PR on the system.

**Comment by jamesobutler** [comment]
Qt 6.5 specifies macOS target platform of macOS 11, 12, 13. https://doc-snapshots.qt.io/qt6-6.5/supported-platforms.html#macos

**Comment by jcfr** [comment]
We will update the documentation in a follow-up pull-request.

**Pull request merged**
