### PR TITLE
Sqlite3

### PR DESCRIPTION
**Pull request by BishopWolf**
Enabling support for sqlite3 by bundling an internal sqlite3 amalgamation

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you! I've started a test build on Windows. I'll let you know how it works.

**Comment by lassoan** [comment]
On Windows, sqlite3.h is not found in the binary directory but only in the source directory. Could you please add a set(${proj}_INCLUDE_DIR ${EP_SOURCE_DIR}) and pass it to Python as SQLITE3_INCLUDE_PATH?

Please also rebase your branch on latest master and squash all the commits (so that we see only a single commit, which contains all the changes relative to the latest master).

**Comment by BishopWolf** [comment]
I don't find where to squash the commits, It is easier in gitlab ;)

**Comment by lassoan** [comment]
I've cleaned up things and tried to follow the approach of bz2 to fix Windows build (there were issues due to multi-configuration - in the build tree there are 4 library versions, Release, Debug, RelWithDebInfo, and MinSizeRel, in subfolders, while there is only one in the install folder):

https://github.com/lassoan/Slicer/commit/aafaff3da22251f925720394f30e71ae7f9bf291

Could you please test if it works on linux and mac?

**Comment by lassoan** [comment]
Using my branch referenced above, sqlite3 works well in Release mode on Windows. I'll test starting from a clean build Release mode, and incremental and clean build Debug mode.

**Comment by lassoan** [comment]
@BishopWolf I would also recommend you to add a simple Python scripted test that checks if sqlite3 package is available and works well in Python.

**Comment by lassoan** [comment]
I've added a test, see updated branch here: https://github.com/lassoan/Slicer/tree/sqlite3

I've tested this on Windows, from incremental and clean build, release and debug mode, and it worked.

Please test the build on Linux and Mac, too, in both Debug and Release mode.

**Comment by lassoan** [comment]
@pieper could you test this branch on Mac? https://github.com/lassoan/Slicer/tree/sqlite3

**Comment by BishopWolf** [comment]
I am having a big problem with my compiler in MacOS catalina
````
[ 37%] Performing build step for 'qRestAPI'
In file included from cryptlib.c:117:
./cryptlib.h:62:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h>
          ^~~~~~~~~~
```
it is related to [this issue](https://bbqsoftwares.com/blog/xdebug-catalina-issue#the-catalina-issue) and I haven't found a solution yet.
OTOH, I am 2 weeks on vacations with no access to my linux server so I can't test for now. If somebody else can do this before january it will be good.

**Comment by lassoan** [comment]
No worries, have a nice vacation, we'll finish next year.

**Comment by pieper** [comment]
> @pieper could you test this branch on Mac (if there is any build error; and if not, does import sqlite3 throws any error)? https://github.com/lassoan/Slicer/tree/sqlite3

@lassoan - I was able to build python on mac catalina and I could import sqlite3 with no errors.

@BishopWolf - I found I needed to set the SDKROOT as a workaround.  See https://issues.slicer.org/view.php?id=4681

**Comment by lassoan** [comment]
Great, thanks a lot for testing. It seems that it works on Windows and Mac then, so it just has to be tested on linux now.

@BishopWolf it would be nice if you could test if build instructions described here work for you: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Build_Instructions#Mac_OSX_10.14_.28Mojave.29

**Comment by BishopWolf** [comment]
I had no problems to build before, neither mac nor Linux, it is just Mac Catalina who creates an extra issue. But I have no access now to my linux Station until January.

**Comment by jcfr** [comment]
Thanks @BishopWolf, @lassoan and @pieper :pray: 

On my side, I am also heading out of town until January 6th and I don't think I will have the time to look into this. (unless I get bored in the :airplane: [likelihood 75%] or in the :mountain:  [likelihood 1%] .... happy holidays to all !)

**Comment by pieper** [comment]
Enjoy the holiday time everyone!

**Comment by BishopWolf** [comment]
I have fixed my build system, I needed to reinstall xcode, CLT and homebrew. Now it works and it is compiling. However, compilation stops at
```
/Users/alexvergaragil/Documents/GIT/Slicer/Modules/Loadable/SubjectHierarchy/Widgets/qSlicerSubjectHierarchyPluginLogic.cxx:574:42: error:
      out-of-line definition of 'registerViewMenuAction' does not match any declaration in
      'qSlicerSubjectHierarchyPluginLogic'
void qSlicerSubjectHierarchyPluginLogic::registerViewMenuAction(QAction* action)
                                         ^~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/alexvergaragil/Documents/GIT/build/Slicer/Slicer-build/Modules/Loadable/DoubleArrays/qSlicerDoubleArraysModuleGenericTest.cxx:38:
```

**Comment by BishopWolf** [comment]
The last push is to add a line to solve my build problems. But I wonder how can you build without it?

**Comment by lassoan** [comment]
I've rebased on latest Slicer master and squashed all the commits. I've also removed sqlite dependency in SuperBuild.cmake, which should not be necessary.

**Comment by lassoan** [comment]
Thanks for all your testing and fixes. Squashed and merged: https://github.com/Slicer/Slicer/commit/15bc3838623449df79e32ecd5303062000868feb

**Comment by sjh26** [comment]
Hi all:

This has broken the factory linux build.  See: http://slicer.cdash.org/viewBuildError.php?buildid=1786325.  Are there any changes to the factory machine that need to be made for this to work?

**Comment by lassoan** [comment]
This has been tested on Linux and worked, but not on the factory computer. We don't know if something went wrong while cleaning up and rebasing or the factory build environment is different compared to what this was tested on.

@sjh26 It would be great if you could investigate and fix this.

**Comment by sjh26** [comment]
The issue appears to be here:

/work/Preview/Slicer-0-build/sqlite-install/lib/libsqlite3.a  is not a valid path, the factory build has

/work/Preview/Slicer-0-build/sqlite-install/lib64/libsqlite3.a

working on getting this sorted

**Comment by pieper** [comment]
I just doublechecked and a fresh linux build from the current master works for me.

**Comment by sjh26** [comment]
Possibile fix here: https://github.com/sjh26/Slicer/commit/ec8ffb6bc34abcee64c8800c63e44ec950806e5f

I am currently testing on the factory and it has at least gotten past the python build that was throwing the error.  If someone could test locally that would be great.

Synopsis:
The sqlite3 repo uses [GNUInstallDirs](https://cmake.org/cmake/help/v3.16/module/GNUInstallDirs.html) to determine the lib install path.  It is not consistent between linux distros. Most of our other libraries hardcode it as "lib".  Since GNUInstallDirs can return wither "lib" or "lib64" depending on distro, we need to force the value to maintain consistency.

**Comment by sjh26** [comment]
Test build is good: http://slicer.cdash.org/buildSummary.php?buildid=1790968

Merged in  [28708](http://svn.slicer.org/Slicer4/trunk@28708)

**Comment by lassoan** [comment]
Awesome, thank you!

**Pull request closed without merging**
