### PR TITLE
BUG: Fix warning messages logged by slice offset slider

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
The range of the slice offset slider in qMRMLSliceControllerWidget is set using the depth dimension of the slice bounds.

For thin volumes (such as ultrasound), the bounds could be slightly smaller than the spacing due to floating point errors. In these cases, trying to set the step size of the slider to the spacing would result in a warning message since the step size would be greater than the maximum value.

Fixed by setting the step size to the smaller of the either the slice offset or the slice bounds depth.

### CODE REVIEW

**Comment by lassoan** [comment]
@Sunderlandkyl now that the pull request is approved, do you have permission to rebase&merge?

**Comment by Sunderlandkyl** [comment]
I do not, no.

**Comment by jcfr** [comment]
@Sunderlandkyl  I just invited you to the https://github.com/orgs/Slicer/teams/slicer-developer/members team, once you accept the invitation .. you should be able to merge

**Comment by Sunderlandkyl** [comment]
@jcfr It still says I'm not authorized to merge the pull request.

**Comment by jcfr** [comment]
I thought write access gave merge access ... what about now ? I just added you to https://github.com/orgs/Slicer/teams/slicer-core/members

**Comment by Sunderlandkyl** [comment]
Works now, thanks @jcfr!

**Pull request merged**
