### PR TITLE
BUG: Fix python wrapping of vtkSlicerCLIModuleLogic using VTK9

### LINKED ISSUE #5266: vtkSlicerCLIModuleLogic Python class is not found
Using Slicer-4.11.20200930:

```ptyhon
>>> slicer.vtkSlicerCLIModuleLogic()
(qSlicerBaseQTCLIPython.vtkSlicerCLIModuleLogic)00000167BA933648
```

Using latest master:

```python
>>> slicer.vtkSlicerCLIModuleLogic()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: this class cannot be instantiated
```

I’ve debugged into wrappython.exe and the problem is that for some reason the hierarchy cannot find the parent’s class in the hierarchy and so it determines that vtkSlicerCLIModuleLogic is not a VTK class, therefore it looks for a public constructor (instead of New()), which is of course is not found.

Originally reported here: https://discourse.slicer.org/t/calls-to-cli-makes-tests-to-fail/13835/10?u=lassoan

### PR DESCRIPTION
**Pull request by jcfr**
Fixes #5266

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Thank you, it looks good. What is the reason this has only came up for VTK9?

**Comment by jcfr** [comment]
> What is the reason this has only came up for VTK9?

The CMake infrastructure to collect hierarchy files has been revamped in VTK9 and the module we maintained in `vtkAddon` does not handle the case of `vtkLibrary1` -> `qSlicerLibrary1` -> `vtkLibrary2`. 

See https://discourse.vtk.org/t/issue-with-using-vtkpythonutil-getobjectfrompointer-for-custom-vtk-classes/4100/ and https://github.com/Slicer/vtkAddon/commit/5df87dee75c049320943f445200b4cbe7309f811

**Comment by lassoan** [comment]
Thanks for the explanation and congratulations for being able to track down this issue, so deeply in the Python wrapping infrastructure. Hopefully such issues will not come up too often, because it seems quite difficult to identify the problem.

**Comment by jcfr** [comment]
Considering I had spent a fair amount of time when working on the initial transition, it didn't take too long to address this particular one. 

That said, it would have taken a significant amount time without that initial investment.

> Hopefully such issues will not come up too often

This is a very special case and I don't foresee this happening in extensions.

**Pull request merged**
