### PR TITLE
Use equal default for C++11

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks :pray: 

I will try to build the topic later to confirm the VTK wrapping behave.

**Comment by hjmjohnson** [comment]
@jcfr Are there issues with VTK wrapping?

**Comment by jcfr** [comment]
Looking at the git history associated with the VTK wrapping tools, I saw some changed related to handling of C++11 features (enum, default initializer, ...)

This is why I think we shouldn't rush that change

**Comment by hjmjohnson** [comment]
@jcfr Can we please take this to completion?  If you want to reject it, then let's take care of that now. Monitoring outstanding patches is time-consuming.

**Comment by lassoan** [comment]
@jcfr are there things that you are sure that are safe to change or things that should not be changed? So many files have changed so that if these changes are not merged soon then it'll be very hard to merge them due to conflicting changes.

**Comment by jcfr** [comment]
I am building locally and testing, I will integrate when this is done.

**Pull request merged**
