### PR TITLE
STYLE: Remove dead code for BlobDetection and ConnectedComponent CLI modules

### PR DESCRIPTION
**Pull request by jcfr**
The code has **NOT** been compiled since r20744 [1] from August 2010.

[1] http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=20744)

Associated issue was:
https://issues.slicer.org/view.php?id=2809)

And a excerpt from @pieper reply from 2012 on the slicer-devel [2] mailing
list thread entitled `Re: Adding new modules to Slicer core? `:

  I haven't looked at this in detail, but I think the module has
  the **potential for wide utility**, but since it's **currently disabled**
  it's not yet widely used. It also seems that it **doesn't have documentation**,
  which is probably why it is currently disabled.  So yes, for now I think
  BlobDetection and the related module ConnectedComponent **should move to
  an extension** (as should a few other specialized modules).  We should
  probably make this a group project at some point, but as we discussed
  on yesterday's call performance optimization and ITKv4 are higher
  priorities right now :)

[2] http://slicer-devel-archive.65872.n3.nabble.com/Adding-new-modules-to-Slicer-core-tp4025907p4026923.html

For reference, see also associated discourse topic:
https://discourse.slicer.org/t/slicer-5-0-deprecation-discussion-wiki/2377/8?u=jcfr

### CODE REVIEW

**Comment by lassoan** [comment]
We could add a "LegacyModules" extension (or something similar) and put these two modules in there. Maybe we could also move modules from Legacy category into that extension.

**Comment by jcfr** [comment]
I like that idea.

May be we could host in in the NA-MIC organization ? 

E.g https://github.com/NA-MIC/SlicerLegacyModules  

The idea being to keep the Slicer organization "lean"

**Comment by lassoan** [comment]
Why not in Slicer organization?

**Comment by jcfr** [comment]
Then, for the repository few options: `SlicerLegacyModules  or `SlicerLegacyModulesExtension`  or ... ?

**Comment by lassoan** [comment]
I think LegacyModules as extension name, SlicerLegacyModules as repository name would be good.

**Comment by jcfr** [comment]
All set. Here it is: https://github.com/Slicer/SlicerLegacyModules

There is also a step-by-step guide explaining how to extract the module history.

**Comment by jcfr** [comment]
Closing. Integrated in [r27106](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27106)

**Comment by jcfr** [comment]
Would be great if someone could help design the logo for https://github.com/Slicer/SlicerLegacyModules extension.

**Comment by jcfr** [comment]
May be an image of [mamouth](https://duckduckgo.com/?q=mamouth&iax=images&ia=images) with Slicer logo ?

**Comment by lassoan** [comment]
Thank you! Could you give me write access to the repository?

The logo could be also based on a "museum" icon - https://www.google.ca/search?q=icon+museum&tbm=isch.

**Comment by jcfr** [comment]
> Could you give me write access to the repository?

All set. Team [Slicer-core](https://github.com/orgs/Slicer/teams/slicer-core/members) was  associated with the repo.

**Comment by lassoan** [comment]
Perfect, thank you!

**Pull request closed without merging**
