### PR TITLE
ENH: Add customization of markup text font and background appearance

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Adds additional options to the vtkMRMLMarkupsDisplayNode to customize text display:
- TextFontFamily
- TextFontFamily;
- TextBold;
- TextItalic;
- TextShadow;
- TextBackgroundColor
- TextBackgroundVisibility;
- TextBackgroundOpacity

image

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
Changing to use a vtkTextProperty to contain all text display options makes sense to me.

**Comment by jcfr** [comment]
Thanks @Sunderlandkyl  for accommodating, these changes are great.

**Comment by Sunderlandkyl** [comment]
@lassoan I've updated the MRMLNode to use a vtkTextProperty object.

If you think that we will need a WriteXML/ReadXML macro for vtkTextProperty objects for other nodes, then I'll go ahead and convert the serialization functions to Read/WriteXML macros.

**Review by lassoan — COMMENTED** [review]
This is great, thank you. I have only one small comment (Set/SetAndObserve) and a few trivial ones.

**Review by lassoan — COMMENTED** [review]
Thank you very much, I've added a few mostly trivial comments. We could slightly simplify the code if GetTextProperty() method would be available in the public API but SetAndObserveTextProperty() would be kept protected. Because then we could easily ensure that the returned text property is always valid and we would not need extra checks and default value initializations at a number of places. We'll probably add a few more text properties later, so it is worth investing time into getting a simpler, more straightforward API.

**Comment by Sunderlandkyl** [comment]
> We could slightly simplify the code if GetTextProperty() method would be available in the public API but SetAndObserveTextProperty() would be kept protected.

The one reason that I could think that we might want to keep SetAndObserveTextProperty public would be so that you could set the same vtkTextProperty on multiple markups, and be able to update them all without having to update their vtkTextProperty individually.

**Comment by lassoan** [comment]
> The one reason that I could think that we might want to keep SetAndObserveTextProperty public would be so that you could set the same vtkTextProperty on multiple markups, and be able to update them all without having to update their vtkTextProperty individually.

OK, if you think this would be a useful feature then keep it like this, just clarify the documentation (what happens if nullptr is set).

I think we should still make GetTextProperty always return a valid text property (by replacing nullptr with a pointer to a default text property object; either when calling SetTextProperty(nullptr) or when calling GetTextProperty()). It would make the display node a bit more complex/opaque, but simplify classes that use it, and it would also centralize where default text properties are set.

**Comment by Sunderlandkyl** [comment]
OK, I have no particular use case that requires setting the same ```vtkTextPropery``` to multiple nodes, so I've just removed the function to set it. The ```GetTextProperty``` method should now always return a valid pointer,

**Review by lassoan — APPROVED** [review]
Thank you, it looks good now. Sorry for all the nitpicks.

**Comment by pieper** [comment]
If you think it would help to use the same text property for multiple nodes, then it would be good to make a new `vtkMRMLTextPropertyNode` that others could observe through references so the relationship would be preserved through scene save and restore.  But I agree I'm not sure it will come up often enough to be worth that effort.

**Comment by lassoan** [comment]
Saving/reloading is a good point - and now that I think about it, sequences, scene views, and undo/redo may be confused by shared data. It is probably safer to keep object members of different nodes independent (as it is done in the final implementation).

**Comment by Sunderlandkyl** [comment]
Thanks for reviewing! Better to do things right the first time then fixing them later.

**Pull request merged**
