### PR TITLE
Fix minor bugs and improve readability of the CLI module template.

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by vovythevov** [comment]
Thanks @thewtex for the contribution !

I think that since this is the example people use to write their CLI, it should use the plugin watcher to communicate progress with Slicer (for reference https://github.com/Slicer/Slicer/blob/master/Base/CLI/itkPluginFilterWatcher.h  and https://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/SlicerExecutionModel#Showing_Progress_in_an_Application)

This might be a little bit outside the scope of your work, but would you mind adding this ?

**Comment by jcfr** [comment]
:+1: 

Thanks for the change. Will integrate.

If you have a chance, you could also apply the change to: https://github.com/Slicer/Slicer/tree/master/Utilities/Templates/Modules/CLI 

Moving forward, I will add a README file to the Extensions/Testing folder and add a custom command to re-generate them using the wizard.

**Comment by thewtex** [comment]
@vovythevov @jcfr thanks for the tips.  Yes, will do.

**Comment by jcfr** [comment]
@thewtex Thanks again for the patches. They have been integrated in [r25019](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25019) to  [r25023](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25023)

Additionally, a target named `SlicerGenerateExtensionTemplates` has been added in [r25024](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25024)

Extension templates in `Slicer/Extensions/Testing` have been re-generated in [r25025](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25025)

**Comment by thewtex** [comment]
@jcfr Excellent, thank you!

**Pull request closed without merging**
