### PR TITLE
ENH: Additional costructor slice widgets

### PR DESCRIPTION
**Pull request by Punzo**
Hi,

I'd like to add the submitted constructors in the classes qMRMLSliceWidget and qMRMLSliceControllerWidget. In this way I can heridate the private calsses for custom widgets, then registered using the factory as described in https://github.com/Slicer/Slicer/pull/309#issuecomment-142910132 .

@jcfr may you take a look?

### CODE REVIEW

**Comment by jcfr** [comment]
@Punzo Thanks again for your contribution. Since I be in vacation next week, I will take care of this when I return on Oct 18th.

**Comment by Punzo** [comment]
Hi @jcfr,

had you time to check on this? 

Thanks,

Davide.

**Comment by jcfr** [comment]
@Punzo This will wait after the 4.5 release. But no worry, the change still have a chance to make it into the patch release planned for early December.

**Comment by jcfr** [comment]
Integrated in [r24762](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24762) and [r24763](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24763)

**Comment by Punzo** [comment]
thanks for integrating

**Pull request closed without merging**
