### PR TITLE
STYLE: "become"

### PR DESCRIPTION
**Pull request by tdiprima**
Please consider this small fix.  Changed "be come" to "become".
Thank you :)

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the fix :+1:  

Integrated in [r25860](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25860)

**Comment by lassoan** [comment]
Note that this is template is for the old editor module. Template for the current segment editor is available here:
https://github.com/Slicer/Slicer/tree/master/Utilities/Templates/Modules/ScriptedSegmentEditorEffect
The easiest way to use it is to run the ExtensionWizard module in Slicer to generate an extension and within that add a 'scriptedsegmenteditoreffect' module.

**Comment by lassoan** [comment]
@jcfr Duplication between [1] and [2] is confusing and difficult to maintain. Should we change extension testing to use [1] and delete [2]; or change extension wizard to use [2] and delete [1]?

[1] https://github.com/Slicer/Slicer/tree/master/Utilities/Templates/Modules
[2] https://github.com/Slicer/Slicer/tree/master/Extensions/Testing

**Comment by jcfr** [comment]
Templates in https://github.com/Slicer/Slicer/tree/master/Extensions/Testing are full example integrating multiple modules that are automatically generated using the Slicer templates generator targets.

See here for more details: https://github.com/Slicer/Slicer/pull/493#issuecomment-219512388

**Pull request closed without merging**
