### PR TITLE
STYLE: Prefer c++11 'using' to 'typedef'

### PR DESCRIPTION
**Pull request by hjmjohnson**
The check converts the usage of typedef with using keyword.

```
cd ${BLDDIR}
run-clang-tidy.py -extra-arg=-D__clang__ -checks=-*,modernize-use-using  -header-filter=.* -fix
```

See https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-using.html

### CODE REVIEW

**Comment by jcfr** [comment]
Let's delay this one until #4810 is integrated

**Comment by hjmjohnson** [comment]
> Let's delay this one until #4810 is integrated

Why?  They are unrelated, and furthermore they look like they will not conflict.  There are only 2 typedefs in #4810 diff, and they are not part of the changed code.

**Comment by jcfr** [comment]
Et voila,  sequences module has been integrated. 

Would be awesome if you could rebase this topic and re-run the clang-tidy script. :pray:

**Comment by hjmjohnson** [comment]
> See my last comment

Done.

**Comment by hjmjohnson** [comment]
@jcfr Waited for #4810 now this should be ready to merge.

**Comment by jcfr** [comment]
Thanks for the update. I will review and integrate shortly.

**Comment by jcfr** [comment]
Look we need will have to tweak something, I get the following error:

```
vtkWrapHierarchy-8.2: In /home/jcfr/Projects/Slicer/Libs/MRML/Core/vtkMRMLClipModelsNode.h:96: syntax error.
```

**Comment by jcfr** [comment]
I suspect we will have to wait for the VTK version to be updated, or we should identify the fix for VTK python  wrapping that need to be backported.

**Comment by hjmjohnson** [comment]
I don't have this error on Ubuntu 18.04 or Mac with my builds.  Too many outstanding issues to untangle.  Will remove to wait for other build failures to complete first.

**Pull request closed without merging**
