### PR TITLE
ENH: Fix 3943 and other enhancements for slice view annotaitons

### PR DESCRIPTION
**Pull request by mehrtash**
* Fixed #3943 by replacing DICOM study date and study time with series date and
series time.
* Moved slice view annotations settings gear from Data Probe small widget (main
 screen) to the Data probe module in order to preserve more screen real
  estate for the module uis.
  * Fixed problem with color scalarbar range labels.
  * Added an option to change format of color scalarbar range label and save the user settings in application settings.
  * Change ruler text font size and family according to other text
  annotations.

### CODE REVIEW

**Comment by mehrtash** [comment]
@jcfr @fedorov

I could reproduce the bug that you've mentioned in [1]. It is fixed now.

[1] https://github.com/Slicer/Slicer/pull/232

**Comment by jcfr** [comment]
I just tested this and I am not able to see the "Gear" annotation settings. See screenshot below.

3943-build-of-2015-02-23

**Comment by mehrtash** [comment]
That is the correct behavior. Please open the Dataprobe module from the modules list. You can find the settings gear there. It is moved there since we got comments that the gear wasting screen real estate.

**Comment by mehrtash** [comment]
Here is the attachment showing the dataprobe module and settings gear.

**Comment by jcfr** [comment]
I see. Is there any advantage in keep the settings UI as a popup ?  I guess we could reduce the number of clicks by adding the slice view annotation control directly to the DataProbe module panel ?

**Comment by mehrtash** [comment]
Good point @jcfr. I applied your suggestion to the code and squashed the commits. Please test it again. Thanks.

**Comment by jcfr** [comment]
Looks good. 

A different issue that could probably be addressed by a follow-up commit: When disabling and then enabling the slicer view annotations, all settings are enabled independently of their previous value.

**Comment by mehrtash** [comment]
@jcfr It should be fixed now. However this is for the main features including: corner annotation texts, ruler and color scalarbar.

**Comment by jcfr** [comment]
Fixed in [r23981](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23981)

**Comment by jcfr** [comment]
If you happen to do some more work on slicer view annotation, there is now an enum associated with vtkCornerAnnotation that should avoid using the integer 0, 1, 2 and 3 to identify the text location.

It has been added to Slicer/VTK6 and backported to Slicer/VTK5.
See https://github.com/Slicer/VTK/tree/slicer-release-5.10_2014-04-03
and https://github.com/Slicer/VTK/tree/slicer-v6.2.0-d733280_2015-02-05

**Pull request closed without merging**
