### PR TITLE
ENH: Add perceptually uniform color lookup tables

### PR DESCRIPTION
**Pull request by fepegar**
Add matplotlib's new perceptually uniform colormaps to Slicer default color lookup tables. Issue 4255

### CODE REVIEW

**Comment by fedorov** [comment]
Thanks for your contribution!

Can you include screenshots of the LUT palette in this PR comments?

**Comment by fepegar** [comment]
Sure:
colors

**Comment by pieper** [comment]
I made a test build of this but the new color tables don't show up in the application that I can see.

@naucoin could you comment on how these should be integrated?

**Comment by fepegar** [comment]
I thought [this function](https://github.com/Slicer/Slicer/blob/846a654748e263ca51ac43c0d324d260c03e008e/Modules/Loadable/Colors/Logic/vtkSlicerColorLogic.cxx#L131) would look for all the lookup tables in Slicer/Base/Logic/Resources/ColorFiles, but I didn't read it thoroughly.

**Comment by naucoin** [comment]
That's correct, FindColorFiles scans that directory and examines files to see if they can be read. I did a quick check of just copying in Inferno.txt and building, and it's not getting installed to the build directory, it should be presesnt in `Slicer-build/share/Slicer-4.5/ColorFiles`. Ah, right, because the files are globbed, CMake doesn't detect that there's been a change, try touching `Slicer/Base/Logic/Resources/CMakeLists.txt `and rebuilding. Once I did that the new color file loaded into my built Slicer. The nightly builds are done from scratch so they won't have a problem packaging the new files, so this pull request looks good to me!

**Comment by pieper** [comment]
Touching the cmake file worked - thanks @naucoin !

Committed as r25368

**Comment by fepegar** [comment]
Thank you!
Should we include some file or text giving credit to matplotlib? They mention something in the first paragraph here: https://bids.github.io/colormap/

**Comment by pieper** [comment]
Yes, it's good practice to include that sort of reference in the commit
messages or somewhere.  Also a link to the mailing list archive page where
the topic was discussed.  I'm not sure but I think it's also possible to
put a comment directly in the color file (do you know Nicole?)

**Comment by fepegar** [comment]
I edited my first comment on this PR. I think Slicer color lookup tables can have commented lines with #. I can add some comments in the colormaps about their authors.

**Comment by naucoin** [comment]
Yes, color files can have comment lines starting with a #.

**Pull request closed without merging**
