### PR TITLE
Fiber Bundle Label Selection

### PR DESCRIPTION
**Pull request by zhangfanmark**
Hi @jcfr @pieper ,

Could you check the updates of the FiberBundleLabelSelection module? Please let us know if there is anything needed to be further updated. 
Thanks a lot!

Regards,
Fan

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks @zhangfanmark 

I will review shortly and let you know if there any questions.

In the mean time, could you create a wiki page for the module ?

The following page doesn't exist: http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/FiberBundleLabelSelection

For details, see http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Tutorials/DocumentModule

Cc: @pieper @ljod

**Comment by zhangfanmark** [comment]
Hi @jcfr  

Sure, could you accept my request for editing the wiki page? 

Regards,
Fan

**Comment by jcfr** [comment]
Hi,

You should be all set.

Jc

On Mon, Nov 2, 2015 at 5:14 PM, zhangfanmark <notifications@github.com>
wrote:

> Hi @jcfr <https://github.com/jcfr>
>
> Sure, could you accept my request for editing the wiki page?
>
> Regards,
> Fan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/395#issuecomment-153174502>.
>



-- 
+1 919 869 8849

**Comment by pieper** [comment]
Looks quite nice to me.

**Comment by jcfr** [comment]
Integrated in [r24720](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24720)

Thanks again for contributing a test. :+1: 

Remarks:
* Make sure your editor is configured to use spaces instead of tabs
* Dependency of the `CompareTest` to the `Test` generating output has been added

**Comment by jcfr** [comment]
Looking at the associated issue [#4025](http://www.na-mic.org/Bug/view.php?id=4025), let's note that the test only confirm that module work for `.vtk` file. A similar test should be added for '.vtp' input.

**Comment by zhangfanmark** [comment]
Hi @jcfr , yes, I will add a test for vtp and will submit it shortly. 

Thanks.

**Comment by jcfr** [comment]
Great. Thanks for the follow up.

**Comment by jcfr** [comment]
And no particular rush .. this will be integrated after the release.

**Comment by zhangfanmark** [comment]
Hi @jcfr 

Just had a check of the commit https://github.com/Slicer/Slicer/commit/6061a14d1a80465b3ef614ec613226504041b012 . A wrong email address was assigned to me. Could you take a look? Mine should be zhangfanmark@gmail.com

Thanks.

**Comment by jcfr** [comment]
I was wondering what was the veggie domain ... I added a note on our document when we will transition from SVN to pure-git. 
See http://wiki.slicer.org/slicerWiki/index.php/Documentation/Labs/TransitionToGit#Authorship

In the mean, make sure to configure your name and email. See https://help.github.com/articles/setting-your-email-in-git/ and

**Comment by zhangfanmark** [comment]
Thanks! I'll have a double check of the configuration.

Regards,
Fan

**Pull request closed without merging**
