### PR TITLE
COMP: use proper variable evaluation in SlicerExtensionCPack

### PR DESCRIPTION
**Pull request by ihnorton**
Should fix UKFTractography extension packaging due to using incorrect fixup script. Has been broken since 195c0d55.

See build error: http://slicer.cdash.org/buildSummary.php?buildid=875941

### CODE REVIEW

**Comment by ihnorton** [comment]
cc @ljod @yrathi

**Comment by ihnorton** [comment]
To clarify, this is necessary because UKFTractography uses `UKFTractography_SUPERBUILD` as an `option`, so it is always defined.

**Comment by ihnorton** [comment]
(CI non-failure due to this changing CMake file)

**Comment by jcfr** [comment]
Thanks for the patch

Integrated in [r25303](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25303)

**Comment by ihnorton** [comment]
Looks good now, thanks: http://slicer.cdash.org/buildSummary.php?buildid=876325

**Pull request closed without merging**
