### PR TITLE
Fix color logic build link error

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by msmolens** [comment]
On Visual Studio 2013 it's necessary to add the following to vtkMRMLColorLogic.cxx:

    #include <functional>

to fix the following errors:

    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1452): error C2039: 'not1' : is not a member of 'std'
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1452): error C2039: 'ptr_fun' : is not a member of 'std'
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1452): error C2065: 'ptr_fun' : undeclared identifier
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1452): error C2062: type 'int' unexpected
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1454): error C2039: 'not1' : is not a member of 'std'
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1454): error C2039: 'ptr_fun' : is not a member of 'std'
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1454): error C2065: 'ptr_fun' : undeclared identifier
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1454): error C2062: type 'int' unexpected
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1452): error C3861: 'not1': identifier not found
    C:\path\to\Slicer\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1454): error C3861: 'not1': identifier not found

**Comment by fedorov** [comment]
Confirmed that this branch, together with the include suggested by @msmolens, builds fine on mac

**Comment by naucoin** [comment]
Apologies for the radio silence, I've been trying to update my windows build environment so I can work on this as well. Thanks for all the help!

**Comment by jcfr** [comment]
Thanks @fedorov and @msmolens 

I integrated all the validated fix so far in [r24750](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24750) and [r24751](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24751)

The last issue remaining is the link error. No closing this PR.

**Comment by lassoan** [comment]
I'll commit a fix for the link error soon. The problem was that the export macro should be placed _after_ the struct keyword.

**Comment by lassoan** [comment]
Fix committed into the trunk.

**Comment by fedorov** [comment]
thank you Andras! :+1:

**Comment by naucoin** [comment]
Thank you @lassoan !!!

**Pull request closed without merging**
