### PR TITLE
COMP: CompareVolumes fix int division add features

### PR DESCRIPTION
**Pull request by pieper**
Mainly addresses: https://github.com/pieper/CompareVolumes/commit/381f9eb134b006b6c13b97a15a8c5ef111dedcf0

### CODE REVIEW

**Comment by jcfr** [comment]
Or we could just update it while doing a "Squash and merge"

**Comment by pieper** [comment]
Okay, if you insist! 😉  

Actually don't merge this right now anyway since I'm adding some more changes since I'm in the code anyway

**Comment by jcfr** [comment]
> re: WIP

You should be able to mark the PR as "draft", there is a link on the top right under Reviewers:

image

**Comment by pieper** [comment]
@jcfr the latest commit message https://github.com/Slicer/Slicer/pull/5152/commits/016ebf1b0192d5ede02235eecb3da3098650f2c5 can be used for the squash and merge message.

**Comment by lassoan** [comment]
Is this ready to be merged?

**Comment by pieper** [comment]
Yes, it would be great to merge it.

**Pull request merged**
