### PR TITLE
Improve versioning and distinguish nightly shortcuts

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by pieper** [comment]
LGTM.  I'll be happy to test any resulting installers.

**Comment by jcfr** [comment]
Thanks @pieper 

Since the function `isRelease` is removed, here is the corresponding migration guide explaing that `releaseType` should be used. See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide /Slicer#Slicer_4.8:_Application:_isRelease.28.29_function_not_available

In a follow up PR, I will add the version info to `Slicer.app` on macOS. We will have something like `Slicer-X.Y.Z.app` for stable build and `Slicer-X.Y.Z-YYYY-MM-DD.app`

**Comment by jcfr** [comment]
Integrated in [r26419](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26419) to [r26422](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26422)

**Comment by pieper** [comment]
Tested today's nightly on windows and it works great; big improvement!

**Comment by jcfr** [comment]
Great. Thanks for the feedback.

As a side note, I revert the change updating the macOS package since it prevented the packaging from happening

**Pull request closed without merging**
