### PR TITLE
COMP: update VTK8 git tag

### PR DESCRIPTION
**Pull request by Punzo**
Including Clinck and Drag modification made in VTK: https://gitlab.kitware.com/vtk/vtk/merge_requests/3160

This is necessary for https://github.com/Slicer/Slicer/pull/770

### CODE REVIEW

**Comment by Punzo** [comment]
I tried to compile, but I get the following error:

fatal: reference is not a tree: f3e5b343f293c980d0acf5a34798d7f19dd0fd56
CMake Error at VTKv8-prefix/tmp/VTKv8-gitclone.cmake:75 (message):
  Failed to checkout tag: 'f3e5b343f293c980d0acf5a34798d7f19dd0fd56'

Just changing the git tag is not enough?

**Comment by fedorov** [comment]
I believe Slicer is using a patched version of VTK (see https://github.com/Punzo/Slicer/blob/9237f66b8d98cef53b80be5f2eb9065006224784/SuperBuild/External_VTKv8.cmake#L117), and you are probably referring to a commit in the upstream VTK.

**Comment by Punzo** [comment]
thanks @fedorov, I really I didn't notice (: ok thanks

**Comment by jcfr** [comment]
I will update Slicer VTK8 now.

(Note that the feature will be available when building Slicer with Qt5 + VTK8)

**Comment by Punzo** [comment]
ok, thanks Jc. Yeap, that's fine for now. At the moment the binaries are built still with QT4 + VTK7, aren't they?

**Comment by jcfr** [comment]
> At the moment the binaries are built still with QT4 + VTK7, aren't they?

Yes.

After we complete the current release cycle (to be announced shortly), we will switch the trunk to build against Qt5 + VTK8

**Comment by Punzo** [comment]
ok, great !!!

**Comment by hina-shah** [comment]
@jcfr : Aah! the folder that compiles VTK in master is named VTKv8, even though it compiles vtk7. Which confused me for a while. I understand this might be intentional for the future switch though. Would it be worth changing the name of the directory?

**Comment by lassoan** [comment]
I agree that it is confusing but I'm not sure if it's worth the effort to change the current behavior, as we'll move to VTK8 in a few weeks.

**Comment by jcfr** [comment]
Apologize for the confusion.

This was an side effect of adding External_VTKv8 file with support for both version. And as mentioned by Andras, since we will transition soon, it is not worth the hassle of updating it.

**Comment by jcfr** [comment]
VTKv8 version updated in [r26375](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26375)

**Comment by jcfr** [comment]
@Punzo  If you would like to see your latest VTKv8 contribution in the current Slicer build based of VTKv7, you should consider backporting kitware/VTK@14dfc51 on top of branch [Slicer/VTK@slicer-v7.1.0-2016-09-23-3b13ad9](https://github.com/Slicer/VTK/tree/slicer-v7.1.0-2016-09-23-3b13ad9)

**Comment by Punzo** [comment]
HI @jcfr thanks! OK. Well updating Slicer/VTK@slicer-v7.1.0-2016-09-23-3b13ad9 can be worth to do only if we want to integrate https://github.com/Slicer/Slicer/pull/770 now and having it in the stable release. Please let me know: in the positive case, I'll update Slicer/VTK@slicer-v7.1.0-2016-09-23-3b13ad9 between today and tomorrow.

**Comment by Punzo** [comment]
done in https://github.com/Slicer/VTK/pull/14 @jcfr

**Comment by jcfr** [comment]
VTKv7 version updated in [r26379](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26379)

**Comment by Punzo** [comment]
Ok, thanks. can https://github.com/Slicer/Slicer/pull/770 be integrated, now? or I need to rebase to the master?

**Pull request closed without merging**
