### PR TITLE
STYLE: SegmentEditorPaintEffect: Minor simplification to ease code reading

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by lassoan** [comment]
Looks good (probably this code was written before the GetWorldToImageMatrix convenience method was added).

**Comment by lassoan** [comment]
Are you going to merge it?

**Comment by jcfr** [comment]
> Are you going to merge it?

Yes. Thanks for looking

**Comment by jcfr** [comment]
Integrated in [r25598](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25598)

**Pull request closed without merging**
