### PR TITLE
Updates for editor per structure section

### PR DESCRIPTION
**Pull request by mehrtash**
regular expression fails to match expressions with special characters. Structures created for volume nodes containing parentheses and brackets would not show up in structures table.
fnmatch can match expressions containing these characters.

### CODE REVIEW

**Comment by mehrtash** [comment]
@pieper @fedorov @jcfr 
I'm trying to fix some identified issues in per-structure part of the editor module. I will add more commits to this pull request I could fix the others.

**Comment by fedorov** [comment]
+1

As the background, this is one of the issues we identified while trying to use Editor per-structure functionality in a radiology workflow. The specific bug Alireza fixed here made it impossible to add structures for a master volume that had parentheses in the node name.

**Comment by mehrtash** [comment]
@jcfr Done. :white_check_mark:

**Comment by pieper** [comment]
Looks good to me.  If I were writing the code today I would have used
fnmatch instead of re anyway.  It's just more readable for most cases.
Thanks!

**Comment by fedorov** [comment]
Any objections for these changes to be integrated?

**Comment by pieper** [comment]
Confirmed - those all look fine.  Thanks!

**Comment by jcfr** [comment]
+1 LGTM

After fixing the typo in the commit message, please integrate.
Jc

On Thu, Mar 12, 2015 at 10:07 AM, Steve Pieper <notifications@github.com>
wrote:

> Confirmed - those all look fine. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/245#issuecomment-78485477>.
>



-- 
+1 919 869 8849

**Comment by fedorov** [comment]
Committed in r24061 http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24061

I thought "git svn dcommit" will add the author in the commit message, but apparently it doesn't. Very sorry there is no credit to Alireza in the commit message...

**Comment by jcfr** [comment]
Hi Andriy,

You should use:

git svn dcommit --add-author-from

See link "Integrate topic from external contributor" in the "Source How-to"
on the right on the developer wiki:


http://www.slicer.org/slicerWiki/index.php/Slicer:git-svn#Integrating_topic_from_external_contributor


All of that said, I added the commit to the list that need authorship
adjustment.  We will consider them when transitioning to git:


http://www.slicer.org/slicerWiki/index.php/Documentation/Labs/TransitionToGit#Authorship


Hth
Jc

On Thu, Mar 12, 2015 at 4:12 PM, Andrey Fedorov <notifications@github.com>
wrote:

> Committed in r24061
> http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24061
>
> I thought "git svn dcommit" will add the author in the commit message, but
> apparently it doesn't. Very sorry there is no credit to Alireza in the
> commit message...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/245#issuecomment-78595247>.
>



-- 
+1 919 869 8849

**Comment by fedorov** [comment]
> We will consider them when transitioning to git

Great, thanks! 

I think it would help if there was centralized merging of the proposed commits. I imagine it can even be done by a robot, once the branch is ready for merge. This would help with reducing the time to commit and support uniformity of the commit process.

**Comment by jcfr** [comment]
Streamlining the process would be good. We will get there.

In the mean time, I don't mind integrating PR.

On Thu, Mar 12, 2015 at 4:21 PM, Andrey Fedorov <notifications@github.com>
wrote:

> We will consider them when transitioning to git
>
> Great, thanks!
>
> I think it would help if there was centralized merging of the proposed
> commits. I imagine it can even be done by a robot, once the branch is ready
> for merge. This would help with reducing the time to commit and support
> uniformity of the commit process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/245#issuecomment-78599699>.
>



-- 
+1 919 869 8849

**Comment by fedorov** [comment]
Ok, thanks - it would be very helpful, at least for me!

**Pull request closed without merging**
