### PR TITLE
ENH: Made view axis labels configurable

### PR DESCRIPTION
**Pull request by lassoan**
For some applications standard left/right, posterior/anterior, inferior/superior axis labels are not optimal. For example for eye image analysis temporal/nasal labels are more appropriate than left/right.
Labels may have to be view-specific, e.g., show standard labels on a large overview image and show custom labels in a view that shows a small segmented structure.

Implemented solution:
* vtkMRMLAbstractViewNode stores axis labels (SetAxisLabel/GetAxisLabel methods can be used to set/get the labels)
* vtkMRMLViewDisplayableManager and vtkMRMLOrientationMarkerDisplayableManager read labels from vtkMRMLAbstractViewNode instead of using hard-coded strings to show in Cube and Axes orientation markers and 3D cube labels
* DataProbe read labels from vtkMRMLAbstractViewNode instead of using hard-coded string

No user interface is implemented, as this is an advanced feature for module developers. Example use:

```
sliceNode = slicer.mrmlScene.GetNodeByID('vtkMRMLSliceNodeRed')
sliceNode.SetOrientationMarkerType(slicer.vtkMRMLAbstractViewNode.OrientationMarkerTypeAxes)
sliceNode.SetOrientationMarkerSize(slicer.vtkMRMLAbstractViewNode.OrientationMarkerSizeLarge)
sliceNode.SetAxisLabel(0,'Proximal')
sliceNode.SetAxisLabel(1,'Distal')

viewNode = slicer.mrmlScene.GetNodeByID('vtkMRMLViewNode1')
viewNode.SetOrientationMarkerType(slicer.vtkMRMLAbstractViewNode.OrientationMarkerTypeAxes)
viewNode.SetOrientationMarkerSize(slicer.vtkMRMLAbstractViewNode.OrientationMarkerSizeLarge)
viewNode.SetAxisLabel(0,'Proximal')
viewNode.SetAxisLabel(1,'Distal')
```

### CODE REVIEW

**Comment by lassoan** [comment]
@Punzo Could you please check if this is useful for you and if you have any related requests?

**Comment by Punzo** [comment]
Hi this is a very nice patch! It was in my to do list, so yes it is definitively useful for me. 

For my purpose the patch works as it is.

I agree regarding the interface: any extension should provide its own modification.
 
For example, for the axis labels on the qMRMLThreeDViewControllerWidget, the extensions have to provide a modification of the ctkAxesWidget. This should be possible overriding the method createViewFromNode using the ViewFactory (so allocating a new custom qMRMLThreeDViewControllerWidget).

Maybe, can be useful for other people to write something in the documentation regarding all of this?

**Comment by lassoan** [comment]
Integrated into rev 24961

**Comment by jcfr** [comment]
Thanks :+1:

**Pull request closed without merging**
