### PR TITLE
DOC: Update ReadTheDocs style

### PR DESCRIPTION
**Pull request by jcfr**
Remaining work:
* [x] include logo. See https://github.com/Slicer/Slicer/pull/5113#issuecomment-676471002
* [x] address remaining style issues

Logo preview from @faiza-a original design work directly updating the html/css:

image

It turns out that the [html_logo settings](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_logo) in sphinx documentation does not allow to directly update the exact location.  This is not a problem.

Questions:

* @faiza-a: In commit 9de6fc1 I fixed the height/width of the logo to be 64/64 ... is there a better way to achieve this ? (e.g an approach compliant with reactive website)

### CODE REVIEW

**Comment by jcfr** [comment]
Remaining issues:

_The purpose of these screenshots is too illustrate the problem that should be addressed across the documentation._

* too wide spaces between lines.

image

image

image


* Padding at the bottom is two thick:

image

Source: https://slicer--5113.org.readthedocs.build/en/5113/developer_guide/slicer.html#module-slicer.util

**Comment by jcfr** [comment]
Last commit is adding the logo:

image

need to add styling to ensure the size is correct

**Comment by jcfr** [comment]
Updated custom css to fix width/height of logo:

image

**Comment by jcfr** [comment]
>* @faiza-a: In commit 9de6fc1 I fixed the height/width of the logo to be 64/64 ... is there a better way to achieve this ? (e.g an approach compliant with reactive website)

Logo seems to be displayed properly on mobile: 

image

**Comment by faiza-a** [comment]
> Remaining issues:
> 
> _The purpose of these screenshots is to illustrate the problem that should be addressed across the documentation._
> 
> * too wide spaces between lines.
> 
> image
> 
> image
> 
> image
> 
> * Padding at the bottom is two thick:
> 
> image
> 
> Source: https://slicer--5113.org.readthedocs.build/en/5113/developer_guide/slicer.html#module-slicer.util

working on it

**Pull request merged**
