### PR TITLE
Update SimpleITK version to past 1.0.0

### PR DESCRIPTION
**Pull request by blowekamp**
This update to SimpleITK contains the 1.0.0 release, several CMake
related patches on the release branch, plus a patch to enable building
debug SimpleITK against release python for Windows.

### CODE REVIEW

**Comment by blowekamp** [comment]
@lassoan This should work in debug mode now for windows. SimpleITK should always be shared by default on windows. The libraries are going to be very large.

**Comment by lassoan** [comment]
Thank you. I've started Windows builds in debug and release modes.

**Comment by lassoan** [comment]
There were no build errors in either release or debug mode but in debug mode I don't see Simple Filters module in debug mode and import SimpleITK fails:

```
import SimpleITK
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\D\S4Dsi\python-install\Lib\site-packages\SimpleITK\__init__.py", line 1, in <module>
    from .SimpleITK import *
  File "C:\D\S4Dsi\python-install\Lib\site-packages\SimpleITK\SimpleITK.py", line 21, in <module>
    _SimpleITK = swig_import_helper()
  File "C:\D\S4Dsi\python-install\Lib\site-packages\SimpleITK\SimpleITK.py", line 20, in swig_import_helper
    return importlib.import_module('_SimpleITK')
  File "C:\D\S4Dsi\python-install\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _SimpleITK

```
I start a clean build.

**Comment by blowekamp** [comment]
Hmm... Not much to go on. For you output, SimpleITK was installed into the python site-package directory.

What is the content of "C:\D\S4Dsi\python-install\Lib\site-packages\SimpleITK\"? Does it contain the shared library "_SimpleITK.pyd"?

SimpleITK is always build with shared libraries on windows, so I would not expect this to differ between release and debug modes.

With this revision of SimpleITK, the shared libraries have been renamed from libSimpleITKBasicFilters{##} to libSimpleITK_{ITK_MODULES_NAME}. This should be installed into Slicer as well... I'm not sure the proper location on windows.

**Comment by lassoan** [comment]
I've started a clean build, maybe it'll help. If not then I'll write you the info you asked for.

**Comment by lassoan** [comment]
Starting the build from scratch made it work! So, this version works well on Windows, both in debug and release mode. It'll make it much easier to debug projects that use modules depending on SimpleITK. Thanks a lot for working on this.

**Comment by blowekamp** [comment]
That is great news! I have merged the patch which enables windows debug mode into SimpleITK's release branch. It it will be included in the 1.0.1 patch release at the end of the month.

Thank you for testing this! I did not know this feature was needed to debug ITK/SimpleITK code itself. I am glad it is useful. Also note that filters have a "Debug" parameter which prints the ITK filter state before execution. Contributions to SimpleITK are welcome. We have moved to a Github workflow for issues and pull request now, so hopefully it is easier than the separate resources before.

**Comment by jcfr** [comment]
Integrating now and rebuilding docker images.

**Comment by jcfr** [comment]
As soon as my local build complete, I will integrate.

**Comment by jcfr** [comment]
Integrated in [r26010](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26010)

**Pull request closed without merging**
