### PR TITLE
BUG: Fix Segment Editor Undo/Redo by reverting r28672

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Changing the way that lablemap representations were copied broke the Undo/Redo functionality.
Copying segments between segmentations will still need to be fixed, however it is less important than Undo/Redo.

### CODE REVIEW

**Comment by jcfr** [comment]
Good catch. Is there a test that can be updated to capture regression associated with undo/redo ?

**Comment by Sunderlandkyl** [comment]
Probably one of the vtkSegmentationTest could and should be updated to test undo/redo.
I'll start working on it.

**Comment by jcfr** [comment]
> could and should be updated to test undo/redo.
I'll start working on it.

Thanks for working on this :pray:

**Comment by lassoan** [comment]
Thank you, merged.

**Pull request closed without merging**
