### PR TITLE
BUG: Corection of the ExtensionWizard "compare URL" generation

### PR DESCRIPTION
**Pull request by jbvimort**
The extensionWizard now handel the creation of the "Compare URL" when somoene contribute to the Extension Description File using Extension Wizard

### CODE REVIEW

**Comment by jcfr** [comment]
@jbvimort  Thanks for your contribution. Looks good :+1: 

Before integrating your change, could you provide the step allowing to reproduce the issue you fixed ? That would allow me to provide more details in the commit message.

**Comment by jbvimort** [comment]
Of course!

The issue appear when you try to use the ExtensionWizard to Contribute to
the Extension Description file has it is indicated in the following command
line: $ bin/slicerExtensionWizard --contribute ~/src/Slicer-MyExtension/

This error appear:

building compare URL for update

failed to build compare URL: 404 {u'documentation_url':

u'https://developer.github.com/v3/repos/commits/#compare-two-commits',

u'message': u'Not Found'}


The modification in this commit fixed that, and the ExtentionWizard now
create the compare URL>

**Comment by jcfr** [comment]
@jbvimort Using the latest version of Slicer, I tried to reproduce the problem using the following steps and wasn't able to get the error you reported. See https://github.com/Slicer/ExtensionsIndex/pull/1134

Here are the steps:

* Step1:

```
$ ./bin/slicerExtensionWizard --create Slicer-MyTestExtension --addModule cli:MyTestCLI  ~
[...]
```

* Step2:

```
jcfr@karakoram:Slicer-build $ ./bin/slicerExtensionWizard --publish ~/Slicer-MyTestExtension/
creating github repository
[...]
updating extension meta-information
[...]
```

* Step3:

```
jcfr@karakoram:Slicer-build $ ./bin/slicerExtensionWizard --contribute ~/Slicer-MyTestExtension/
[...]
creating pull request
created pull request https://github.com/Slicer/ExtensionsIndex/pull/1134
```

Note that I updated your commit message in a new commit https://github.com/jcfr/Slicer/commit/96aea4891c9d67206a31437cd2fc60ab78e657d9 available on branch [381-update-ExtensionWizard](https://github.com/jcfr/Slicer/tree/381-update-ExtensionWizard) published on my fork.

Here is the commit message:
```
 BUG: ExtensionWizard: Fix "compare URL" generation

The extensionWizard now handles the creation of the "Compare URL" when someone
contributes a new Extension Description File using Extension Wizard.

The issue appeared when using the ExtensionWizard as reported below:

$ bin/slicerExtensionWizard --contribute ~/src/Slicer-MyExtension/

The reported error was:

//------------
building compare URL for update failed to build
compare URL: 404 {u'documentation_url':
u'https://developer.github.com/v3/repos/commits/#compare-two-commits';,
u'message': u'Not Found'}
//------------
```

What is not clear is this section `[...] when someone contributes a new Extension Description File using Extension Wizard [...]` ... are you sure the problem happen when a *new* extension description file is submitted ?

**Comment by jbvimort** [comment]
Sorry, my bad!

This error appear when someone contribute to an extension file that already exist (the URL that allow other users to see differences between the two versions of the extension code is not generated). But when someone create a new extension file I don't think this URL is created.

So, no, its not when  a new extension description file is submitted, but when an extension description file that already exist is updated.

Is that more clear?

**Comment by jcfr** [comment]
Integrated in [r24667](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24667)

**Pull request closed without merging**
