### PR TITLE
Update to VTK 7

### PR DESCRIPTION
**Pull request by msmolens**
This updates Slicer to use VTK 7.

See:
- https://www.slicer.org/slicerWiki/index.php/Documentation/Labs/VTK7.
- http://massmail.spl.harvard.edu/public-archives/slicer-devel/2016/040450.html

### CODE REVIEW

**Comment by jcfr** [comment]
@msmolens Outstanding work 

Cc: @Slicer/slicer-core @pieper  @lassoan

**Comment by msmolens** [comment]
Integrated in [r25219](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25219) to [r25227](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25227).

**Comment by jcfr** [comment]
Congrats :+1:

**Comment by jcfr** [comment]
Congrats :+1:

**Comment by thewtex** [comment]
Way to go!

**Comment by pieper** [comment]
Nice!

**Pull request closed without merging**
