### PR TITLE
Update ITK from v4.13 to v5.0rc1, BRAINSTools and SimpleITK [ci skip]

### PR DESCRIPTION
**Pull request by jcfr**
To help extension developers transition their code base, a migration guide is also
available on the wiki.
See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide/ITK4-to-ITK5

This commit implements the following changes

- Compatibility with refactor of threading models in ITK: Fix compilation
  using ProcessingThreader class instead of PlatformMultiThreader.
  ITKv5 reorganized the multi-threading capabilities of ITK into a more modular organization
  and naming to support several modern parallelism paradigms.

  Note that these changes allow Slicer to compile with ITKv5, but does not take advantage
  of any enhancement supporting new threading models. ProcessingThreader
  is still the old-renamed PlatformMultiThreader.

  These changes were originally associated with PR https://github.com/Slicer/Slicer/pull/1057

- Fix compilation issue related to ComputeJacobianWithRespectToPosition parameter mismatch.

  ITKv5 change the argument of some transform functions from JacobianType to JacobianPositionType.
  This fixes the new signatures.

  These changes were originally associated with PR https://github.com/Slicer/Slicer/pull/1055

List of BRAINSTools changes:

```
$ git shortlog --no-merges b045970..ac4dafaa

[...]
```

List of SimpleITK changes:

```
$ git shortlog --no-merges v1.1.0..dc5c1a1d

[...]
```

List of ITK changes:

```
```

Co-authored-by: Pablo Hernandez-Cerdan <pablo.hernandez.cerdan@outlook.com>
Co-authored-by: Hans Johnson <hans.j.johnson@gmail.com>
Co-authored-by: Sam Horvath <sam.horvath@kitware.com>
Co-authored-by: Jean-Christophe Fillion-Robin <jcfr@kitware.com>

### CODE REVIEW

**Comment by phcerdan** [comment]
SimpleITK major change lists from 1.1 and 1.2 for Slicer:
More information at: https://github.com/SimpleITK/SimpleITK/releases
- Compatibility with ITKv5
- New Filters: ObjectnessMeasuresImageFiler (Frangi's vesselness), IterativeInverseDisplacementFieldImageFilter, UnsharpMaskImageFilter, and RoundImageFilter.
- Multi-resolution BSpline registration by adapting the BSplineTransform resolution in the ImageRegistrationMethod
- Added support for multi-component images to ClampImageFilter, MeanProjectionImageFilter, SumProjectionImageFilter, and the TileImageFilter.

ITK major change lists from 4.13 to 5.0rc1:
More information at: https://github.com/InsightSoftwareConsortium/ITK/releases
- Completed transition to modern features introduced in c++11
- Third Parties updated and full support for new ones, such as DCMTK and Eigen3.
- Multiple performance improvements:
  - N4BiasFieldCorrectionImageFilter accelerated through itk::ImageBufferRange and other optimizations.
  - Various modern C++ improvements related to default constructors and move operations.
  - ResampleImageFilter::CastPixelWithBoundsChecking is now faster.
  - Data copies in itk::BSplineTransform were reduced.
  - The number of evaluations in line search optimizer were reduced by half.
  - CanRead is now faster for inspection of potential DICOM files, both with the GDCM and DCMTK DICOM backends.
- Added Frequency Domain Support for working with images in the dual domain, such as the output of FFT images.
- A new Simple Linear Iterative Clustering (SLIC) super-pixel segmentation filter is available.

BRAINSTools major change lists:
- Completed transition to modern features introduced in c++11
- Update of third-party libraries
- Mutliple minor bug fixes and new features

**Comment by jcfr** [comment]
Thanks @phcerdan 

> BRAINSTools .. and new features

Is there anything worth mentioning from a Slicer perspective ? 

Also is there any performance improvements ?

**Comment by phcerdan** [comment]
> Is there anything worth mentioning from a Slicer perspective ?
  Also is there any performance improvements ?

I am going to ask for help to @hjmjohnson for the major change list of BRAINSTools, not sure what are the most relevant ones for Slicer.

**Comment by jcfr** [comment]
Closing. Integrated in [r28016](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28016)

**Pull request closed without merging**
