### PR TITLE
ENH: update filetype for recent changes.

### PR DESCRIPTION
**Pull request by ihnorton**
WIP pending @lassoan fix for issue discussed in https://github.com/Slicer/Slicer/commit/cfdf8cc590450e5bcbe13b75c9cc6a9b5019883e#commitcomment-18997559

cc @naucoin regarding 	a2df48b

### CODE REVIEW

**Comment by ihnorton** [comment]
(CI failure because docker image doesn't have VTK update)

**Comment by jcfr** [comment]
Nice.

Would you mind adding a doxygen or some comment in the code for `GetFileExtensionFromFormatString`. Basically, providing few examples of extension-only vs test+extension string.

Thanks

**Comment by jcfr** [comment]
`GetFileExtensionFromFormatString` is also a good candidate for few unit tests

**Comment by ihnorton** [comment]
> Would you mind adding a doxygen or some comment in the code for GetFileExtensionFromFormatString. Basically, providing few examples of extension-only vs test+extension string.

✔️ 

Per @lassoan we don't want people to use the extension-only format, this fix is just for backward-compatibility. Hence the warning.

> GetFileExtensionFromFormatString is also a good candidate for few unit tests

✔️

**Comment by jcfr** [comment]
> (CI failure because docker image doesn't have VTK update)

New image has been pushed, feel free to restart the build.

**Comment by lassoan** [comment]
Thank you! I've tested, slightly tuned, and merged the changes into the trunk (rev 25358-25360).

**Pull request closed without merging**
