### PR TITLE
ENH: Support restoring SliceViewAnnotations enabled state

### PR DESCRIPTION
**Pull request by jcfr**
Also simplify setting of checkbox state in SliceViewAnnotations

----

This pull request was created while working on this issue:
* https://github.com/Slicer/Slicer/issues/7092

### CODE REVIEW

**Comment by jcfr** [comment]
## CheckLists

* [ ] No error after deleting main settings file, starting Slicer and selecting DataProbe
* [ ] Start Slicer, set display level, exit and restart. Confirm value is restored
* [ ] Start Slicer, click on "Restore Default"

@lassoan @pieper  Any reason we should not save/restore the `displayLevel` ?

**Comment by jcfr** [comment]
## CheckList

**Status:** Updated topic works as expected

* [x] No error after deleting main settings file, starting Slicer and selecting DataProbe
* [x] Start Slicer, disable, exit and restart. Confirm UI is still disabled
* [x] Click on "Restore Default"

**Comment by jcfr** [comment]
@lassoan @pieper  Any reason we should not restore the `enabled` state as well ?

**Comment by pieper** [comment]
> @lassoan @pieper Any reason we should not restore the `enabled` state as well ?

I'm not sure without looking in more detail but if you think it should be restored then I'm okay with it.

**Comment by lassoan** [comment]
Slice view annotations is a mess. It was a quick prototype that got integrated to have this important feature in Slicer, but the design is really fragile and limited. We would need to rebuild it from scratch, using proper MRML-based design and flexibility and extensibility in mind, as overlay on image corners is very important space for displaying information.

**Comment by pieper** [comment]
Many viewers also use these as UI controls/widgets too (e.g. control reslice rotation or window/level tools by clicking on the corresponding corner annotation can be logical and discoverable).

**Comment by jcfr** [comment]
## CheckList

**Status:** Updated topic works as expected

* [x] No error after deleting main settings file, starting Slicer and selecting DataProbe
* [x] Start Slicer, disable, exit and restart. Confirm UI is still disabled
* [x] Click on "Restore Default"

**Review by sjh26 — APPROVED** [review]
lgtm

**Pull request merged**
