### PR TITLE
Fix documentation urls in module panel

### PR DESCRIPTION
**Pull request by jcfr**
The following topic will ensure the expected wiki URL are displayed in the module panel help.

### CODE REVIEW

**Comment by jcfr** [comment]
@lassoan @naucoin @pieper Thanks for reviewing.

**Comment by pieper** [comment]
Looks nice!

**Comment by jcfr** [comment]
Thanks for reviewing. I will integrate later this afternoon.

**Comment by lassoan** [comment]
Thanks, this looks good to me. I've just added a couple of comments to the code.
Also, one general comment: Currently in XML files we have "Documentation/4.4", which means that we need to update this for 4.6, 4.8, etc. => it would be simpler (and somewhat more consistent) to have "Documentation/Nightly" instead

**Comment by jcfr** [comment]
@lassoan Agreed. By default, existing CLI should reference the Nightly namespace. It means we need to:
- [ ] Add a comment in the code and commit msg explaining why the code as been added to the module planel.
- [ ] Update extension templates
- [ ] Add a note here: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Tutorials/DocumentModule#Documentation_for_a_CLI_module 

I will proceed to these update while working on integrating this topic.

**Comment by lassoan** [comment]
Great, these would be perfect!

**Comment by jcfr** [comment]
Integrated in [r24421](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24421), [r24422](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24422), [r24423](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24423) and [r24424](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24424)

**Pull request closed without merging**
