### PR TITLE
Update buildsystem to support packaging of existing extensions

### PR DESCRIPTION
**Pull request by jcfr**
Cc: @hina-shah

### CODE REVIEW

**Comment by hina-shah** [comment]
LGTM! Tested this for SlicerSALT as well on Linux, Mac and Windows.. No further changes needed.

**Comment by jcfr** [comment]
@hina-shah Thanks for the review. I just rebased and integrated your changes (https://github.com/jcfr/Slicer/pull/7). PTAL.

**Comment by hina-shah** [comment]
@jcfr : this looks good. Thanks!

**Comment by jcfr** [comment]
Thanks. Integrated in [r26021](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26021)

**Pull request closed without merging**
