### PR TITLE
ENH: Use common interactor style for slice and 3D views

### PR DESCRIPTION
**Pull request by lassoan**
Common interactor class is responsible for delegating interaction events to displayable managers (and if none of the displayable managers can process an event then emit an interaction event).

Translation from interaction event to camera manipulation events is not hardcoded anymore in the interactor style but it is moved to vtkMRMLCameraWidget.

Added support for double-click events in the interactor.

Added menu (right-click) and action (double-click) events to widgets. They are not handled yet in Slicer core.

### CODE REVIEW

**Comment by lassoan** [comment]
@Sunderlandkyl I've integrated your https://github.com/Slicer/Slicer/pull/1122 PR into this one. Could you please test if the Mac touchpad gestures still work?

**Comment by lassoan** [comment]
Merged in r28095

**Comment by cpinter** [comment]
Nice! We can maybe make the right-click interaction pick a node and show a subject hierarchy context menu for the picked node. It should be quite easy to do.

**Comment by pieper** [comment]
Looks great! 👍 

+100 for subject hierarchy context menu in the viewers.

**Comment by lassoan** [comment]
We are very close to being able to show SH menu. I have all the pieces just need to put it together.

**Comment by jcfr** [comment]
@lassoan Could update the migration guide to document the class renames ? See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide#Slicer_backward_incompatible_changes

**Pull request closed without merging**
