### PR TITLE
ENH: Enable markup preview when holding shift key

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Allows markups (and other widgets) to process events when the crosshair position is being changed with shift + mouse move.
This is done by processing ActionSetCrosshairPosition in CanProcessInteractionEvent, rather than ProcessInteractionEvent.

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
Thank you, this is good. I've also tested and it works very intuitively. I added a few comments to explain the rationale behind our choices.

**Comment by lassoan** [comment]
I've just noticed one thing that we should change: Shift+MouseMove in place mode should work the same way in 3D views, too.

**Comment by Sunderlandkyl** [comment]
Thanks! I've updated the comments and added the same behavior to vtkMRMLCameraWidget.

**Review by lassoan — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
