### PR TITLE
ENH: ScreenCapture: Allow setting of max number of frame to capture.

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @hherhold  

Is it ok to have your contribution credited as Hollister Herhold <hherhold@Hollisters-MBP.fios-router.home> or would prefer something different ?

**Comment by hherhold** [comment]
Ah crud. Thought I fixed my config. "Hollister Herhold <hherhold@amnh.org>" is preferable. Sorry about that.

Thanks!

**Comment by jcfr** [comment]
Great. Thanks again for your contribution.

Integrated in [r](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26507) / https://github.com/Slicer/Slicer/commit/d9b890503730f8d06f3c166209e7986c9fd5a0ab

**Comment by lassoan** [comment]
Thank you @hherhold. I hope to see further contributions from you in the future!

**Comment by hherhold** [comment]
Thank you!

**Pull request closed without merging**
