### PR TITLE
BUG: Update Terminologies default color behavior

### PR DESCRIPTION
**Pull request by smrolfe**
This commit changes the default color assignment for Terminologies with modifiers. 

Currently if there is no modifier selected, the type is assigned the "invalid color", as discussed in this [forum post](https://discourse.slicer.org/t/terminologies-questions/27384/28) and [issue](https://github.com/Slicer/Slicer/issues/6972). This commit assigns the color of the first modifier to the type. This is the heuristic that is followed for the assignment of the color box displayed in the property type viewer.

### CODE REVIEW

**Comment by lassoan** [comment]
@smrolfe thanks a lot for working on this. The behavior should be to use the color, name, and terminology of the non-modified term. @cpinter what do you think?

**Comment by smrolfe** [comment]
@lassoan this would be best, but in the examples I've looked at, the non-modified term does not have a color specified: https://discourse.slicer.org/t/terminologies-questions/27384/24?u=smrolfe

**Comment by muratmaga** [comment]
> @smrolfe thanks a lot for working on this. The behavior should be to use the color, name, and terminology of the non-modified term. @cpinter what do you think?

@lassoan we can decorate our custom jsons with RGB properties for non-modified state. None of the the Slicer's bundled JSON files do that AFAIK. For our use case, L/R, L and R (or unmodified state) are going to have same color. So it is really up to you guys how to handle it. But even if you do add the RGBs, the bug is still there (see the issue here https://github.com/Slicer/Slicer/issues/6972).

**Review by cpinter — COMMENTED** [review]
Can you please describe the change in more detail in the commit message? I may be missing something but I don't understands what this fixes exactly and how. Thanks!

For consistency I'd use `this->CurrentTypeObject->GetRecommendedDisplayRGBValue` instead of `this->recommendedColorForType`, it will make the code more readable.

Also, invalid values need to be checked in every case.

Thank you!

**Comment by smrolfe** [comment]
> For consistency I'd use `this->CurrentTypeObject->GetRecommendedDisplayRGBValue` instead of `this->recommendedColorForType`, it will make the code more readable.

`this->recommendedColorForType` is an existing function that checks the colors assigned to the modifiers if no color was found for the type, and returns the first one found. It's used to create the color preview when the property type table is populated. 

I will update the pull request shortly with your suggestions, thanks @cpinter!

**Comment by smrolfe** [comment]
@lassoan @cpinter @muratmaga 

This pull request is ready for review.

**Pull request closed without merging**
