### PR TITLE
Change organization name and domain to slicer.org from Slicer

### PR DESCRIPTION
**Pull request by lassoan**
Commit https://github.com/Slicer/Slicer/commit/b0b9be57cb7d1a1e462143ec74e3d37d271d114d modified the organization name to Slicer from NA-MIC, which caused a name clash with the Slicer executable.

This commit changes the organization name to slicer.org. The final decision on the used organization name has not been made yet, this commit is a quick fix to resolve a blocking issue.

see https://github.com/Slicer/Slicer/issues/6878

We also change the organization domain name from www.slicer.org to slicer.org for consistency.

### CODE REVIEW

**Review by pieper — APPROVED** [review]
Thanks for the quick fix!  I think slicer.org will work well and I don't see any obvious better choice.

**Comment by pieper** [comment]
I'll let you merge - the commit name could be either BUG or ENH I guess.

**Comment by lassoan** [comment]
Thanks for the review, I'm merging it now.

**Comment by jcfr** [comment]
Thanks for addressing this. Using `slicer.org` consistently is a great idea.

**Comment by jamesobutler** [comment]
From the Control Panel programs and features area on Windows, marking the publisher as "slicer.org" is a unlike any of the other publisher names I have.
image
image

**Comment by lassoan** [comment]
Organization name in the installer (that shows up in your screenshots) could be a different string than the installation folder name, but I don't know if we want to complicate things (add another CMake variable, allow custom applications to override, add to the template, etc).

**Pull request merged**
