### PR TITLE
BUG: teach 'slicer_add_python_unittest' to add needed search paths

### PR DESCRIPTION
**Pull request by ihnorton**
ref http://www.na-mic.org/Bug/view.php?id=4242

cc @lassoan

### CODE REVIEW

**Comment by jcfr** [comment]
Commit  	e17bcbe (except removal of line in [SegmentEditor/CMakeLists.txt](https://github.com/Slicer/Slicer/pull/610/commits/e17bcbe3fb684406e421fedff9376dc9e786c65d#diff-9b1f032c84890bf02c0fdea14649da14) is now integrated as [r25550](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25550)

**Comment by ihnorton** [comment]
Rebased.

**Comment by vovythevov** [comment]
+1 !
I am writing an extension with python unittest testing and this fix makes it work.

**Comment by jcfr** [comment]
Fix rebased and forced pushed. After confirming CI is green, will be integrating.

**Comment by jcfr** [comment]
Integrated in [25783](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25783)

**Pull request closed without merging**
