### PR TITLE
ENH: Use inclusive language for segmentation source representation

### PR DESCRIPTION
**Pull request by adamaji**
See https://tools.ietf.org/id/draft-knodel-terminology-09.html#name-master-slave

This PR follows earlier work for using more inclusive language and removing usage of "master" in the code (https://github.com/Slicer/Slicer/pull/6277). It seems like this instance made it through?

Also, it's user facing:
image

Before I continue here:
- Is "main" an acceptable replacement in this context?
- Should I be following the deprecation of the earlier API changes as opposed to replacement? (Given that Slicer 5.0.x extensions are no longer being built?)

### CODE REVIEW

**Review by jamesobutler — COMMENTED** [review]
> Should I be following the deprecation of the earlier API changes as opposed to replacement? (Given that Slicer 5.0.x extensions are no longer being built?)

Yes you should mark them as deprecated here in Slicer like the others so that extensions have time to update and so they don't immediately start to fail when using the Slicer Preview. Once the code makes it into Slicer stable, then extensions could be updated to use the new value entirely as the latest versions of Slicer extensions often are only kept compatible with the latest Slicer stable and preview. For example https://github.com/lassoan/SlicerSegmentEditorExtraEffects/pull/53 was integrated because `setSourceVolume` exists in both the latest Slicer stable and preview.

**Comment by cpinter** [comment]
I have understood that now we call it source representation, at least
previous changes pointed to that direction. It is more descriptive of its
actual purpose than "main" as well I think.

**Review by jamesobutler — APPROVED** [review]
Thanks for your contribution. I have continued your work to update the terminology from `main` to `source` here and added the various deprecation warnings for changes to the public API.

I have confirmed things build successfully on Windows and that tests are still passing.

**Comment by jcfr** [comment]
To follow up on the integration, since we check for new warnings, the test ` py_nomainwindow_test_slicer_util_save` started to fail.

```
Warning: In /work/Preview/Slicer-0/Libs/MRML/Core/vtkMRMLSegmentationNode.h, line 222
vtkMRMLSegmentationNode (0x45032a0): vtkSegmentation::SetMasterRepresentationToBinaryLabelmap() method is deprecated, please use SetSourceRepresentationToBinaryLabelmap method instead
```

See https://slicer.cdash.org/test/24940170

The following pull request is updating the test:
* https://github.com/Slicer/Slicer/pull/7022

**Pull request merged**
