### PR TITLE
ENH: Update teem

### PR DESCRIPTION
**Pull request by jcfr**
```
$ git shortlog a0ae38a..b83e546 --no-merges
kindlmann (14):
      initial (broken) implementation of nrrdEncodingZRL, and adding nrrdSpaceRightUp and nrrdSpaceRightDown; both of which are reasons for using nrrd magic 6
      forgot to add this
      adding mysteriously missing dyeSpace airEnum, and a utility for command-line image space conversion
      added dieSpace
      whoa! key/value pairs were never saved correctly in plain text files!
      the road ahead
      long-overdue update to logic test after signed->unsigned change
      added airBitsSet
      comment about importance of large values for seekContext->pldArrIncr
      removing copy/paste code from gzip
      first pass at ZRL decompression
      fix from Adam J Shaw
      no need
      fixed bug caused by saving a 3D 1-by-X-by-Y array to an image format like PNG, with fields like space directions that can be usefully preserved in the image meta data: 3 space directions were saved in the image, not two.  This fix is a pretty simplistic one, but it is used in a very targeted way, so it seems safe

rjosest (23):
      fixing double/float precision warnings
      fixing double/float precision warnings
      COMP: Add try_compile to test AIR_EXISTS MACRO
      COMP: adapt to older version of libpng that's part of VTK 5.1
      COMP: Get rid of warnings.
      COMP: fix warning
      COMP: remove debug print from CMakeLists.txt
      COMP: Build/Install modernization
      STYLE: Convert CMake-language commands to lower case
      STYLE: Remove CMake-language block-end command arguments
      COMP: Fix cmake warnings
      STYLE: Remove end-of-line spaces to improve maintenance
      COMP: Update to cmake 2.8 compatibility.
      ENH: Prefer to use $<TARGET_FILE:tgt> for testing
      STYLE: Remove outdated cmake variable
      STYLE: Remove unnecessary conditionals for cmake 2.6
      COMP: Associate component with teem install rules
      COMP: Restore library output path to "lib" folder
      COMP: Prevent target double inclusion with older version of CMake
      COMP: Remove discardd qualifiers warning
      COMP: Remove compiler warnings
      COMP: Fixes a set-but-not-used warning
      COMP: Fixes array-bounds warnings that occur when using O2 optimization on GNUC compilers
```

### CODE REVIEW

**Comment by jcfr** [comment]
@pieper @hjmjohnson @ljod  Let me know if I should wait for [#3977](http://www.na-mic.org/Bug/view.php?id=3977#c13012) to be addressed before integrating this.

**Comment by jcfr** [comment]
@ljod Let me know if [ljod/Slicer@ca5080b](https://github.com/ljod/Slicer/commit/ca5080bd1c90cf7e941a2ec7703ed3a3800ce015?w=1) fixes the issue.

**Comment by pieper** [comment]
I believe that Slicer bug #3977 is independent of teem so no problem integrating the new version from that perspective.

Yes, I believe Lauren's change fixes the multithreading issue.

**Comment by ljod** [comment]
Yes I agree with Steve.

I'm not a super user of github--what should I do to get this change pushed
to the main slicer repository? I've made a few later commits in my repo
that do not belong in the slicer head at this point.
Lauren

Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by jcfr** [comment]
@ljod  The idea is to create a topic that only include the commit I referenced above. The steps would then be the following:
1. `git checkout 7f471a37d`  # This is the first commit that `ljod/Slicer/master` and `Slicer/Slicer/master` have in common
2. `git checkout -b 3977-dti-computation-not-reproducible` # Create a topic that will include your commit
3. `git cherry-pick ca5080b` # This "cherry-pick" you commit and adds it on the topic we just created
4. git push ljod 3977-dti-computation-not-reproducible # This publish your topic 
5. Go on http://github.com/ljod/Slicer and you should be able to create a Pull requests

I also noticed that your IDE settings modified the end of line for the entire file, moving forward would be good to avoid this. This two link illustrates it:
* Link ignoring space changes: https://github.com/ljod/Slicer/commit/ca5080bd1c90cf7e941a2ec7703ed3a3800ce015?w=1
* Link that do not ignore space change: https://github.com/ljod/Slicer/commit/ca5080bd1c90cf7e941a2ec7703ed3a3800ce015

For this one I could take care of it. 

Instead, would be great if you could spend some time to add a test that:
(a) would fail without your patch
(b) pass after your patch is included

To make things easier on your side, you could simply attach a batch file implementing this test. The batch file could invoke `cmake -E compare_files /path/to/image1 /path/to/image2`.

**Comment by ljod** [comment]
Thanks. Do you have an example batch script you could point me to?

On Tuesday, April 21, 2015, Jean-Christophe Fillion-Robin <
notifications@github.com> wrote:

> @ljod <https://github.com/ljod> The idea is to create a topic that only
> include the commit I referenced above. The steps would then be the
> following:
> 1. git checkout 7f471a37d # This is the first commit that
> ljod/Slicer/master and Slicer/Slicer/master have in common
> 2. git checkout -b 3977-dti-computation-not-reproducible # Create a topic
> that will include your commit
> 3. git cherry-pick ca5080b # This "cherry-pick" you commit and adds it on
> the topic we just created
> 4. git push ljod 3977-dti-computation-not-reproducible # This publish your
> topic
> 5. Go on http://github.com/ljod/Slicer <https://github.com/ljod/Slicer>
> and you should be able to create a Pull requests
>
> I also noticed that your IDE settings modified the end of line for the
> entire file, moving forward would be good to avoid this. This two link
> illustrates it:
>
>    - Link ignoring space changes: ljod@ca5080b?w=1
>    <https://github.com/ljod/Slicer/commit/ca5080bd1c90cf7e941a2ec7703ed3a3800ce015?w=1>
>    - Link that do not ignore space change: ljod@ca5080b
>    <https://github.com/ljod/Slicer/commit/ca5080bd1c90cf7e941a2ec7703ed3a3800ce015>
>
> For this one I could take care of it.
>
> Instead, would be great if you could spend some time to add a test that:
> (a) would fail without your patch
> (b) pass after your patch is included
>
> To make things easier on your side, you could simply attach a batch file
> implementing this test. The batch file could invoke cmake -E
> compare_files /path/to/image1 /path/to/image2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/262#issuecomment-94834452>.
>
> The information in this e-mail is intended only for the person to whom it
> is
> addressed. If you believe this e-mail was sent to you in error and the
> e-mail
> contains patient information, please contact the Partners Compliance
> HelpLine at
> http://www.partners.org/complianceline . If the e-mail was sent to you in
> error
> but does not contain patient information, please contact the sender and
> properly
> dispose of the e-mail.
>


-- 
Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by jcfr** [comment]
@ljod Simply implement the test in your favourite scripting language (bash, perl, python, cmake, ... ). I expect the script to return 0 if it succeed, return 1 (or greater) for failure. It could like this:

```
#! /usr/bin/env bash

/path/to/cli /path/to/some/input /path/to/some/output1
/path/to/cli /path/to/some/input /path/to/some/output2
cmake -E compare_file  /path/to/some/output1  /path/to/some/output2
[[ $? != 0 ]] && echo "Failed: output1 is expected to match output2" && exit 1
```

**Comment by jcfr** [comment]
Teem has been updated in Slicer trunk. See [r24185](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24185)

**Comment by jcfr** [comment]
There are issue on windows ...
See http://slicer.cdash.org/viewBuildError.php?buildid=425568

**Comment by jcfr** [comment]
Fixed in https://github.com/Slicer/teem/commit/e4746083c0e1dc0c137124c41eca5d23adf73bfa

Integrated in Slicer as of [r24187](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24187)

@hjmjohnson Would be great if you could work with Raul to get this integrated upstream.

It may also be worth looking at adding appveyor-ci and travis-ci continyous integration to teem.

**Pull request closed without merging**
