### PR TITLE
COMP: Fix link error when toggling Slicer_BUILD_WEBENGINE_SUPPORT

### PR DESCRIPTION
**Pull request by jcfr**
This commit ensures the `moc_*.cpp` and `moc_*.parameters` files are regenerated
when the option `Slicer_BUILD_WEBENGINE_SUPPORT` is toggled.

It address the following errors reported when setting `Slicer_BUILD_WEBENGINE_SUPPORT`
to ON after Slicer was first build with the option OFF:

```
  CMakeFiles/qMRMLWidgets.dir/qMRMLLayoutManager.cxx.o: In function `qMRMLLayoutChartViewFactory::qMRMLLayoutChartViewFactory(QObject*)':
  qMRMLLayoutManager.cxx:(.text+0x7b0): undefined reference to `vtable for qMRMLLayoutChartViewFactory'
  CMakeFiles/qMRMLWidgets.dir/qMRMLLayoutManager.cxx.o: In function `qMRMLLayoutManager::setMRMLColorLogic(vtkMRMLColorLogic*)':
  qMRMLLayoutManager.cxx:(.text+0x4c74): undefined reference to `qMRMLLayoutChartViewFactory::staticMetaObject'
  CMakeFiles/qMRMLWidgets.dir/qMRMLLayoutManager.cxx.o: In function `qMRMLLayoutManager::mrmlColorLogic() const':
  qMRMLLayoutManager.cxx:(.text+0x4d3f): undefined reference to `qMRMLLayoutChartViewFactory::staticMetaObject'
  collect2: error: ld returned 1 exit status
```
See https://discourse.slicer.org/t/build-error-linux/6738

### CODE REVIEW

**Comment by lassoan** [comment]
It would be nice to fix the MRML_WIDGETS_HAVE_WEBGINE_SUPPORT typo.

**Comment by jcfr** [comment]
> typo

Good catch. Indeed, I will do a first commit fixing the typo, and then the bug fixes for the link error

**Comment by gregsharp** [comment]
Testing now.   

Why would the option Slicer_BUILD_WEBENGINE_SUPPORT be toggled?  I am building from a fresh build tree and never touch that option.

**Comment by jcfr** [comment]
> Why would the option Slicer_BUILD_WEBENGINE_SUPPORT be toggled?

To clarify, if you do a clean build (with option Slicer_BUILD_WEBENGINE_SUPPORT set to ON (default) or OFF), there are no issues. Nightly builds (as well some of our custom Slicer app build) confirm this.

The problem arises in that case:
- do a clean build with Slicer_BUILD_WEBENGINE_SUPPORT either ON (default) or OFF
- toggle Slicer_BUILD_WEBENGINE_SUPPORT, then reconfigure. Problem happens at that time. I encountered the same problem yesterday in one of my build tree ... and I think this patch will address that.

**Comment by gregsharp** [comment]
It seems the problem is resolved with the patch.  Thank you!
But without the patch, I still reproduce the problem starting from a fresh build tree and I never touch the option.

**Comment by jcfr** [comment]
>  I still reproduce the problem starting from a fresh build tree and I never touch the option.

Gotcha. I will clarify this in the commit message. Thanks again for taking the time to test and report back :pray:

**Comment by jcfr** [comment]
Closing. Fix integrated in [r28262](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28262) and [r28263](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28263)

**Pull request closed without merging**
