### PR TITLE
ENH: Improved logging for easier troubleshooting

### PR DESCRIPTION
**Pull request by lassoan**
When users report a crash we need to ask a lot of questions (what operating system, Slicer version is used, how much memory is in the computer, how large images are loaded, what module was used, etc). Instead, we will be able to just ask them to provide the application log, as it will contain all these information. Lots of useful information is included now and as we identify further important troubleshooting data, those should be added to the application log, too.

* Added vtkInfoMacro logging macro, that logs an INFO message from VTK objects. vtkDebugMacro was not usable for information logging, as it only logs the message if debug is enabled for the particular object (also, typically debug output contains many low-level details).
* Added more detailed system and application info logging (operating system, memory, CPU, additional module paths, developer mode flag, executable CLI preference flag).
* Fixed system info logging for Windows (vtksys computes returns incorrect virtual memory size and number of physical CPUs).
* Log whenever user switches to another module (in case of a crash we know then what module was active).
* Log loaded volume size (this allows us to see if the volume size is very large compared to the available memory), for example: vtkMRMLVolumeArchetypeStorageNode (000000DC38FDF230): Loaded volume from file: C:/S4/Libs/MRML/Core/Testing/TestData/fixed.nrrd. Dimensions: 65x65x32. Number of components: 1. Pixel type: short.

### CODE REVIEW

**Comment by lassoan** [comment]
Merged in rev 24039

**Comment by jcfr** [comment]
@lassoan Thanks for your work on this. :+1:

**Comment by jcfr** [comment]
There is a compile error ... 

```
jcfr@karakoram:Slicer-build $ make vtkAddon
Building CXX object Libs/vtkAddon/CMakeFiles/vtkAddon.dir/vtkOrientedBSplineTransform.cxx.o
In file included from /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:10:0:
/home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.h:30:22: fatal error: vtkAddon.h: No such file or directory
 #include "vtkAddon.h"
                      ^
compilation terminated.
make[3]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/vtkOrientedBSplineTransform.cxx.o] Error 1
make[2]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/all] Error 2
make[1]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/rule] Error 2
make: *** [vtkAddon] Error 2

```

**Comment by lassoan** [comment]
Builds fine on Windows. It would be great if you could investigate/fix on Linux.

**Comment by jcfr** [comment]
Seems the file `vtkAddon.h` is missing, I started a topic to fix this ...
https://github.com/jcfr/Slicer/tree/fix-vtk-addon

After creating the file with what I think should be the content, I now have
the following error. Is your local version of "vtkAddon.h" different from
[1]

[1]
https://github.com/jcfr/Slicer/blob/32f9e46e7b66816bd2b7097ea61eed91ce4ee82a/Libs/vtkAddon/vtkAddon.h

/home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:150:14:
error: ‘class vtkOrientedBSplineTransform’ has no member named
‘Coefficients’
   if (!this->Coefficients || !this->CalculateSpline)
              ^
/home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:
In member function ‘virtual void
vtkOrientedBSplineTransform::ForwardTransformDerivative(const double*,
double*, double (*)[3])’:
/home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:201:14:
error: ‘class vtkOrientedBSplineTransform’ has no member named
‘Coefficients’
   if (!this->Coefficients || !this->CalculateSpline)
              ^
/home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:
In member function ‘virtual void
vtkOrientedBSplineTransform::InverseTransformDerivative(const double*,
double*, double (*)[3])’:
/home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:270:14:
error: ‘class vtkOrientedBSplineTransform’ has no member named
‘Coefficients’
   if (!this->Coefficients || !this->CalculateSpline)
              ^
make[3]: ***
[Libs/vtkAddon/CMakeFiles/vtkAddon.dir/vtkOrientedBSplineTransform.cxx.o]
Error 1
make[2]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/all] Error 2
make[1]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/rule] Error 2


On Mon, Mar 9, 2015 at 11:11 PM, Andras Lasso <notifications@github.com>
wrote:

> Builds fine on Windows. It would be great if you could investigate/fix on
> Linux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/205#issuecomment-77988553>.
>



-- 
+1 919 869 8849

**Comment by jcfr** [comment]
Great. I just noticed you last commit.
Will let you know how it goes for me.

On Mon, Mar 9, 2015 at 11:37 PM, Jean-Christophe Fillion-Robin <
jchris.fillionr@kitware.com> wrote:

> Seems the file `vtkAddon.h` is missing, I started a topic to fix this ...
> https://github.com/jcfr/Slicer/tree/fix-vtk-addon
>
> After creating the file with what I think should be the content, I now
> have the following error. Is your local version of "vtkAddon.h" different
> from [1]
>
> [1]
> https://github.com/jcfr/Slicer/blob/32f9e46e7b66816bd2b7097ea61eed91ce4ee82a/Libs/vtkAddon/vtkAddon.h
>
> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:150:14:
> error: ‘class vtkOrientedBSplineTransform’ has no member named
> ‘Coefficients’
>    if (!this->Coefficients || !this->CalculateSpline)
>               ^
> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:
> In member function ‘virtual void
> vtkOrientedBSplineTransform::ForwardTransformDerivative(const double*,
> double*, double (*)[3])’:
> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:201:14:
> error: ‘class vtkOrientedBSplineTransform’ has no member named
> ‘Coefficients’
>    if (!this->Coefficients || !this->CalculateSpline)
>               ^
> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:
> In member function ‘virtual void
> vtkOrientedBSplineTransform::InverseTransformDerivative(const double*,
> double*, double (*)[3])’:
> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:270:14:
> error: ‘class vtkOrientedBSplineTransform’ has no member named
> ‘Coefficients’
>    if (!this->Coefficients || !this->CalculateSpline)
>               ^
> make[3]: ***
> [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/vtkOrientedBSplineTransform.cxx.o]
> Error 1
> make[2]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/all] Error 2
> make[1]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/rule] Error 2
>
>
> On Mon, Mar 9, 2015 at 11:11 PM, Andras Lasso <notifications@github.com>
> wrote:
>
>> Builds fine on Windows. It would be great if you could investigate/fix on
>> Linux.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Slicer/Slicer/pull/205#issuecomment-77988553>.
>>
>
>
>
> --
> +1 919 869 8849
>



-- 
+1 919 869 8849

**Comment by jcfr** [comment]
It now compiles as expected.  My version was missing the vtkVersion.h

On Mon, Mar 9, 2015 at 11:38 PM, Jean-Christophe Fillion-Robin <
jchris.fillionr@kitware.com> wrote:

> Great. I just noticed you last commit.
> Will let you know how it goes for me.
>
> On Mon, Mar 9, 2015 at 11:37 PM, Jean-Christophe Fillion-Robin <
> jchris.fillionr@kitware.com> wrote:
>
>> Seems the file `vtkAddon.h` is missing, I started a topic to fix this ...
>> https://github.com/jcfr/Slicer/tree/fix-vtk-addon
>>
>> After creating the file with what I think should be the content, I now
>> have the following error. Is your local version of "vtkAddon.h" different
>> from [1]
>>
>> [1]
>> https://github.com/jcfr/Slicer/blob/32f9e46e7b66816bd2b7097ea61eed91ce4ee82a/Libs/vtkAddon/vtkAddon.h
>>
>> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:150:14:
>> error: ‘class vtkOrientedBSplineTransform’ has no member named
>> ‘Coefficients’
>>    if (!this->Coefficients || !this->CalculateSpline)
>>               ^
>> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:
>> In member function ‘virtual void
>> vtkOrientedBSplineTransform::ForwardTransformDerivative(const double*,
>> double*, double (*)[3])’:
>> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:201:14:
>> error: ‘class vtkOrientedBSplineTransform’ has no member named
>> ‘Coefficients’
>>    if (!this->Coefficients || !this->CalculateSpline)
>>               ^
>> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:
>> In member function ‘virtual void
>> vtkOrientedBSplineTransform::InverseTransformDerivative(const double*,
>> double*, double (*)[3])’:
>> /home/jcfr/Projects/Slicer/Libs/vtkAddon/vtkOrientedBSplineTransform.cxx:270:14:
>> error: ‘class vtkOrientedBSplineTransform’ has no member named
>> ‘Coefficients’
>>    if (!this->Coefficients || !this->CalculateSpline)
>>               ^
>> make[3]: ***
>> [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/vtkOrientedBSplineTransform.cxx.o]
>> Error 1
>> make[2]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/all] Error 2
>> make[1]: *** [Libs/vtkAddon/CMakeFiles/vtkAddon.dir/rule] Error 2
>>
>>
>> On Mon, Mar 9, 2015 at 11:11 PM, Andras Lasso <notifications@github.com>
>> wrote:
>>
>>> Builds fine on Windows. It would be great if you could investigate/fix
>>> on Linux.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/Slicer/Slicer/pull/205#issuecomment-77988553>.
>>>
>>
>>
>>
>> --
>> +1 919 869 8849
>>
>
>
>
> --
> +1 919 869 8849
>



-- 
+1 919 869 8849

**Pull request closed without merging**
