### PR TITLE
DOC: Update sceneviews.md replacing literal \n with newline

### PR DESCRIPTION
**Pull request by Leengit**
Facilitate visual parsing of the raw markdown files replacing literal "\n" with actual newlines.

### CODE REVIEW

**Comment by jcfr** [comment]
Great progress. 

Can you also take care of

> Update all markdown files found in [Docs](https://github.com/Slicer/Slicer/tree/main/Docs) directory

**Review by jcfr — CHANGES_REQUESTED** [review]
Great progress. 

Can you also take care of

> Update all markdown files found in [Docs](https://github.com/Slicer/Slicer/tree/main/Docs) directory

**Comment by Leengit** [comment]
> Can you also take care of ...

I don't see any other use of `\n` in `Docs/.../*.md` files, except inside quoted C++ or Python strings where it needs to be kept.

**Comment by jcfr** [comment]
It turns out that the files I was looking at generated and consolidated in the `Docs/_moduledescriptions` folder as part of the documentation build process.

Looking at the documentation page of module like "Cast Scalar Volume", we can see that there are literal `\n`.

See https://slicer.readthedocs.io/en/latest/user_guide/modules/castscalarvolume.html

The issue is specific to the function `_generatemd` [^1] taking file like `CastScalarVolume.xml`[^2] as input.

[^1]: https://github.com/Slicer/Slicer/blob/ef38f694dc3675faf3c8203446e0f5434c35c202/Docs/conf.py#L263-L269

[^2]: https://github.com/Slicer/Slicer/blob/ef38f694dc3675faf3c8203446e0f5434c35c202/Modules/CLI/CastScalarVolume/CastScalarVolume.xml#L5

**Review by jcfr — APPROVED** [review]
We will squash & merge and address the generation of CLI documentation independently.

**Pull request merged**
