### PR TITLE
BUG: Fixed parent transform setting by drag-and-drop

### PR DESCRIPTION
**Pull request by lassoan**
In Data module / Transform hierarchy tab, transform parent can be set by drag-and-drop even if
the transform is being constantly modified (such as in a surgical navigation scenario, when
position tracker device continuously updates the transform through OpenIGTLink).

Fixes https://issues.slicer.org/view.php?id=4138

### CODE REVIEW

**Comment by pieper** [comment]
Sounds like a good fix to me. 👍

**Comment by jcfr** [comment]
Ditto :+1: 

If feasible, do you think you could add a regression test ?

**Comment by lassoan** [comment]
> If feasible, do you think you could add a regression test ?

Yes, it would be nice to have a test but seems hard to implement. Do you know how to simulate a drag-and-drop in a QTreeView? (QtTesting operates on the scene model, we would need a solution that manipulates the GUI widget)

**Comment by pieper** [comment]
You could use the QtTesting infrastructure to record a test to xml, or you could write a script that emulates the mouse actions.  We use both approaches in various tests, but gui testing is still pretty fragile when the code changes.

**Comment by lassoan** [comment]
I've checked QtTesting, but it only simulates the end result of the drag-and-drop operation (calls reparent on the model), while the problem was in how the GUI widget behaves between start dragging and dropping (before reparent is called).

**Comment by lassoan** [comment]
Committed r26186

**Pull request closed without merging**
