### PR TITLE
BUG: FixedParametersValueType -> FixedParametersType

### PR DESCRIPTION
**Pull request by hjmjohnson**
Incorrect copy-n-paste error for ITK after 4.8.1.

### CODE REVIEW

**Comment by jcfr** [comment]
@hjmjohnson Thanks for you contribution 

Which problem is this fixing ? How can be done to reproduce the problem fixed by this commit ?

Cc: @lassoan

**Comment by hjmjohnson** [comment]
@Jcfr,

I testing a build with the newest version of ITK.  Basically preparing for future.

I have a few more patches as well.  These should all be backwards compatible for many many revisions of ITK.

Hans


From:  Jean-Christophe Fillion-Robin
Reply-To:  Slicer/Slicer
Date:  Monday, October 5, 2015 at 11:08 PM
To:  Slicer/Slicer
Cc:  Hans Johnson
Subject:  Re: [Slicer] BUG: FixedParametersValueType -> FixedParametersType (#363)


@hjmjohnson Thanks for you contribution 

Which problem is this fixing ? How can be done to reproduce the problem fixed by this commit ?

Cc: @lassoan

**Comment by jcfr** [comment]
> preparing for future.

:+1: 

I tweaked the commit message and integrated in [r24605](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24605)

**Comment by jcfr** [comment]
> I have a few more patches as well. These should all be backwards compatible for many many revisions of ITK.

This is great. Thanks for your help with Slicer.

**Pull request closed without merging**
