### PR TITLE
ENH: add more DCMTK applications

### PR DESCRIPTION
**Pull request by fedorov**
Applications added:
 - dcm2xml: convert DICOM into XML representation
   (http://support.dcmtk.org/docs/dcm2xml.html)
 - dsr2xml: convert SR DICOM into XML representation
   (http://support.dcmtk.org/docs/dsr2xml.html
 - dsrdump: SR-specific version of dcmdump already included
   (http://support.dcmtk.org/docs/dsrdump.html)

### CODE REVIEW

**Comment by fedorov** [comment]
This topic has already been discussed with @pieper. Any other apps you want to include Steve?

**Comment by jcfr** [comment]
:+1: Looks good. Can you run `git svn dcommit` ? Or would like me to integrate ?

**Comment by fedorov** [comment]
committed in r24197

**Comment by fedorov** [comment]
r24197 = 2becc8be0d6f8e0c63a1193a387da3c04563e3cd (just testing if this would link to the specific commit in Slicer github tree)

**Comment by fedorov** [comment]
It does - cool!

**Pull request closed without merging**
