### PR TITLE
BUG: remove deprecated DICOM SEG export from Editor

### PR DESCRIPTION
**Pull request by fedorov**
This functionality depended on now deprecated and non-existing functionality in
the Reporting module. The updated version of the Reporting module uses dcmqi,
https://github.com/QIICR/dcmqi, for DICOM SEG conversion, which in turn has an
interface different from what is used in this implementation.

DICOM SEG export will be provided in the updated Reporting extension, which is
reusing Segment Editor components for editing. It is possible that this export
functionality will be available in the main application in the future.

### CODE REVIEW

**Comment by fedorov** [comment]
CircleCI is failing for what appears to be an unrelated reason

**Comment by jcfr** [comment]
> CircleCI is failing for what appears to be an unrelated reason

@MayeulChassagnard Would you mind having a look at this ?

**Comment by pieper** [comment]
@fedorov the editor related changes LGTM.  Go ahead and commit when you are ready or let me know if you want me to do it tomorrow (I'm just back from being out a few days).

**Comment by fedorov** [comment]
Thanks for the review.

Merged in r25564 = ffd102a4cb353d66872ecbd06d210eddf4d76506

**Pull request closed without merging**
