### PR TITLE
3698 mrb saving remember last save location

### PR DESCRIPTION
**Pull request by naucoin**
Reset the save location for an MRB scene to the MRB location rather than the temporary extraction directory. Then mark storable nodes as modified since read to trigger a re-save since the temporary directory was removed.
Allow loading of MRBs from the command line with relative paths.

### CODE REVIEW

**Comment by jcfr** [comment]
@naucoin Are you planning on pushing any other update to this topic or is it good for final review and integration ?

**Comment by naucoin** [comment]
That's the last commit for this topic, it's ready for integration.

**Comment by jcfr** [comment]
Feel free to commit to the trunk.

[LGTM](http://www.lgtm.in/i/qHTl7iePp)

[:+1:](http://www.lgtm.in/u/qHTl7iePp) [:-1:](http://www.lgtm.in/r/qHTl7iePp)

**Comment by jcfr** [comment]
Integrated in [24044](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24044) and [24045](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24045)

**Pull request closed without merging**
