### PR TITLE
ENH: added draw circle by border on scissors segmentation effect

### PR DESCRIPTION
**Pull request by fbordignon**
Enhancement based on #6203

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
Thank you, this will be great, thank you! A few small things to improve:
- The option is both for circle and rectangle. Rename variable names and tooltips accordingly. (instead of "circle" we could use "region").
- Add the new parameter to Docs\developer_guide\modules\segmenteditor.md
- The new parameter's default value should be set so that default behavior is still centered. This should also be the case for existing scenes, where the new parameter is missing (and so probably a missing int parameter will be reported to have value = 0)

**Comment by fbordignon** [comment]
> The option is both for circle and rectangle. Rename variable names and tooltips accordingly. (instead of "circle" we could use "region").
The default behavior of the rectangle is by the border.

Option one: Create two parameters, one for the rectangle and another one for the circle, so that the default for the rectangle is by the border and for the circle is centered.

Option two: Change the default behavior of the rectangle to be centered so that the checkbox has one parameter only (regionCenteredMode) which controls the behavior of the rectangle and the circle.

Does any of these seem reasonable?

**Comment by lassoan** [comment]
The behavior is good, just need to rename variables, update tooltip, etc. to reflect this.

**Comment by fbordignon** [comment]
Sorry, I did not understand.
The current behavior of the rectangle is to draw it using the borders and the current behavior of the circle is to draw it starting by the center.
The changes I've committed are modifying only the behavior of the circle controlled by the checkbox.
Are you proposing for the checkbox to affect both the circle and the rectangle?

If that so, the parameter CircleCenteredMode will need to be renamed to RegionCenteredMode with default value=0.
The checkbox circleCenteredCheckBox will be renamed to regionCenteredChecBox, which by default will be enabled for the circle and disabled for the rectangle? How can I accomplish that with only one parameter? Don't I need one parameter for the circle and one for the rectangle defaulting to the current behaviors respectively?

**Review by lassoan — APPROVED** [review]
I've fixed the review comments (easier than explain) and tested everything. All looks good, will merge now.

**Comment by fbordignon** [comment]
Ok cool. In summary both behaviors defaults to drawing by the boundary now.
I've noticed a small issue with the checkbox. Issued a PR linked above.

Thanks

**Pull request merged**
