### PR TITLE
ENH: Allow cut, copy, and paste of fiducials in markups module

### PR DESCRIPTION
**Pull request by lassoan**
Selected markups can be cut or copied to clipboard.
Markups can be pasted to an Excel spreadsheet or pasted into the same or another markup list node Slicer.

### CODE REVIEW

**Comment by lassoan** [comment]
Example:

image

Probably fixes https://issues.slicer.org/view.php?id=4577.

**Comment by pieper** [comment]
Looks nice 👍

**Comment by jcfr** [comment]
Thanks for the PR. :+1

**Comment by lassoan** [comment]
Merged inr27274.

**Pull request closed without merging**
