### PR TITLE
Udpate to itk v4.8rc2

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@thewtex Would be awesome if you could also do a test build (windows ? Mac ?). Will do linux on my side.

**Comment by thewtex** [comment]
Yes, on the way :-)  Thanks!

**Comment by jcfr** [comment]
@thewtex Thanks

@blowekamp Note sure if it is directly related to the ITK update but I noticed the warnings like these ones:

```
/home/jcfr/Projects/Slicer-Debug/SimpleITK/Code/Explicit/src/sitkExplicitITKDefaultPixelAccessor.cxx:23:41: warning: type attributes ignored after type is already defined [-Wattributes]
 template class SITKExplicit_EXPORT itk::DefaultPixelAccessor<bool>;
                                         ^

/home/jcfr/Projects/Slicer-Debug/SimpleITK/Code/Explicit/src/sitkExplicitITKVectorImage.cxx:42:41: warning: type attributes ignored after type is already defined [-Wattributes]
 template class SITKExplicit_EXPORT itk::VectorImage<unsigned long, 3u>;
                                         ^

/home/jcfr/Projects/Slicer-Debug/SimpleITK/Code/Explicit/src/sitkExplicitITKImportImageContainer.cxx:50:41: warning: type attributes ignored after type is already defined [-Wattributes]
 template class SITKExplicit_EXPORT itk::ImportImageContainer<itk::SizeValueType, unsigned char>;
                                         ^


/home/jcfr/Projects/Slicer-Debug/SimpleITK/Code/Explicit/src/sitkExplicitITKLabelMap.cxx:38:41: warning: type attributes ignored after type is already defined [-Wattributes]
 template class SITKExplicit_EXPORT itk::LabelMap<itk::ShapeLabelObject<unsigned long, 3u> >;
                                         ^



/home/jcfr/Projects/Slicer-Debug/SimpleITK/Code/Explicit/src/sitkExplicitITKImageConstIterator.cxx:64:41: warning: type attributes ignored after type is already defined [-Wattributes]
 template class SITKExplicit_EXPORT itk::ImageConstIterator<itk::Image<unsigned short, 3u> >;

/home/jcfr/Projects/Slicer-Debug/SimpleITK/Code/Explicit/src/sitkExplicitITKImageScanlineConstIterator.cxx:59:41: warning: type attributes ignored after type is already defined [-Wattributes]
 template class SITKExplicit_EXPORT itk::ImageScanlineConstIterator<itk::Image<unsigned short, 3u> >;
                                         ^
[...]
```

**Comment by blowekamp** [comment]
@jcfr 

I am getting those warning on some compilers for SimpleITK standalone too [1]. This is with gcc 4.8.2 on RH7. Other compilers require that export specification there. This warning can be safely ignored, but I'll look into it again as it's annoying.

What compiler did you get this with?

[1] https://open.cdash.org/viewBuildError.php?type=1&buildid=3873695

**Comment by jcfr** [comment]
@blowekamp Thanks for commenting. If I understand, would it make sense to ensure `SITKExplicit_EXPORT_EXPLICIT` is defined to empty string on gcc ?

```
$ g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
```

**Comment by blowekamp** [comment]
@jcfr I think it's only this compiler complaining. And it may be required for this compiler even though it's complaining. 

The issue is related to getting the correct export specification for the ITK's declaration, the explicit declaration for external linkage, the export specification for instantiation, AND correct order for super classes. AND shared and static libraries linkage.

It's a non-trivial problem, this is just a warning, I'm not sure I can do any better. Help and additional insights into the problem is welcomed.

Thanks.

**Comment by jcfr** [comment]
@blowekamp Agreed. I will add warning suppression on dashboard if needed.

**Comment by thewtex** [comment]
MacOSX build:

  http://slicer.cdash.org/buildSummary.php?buildid=513216

This is 10.10 with recent XCode.

**Comment by jcfr** [comment]
Integrated in [r24360](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24360)

**Comment by jcfr** [comment]
@thewtex Thanks for testing on MacOSX. 

Let's pay attention to tomorrow windows dashboard and address issue as they arise.

**Comment by thewtex** [comment]
Will do.  Thanks @jcfr !

**Comment by jcfr** [comment]
The MacOSx dashboard failed with the following error.

See http://slicer.cdash.org/viewBuildError.php?buildid=513363

```
Undefined symbols for architecture x86_64:
  "typeinfo for itk::SingleValuedNonLinearVnlOptimizerv4", referenced from:
      typeinfo for itk::LBFGSOptimizerBasev4<vnl_lbfgsb> in libSimpleITKRegistration-0.9.a(sitkImageRegistrationMethod_CreateOptimizer.cxx.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
Undefined symbols for architecture x86_64:
  "typeinfo for itk::SingleValuedNonLinearVnlOptimizerv4", referenced from:
      typeinfo for itk::LBFGSOptimizerBasev4<vnl_lbfgsb> in libBRAINSCommonLib.a(BRAINSFitHelper.cxx.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jcfr** [comment]
Compiler is `llvm-3.1`. For more details see here: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Factory#factory.kitware

**Comment by thewtex** [comment]
@jcfr Thanks for the note.  Will investigate. @hjmjohnson does this ring any bells?

**Comment by jcfr** [comment]
For info, Slicer is based of BRAINSTools of May 15 [1], that said I
couldn't see any new commit in the official repo that would solve this.

Also noticed that windows broke, but this one should be easier to fix. See
[3]

[1] https://github.com/Slicer/BRAINSTools/commits/slicer-2015-05-12-980803c

[2] https://github.com/BRAINSia/BRAINSTools/commits/master

[3] http://slicer.cdash.org/viewBuildError.php?buildid=513365

On Thu, Jun 25, 2015 at 9:50 AM, Matt McCormick <notifications@github.com>
wrote:

> @jcfr <https://github.com/jcfr> Thanks for the note. Will investigate.
> @hjmjohnson <https://github.com/hjmjohnson> does this ring any bells?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/296#issuecomment-115263849>.
>



-- 
+1 919 869 8849

**Comment by jcfr** [comment]
@blowekamp Thanks for the [patch]( http://review.source.kitware.com/#/c/19940/1) :+1:

**Comment by jcfr** [comment]
Now looking at windows build problem.

**Pull request closed without merging**
