### PR TITLE
Fix json cpp packaging

### PR DESCRIPTION
**Pull request by vovythevov**
CC: @jcfr, @lassoan

### CODE REVIEW

**Comment by pieper** [comment]
@fedorov FYI

**Comment by fedorov** [comment]
All I can say - I hope this does it!

Thanks! 👍

**Comment by jcfr** [comment]
Please, integrate. Tomorrow nightly will confirm it works as expected. 

Thanks

**Comment by vovythevov** [comment]
Integrated in [r25417](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25417) and [r25418](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25418)

**Comment by cpinter** [comment]
@jcfr I cannot see the new commits in the github mirror. Is it because of a delay, or is it something more? Thanks!

**Comment by jcfr** [comment]
I manually triggered the sync yesterday .. something is definitively off with the sync bot. Having an other look now

**Comment by jcfr** [comment]
Got it .. the error log was reporting:

```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```

due to some  recent updates.

After explicitly starting XCode and accepting the license, things are now back in order.

**Comment by cpinter** [comment]
Thanks a lot! This was quick!

**Comment by fedorov** [comment]
@vovythevov as reported by @pieper, jsoncpp libraries are not installed in the proper locations. Can you please take a look at this issue: http://www.na-mic.org/Bug/view.php?id=4281 ?

**Comment by vovythevov** [comment]
Thanks @fedorov for the mention ! I hadn't seen this issue.
I added a note there (looks like the issue comes from JsonCpp).

**Comment by vovythevov** [comment]
Note: Issue was fixed by @jcfr in [r25465](https://github.com/Slicer/Slicer/commit/640e4581038bd9b2792a2e337c1d6e7b10d92cda).

**Pull request closed without merging**
