### PR TITLE
ENH: add Bishop and Rotation Minimizing Frames to the endoscopy module

### LINKED ISSUE #6476: Endoscopy jitters a bit
## Summary

While using the endoscopy module for a given path curve when it's playing you can see the camera jitter a bit

## Steps to reproduce

A complex enough path (with enough torsion)

## Expected behavior

Camera doesn't jitter a bit

## Environment
- Slicer version: Slicer-5.1.0-2022-07-20
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by mauigna06**
Together with:
https://github.com/Slicer/vtkAddon/pull/28

Fixes #6476

### CODE REVIEW

**Comment by jamesobutler** [comment]
I've pushed an update to resolve the lint CI failure.

**Comment by lassoan** [comment]
@mauigna06 Has this ended up significantly helping? As I recall, the change was not ended up as useful as initially seemed.

**Comment by mauigna06** [comment]
Hi Andras.

I may be able give a longer explanation on the weekend but I think the answer is no

**Comment by mauigna06** [comment]
> As I recall, the change was not ended up as useful as initially seemed.

Yes, that's right. Just resampling the spline with enough points got rid of the jittering on the endoscopy simulation.

Also I don't notice if the path is more stable while using bishop frames rather than the current implementation of the endoscopy module. But the current implementation appears to select a better first frame by using the normal of the plane-fit of the spline, making the fly through experience a bit nicer

**Comment by lassoan** [comment]
Thank you for experimenting with this. It has been useful to learn all this even if it did not lead to any source code change in the end.

**Pull request closed without merging**
