### PR TITLE
BUG: Fix failing ModelToLabelMapTest

### PR DESCRIPTION
**Pull request by naucoin**
When putting in a fix for using the passed in label value, the baseline file
OAS10001.1.mha was removed as it didn't seem to be in use any more. A closer
examination of the ctest output showed that that file was being
picked up as the baseline image when the test was passing as of May 11/16:
http://slicer.cdash.org/testDetails.php?test=7318110&build=825978
BaselineImageName	OAS10001.1.mha

With the last change[1], the test is failing:
http://slicer.cdash.org/testDetails.php?test=7329855&build=828864
BaselineImageName	OAS10001.mha

Local testing shows that the test would pass if the file OAS10001.1.mha was
reinstated, but to avoid confusion going forward as to how ctest globs
the baseline image files, I decided to go with testing the CLI with the
same input model (transformed to overlap the input image volume when both
are loaded in Slicer) for both the 255 and 128 output label cases, and to generate a
new output baseline image. I removed the untransformed model file and the now unused
baseline image and, locally, ctest is comparing the outputs of both tests against
teh correct baselines.

[1] https://github.com/Slicer/Slicer/commit/8707bb9ed2503f67ac0af29782c16db97adeab40

Reported-by: Andras Lasso <lasso@queensu.ca>

Issue #3233

### CODE REVIEW

**Comment by naucoin** [comment]
@lassoan Hopefully this will fix the failing test problem, I'll check in on the CircleCI build once it's completed running the tests.

**Comment by jcfr** [comment]
>  check in on the CircleCI 

I will publish an updated image asap. The recent CTK update will prevent the CI from completing

**Comment by naucoin** [comment]
@jcfr Thanks! I ran the tests locally to confirm that they pass.

**Comment by jcfr** [comment]
I also confirm test pass. 

Please, `git svn dcommit`.

**Comment by naucoin** [comment]
Done:
http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25091
https://github.com/Slicer/Slicer/commit/e3637ad52e6bf1ce614b916e69170404ff667b9e

**Comment by jcfr** [comment]
Thanks

**Pull request closed without merging**
