### PR TITLE
Fix and test extension build system

### PR DESCRIPTION
**Pull request by jcfr**
This topic will fix errors happening when building, testing or packaging extensions with dependencies.

It checks for the following:
* Generated description files are correct
* Submission to CDash are done
* Upload to extension server are done
* CMakeCache.txt of built extensions contains expected variables (e.g _DIR variables, ...)

Remaining tasks:
* [x] Check list of requests done to mock server are the expected ones.
* [ ] Install packages extensions and check dependent one are also installed

Notes:
* To ensure the test run in reasonable time, extensions used in the tests contains only scripted module. 
* extension sources used in the test are currently checked in the source (Testing/TestExtA, ...). I will revisit this to use the extension wizard.

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov @lassoan @pieper

**Comment by fedorov** [comment]
@jcfr what is the process to verify if this contribution fixed the issue described in http://www.na-mic.org/Bug/view.php?id=4200 ? (assuming it is indeed supposed to fix that issue - I am guessing, since there is no direct reference)

**Comment by jcfr** [comment]
@fedorov I added reference to the issue.  This topic also add test exercising the full cycle of extension build with dependencies.  The last step is to confirm extension with dependencies can also be installed, I will now add a test checking this.

**Comment by fedorov** [comment]
@jcfr another mysterious issue that seems to be on the same topic

SlicerPathology s4ext file points to this as the extension icon: 

https://raw.githubusercontent.com/SBU-BMI/SlicerPathology/master/SlicerPathology.png

(see https://github.com/Slicer/ExtensionsIndex/blob/master/SlicerPathology.s4ext)

However, extension manager in the latest nightly shows old icon:

image

(note that the Revision correctly lists the latest version of SlicerPathology trunk that has the updated icon: https://github.com/SBU-BMI/SlicerPathology/commit/ae5d1c49c496a84a6a61c770050e26e0451d26ae)

**Comment by fedorov** [comment]
cc: @ebremer

**Comment by jcfr** [comment]
@fedorov The last issue has been reported as http://na-mic.org/Mantis/view.php?id=4231

**Comment by jcfr** [comment]
Closing this PR. Improvement and fixes have been integrated in [r25210](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25210) to [r25218](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25218)

**Pull request closed without merging**
