### PR TITLE
DOC: Remove Pixel Medical from commercial partners

### PR DESCRIPTION
**Pull request by cpinter**
- Due to ceasing its operations, Pixel Medical is removed from the commercial partners list
- Add some details to the Ebatinca commercial partner

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Thanks for the update. It would make sense to add focus areas for all commercial partners.

**Comment by lassoan** [comment]
Don't forget to upsets this page, too: https://www.slicer.org/commercial-use.html

**Comment by jcfr** [comment]
> Update [commercial-use](https://www.slicer.org/commercial-use.html) page

See https://github.com/Slicer/slicer.org/pull/155

**Comment by cpinter** [comment]
Excellent, thank you a lot both!

**Pull request merged**
