### PR TITLE
ENH: scripted helper module to suggest SlicerDMRI extension

### PR DESCRIPTION
**Pull request by ihnorton**
We got a request to make more obvious to users where to find the modules that are now in SlicerDMRI extension. Not sure if this can make it in to release (great if so), but we'd like to have it in the nightly for a few months too.

### CODE REVIEW

**Comment by ihnorton** [comment]
cc @ljod

**Comment by jcfr** [comment]
Great. I will locally test and then integrate.

**Comment by jcfr** [comment]
The text do not wrap and force the module to panel to extend. 

Could you look into word wrap ? See http://doc.qt.io/qt-4.8/qlabel.html#wordWrap-prop

dmriinstall-too-wide

**Comment by ihnorton** [comment]
Updated, now uses wordWrap and does not expand.

**Comment by jcfr** [comment]
Great. Thanks

**Comment by jcfr** [comment]
That I will make it to the release, I will cut it a little later tonight

**Comment by jcfr** [comment]
I tweaked things a little. Instead of using `QLabel`, I used the `ctkFittedTextBrowser`.

As a side I also added a redirect from the DMRIInstall wiki page to the extension page.
See https://www.slicer.org/slicerWiki/index.php?title=Documentation/Nightly/Modules/DMRIInstall&redirect=no

Here is the result:

screenshot from 2016-10-12 00-52-15

**Comment by jcfr** [comment]
Integrated in [r25425](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25425)

**Comment by ihnorton** [comment]
Awesome, thanks.

**Pull request closed without merging**
