### PR TITLE
COMP: Speed up incremental build

### PR DESCRIPTION
**Pull request by achataigner**
vtkSlicerVersionConfigureInternal.h is renamed vtkSlicerVersionConfigureMinimal.h.

#include "vtkSlicerVersionConfigure.h" is replaced by #include "vtkSlicerVersionConfigureMinimal.h" when it is possible, therefore no compilation is required if git commit is changed.

### CODE REVIEW

**Comment by achataigner** [comment]
Hi all, could I have some feedback on this branch ?

**Comment by achataigner** [comment]
Thanks a lot for your feedback, I will apply these changes tomorrow.

**Comment by achataigner** [comment]
Done

**Review by jcfr — COMMENTED** [review]
The "internal" was used to indicate the file was not intended to be directly included.

It was in it own file for convenience so that it could be re-configured at build time [^1]

What about calling the file  `vtkSlicerVersionConfigure.h.in`.

[^1]: https://github.com/Slicer/Slicer/blob/main/CMake/SlicerConfigureVersionHeaderTarget.cmake

**Comment by lassoan** [comment]
The idea is to split version configuration file to two parts:
- Minimal: contains version major/minor/patch, whith changes only when a new release is created. 
- Full: contains git hash, revision, etc. that changes with each commit (in addition to the minimal version info)

At most places we only need information from "Minimal". At all those places it makes sense to include only that, because it is rarely changing. If we include the "Full" version information everywhere then more stuff are rebuilt when there is  a new commit.

Since we already had a "...Internal" configuration, it made sense to reuse that. The rename was necessary to reflect that it is not an internal implementation detail anymore but it is part of the public API that modules should use when the minimal version information is sufficient.

**Comment by achataigner** [comment]
Thank you Andras for your explanations.

**Comment by jcfr** [comment]
Before doing so, would it possible to split  into two commits:
- first one renaming the file and updating its header (remove the warning + include description)
- second one doing the speed optimization by changing what is included.

Would you have time to help with this as well ?

**Comment by achataigner** [comment]
Done

**Comment by jcfr** [comment]
Thanks @achataigner :pray: 

I tweaked the wording to provide additional guidance.

**Comment by jcfr** [comment]
Next, we should also update https://github.com/Slicer/Slicer/blob/main/CMake/SlicerConfigureVersionHeaderTarget.cmake

**Review by jcfr — APPROVED** [review]

**Comment by achataigner** [comment]
Thanks a lot

**Pull request merged**
