### PR TITLE
BUG: few fix in Unit Module and MRML

### PR DESCRIPTION
**Pull request by Punzo**
few minor bug fix

### CODE REVIEW

**Comment by Punzo** [comment]
Hi jcfr, 

I should have done two different commits (sorry!). 
the changes in vtkMRMLUnitNode are not really BUG.
1) strstream.setf(ios::fixed,ios::floatfield; guarantee that the returned string will have a number of decimals equal to precision (instead of a number of digit equal to precision). This prevents the cut of decimals when we have big numbers.
2) The spaces is just a style. I actually inserted them in ENH: adding extra units support #302. I thought simply will be better to leave them and I could add the spaces in my extension.

**Comment by jcfr** [comment]
@Punzo Thanks for clarification :) I now have enough information to move forward and integrate, it all makes sense.

**Comment by Punzo** [comment]
you are welcome :). Thanks for integrating.

**Comment by jcfr** [comment]
Note that most of this PR has been integrated in r24534, r24535 and r24536. 

The rest will be integrated has part of #337

**Pull request closed without merging**
