### PR TITLE
ENH: Make color selector search box case-insensitive

### PR DESCRIPTION
**Pull request by rweiss42**
I'd like to propose that the search box in Editor's color selector be case-insensitive.  This is an extremely minor tweak.  Objections/concerns?

### CODE REVIEW

**Comment by fedorov** [comment]
+1

**Comment by jcfr** [comment]
:+1: 

@fedorov Can you integrate ?

**Comment by jcfr** [comment]
After cherry-picking the commit on top of you current master and making sure it works as expected, you can then run `git svn dcommit --add-author-from`

**Comment by jcfr** [comment]
An convenient add on to git is https://hub.github.com/ 

It allow to directly cherry-pick a commit given its github url.

**Comment by fedorov** [comment]
JC, I need to work on something else, and need to run soon ... 

in any case we probably should wait to hear from @pieper as a courtesy...

**Comment by jcfr** [comment]
Good point :)

**Comment by pieper** [comment]
+1  :+1:

**Comment by jcfr** [comment]
@rweiss42 Thanks for your contribution. It has been integrated in [r24199](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24199)

**Pull request closed without merging**
