### PR TITLE
STYLE: SimpleMarkupsWidget: Add Markups logic setter/getter.

### PR DESCRIPTION
**Pull request by jcfr**
Allow the widget to be used with any given Markups logic

### CODE REVIEW

**Comment by jcfr** [comment]
@mholden8 Could you review this patch ? Thanks

With this change, the user of the widget  will be expected to set the Markups logic.

**Comment by mholden8** [comment]
@jcfr Thanks for doing this. This makes sense to me.

My one comment would be now that the markups logic (and scene) are not automatically set, if the user tries to use the widget without setting the markups logic, there will be a run-time error.

Probably there should be a check before each instance where the markups logic is used to ensure the logic has already been set. If you agree, I can add these checks.

**Comment by jcfr** [comment]
> Probably there should be a check before each instance where the markups logic is used to ensure the logic has already been set.

Makes sense. Thanks for working on this.

**Comment by jcfr** [comment]
Since I am travelling from August 12 to 19, if not already done, I will be integrating this topic when I return.

**Comment by jcfr** [comment]
Closing this PR. It is obsoleted by commit [r24937](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24937)

**Pull request closed without merging**
