### PR TITLE
ENH: Add SlicerMacroBuildScriptedCLI CMake function

### LINKED ISSUE #5306: Add CMake function to configure Python CLI
## Is your feature request related to a problem? Please describe.

Now that python CLIs are being used, copying the CMake code is not sustainable.

## Describe the solution you'd like

Create a CMake function called `SEMMacroBuildScriptedCLI` and re-factor (and fix) code like this one:

https://github.com/Slicer/Slicer/blob/a9352b45aee01c425511df472d0c7a91a97df12e/Base/QTCLI/Testing/CMakeLists.txt#L22-L39

https://github.com/Slicer/Slicer/blob/de2e43a7271b2f72d5537ea0a9af1288beb44055/Utilities/Templates/Modules/ScriptedCLI/CMakeLists.txt#L8-L29

see also https://github.com/Slicer/Slicer/pull/4747

### PR DESCRIPTION
**Pull request by jcfr**
Fixes #5306

### CODE REVIEW

**Comment by jcfr** [comment]
I still need to test this on macOS and Windows

**Comment by jcfr** [comment]
Support for generator expression with `OUTPUT` parameter of `add_custom_command` was added in CMake >= 3.20:
* https://gitlab.kitware.com/cmake/cmake/-/issues/12877
* https://cmake.org/pipermail/cmake/2014-August/058387.html

I will implement a workaround to support older CMake

**Comment by jcfr** [comment]
I tested the changes on Windows and Linux and I was able to "build" scripted CLIs

**Review by sjh26 — APPROVED** [review]

**Comment by jcfr** [comment]
For future reference, this commit is also relevant:
* d9562a0629cd0e2dfb502bbf330ccbddeb7d8cd2 `ENH: Update SlicerMacroBuildScriptedCLI to display comment only if needed`

**Pull request merged**
