### PR TITLE
Import more series information from DICOM images

### PR DESCRIPTION
**Pull request by lassoan**
In addition to series modality and series number, also read these fields from DICOM into metadata in the scene: seriesDescription, seriesDate, seriesTime, contentDate, contentTime, manufacturer, model.

This allows preserving more information when importing and then exporting DICOM images.

Also changed default series number to 301 (from 1) because values <100 are typically used for primary acquisitions, while higher numbers are used for processed data.

### CODE REVIEW

**Comment by pieper** [comment]
Are the translation-related changes meant to be part of this PR?

**Comment by lassoan** [comment]
> Are the translation-related changes meant to be part of this PR?

Yes, it was just a small improvement, I didn't want to add a new pull request for it. Please have a look at that, too.

**Review by pieper — APPROVED** [review]
LGTM 👍 

You might add a comment about how having the extra dicom tags can be used.

**Comment by lassoan** [comment]
Thanks for the review.

> You might add a comment about how having the extra dicom tags can be used.

These tags are used during DICOM export as default values.

**Pull request merged**
