### PR TITLE
ENH: Secure the bugtracker link

### PR DESCRIPTION
**Pull request by jondo**
Using the HTTPS version of the bugtracker avoids that login passwords are transferred in plain text.

### CODE REVIEW

**Comment by pieper** [comment]
LGTM - thanks!

**Comment by jondo** [comment]
This closes https://www.na-mic.org/Bug/view.php?id=4368.

**Comment by jcfr** [comment]
Thanks for the PR. Testing locally, will integrate asap.

**Comment by jcfr** [comment]
Integrated in [r25985](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25985)

**Pull request closed without merging**
