### PR TITLE
STYLE: SampleData: Acknowledge "Osirix DICOM image library"

### PR DESCRIPTION
**Pull request by jcfr**
Suggested-by: Sonia Pujol <spujol@bwh.harvard.edu>

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @pieper

**Comment by spujol** [comment]
Yes, adding the text in the Acknowledgements sounds good.

**Comment by jcfr** [comment]
@spujol Great. Thanks for the review.

After getting feedback from @pieper , I will integrate

**Comment by pieper** [comment]
LGTM - thanks!

**Comment by jcfr** [comment]
Thanks for the review.

Integrated in [r25509](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25509)

**Pull request closed without merging**
