### PR TITLE
ENH: Added orientation marker to slice view annotations

### PR DESCRIPTION
**Pull request by mehrtash**
This will fix issue #2935 (http://na-mic.org/Mantis/view.php?id=2935).

Also:
* Refactoring slice view annotation code.
* Changed ScalarBar implementation:Instead of adding widget to the interacotor the scalarbar actor is directly added to the renderer. The previous implementation(widget) had conflicts with orientation marker renderer.

### CODE REVIEW

**Comment by mehrtash** [comment]
Some screenshots:
[1](https://cloud.githubusercontent.com/assets/2693004/8014701/b3ff69c8-0ba0-11e5-8ede-a0342ffd29b7.PNG)

**Comment by fedorov** [comment]
Alireza, thanks a lot for working on this!

I tested by building your Slicer branch from scratch, and have this error repeated in the python console. Text annotations and scalar bar do not show up.

```
Traceback (most recent call last):
  File "/Users/fedorov/local/builds/Slicer4-Debug/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 335, in onCornerTextsActivationCheckBox
    self.updateSliceViewFromGUI()
  File "/Users/fedorov/local/builds/Slicer4-Debug/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 486, in updateSliceViewFromGUI
    self.makeAnnotationText(sl)
  File "/Users/fedorov/local/builds/Slicer4-Debug/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 1132, in makeAnnotationText
    self.drawCornerAnnotations()
  File "/Users/fedorov/local/builds/Slicer4-Debug/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 1286, in drawCornerAnnotations
    text = self.fitText(text, self.maximumTextLength)
  File "/Users/fedorov/local/builds/Slicer4-Debug/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 1268, in fitText
    text = text[:preSize] + "..." + text[-postSize:]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by mehrtash** [comment]
@fedorov Thanks for testing the patch. It should be fixed now.

**Comment by fedorov** [comment]
Thank you, this fixed the issue!

The remaining issue is leaks on exit. These appear when I start with Human annotation disabled, enable it and exit. Seems to be related to getting the models set up, as vtkSTLReader is leaking. Reading an STL with slicer.util.loadModel() does not result in a leak,

```
Class "vtkCellData" has 4 instances still around.
Class "vtkCollection" has 5 instances still around.
Class "vtkSTLReader" has 4 instances still around.
Class "vtkInformationVector" has 12 instances still around.
Class "vtkPointData" has 4 instances still around.
Class "vtkCompositeDataPipeline" has 4 instances still around.
Class "vtkObservation" has 4 instances still around.
Class "vtkMRMLNodeReference" has 8 instances still around.
Class "vtkObserverManager" has 4 instances still around.
Class "vtkIntArray" has 16 instances still around.
Class "vtkPoints" has 4 instances still around.
Class "vtkInformation" has 56 instances still around.
Class "vtkEventBroker" has 1 instance still around.
Class "vtkPolyData" has 4 instances still around.
Class "vtkAlgorithmOutput" has 4 instances still around.
Class "vtkMRMLModelNode" has 4 instances still around.
Class "vtkInformationIntegerValue" has 108 instances still around.
Class "vtkCellArray" has 4 instances still around.
Class "vtkTagTable" has 4 instances still around.
Class "vtkFloatArray" has 4 instances still around.
Class "vtkInformationStringValue" has 4 instances still around.
Class "vtkInformationExecutivePortVectorValue" has 4 instances still around.
Class "vtkIdTypeArray" has 4 instances still around.
Class "vtkFieldData" has 4 instances still around.
Class "vtkTimerLog" has 1 instance still around.
Class "vtkUnsignedLongArray" has 8 instances still around.
Class "vtkCommand or subclass" has 12 instances still around.
Class "vtkInformationExecutivePortValue" has 4 instances still around.
```

**Comment by mehrtash** [comment]
@fedorov I could reproduce the vtk leaks issue. This is fixed now. Please try again and let me know if there are other any issues.
Thanks

**Comment by fedorov** [comment]
+1

looks good to me!

@jcfr @pieper any concerns integrating this commit?

**Comment by jcfr** [comment]
I will try the topic tomorrow. 

In the mean time, what is the license of the STL model ?

**Comment by mehrtash** [comment]
I created STL models with MakeHuman [1]. I think based on [2] the exported models are under CCO licence. [3] is the license explanation.

[1] http://www.makehuman.org/
[2] http://www.makehuman.org/doc/faq/can_i_sell_models_created_with_makehuman.html
[3] http://www.makehuman.org/content/license_explanation.html

**Comment by jcfr** [comment]
Great. Would be great to mention this in the commit message.

**Comment by fedorov** [comment]
Alireza, as aside, next time it will be helpful to see commit history instead of one big commit. I know you were not clear on the rules, but looking at this pull request https://github.com/Slicer/Slicer/pull/287, this is ok and is more helpful.

**Comment by mehrtash** [comment]
@jcfr I added the note to the commit message.

@fedorov Yes, that is true. My understanding was commits should be squashed for Slicer pull requests. But you are right smaller commits make more sense and are much more useful.

**Comment by jcfr** [comment]
Thanks.

Assuming the software is in a working state between each commit, it makes
sense to have multiple commit. It also make review and tracking of
potential problem easier.

To achieve this, I extensively make use of "git rebase --interactive" to
create a meaningful sequences of commit.

Hth
Jc

On Wed, Jun 10, 2015 at 9:57 AM, Alireza Mehrtash <notifications@github.com>
wrote:

> @jcfr <https://github.com/jcfr> I added the note to the commit message.
>
> @fedorov <https://github.com/fedorov> Yes, that is true. My understanding
> was commits should be squashed for Slicer pull requests. But you are right
> smaller commits make more sense and are much more useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/286#issuecomment-110764122>.
>



-- 
+1 919 869 8849

**Comment by mehrtash** [comment]
Hi @jcfr , any update on this?

**Comment by fedorov** [comment]
@jcfr @pieper this issue has been without updates for over a month. All of the concerns have been addressed.

Is there any timeline when it will be reviewed?

**Comment by jcfr** [comment]
:+1: 

Integrated in [r24418](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24418)

**Comment by fedorov** [comment]
Thank you JC

**Pull request closed without merging**
