### PR TITLE
ENH: Update ITK to 5.2.1

### PR DESCRIPTION
**Pull request by dzenanz**
This is a bugfix release.

### CODE REVIEW

**Comment by jamesobutler** [comment]
The changelog for reference:
```
$ git shortlog --topo-order --no-merges v5.2.0..v5.2.1
Bradley Lowekamp (7):
      BUG: Register ComposeScaleSkewVersor3DTransform transform
      BUG: Add tests demonstration current behavior of histogram based median
      BUG: Fix StatisticsLabelMap median for even number of pixels
      ENH: StatisticsLabelMapFilter use improve integer histogram
      ENH: Add additional testing for zero sized label object
      BUG: Fix HDF5 installation with cmake targets
      BUG: Propagate usage of HDF5 find_package NO_MODULE arg to install

Dženan Zukić (9):
      Revert "COMP: Use CMake 3.18.4 in macOS CI builds"
      COMP: Update KWStyle to fix compile warnings on Ubuntu 20.04
      BUG: add support for long long pixel types in PyBuffer
      COMP: Restore generation of static runtime library on MSVC
      ENH: fix Python multi-processing hang on unix
      ENH: Python wrapping reads VLV pixel type correctly
      COMP: Update KWStyle's version to avoid compile errors with C++23
      COMP: use WRAP_ITK_SCALAR instead of WRAP_ITK_REAL in mesh filters
      ENH: Add support for long long pixel types to ImageDuplicator wrapping

GDCM Upstream (1):
      GDCM 2021-06-07 (4404b770)

Lee Newberg (3):
      BUG: Ellipsis is not iterable
      ENH: Propagate StatisticsLabelMapFilter's default NumberOfBins
      ENH: Wrap itkAdaptiveHistogramEqualizationImageFilter for Python.

Matt McCormick (15):
      BUG: Add vnl_vector_from_array to extras __all__
      ENH: Update CastXML source builds to v0.4.3, LLVM 11.1.0
      ENH: Add CastXML binary for macOS arm64
      ENH: Add Linux arm64 CastXML binaries
      COMP: Backport CastXML arm64 Eigen support
      COMP: Do not add IPO to Python wrapping if not supported
      COMP: Only use np.float128 when available
      COMP: Make floating point exceptions a no-op with MUSL, Linux, ARMv8
      BUG: Do not create global multiprocessing RLock
      BUG: Support double colons in Changelog commit summary
      STYLE: Apply black to AuthorsChangesSince.py script
      COMP: Use numpy==1.20.3 for CI testing
      COMP: Use mallinfo2 when available
      ENH: Bump the ITK CMake version to 5.1.0
      ENH: Content link synchronization for ITK 5.2.1

Niels Dekker (1):
      BUG: `Similarity3DTransform::SetScale` should recompute `m_Offset`

Pablo Hernandez-Cerdan (1):
      ENH: Increase hook-max-size for next GDCM update

Stephen R. Aylward (5):
      BUG: SpatialObject writes object color
      BUG: TubeSpatialObject missing CopyInformation
      BUG: TubeSpatialObject didn't preserver Artery flag
      COMP: Update SpatialObjects to correct const-ness
      ENH: Updated SpatialObject wrapping to support CONST_POINTER

Thompson, Darren (IM&T, Clayton) (2):
      COMP: Removed constructor template parameters from the VNL library
      COMP: Removed constructor template parameters from itkSmapsFileParser

Tom Birdsong (1):
      ENH: Add `float` wrappings for itkSymmetricSecondRankTensor

VXL Maintainers (1):
      VXL 2021-07-19 (22f874db)
```

**Comment by jamesobutler** [comment]
I'm building with this update on Windows and will re-run testing as a sanity test to make sure everything is still working.

**Comment by dzenanz** [comment]
This should be a low-risk update. It can/should be done while waiting on #5807.

**Comment by jamesobutler** [comment]
The same tests that are failing on the factory windows build machine were also the same failing during my tests. Therefore everything looks to be safe here.

**Review by jamesobutler — APPROVED** [review]

**Pull request merged**
