### PR TITLE
Visual dicom browser enhs

### PR DESCRIPTION
**Pull request by Punzo**
New PR for visual DICOM browser enhancements. This is a work in progress.

Depends on:

https://github.com/commontk/CTK/pull/1217

### CODE REVIEW

**Comment by Punzo** [comment]
@lassoan this is ready for review.

**Comment by Punzo** [comment]
Needs https://github.com/commontk/CTK/pull/1218 to be merged

**Comment by Punzo** [comment]
https://github.com/commontk/CTK/pull/1218 has been merged and I have updated CTK tag here. This is ready for review @lassoan . Thanks!

**Review by lassoan — APPROVED** [review]
Thank you, it looks good.

**Pull request merged**
