### PR TITLE
Consistently read launcher settings

### PR DESCRIPTION
**Pull request by jcfr**
This PR updates Slicer Core application so that it consistently reads environment settings (`PATH`, `LD_LIBRARY_PATH`, `PYTHONPATH`, ...) for both the main application and installed extensions using the same interface provided by [ctkAppLauncherSettings.h](https://github.com/commontk/AppLauncher/blob/714ef57b693a7a7459d7f2ac8fd6bb8094f15f2e/Base/ctkAppLauncherSettings.h#L10-L131).

It addresses issue Radiomics/SlicerRadiomics/issues/18

It was tested (by starting Slicer, installing an extension and re-starting) using:

* [x] Linux build tree  (tested using SlicerRadiomics extension packaged locally)
* [x] Linux Install tree (tested using SlicerRadiomics extension packaged locally)
* [x] MacOSx build tree (tested using SlicerRadiomics extension packaged locally)
* [x] MacOSx Install tree (tested using SlicerRadiomics extension packaged locally)
* [x] Windows build tree (application starts -  can not yet test use of SlicerRadiomics)
* [x] Windows Install tree (application starts - can not yet test use of SlicerRadiomics)

### CODE REVIEW

**Comment by jcfr** [comment]
Following my test, I fix few things and this fully functional and address https://github.com/Radiomics/SlicerRadiomics/issues/18

I still need to fix one build warning related the AppLauncherLib on MacOSX and I will integrate.

**Comment by jcfr** [comment]
Warnings have been addressed.

**Comment by jcfr** [comment]
Integrated in [r26040](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26040) to [r26042](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26042)

**Comment by ihnorton** [comment]
@jcfr this adds `-lCTKAppLauncherLib` to the command line (for anything using `SlicerMacroBuildModuleLogic`, from what I can tell) without adding a corresponding search path.

**Comment by ihnorton** [comment]
(in other words: it's probably going to break most C++ extensions)

**Comment by jcfr** [comment]
Good catch 

Two options:
(1) add the dependency as private and bump required CMake version to 3.0. 
(2) ensure find_package(CTKAppLauncherLib  ..) is done in SlicerConfig

In the mean time, I will most likely go with (2)

**Comment by jcfr** [comment]
@ihnorton See https://github.com/Slicer/Slicer/pull/729

**Comment by pieper** [comment]
Tested this morning's nightly build on mac and confirmed that I can install and run SlicerRadiomics extension. :1st_place_medal:

**Comment by jcfr** [comment]
Windows fixes will be next !

**Pull request closed without merging**
