### PR TITLE
ENH: VolumeRenderingModuleWidget: Extend API adding a new signal

### PR DESCRIPTION
**Pull request by Punzo**
signals to synch the current MRMLVolumeRendeingDisplayNode from the VolumeRenderingModuleWidget to another ModuleWidgets.

See:
https://github.com/Slicer/Slicer/pull/432
https://github.com/Slicer/Slicer/pull/377

P.S.: setting NodeReferenceID (i.e. restoring selected node at Slicer restart) as suggested by lassoan will be addressed later in another PR.

### CODE REVIEW

**Comment by lassoan** [comment]
Looks good to me.

**Comment by pieper** [comment]
+1

**Comment by Punzo** [comment]
Hi,

sorry a small change in https://github.com/Punzo/Slicer/commit/5f3fa6636b38042d3cf13d3ed8725730d8f719eb: 
onCurrentMRMLVolumeNodeChanged I use again  currentVolumeNodeChanged signal (as in https://github.com/Slicer/Slicer/pull/432).

I think it is more functional and intuitive.

**Comment by jcfr** [comment]
Thanks again for your patches :+1: 

Integrated in [r24922](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24922)

**Pull request closed without merging**
