### PR TITLE
BUG: Fix delayDisplay

### PR DESCRIPTION
**Pull request by fepegar**
Docstring says "If autoCloseMsec == 0 then the window is not closed until the user clicks on it.", but the dialog was not shown in this case.

### CODE REVIEW

**Comment by pieper** [comment]
LGTM

**Comment by jcfr** [comment]
Thanks for fixing this. Looks good. I will plan on squashing the commit and integrating.

I originally incorrectly documented the method in https://github.com/Slicer/Slicer/commit/aa5b8753c6258262c518458330c3849a7cb4cc50#diff-42dc7f34141a60bc1225fb50b970a058), and before than i broke the support for "display until user click OK" in https://github.com/Slicer/Slicer/commit/ac2614c66664d9c93fa20766eccb38da30ffb796#diff-42dc7f34141a60bc1225fb50b970a058

**Comment by fepegar** [comment]
Thanks @jcfr!

**Comment by jcfr** [comment]
Closing. Integrated in [r28371](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28371)

**Pull request closed without merging**
