### PR TITLE
COMP: BuildSystem: Ensure extension can find CTKAppLauncherLib

### PR DESCRIPTION
**Pull request by jcfr**
Reported-by: Isaiah Norton <inorton@bwh.harvard.edu>

### CODE REVIEW

**Comment by ihnorton** [comment]
That works, thanks. 👍

**Comment by jcfr** [comment]
Great. Thanks for the review :)

Ci is green, QA is good. Will integrate.

**Comment by jcfr** [comment]
Integrated in [r26048](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26048)

**Comment by cpinter** [comment]
Awesome! Trying it now.

**Comment by cpinter** [comment]
Confirmed, works

**Pull request closed without merging**
