### PR TITLE
Enable i18n

### PR DESCRIPTION
**Pull request by lassoan**
Build Slicer with i18n enabled by default.

It is marked as draft because first need to merge this CTK language box improvement (https://github.com/commontk/CTK/pull/1019), but otherwise it is fully ready for review.

It should get into today's nightly build so that it can be shown at the project presentations tomorrow.

### CODE REVIEW

**Review by pieper — APPROVED** [review]
LGTM 👍

**Comment by pieper** [comment]
Do you want to add an update to the CTK tag in this PR too?

**Comment by jcfr** [comment]
> Do you want to add an update to the CTK tag in this PR too?

That is indeed then plan (PR marked as draft)

**Comment by jcfr** [comment]
I suggest to also cherry pick these commits from https://github.com/Slicer/Slicer/pull/6050:

```
ENH: i18n: Add support for generating translation templates
STYLE: i18n: Simplify *.ts files removing location 
```

as well as 

```
ENH: i18n: Add GenerateSlicerTranslationQMFiles target 
```

**Comment by lassoan** [comment]
I agree, we should integrate the developments in #6050, but I cannot do that today. I will work on the module that can update translations from crowdin, as it would be nice to demo that tomorrow.

**Comment by lassoan** [comment]
@sjh26 I've updated the default value of `Slicer_BUILD_I18N_SUPPORT` to `ON` in the latest master yesterday. Still, it seems that Slicer was built with this option disabled (I've only tested on Windows). I did not find any reference to this CMake variable. Could you check on the factory machines? Maybe there is some cached configuration that preserves the previous value of `Slicer_BUILD_I18N_SUPPORT` and so it is not sufficient to just change the default value.

**Pull request merged**
