### PR TITLE
BUG: Fix table read/write error

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
This commit ensures that single component vectors that have no component name do not return a component name of "0".

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
@lassoan this fix was meant to be in the previous pull request, however it somehow got removed. I probably missed staging this change.

**Comment by lassoan** [comment]
I've forced-push a stylistic change. Before merging, it would be nice to ensure that generated component names are unique.

**Comment by Sunderlandkyl** [comment]
Component names should now be unique when saving.

**Comment by lassoan** [comment]
Thanks a lot, merged (r28755).

**Pull request closed without merging**
