### PR TITLE
ENH: Modernize: add override in virtual functions of derived classes

### PR DESCRIPTION
**Pull request by phcerdan**
After ITK_OVERRIDE and VTK_OVERRIDE have been replaced for `override`
we run clang-tidy to add overrides on virtual functions of derived
classes.

Example:

```diff
-virtual void ShowProgress()
+void ShowProgress() override
```

This allows compiler warnings and errors if the method
does not override the base class after a change in the base class.

Check the Slicer Wiki for an updated version of the documentation on
how to run clang-tidy.
https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/MigrationGuide#C.2B.2B11:_Update_source_code_to_use_override

```
run-clang-tidy.py -checks=-*,modernize-use-override  -header-filter=.* -fix
```

Multiple `override` are added to the same method.

```cpp
void PrintSelf(ostream& os, vtkIndent indent) override override override;
```

Clean them with (15 here is just a high enough number):

```
for n in `seq 1 15`;
do
    ack "override override" -l --print0 | xargs -0 -n 1 sed -i \
    's/override override/override/g'
done
```

When all of them are fixed, you should see in the terminal:
```
sed: no input files
```

This branch includes #1109 and #1107 (VTK_OVERRIDE and ITK_OVERRIDE)

### CODE REVIEW

**Comment by jcfr** [comment]
Commit `COMP: qSlicerAbstractCoreModule: Add override to qSlicerGetTittleMacro ` integrated in [r28034](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28034)

**Comment by jcfr** [comment]
Commit `STYLE: Replace ITK_OVERRIDE with override` integrated in [r28022](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28022)
Commit `STYLE: Replace VTK_OVERRIDE with override` integrated in [r28021](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28021)

**Comment by jcfr** [comment]
@phcerdan Could you push force this topic by running `run-clang-tidy` script and so that it contains an up-to-date commit like `ENH: Modernize: add override in virtual functions of derived classes ` ?

It failed for me,

After re-configuring the inner Slicer project with `-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON` so that it generates `compile_commands.json`, running `clang-tidy` failed:

```
$ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON .
[...]

$ run-clang-tidy-5.0.py -checks=-*,modernize-use-override  -header-filter=.* -fix
[...]
/home/jcfr/Projects/Slicer-test-RelWithDebInfo/DCMTK/dcmdata/include/dcmtk/dcmdata/dcvrobow.h:351:18: warning: prefer using 'override' or (rarely) 'final' instead of 'virtual' [modernize-use-override]
    virtual void postLoadValue();
    ~~~~~~~~~~~~~^              ~
                                 override

[...]
Suppressed 87 warnings (85 in non-user code, 2 with check filters).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Applying fixes ...
Traceback (most recent call last):
  File "/usr/bin/run-clang-tidy-5.0.py", line 217, in <module>
    main()
  File "/usr/bin/run-clang-tidy-5.0.py", line 214, in main
    apply_fixes(args, tmpdir)
  File "/usr/bin/run-clang-tidy-5.0.py", line 96, in apply_fixes
    subprocess.call(invocation)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by phcerdan** [comment]
Sure @jcfr, it seems a failure in the --apply step in a non-existent file.
I am using clang-tidy 7.0.1, that might include some bug-fixes from the 5.0 you are using.

Anyway, re-applying on top of current master. It seems VTK_OVERRIDE and ITK_OVERRIDE are already replaced there.

**Comment by phcerdan** [comment]
Closing, follow on in: #1116

**Pull request closed without merging**
