### PR TITLE
ENH: Added OBJ file save option for model nodes

### PR DESCRIPTION
**Pull request by lassoan**
Reading from .obj files are already supported, users requested ability to also save as .obj file to be able to load the exported models directly into Unity.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the patch. After CI is green, :+1: 

Should a small test be added ? 

Could also you also update the wiki page: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/SlicerApplication/SupportedDataFormat

**Comment by jcfr** [comment]
Very nice. I am building now to confirm test pass.

**Comment by lassoan** [comment]
I've added a test and updated the wiki page.

**Comment by jcfr** [comment]
No problem compiling. Test also pass.

Integrated in [r25421](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25421)

**Pull request closed without merging**
