### PR TITLE
Update support for newer dcmtk locking

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by pieper** [comment]
This looks fine to me.

@fedorov do you have any concerns?

**Comment by fedorov** [comment]
No concerns from me. I have not been contributing to or using the functionality in question. 

In fact, I am not even sure why this PET calculation module is in the Slicer core - we have an extension for this purpose, and none of [the developers of this module](https://github.com/Slicer/Slicer/blob/1421c5a3c07b8fd39965bcc7d6ee55fc537fdbf0/Modules/CLI/PETStandardUptakeValueComputation/PETStandardUptakeValueComputation.xml#L9) is around for quite some time.

**Comment by lassoan** [comment]
@fedorov should we remove this CLI from Slicer core? Does the extension to everything just as good or better as the PETStandardUptakeValueComputation core module?

**Comment by fedorov** [comment]
I would think it is a good idea to remove this module from the core, but I also think @chribaue would be the best expert to comment on this. I believe the functionality in https://github.com/QIICR/Slicer-PETDICOMExtension was based on this Slicer core module, but there were a lot of improvements. I also just realized we will probably need to make the same change that Hans did related to the DCMTK upgrade. Christian, will you look into this?

**Comment by pieper** [comment]
@fedorov what about Quantitative Reporting - does it need to be updated to account for this upgrade?

**Comment by chribaue** [comment]
I agree with @fedorov's your assessment. The mentioned module was the starting point for our developments. It doesn't support other SUV types, actual data normalization, creation of RWVM files, or anything related to data provenance, all of which is covered by our extension. There is nothing the old module allows you to do that you can't do with our extension.

For me it was always confusing that there's a module in the Slicer core that seems like it can be used for SUV normalization, but it can't. I would as well opt to remove it from the Slicer core.

**Comment by fedorov** [comment]
Thank you Christian, good to know we are in consensus! Will you update this line as Hans did in this PR: https://github.com/QIICR/Slicer-PETDICOMExtension/blob/master/SUVFactorCalculatorCLI/itkDCMTKFileReader.cxx#L1142? I actually don't remember why there is this customized DCMTK reader at all, it was probably ITK code duplicated at some point in the Slicer core, and carried over into the extension. Do you remember the history Christian, and whether it is needed?

@pieper I don't think QuantitativeReporting needs any upgrades, it is not using this dictionary locking functionality, unless I am forgetting something. I do need to update dcmqi to use this newer version of DCMTK, as it will fix another important bug: https://github.com/QIICR/dcmqi/issues/289.

**Comment by lassoan** [comment]
Thank you, I've added a note to Slicer5 roadmap - https://www.slicer.org/wiki/Documentation/Labs/Slicer5-roadmap#PETStandardUptakeValueComputation

**Comment by chribaue** [comment]
@fedorov I updated our code following Hans' example.

I'm not sure why there's a customized DCMTK reader. If I find some time, I'll compare our version to that in Slicer's ITK.

**Comment by fedorov** [comment]
Thank you Christian!

**Comment by hjmjohnson** [comment]
@phcerdan   Did you already apply these fixes in another patch?

Please close this issue once you have gained all the knowledge that you need since it is now superseded by your works.

**Comment by jcfr** [comment]
CTK has been updated but these changes have not been applied.

Currently doing a test build, it will be integrated shortly.

**Comment by jcfr** [comment]
Closing. Fix integrated in [r28046](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28046) and CTK last updated in [r28015](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=28015)

**Pull request closed without merging**
