### PR TITLE
BUG: Patch SimpleITK  explicitly set sitk default visibility

### PR DESCRIPTION
**Pull request by blowekamp**
Change SimpleITK to export ITK symbols with the default visibility on
OSX. This resolves run-time duplication of symbols causing
dynamic_cast failures.

Update ITK to da0e39
--------------------

List of changes:

$ git shortlog v5.1rc01..da0e39 --no-merges
Antoine Robert (1):
      ENH: Add boundary condition getters and setters

Brad King (1):
      BUG: Update URL for GitSetup hooks checkout

Brad T. Moore (1):
      ENH: Added explicit test of VectorImage with ExpandImageFilter

Bradley Lowekamp (14):
      BUG: Use unique_ptr::reset() to delete held pointer
      COMP: Remove unused region parameter in default copy constructor
      ENH: Update to latest GoogleTest release tag
      COMP: Disable GTest using threads
      ENH: Enable CircleCI to retrieve ccache on pull requests
      BUG: Set ConnectedComponentImageFilter's initial background
      value to zero.
      STYLE: Move constructor to hxx, use inline initialization for
      ivars
      COMP: Fix DCMTK unused CMake variable warning
      Revert "BUG: SetScale() and SetSkew() did not recompute offset:
      ScaleSkewVersorT (#1523)"
      BUG: Prevent integer underflow in CropImageFilter
      ENH: Add VectorImage support to MeanImageFilter
      ENH: Add test for sorting and size  in
      RelabelComponentImageFilter
      BUG: Fix RelabelComponentImageFilter with sorting off, size on
      PERF: Refactor RelabelComponentImageFilter

Davis Vigneault (5):
      BUG: Bump Cuberille Git Hash
      ENH: Bump Cuberille Commit Hash
      BUG: Delaunay Cell Data
      BUG: Handle CellData in Decimation Filter
      BUG: Bump Cuberille Commit Hash

Dženan Zukić (11):
      BUG: fix null pointer dereference in
      itkInOrderTreeIterator.h:102
      Update Release.md
      ENH: updating remote modules
      ENH: Deprecate TreeContainer group of classes
      BUG: Baseline and test image order was reversed in GDCM tests
      ENH: adding JPEG2000 ICT and RCT encoding compliance tests
      STYLE: ivar initialization into the header file in
      GDCMSeriesFileNames
      COMP: expose TransformCategoryType under LEGACY
      STYLE: cleaning up excessive white space in example
      ENH: update example to support non-overlapping images
      BUG: incorrect neighbor determination in scan-line derived
      filters

Eigen Upstream (1):
      Eigen3 2019-12-09 (c5d991ff)

Flavien Bridault (1):
      COMP: Fix compiling an app with Clang when ITK is built with GCC

GoogleTest Upstream (1):
      GoogleTest 2019-10-03 (703bd9ca)

Hans J. Johnson (3):
      ENH: When using cmake > 3.12 use FindPython3 module
      COMP: Remove searching for python interpreter
      COMP: Allow building basic ITK on computer without python3.5

Hans Johnson (5):
      COMP: Exceptions should be caught by constant reference
      BUG: Second argument to stream `operator<<` as const
      BUG: Print function should be const
      BUG: Add missing const 'GetDataObject' function signature
      BUG: Set 'GetDataObject' function signature to const

Jared Vicory (1):
      ENH: Wrap ComposeImageFilter for complex types

Matt McCormick (34):
      ENH: Update SCIFIO remote module to 2019-12-11 Git master
      ENH: Update stale-bot comment about issue closure
      ENH: Update content links
      DOC: Update ExternalData kitware rsync command
      DOC: Document how to re-run tests with a PR comment
      ENH: Use curl instead of wget in SourceTarball script
      ENH: Add script to identify release authors
      ENH: Use a script to generate the release changelog
      DOC: Update .mailmap to consolidate author identification
      DOC: Add Stephen R. Aylward to .mailmap
      DOC: Set lang attribute for Doxygen docs
      DOC: Add version-specific Doxygen links to the download page
      DOC: .mailmap entry for Hans J. Johnson
      DOC: Update README links
      STYLE: Updates for ImageIORegionGTest,
      DiscreteGaussianImageFilter
      ENH: clang-format.bash detects clang-format-8 executable
      DOC: Update clang-format.bash path
      ENH: Add clang-format linter GitHub Action
      ENH: Apply clang-format to PR with action:ApplyClangFormat
      DOC: Add clang-format check docs in CONTRIBUTING.md
      DOC: Add Zenodo DOI badge
      ENH: Also run clang-format linter on PRs
      DOC: Remove CONTRIBUTING note about ApplyClangFormat action
      DOC: CONTRIBUTING.md link to ITK Software Guide Development
      Guidelines
      COMP: PYTHON_LIBRARY is missing for Windows configuration
      BUG: Workaround Python3 CMake module bugs
      STYLE: Do not use id as variable in igenerator.py
      ENH: Bump macOS Azure CI images to 10.14
      COMP: Quote Python3_LIBRARY argument
      COMP: Get Input const in CastSpatialObjectFilter
      BUG: Address CastSpatialObjectFilter argument to itkTypeMacro
      BUG: Call itk.down_cast on ProcessObject outputs in functional
      call
      DOC: Add Citation section to README
      DOC: Request updates ITKBibliography.bib

Niels Dekker (3):
      STYLE: Make RecursiveSeparableImageFilter MathEMAMAMAM/SMAMAMAM
      static
      STYLE: Make RecursiveSeparableImageFilter::FilterDataArray const
      STYLE: Locally use unique_ptr within
      RecursiveSeparableImageFilter

Niklas Johansson (1):
      STYLE: Remove unused import inspect

Pradeep Garigipati (1):
      BUG: Remove debug console prints from GPU kernels

Sean McBride (2):
      BUG: fixed off-by-one error found by ASan
      COMP: reformulate a self-assignment to fix
      -Wself-assign-overloaded warning

Simon Rit (1):
      ENH: latest version of remote module RTK

Stephen R. Aylward (5):
      BUG: SetScale() and SetSkew() did not recompute offset:
      ScaleSkewVersorT (#1523)
      BUG: itkMetaImageIO.cxx supports more MetaDataDictionary field
      types
      ENH: Adding function to SOToImageFilter simplify output
      definition (#1531)
      ENH: Adding ComposeScaleSkewVersor 3D Transform (#1539)
      ENH: Adding filter and wrapping for casting within SO hierarchy
      (#1576)

Taylor Braun-Jones (1):
      COMP: Fix unit tests for OpenCV 4

VXL Maintainers (1):
      VNL 2019-12-13 (8af77376)

Vladimir S. FONOV (5):
      ENH: Updated script for Eigen third party update
      ENH: Simplification of the ImageSeriesReader nonuniform sampling
      detection
      BUG: fixes issue# 1498
      ENH: Changed NIFTI IO to support different flavors of Analyze
      readers
      COMP: Fixes error "error: no member named 'cend' in
      'std::__1::__map_const..."

Ziv Yaniv (1):
      BUG: SetLabelForUndecidedPixels value ignored.

Update to SimpleITK to 777520
-----------------------------

List of changes:

$ git shortlog 16a622..777520 --no-merges
Boo Irizarry (3):
      update workflow contrubiting.md file
      update contributing file
      update contributing file again

Bradley Lowekamp (23):
      Load SimpleITK version used in SimpleITKExamples sub-project
      Set SimpleITK version to 2.0.0
      Set more restrictive test template globs
      Update ITK Superbuild version along the 5.1 development branch
      Suppress self assignment warning in Image tests.
      For external project add required flags to preprocessor
      Update Superbuild ITK version along ITKv5.1 development
      Update ITK along 5.1 development
      Update ITK along 5.1 development
      Update MeanImageFilter wrapping to directly use VectorImage
      Add docker to build the SimpleITK doxygen
      AZP add Doxygen build and archive creating to packing build
      Add displacement field test case
      Fix double free from buffer ownership change in
      ImageFromVectorImage
      Update the SimpleITK S3 URL to virtual-host style
      Set ReturnBinMidpoint to match default ITKv5 value
      Update Doxygen version to 1.8.17
      Update superbuild version of ITK
      Update testing results of Otsu changed behavior
      Add more testing for RelabelComponentImageFilter
      Fix AZP package find command path
      Add rename const buffer access methods to C# interface.
      Propagate CMake visibility variables in external projects.

Dave Chen (4):
      Fixed grammer and changed ImageJ to Fiji.
      Added CMake/C++ setup documentation
      Added CMake/C++ setup documentation
      Removed 1st and 2nd person usage

Ziv Yaniv (1):
      Adding license and link to license.

### CODE REVIEW

**Comment by lassoan** [comment]
Our latest switch to the most recent ITK release candidate broke so many things that I would prefer not to upgrade ITK again so soon (especially to an untagged hash) and potentially spend time with regressions again. It's not just Slicer core but BRAINS, Elastix, etc.

Would it be enough to backport specific ITK commits? Would the ITK team confident in tagging the current ITK version as a new release candidate?

**Comment by blowekamp** [comment]
The reason for the upgrade of SimpleITK is to incorporate support for additional CMake variable in the super build which was done [here](https://github.com/SimpleITK/SimpleITK/commit/92f3c863f0b324aa7a30a76f57036ceee3c6c0fa).  This was done on SimpleITK master which includes [this](https://github.com/SimpleITK/SimpleITK/commit/64b2c3937e05a9033ffeee6dd4f4de70f372a415#diff-d52f66897fa9b4d625e37e9918c19642) commit dependent on [this ](https://github.com/InsightSoftwareConsortium/ITK/commit/61bda3f5c44c91350a24c93dfe98296b9f75920f#diff-e29926aa65d50526ccade158c5286daf)commit in ITK. It is just a small tweak the mean  filter.

It may be best to just back port the needed SimpleITK Superbuild patch to a SimpleITK. I probably should have based that commit of the SITK hash Slicer is currently using.

**Comment by lassoan** [comment]
It would be great if you could send a pull request to Slicer's SimpleITK fork that contains the same branch that was used in Slicer before, with the necessary patch.

**Comment by blowekamp** [comment]
Here is the branch:
https://github.com/blowekamp/SimpleITK/tree/slicer-vv1.2.4-2020-02-07-777520bd

Don't know how to create a PR from that to the forked repo with a target branch name, or what ever is needed.

**Comment by lassoan** [comment]
Thank you. I've merged the SITK branch to Slicer's fork (https://github.com/Slicer/SimpleITK/tree/slicer-v1.2.4-2020-02-07-777520bd) and will merge this PR once my Windows build successfully completed.

**Comment by blowekamp** [comment]
I update this branch to remove the ITK update and use the Slicer fork of SimpleITK.

**Comment by blowekamp** [comment]
@lassoan Is the patch to SimpleITK good to go?

**Comment by lassoan** [comment]
I have already merged it 2 days ago. I only tested it on Windows and it still works. Could you try the latest Slicer Preview Release on Mac?

**Comment by lassoan** [comment]
The problem has been confirmed to be fixed.

**Pull request closed without merging**
