### PR TITLE
ENH: Update to DCMTK-3.6.1_20161102

### PR DESCRIPTION
**Pull request by jcfr**
```
Suggested-by: Andriy Fedorov <fedorov@bwh.harvard.edu>
Tested-by: Christian Herz <christianherz1985@gmail.com>

$ git shortlog efe1a17..DCMTK-3.6.1_20161102 --no-merges
Jan Schlamelcher (11):
      Fixed wrong usage of checkStringValue() in dcmpmap.
      Several fixes for dcmpstat.
      Fixed 32 vs. 64 bit problem in dcmqrdb.
      Fixed using third party libraries with MinGW.
      Fixed a problem with a previous commit.
      Added OFvariant implementation for C++11.
      Added API documentation for OFvariant etc.
      Updated Makefile dependencies.
      Updated man pages for new development snapshot.
      Updated DCMTK_ABI_VERSION for new development snapshot.
      Updated CHANGES.361 for new development snapshot.

Joerg Riesmeier (3):
      Made clear that options +/-Uo require +Ug.
      Output debug messages when updating attributes.
      Added readXML mode that accepts empty/missing UID.
```

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @fedorov @che85

**Comment by che85** [comment]
LGTM

**Comment by fedorov** [comment]
👍

**Comment by fedorov** [comment]
@nolden @fbudin69500 this might also fix the C++11 issue you mentioned in the past.

Should DCMTK hash be updated for ITK and CTK as well? I am not sure what are the procedures.

**Comment by jcfr** [comment]
Thanks for the review.

Integrated in [r25499](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25499)

> Should DCMTK hash be updated for ITK

Cc: @fbudin69500 

> and CTK

I will take care of this one.

**Comment by jcfr** [comment]
Update of CTK tracked by https://github.com/commontk/CTK/pull/677

**Comment by fbudin69500** [comment]
Awesome! I will test it locally and update ITK!

**Comment by fbudin69500** [comment]
@fedorov I tried to compile the lastest commit of DCMTK with C++11 enabled, both on Linux and MacOS and got errors for both. I am not planning on updating ITK with this new revision since it does not correct that issue, except if you actually need this for other reasons. Let me know.

**Comment by fedorov** [comment]
@fbudin69500 thanks for checking. No, I don't need it in ITK. I only need it in Slicer.

@michaelonken @offis-jas - FYI - I am not sure if C++11 issue was supposed to be fixed in snapshot or not. No urgency to get it fixed from my side.

**Comment by michaelonken** [comment]
Should be fixed by [this DCMTK commit](http://git.dcmtk.org/?p=dcmtk.git;a=commitdiff;h=bf6ba98c706ef3f618203401b558b929c55aa201).

**Comment by fedorov** [comment]
@michaelonken that commit is included in the snapshot, but according to @fbudin69500 it didn't fix the compile error as mentioned in https://github.com/Slicer/Slicer/pull/617#issuecomment-258224631

**Comment by michaelonken** [comment]
Yes I know it's in the snapshot, what a pity, I will ask Jan to have another look...not sure whether he reads his github notifications. Thanks for checking!

**Comment by fedorov** [comment]
more details here: https://github.com/commontk/CTK/pull/675#issuecomment-258454745

**Pull request closed without merging**
