### PR TITLE
2267 add line thickness for label outline

### PR DESCRIPTION
**Pull request by naucoin**
Update the image label outline filter to use a kernel for thicker lines when displaying the label map layer in outline mode.
Uses the SliceIntersectionThickness setting on the display node, setting a default of 3 instead of 1 as used for model slice intersection thicknesses.

### CODE REVIEW

**Comment by fedorov** [comment]
I am in the process of building it to test

**Comment by naucoin** [comment]
@fedorov Thanks!

**Comment by fedorov** [comment]
Looks good to me! Thanks!

image

**Comment by fedorov** [comment]
@chribaue @rbeichel @ejulrich : you should like this! please comment if you have any concerns

**Comment by naucoin** [comment]
Rebased into one commit and merged as cd654faa89279694af12f5d7bbaa053281594881

**Comment by chribaue** [comment]
That sounds awesome! I guess it should be available with the next 
nightly build?

Christian

**Comment by fedorov** [comment]
Yes, if Slicer magic works - you should be able to enjoy it tomorrow!

**Pull request closed without merging**
