### PR TITLE
ENH: Added Segment Editor message in Editor and feature in SH

### PR DESCRIPTION
**Pull request by cpinter**
Message about Segment Editor has been added to the Editor module as agreed with Ron. Segment subject hierarchy plugin extended with Segment Editor option

### CODE REVIEW

**Comment by cpinter** [comment]
The message in Editor looks like this:
image
Please let me know if changes are needed.

**Comment by cpinter** [comment]
Clicking on the blue Segment Editor text takes the user to Segment Editor, with the same master volume selected. Clicking on the feedback link opens the users mailing list wiki page in a browser

**Comment by pieper** [comment]
LGTM!

**Comment by cpinter** [comment]
Integrated in
http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25234
If there are any requests for change, I still can do them.

**Pull request closed without merging**
