### PR TITLE
ENH: quickly reinstall previously installed extensions v3

### PR DESCRIPTION
**Pull request by hmeine**
This is a successor of #698 (since I cannot push to @mneugeba's branch directly).

In addition to that PR, this fixes compilation on Unix, adds translation features and some UI polish.

### CODE REVIEW

**Comment by pieper** [comment]
@jcfr I went over the logic for this with @hmeine and it sounds good.  We expect there may be some tweaks later but we don't expect any harm from merging this now.

**Comment by hmeine** [comment]
@pieper This branch is ready to be merged, I think. And the superceded #698 can then be closed.

**Comment by mneugeba** [comment]
@jcfr @hmeine very good :). This is is a bit behind the pull request it was derived from but includes most of the changes. I also learned, that at least the assert issue (see: https://github.com/Slicer/Slicer/pull/698#issuecomment-352260024) is also fixed now. Is the timeout issue described in the comment still a problem (or a problem at all, maybe it was just local)? Because it would hinder the start of Slicer, if the user is offline.

**Comment by jcfr** [comment]
> If no internet connectivity is available, the timeout seems not to trigge

Few options:
* Make sure the timeout is triggered
* Or ensure internet connection is available before calling the function

Last the new functionality should be documented here: https://www.slicer.org/wiki/Documentation/Nightly/SlicerApplication/ExtensionsManager

**Comment by hmeine** [comment]
I now changed the default such that the startup check is off.  In fact, I renamed the settings key, so that when qRestAPI is fixed, we can just revert this commit and people will get the startup check enabled again.  With this commit, this PR can be merged, and people can explicitly enable the check in the extension manager and finally test this feature.

**Comment by finetjul** [comment]
Hi Hans,

As an answer to your email:

> Hi Julien,
> 
> I am at project week and trying to get https://github.com/Slicer/Slicer/pull/865 merged, which should benefit all Slicer powerusers (like Ron) who often install nightly builds, since they get an easy way to reinstall all their extensions.  There’s one remaining problem, which Mathias described in https://github.com/Slicer/Slicer/pull/698#issuecomment-352260024 , namely that qMidasAPI::synchronousQuery() does not properly time out.
> 
> qMidasAPI::synchronousQuery() uses qRestAPI::setTimeOut(), which is apparently all code from you, from https://github.com/commontk/qRestAPI/commit/07854251e13728e91abec18fa7e78c19aa2553e2
> 
> From reading the code, when the timer fires, QNetworkReply::abort() is called.  OTOH, qMidasAPI::synchronousQuery() relies on SIGNAL(errorReceived(QUuid,QString)) being fired, which does not seem to be the case.  From looking at QNetworkReply::NetworkError (http://doc.qt.io/archives/qt-4.8/qnetworkreply.html), there’s a OperationCanceledError that should be triggered (as well as a TimeoutError and various other errors that might be triggered if no network connection is available).
> 
> Can you help with this?
> 
> We could publicly discuss it in the above PR, for instance: https://github.com/Slicer/Slicer/pull/865
> 
> Thanks
>   Hans
> 
> PS: I wonder why https://github.com/commontk/qRestAPI/commit/07854251e13728e91abec18fa7e78c19aa2553e2#diff-21c1ab43b794715485cc278bad3d3bf4R245 is commented out, or whether that made it work previously?  It was apparently committed like this, and never active in the official sources.`

It seems that abort() does not trigger any error. Can you try to add a breakpoint in the abort() method and see why the signal is not triggered ? Maybe the behavior changed with newer Qt version.

Hth,
Julien.

**Comment by hmeine** [comment]
@pieper @jcfr This should be finally ready to go:
* (Optionally) This could be merged as-is.
* After https://github.com/commontk/qRestAPI/pull/17 and https://github.com/commontk/qRestAPI/pull/16 have been reviewed and merged (I'd propose to merge https://github.com/commontk/qRestAPI/pull/18 as well, while you're at it), and
* qRestAPI has been updated in the SuperBuild,
* https://github.com/Slicer/Slicer/pull/865/commits/66779ae28f2fcf33a50f992f6de0f632df4911fe can be reverted or stripped of this branch, and it can be merged.  (I am happy to prepare this in my repo/this branch, so that we don't need yet another pull request.)

**Comment by jcfr** [comment]
@hmeine  Thanks for updating the PR and fixing qRestAPI. 

Now that qRestAPI has been updated, 66779ae should not be needed ?

Also, would it be possible to squash together the commits that make a coherent unit ?

**Comment by jcfr** [comment]
Closing. This is superseded by https://github.com/Slicer/Slicer/pull/867

**Pull request closed without merging**
