### PR TITLE
Adding label type column in Label Statistics

### PR DESCRIPTION
**Pull request by rweiss42**
The idea is to add a column to the table in Label Statistics that contains the name of the label taken from the label node's color node by GetColorName(i).  It also adds this to the CSV output.

It may be better to add this information to the labelStats dictionary.  The reason I'm doing it outside of this is because I noticed that we are casting the data in labelStats to float when adding to the table.  So instead of checking in the loop whether we are currently adding the label name and not trying to cast, I am just doing it outside of the loop (and therefore outside of the labelStats dictionary).

Is "type" the most appropriate word to use?  Should it be "name" instead?

### CODE REVIEW

**Comment by jcfr** [comment]
@rweiss42  Thanks for your contribution :+1: 

@pieper Could you review ?

**Comment by pieper** [comment]
I didn't test it but it looks good to me - thanks for the contribution!

**Comment by jcfr** [comment]
Great. I will do a final review and integrate then.

**Comment by jcfr** [comment]
Integrated in [r24143](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24143)

**Pull request closed without merging**
