### PR TITLE
Simplify build system removing extension build svn support

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Review by pieper — APPROVED** [review]
LGTM 👍 

We are lucky that svn is a pretty unique pattern of letters.  It also makes me glad that the clearly named variables facilitated this cleanup.

**Comment by pieper** [comment]
This looks good and and any regressions should be easy to fix.  Is the CI being updated?  Currently it fails due to out of date docker images.

**Comment by jcfr** [comment]
Thanks for the review :pray: 

> Currently it fails due to out of date docker images.

I gonna rebase the branch now

**Comment by lassoan** [comment]
@jcfr @pieper It looks like this PR is ready to merge. Is there anything you want to review or change?

**Comment by pieper** [comment]
I think it's good if @jcfr is happy with it.

**Comment by lassoan** [comment]
@jcfr both @pieper and I looked at this PR at the time you created it and it looked good. Do you have any specific concerns or would you like to delay its integration or it should be good to go?

It affects a lot of files and there are already some merge conflicts, so it would be good to integrate it before master branch diverges even more.

**Pull request merged**
