### PR TITLE
STYLE: Fixed dead link in about box

### PR DESCRIPTION
**Pull request by samuelgerber**
Changed link from http://nihroadmap.nih.gov/bioinformatics to https://commonfund.nih.gov/bioinformatics

### CODE REVIEW

**Comment by vovythevov** [comment]
LGTM ! Thanks Sam !

**Comment by pieper** [comment]
👍  Thanks!

**Comment by vovythevov** [comment]
@samuelgerber: Could you change your commit message ? The "DOC" isn't supported. 
Can you use one these please:
```
BUG:   - a change made to fix a runtime issue
           (crash, segmentation fault, exception, or incorrect result,
COMP:  - a fix for a compilation issue, error or warning,
ENH:   - new functionality added to the project,
PERF:  - a performance improvement,
STYLE: - a change that does not impact the logic or execution of the code.
           (improve coding style, comments, documentation).
```

Thanks !

**Comment by jcfr** [comment]
Thanks @samuelgerber

**Comment by vovythevov** [comment]
Fixed in [25982](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25982)

**Pull request closed without merging**
