### PR TITLE
ENH: Add functionality to change crosshair color

### PR DESCRIPTION
**Pull request by RafaelPalomar**
This closes Slicer/Slicer#6439

### CODE REVIEW

**Review by jamesobutler — COMMENTED** [review]
> Some users have pointed out that the color of the crosshair is hard-coded and would like to be able to change it from Python.

@RafaelPalomar Could you also update the python script repository with an example of how to do this? That way when users ask we can point them to it.

Do you think it is more widely needed where there is a GUI option, like in settings, that will allow to change it?

**Comment by RafaelPalomar** [comment]
@jamesobutler, thanks for having a look at this. I updated the documentation with a python snippet to change the crosshair color.

I would wait with adding any GUI option. Changing the color of the crosshair is probably not a very used feature, and doing it in python is simple enough.

I see the readthedocs tests are failing, but it looks more like an infrastructure problem.

**Comment by jamesobutler** [comment]
@RafaelPalomar Yeah the readthedocs are currently failing because your branch is 10 commits behind `main` which actually includes some fixes. If you rebase, then it should allow for the check to pass.

**Comment by RafaelPalomar** [comment]
> If you rebase, then it should allow for the check to pass.

DONE

**Review by jamesobutler — APPROVED** [review]

**Pull request merged**
