### PR TITLE
BUG: vtk_to_numpy function missing in Endoscopy

### PR DESCRIPTION
**Pull request by gaoyi**
the bug was introduced in a258951f473d74f24a93cff95673ea6163a7b5e1, and it's fixed here

corresponding to the Issue:

https://github.com/Slicer/Slicer/issues/6360

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution :pray: 

@gaoyi Could you also associated the email `gy99@tsinghua.org.cn` with your GitHub account ? That way your contribution will be linked with your account.

If not, we could also amend the commit to use your other email `Yi Gao <gaoyicn@outlook.com>`

Let us know what you would prefer.

**Comment by jcfr** [comment]
@lassoan @pieper That seems to be a good candidate for backporting to the 5.0 maintenance branch and generate `v5.0.3`

**Comment by pieper** [comment]
> backporting to the 5.0 maintenance branch and generate `v5.0.3`

I think yes but let's give it a week or so to see if here are other patches we want to include.

**Comment by lassoan** [comment]
Yes, creating 1-2 patch releases a couple of weeks apart sounds like a good plan to me. Do we just push the commits we want to include in the next patch release into the maintenance branch?

**Comment by jcfr** [comment]
> Do we just push the commits we want to include in the next patch release into the maintenance branch?

If the changes have been tested, directly pushing makes sense.

If not, proposing a pull-request is sensible.

Either way, the cherry-picked should be amended to include text like this after the title of the commit and before the body:

```
(cherry picked from commit <SHA[:9]>, PR #<N>)
```

For example, see https://github.com/Slicer/Slicer/commit/5a16fb6493ef31f48f3d473bb5c1ce5ab5f0a960

**Comment by lassoan** [comment]
Is this ready to be merged?

**Pull request merged**
