### PR TITLE
PERF: #4191 don't update widgets in batch mode

### PR DESCRIPTION
**Pull request by pieper**
This really improves the performance of LandmarkRegistration,
particularly when there are large numbers of fiducials
being manipulated.  I haven't seen any side effects.

### CODE REVIEW

**Comment by pieper** [comment]
@naucoin could you have a look at this and see if you expect any negative side-effects?  If there are, can you suggest any other strategies?

http://na-mic.org/Bug/view.php?id=4191

Corresponding fix in LandmarkRegistration is:

https://github.com/pieper/LandmarkRegistration/commit/5f412f9d4e4dbc2175d2a5f8c4ba1105c0543927

**Comment by naucoin** [comment]
will do!

**Comment by naucoin** [comment]
I tested out a few cases (loading from mrml, loading from file, scene view restores) and am not seeing any negative side effects, looks good to me.

**Comment by jcfr** [comment]
Good catch. :+1:

**Comment by pieper** [comment]
Excellent, thanks!  I'm going to go ahead and bump the LandmarkRegistration
hash and then commit so the user can test with tomorrow's nightly.

**Comment by lassoan** [comment]
Normally you when you discard an update event due to batch processing you would need to call SetUpdateFromMRMLRequested(1) -- or do a custom update widget from MRML in OnMRMLSceneEndBatchProcess().

So, unless you have a specific reason not do so, I would add SetUpdateFromMRMLRequested(1) before return.

See for example:
https://github.com/Slicer/Slicer/blob/master/Libs/MRML/DisplayableManager/vtkMRMLModelSliceDisplayableManager.cxx#L599

**Comment by jcfr** [comment]
> you would need to call SetUpdateFromMRMLRequested(1)

Good point. Handling of `UpdateFromMRMLRequested` happens [here](https://github.com/Slicer/Slicer/blob/e9619e379bfcda4bc791cb5679fabf6ae714d17f/Libs/MRML/DisplayableManager/vtkMRMLAbstractDisplayableManager.cxx#L848-L862)

**Comment by pieper** [comment]
Committed as r25094

Thanks for the help!

**Comment by jcfr** [comment]
Landmark registration test is now failing:

```
Two data sets loaded
test_LandmarkRegistrationAffine passed!
no fiducialList for volume PreDentalSurgery-transformed
no fiducialList for volume PostDentalSurgery
no fiducialList for volume PreDentalSurgery
starting test_LandmarkRegistrationThinPlate
Applying transform
no fiducialList for volume PreDentalSurgery-transformed
Exporting as a grid node
test_LandmarkRegistrationThinPlate passed!
Trying to access non-existent handle
```

**Comment by pieper** [comment]
Shoot - at first I thought this was maybe a timeout because the new test made too many fiducials, but this is a real side effect of the change.  Reverting the batch state checking does cause the test to pass, so I guess it's back to square one.  I'll look into this again when I have time.

**Comment by pieper** [comment]
Here's the stack trace from running the test - it seems a new seed can be added before an update has happened.

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libvtkSlicerMarkupsModuleMRMLDisplayableManager.dylib	0x000000012c608ac5 vtkInteractorObserver::EnabledOn() + 21
1   libvtkSlicerMarkupsModuleMRMLDisplayableManager.dylib	0x000000012c60e7bf vtkMRMLMarkupsFiducialDisplayableManager2D::SetNthSeed(int, vtkMRMLMarkupsFiducialNode*, vtkSeedWidget*) + 9743
2   libvtkSlicerMarkupsModuleMRMLDisplayableManager.dylib	0x000000012c616ace vtkMRMLMarkupsFiducialDisplayableManager2D::OnMRMLMarkupsNodeMarkupAddedEvent(vtkMRMLMarkupsNode*) + 1806
3   libvtkSlicerMarkupsModuleMRMLDisplayableManager.dylib	0x000000012c5f33bb vtkMRMLMarkupsDisplayableManager2D::ProcessMRMLNodesEvents(vtkObject*, unsigned long, void*) + 427
4   libMRMLLogic.dylib            	0x0000000107b12a0d vtkMRMLAbstractLogic::MRMLNodesCallback(vtkObject*, unsigned long, void*, void*) + 669 (vtkMRMLAbstractLogic.cxx:199)
5   libvtkCommon-6.3.1.dylib      	0x000000011aeec6b4 vtkCallbackCommand::Execute(vtkObject*, unsigned long, void*) + 84 (vtkCallbackCommand.cxx:43)
6   libMRMLCore.dylib             	0x000000010adc510f vtkEventBroker::InvokeObservation(vtkObservation*, unsigned long, void*) + 255 (vtkEventBroker.cxx:842)
7   libMRMLCore.dylib             	0x000000010adc496c vtkEventBroker::ProcessEvent(vtkObservation*, vtkObject*, unsigned long, void*) + 188 (vtkEventBroker.cxx:688)
8   libMRMLCore.dylib             	0x000000010adc5a80 vtkEventBroker::Callback(vtkObject*, unsigned long, void*, void*) + 512 (vtkEventBroker.cxx:914)
9   libvtkCommon-6.3.1.dylib      	0x000000011aeec6b4 vtkCallbackCommand::Execute(vtkObject*, unsigned long, void*) + 84 (vtkCallbackCommand.cxx:43)
10  libvtkCommon-6.3.1.dylib      	0x000000011ad56cff vtkSubjectHelper::InvokeEvent(unsigned long, void*, vtkObject*) + 2495 (vtkObject.cxx:616)
11  libvtkCommon-6.3.1.dylib      	0x000000011ad572b2 vtkObject::InvokeEvent(unsigned long, void*) + 66 (vtkObject.cxx:785)
12  libvtkSlicerMarkupsModuleMRML.dylib	0x000000012c845c8e vtkMRMLNode::InvokeCustomModifiedEvent(int, void*) + 78 (vtkMRMLNode.h:499)
13  libvtkSlicerMarkupsModuleMRML.dylib	0x000000012c85b29d vtkMRMLMarkupsNode::AddMarkup(Markup) + 125 (vtkMRMLMarkupsNode.cxx:494)
14  libvtkSlicerMarkupsModuleMRML.dylib	0x000000012c85ead8 vtkMRMLMarkupsNode::AddMarkupWithNPoints(int, std::string, vtkVector3d*) + 1288 (vtkMRMLMarkupsNode.cxx:517)
15  libvtkSlicerMarkupsModuleMRML.dylib	0x000000012c85ebbe vtkMRMLMarkupsNode::AddPointToNewMarkup(vtkVector3d, std::string) + 62 (vtkMRMLMarkupsNode.cxx:523)
16  libvtkSlicerMarkupsModuleMRML.dylib	0x000000012c85898a vtkMRMLMarkupsFiducialNode::AddFiducial(double, double, double, std::string) + 186 (vtkMRMLMarkupsFiducialNode.cxx:186)
17  libvtkSlicerMarkupsModuleMRML.dylib	0x000000012c858328 vtkMRMLMarkupsFiducialNode::AddFiducial(double, double, double) + 104 (vtkMRMLMarkupsFiducialNode.cxx:175)
18  libvtkSlicerMarkupsModuleMRMLPythonD.dylib	0x000000012c7b4361 PyvtkMRMLMarkupsFiducialNode_AddFiducial_s1(_object*, _object*) + 241 (vtkMRMLMarkupsFiducialNodePython.cxx:433)
19  libvtkSlicerMarkupsModuleMRMLPythonD.dylib	0x000000012c7b29c3 PyvtkMRMLMarkupsFiducialNode_AddFiducial(_object*, _object*) + 83 (vtkMRMLMarkupsFiducialNodePython.cxx:486)
20  libpython2.7.dylib            	0x000000011c0bbe44 PyEval_EvalFrameEx + 14356
21  libpython2.7.dylib            	0x000000011c0bf8df fast_function + 335
22  libpython2.7.dylib            	0x000000011c0bbb60 PyEval_EvalFrameEx + 13616
23  libpython2.7.dylib            	0x000000011c0bf8df fast_function + 335
24  libpython2.7.dylib            	0x000000011c0bbb60 PyEval_EvalFrameEx + 13616
25  libpython2.7.dylib            	0x000000011c0bf8df fast_function + 335
26  libpython2.7.dylib            	0x000000011c0bbb60 PyEval_EvalFrameEx + 13616
27  libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
28  libpython2.7.dylib            	0x000000011c05480c function_call + 364
29  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
30  libpython2.7.dylib            	0x000000011c0380d3 instancemethod_call + 179
31  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
32  libpython2.7.dylib            	0x000000011c0bf285 PyEval_CallObjectWithKeywords + 165
33  libPythonQt.dylib             	0x0000000108f488c5 PythonQtSignalTarget::call(_object*, PythonQtMethodInfo const*, void**, bool) + 629 (PythonQtSignalReceiver.cpp:124)
34  libPythonQt.dylib             	0x0000000108f485e6 PythonQtSignalTarget::call(void**) const + 70 (PythonQtSignalReceiver.cpp:55)
35  libPythonQt.dylib             	0x0000000108f4952c PythonQtSignalReceiver::qt_metacall(QMetaObject::Call, int, void**) + 268 (PythonQtSignalReceiver.cpp:263)
36  QtCore                        	0x0000000115384e72 QMetaObject::activate(QObject*, QMetaObject const*, int, void**) + 2146
37  libPythonQt.dylib             	0x0000000108fde073 PythonQtShell_QTimer::timerEvent(QTimerEvent*) + 563 (com_trolltech_qt_core2.cpp:2066)
38  QtCore                        	0x0000000115380aa0 QObject::event(QEvent*) + 432
39  libPythonQt.dylib             	0x0000000108fddad2 PythonQtShell_QTimer::event(QEvent*) + 722 (com_trolltech_qt_core2.cpp:2017)
40  QtGui                         	0x000000011441bb0d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 189
41  QtGui                         	0x000000011442046e QApplication::notify(QObject*, QEvent*) + 2030
42  libqSlicerBaseQTGUI.dylib     	0x00000001048e216f qSlicerApplication::notify(QObject*, QEvent*) + 63 (qSlicerApplication.cxx:346)
43  QtCore                        	0x000000011536c54c QCoreApplication::notifyInternal(QObject*, QEvent*) + 124
44  QtGui                         	0x000000011441bbac qt_sendSpontaneousEvent(QObject*, QEvent*) + 44
45  QtGui                         	0x00000001143d2aec QEventDispatcherMacPrivate::activateTimer(__CFRunLoopTimer*, void*) + 188
46  com.apple.CoreFoundation      	0x00007fff87c4d2e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
47  com.apple.CoreFoundation      	0x00007fff87c4cf73 __CFRunLoopDoTimer + 1059
48  com.apple.CoreFoundation      	0x00007fff87cc053d __CFRunLoopDoTimers + 301
49  com.apple.CoreFoundation      	0x00007fff87c08608 __CFRunLoopRun + 2024
50  com.apple.CoreFoundation      	0x00007fff87c07bd8 CFRunLoopRunSpecific + 296
51  com.apple.HIToolbox           	0x00007fff8bb9056f RunCurrentEventLoopInMode + 235
52  com.apple.HIToolbox           	0x00007fff8bb902ea ReceiveNextEventCommon + 431
53  com.apple.HIToolbox           	0x00007fff8bb9012b _BlockUntilNextEventMatchingListInModeWithFilter + 71
54  com.apple.AppKit              	0x00007fff8d9cc8ab _DPSNextEvent + 978
55  com.apple.AppKit              	0x00007fff8d9cbe58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
56  QtGui                         	0x00000001143d44b6 QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 1526
57  QtCore                        	0x000000011536b464 QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 68
58  QtCore                        	0x000000011536b814 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 324
59  QtGui                         	0x00000001148c6405 QDialog::exec() + 229
60  QtGui                         	0x00000001148c6e7e QDialog::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 174
61  QtGui                         	0x00000001148c6faf QDialog::qt_metacall(QMetaObject::Call, int, void**) + 223
62  libPythonQt.dylib             	0x0000000108f4b2f0 PythonQtCallSlot(PythonQtClassInfo*, QObject*, _object*, bool, PythonQtSlotInfo*, void*, _object**, void**, PythonQtPassThisOwnershipType*) + 1808 (PythonQtSlot.cpp:180)
63  libPythonQt.dylib             	0x0000000108f4d138 PythonQtSlotFunction_CallImpl(PythonQtClassInfo*, QObject*, PythonQtSlotInfo*, _object*, _object*, void*, void**, PythonQtPassThisOwnershipType*) + 1240 (PythonQtSlot.cpp:378)
64  libPythonQt.dylib             	0x0000000108f4c137 PythonQtMemberFunction_Call(PythonQtSlotInfo*, _object*, _object*, _object*) + 871 (PythonQtSlot.cpp:275)
65  libPythonQt.dylib             	0x0000000108f4bdc9 PythonQtSlotFunction_Call(_object*, _object*, _object*) + 57 (PythonQtSlot.cpp:262)
66  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
67  libpython2.7.dylib            	0x000000011c0bb41a PyEval_EvalFrameEx + 11754
68  libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
69  libpython2.7.dylib            	0x000000011c0bf806 fast_function + 118
70  libpython2.7.dylib            	0x000000011c0bbb60 PyEval_EvalFrameEx + 13616
71  libpython2.7.dylib            	0x000000011c0bf8df fast_function + 335
72  libpython2.7.dylib            	0x000000011c0bbb60 PyEval_EvalFrameEx + 13616
73  libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
74  libpython2.7.dylib            	0x000000011c05480c function_call + 364
75  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
76  libpython2.7.dylib            	0x000000011c0bbd63 PyEval_EvalFrameEx + 14131
77  libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
78  libpython2.7.dylib            	0x000000011c05480c function_call + 364
79  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
80  libpython2.7.dylib            	0x000000011c0380d3 instancemethod_call + 179
81  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
82  libpython2.7.dylib            	0x000000011c085ebb slot_tp_call + 171
83  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
84  libpython2.7.dylib            	0x000000011c0bb41a PyEval_EvalFrameEx + 11754
85  libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
86  libpython2.7.dylib            	0x000000011c05480c function_call + 364
87  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
88  libpython2.7.dylib            	0x000000011c0bbd63 PyEval_EvalFrameEx + 14131
89  libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
90  libpython2.7.dylib            	0x000000011c05480c function_call + 364
91  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
92  libpython2.7.dylib            	0x000000011c0380d3 instancemethod_call + 179
93  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
94  libpython2.7.dylib            	0x000000011c085ebb slot_tp_call + 171
95  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
96  libpython2.7.dylib            	0x000000011c0bb41a PyEval_EvalFrameEx + 11754
97  libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
98  libpython2.7.dylib            	0x000000011c05480c function_call + 364
99  libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
100 libpython2.7.dylib            	0x000000011c0bbd63 PyEval_EvalFrameEx + 14131
101 libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
102 libpython2.7.dylib            	0x000000011c05480c function_call + 364
103 libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
104 libpython2.7.dylib            	0x000000011c0380d3 instancemethod_call + 179
105 libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
106 libpython2.7.dylib            	0x000000011c085ebb slot_tp_call + 171
107 libpython2.7.dylib            	0x000000011c02b204 PyObject_Call + 100
108 libpython2.7.dylib            	0x000000011c0bb41a PyEval_EvalFrameEx + 11754
109 libpython2.7.dylib            	0x000000011c0bf8df fast_function + 335
110 libpython2.7.dylib            	0x000000011c0bbb60 PyEval_EvalFrameEx + 13616
111 libpython2.7.dylib            	0x000000011c0bf8df fast_function + 335
112 libpython2.7.dylib            	0x000000011c0bbb60 PyEval_EvalFrameEx + 13616
113 libpython2.7.dylib            	0x000000011c0b8346 PyEval_EvalCodeEx + 1894
114 libpython2.7.dylib            	0x000000011c0b7bd6 PyEval_EvalCode + 54
115 libpython2.7.dylib            	0x000000011c0fc75f PyRun_StringFlags + 127
116 libPythonQt.dylib             	0x0000000108e63e0c PythonQt::evalScript(_object*, QString const&, int) + 348 (PythonQt.cpp:876)
117 libPythonQt.dylib             	0x0000000108f47af6 PythonQtObjectPtr::evalScript(QString const&, int) + 70 (PythonQtObjectPtr.cpp:65)
118 libCTKScriptingPythonCore.0.1.dylib	0x00000001084f8c44 ctkAbstractPythonManager::executeString(QString const&, ctkAbstractPythonManager::ExecuteStringMode) + 228 (ctkAbstractPythonManager.cpp:266)
119 libqSlicerBaseQTCore.dylib    	0x0000000107648e85 qSlicerCoreApplication::handleCommandLineArguments() + 3877 (qSlicerCoreApplication.cxx:963)
120 libqSlicerBaseQTGUI.dylib     	0x00000001048e2c93 qSlicerApplication::handleCommandLineArguments() + 131 (qSlicerApplication.cxx:472)
121 libqSlicerBaseQTCore.dylib    	0x00000001076ac4fb qSlicerCoreApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 331 (moc_qSlicerCoreApplication.cxx:160)
122 QtCore                        	0x0000000115380d21 QObject::event(QEvent*) + 1073
123 QtCore                        	0x000000011536c840 QCoreApplication::event(QEvent*) + 16
124 QtGui                         	0x00000001144245cc QApplication::event(QEvent*) + 76
125 QtGui                         	0x000000011441bb0d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 189
126 QtGui                         	0x000000011442046e QApplication::notify(QObject*, QEvent*) + 2030
127 libqSlicerBaseQTGUI.dylib     	0x00000001048e216f qSlicerApplication::notify(QObject*, QEvent*) + 63 (qSlicerApplication.cxx:346)
128 QtCore                        	0x000000011536c54c QCoreApplication::notifyInternal(QObject*, QEvent*) + 124
129 QtCore                        	0x000000011536db00 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 736
130 com.apple.CoreFoundation      	0x00007fff87c16127 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
131 com.apple.CoreFoundation      	0x00007fff87c16080 __CFRunLoopDoObservers + 368
132 com.apple.CoreFoundation      	0x00007fff87c07bbf CFRunLoopRunSpecific + 271
133 com.apple.HIToolbox           	0x00007fff8bb9056f RunCurrentEventLoopInMode + 235
134 com.apple.HIToolbox           	0x00007fff8bb901ee ReceiveNextEventCommon + 179
135 com.apple.HIToolbox           	0x00007fff8bb9012b _BlockUntilNextEventMatchingListInModeWithFilter + 71
136 com.apple.AppKit              	0x00007fff8d9cc8ab _DPSNextEvent + 978
137 com.apple.AppKit              	0x00007fff8d9cbe58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
138 com.apple.AppKit              	0x00007fff8d9c1af3 -[NSApplication run] + 594
139 QtGui                         	0x00000001143d45e0 QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 1824
140 QtCore                        	0x000000011536b464 QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 68
141 QtCore                        	0x000000011536b814 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 324
142 QtCore                        	0x000000011536e08c QCoreApplication::exec() + 188
143                               	0x0000000104500cb3 (anonymous namespace)::SlicerAppMain(int, char**) + 6099
144                               	0x00000001044ff4d2 main + 34
145 libdyld.dylib                 	0x00007fff8822d5c9 start + 1

**Comment by pieper** [comment]
I'm thinking now that I should keep a copies of the Markups node, make all the changes there, and then do a bulk operation to copy them into the scene so the displayable manager can do the update all at once.

We should also think about looking at the Markups displayable manager code to see if we can optimize it.  In the original design discussions we talked about the update from mrml being a pretty lightweight operation that just set parameters of a rendering pipeline so that the real work would happen when there is finally a render.  But from profiling the code it seems there are a lot of operations going on, particularly when adding or removing view node ids and this is where things bog down in the LandmarkRegistration use case.

**Comment by lassoan** [comment]
We usually disable all updates during batch operations using StartModify/EndModify. Doesn't this solve performance problems in your use case?

**Comment by pieper** [comment]
Interesting idea - I had been putting the scene in Batch Processing state but didn't try working at the node level.  Looks like adding and removing view node ids on a display node invokes a normal ModifiedEvent so this should work.  Thanks!

**Comment by lassoan** [comment]
Batch processing state enter/exit is an expensive operation, it's only worth to use it when many nodes are manipulated added/removed. For node-level batch processing Start/EndModify is the most suitable mechanism. Temporarily overriding view IDs has similar performance but such techniques fail when multiple modules operate on the same node; while Start/EndModify is safe to use, even for multiple modules simultaneously.

**Comment by pieper** [comment]
Thanks for the suggestion Andras - I now recall writing those StartModify/EndModify methods many years ago : )

It turns out I found that I was calling the same code far too many times (for each fiducial in a list instead of once per list).  I've committed this change and hopefully that will address the performance issue.

**Pull request closed without merging**
