### PR TITLE
COMP: Update python packages to latest

### PR DESCRIPTION
**Pull request by jamesobutler**
Python packages were last updated on March 7th 2023 (https://github.com/Slicer/Slicer/commit/090d3c7d6457387dee5949e468a6a2a903e0e18b). This PR updates python packages to their latest versions. This type of update is something I usually do on about a quarterly cadence (every 3 months). I am a little later this time as it has been about 3.5 months

Note that SimpleITK isn't being updated here as we build it from source rather than using the provided whl on pypi.

```
PS C:\Users\butlej30383\AppData\Local\slicer.org\Slicer 5.3.0-2023-06-21\bin> ./PythonSlicer.exe "C:\Slicer\Utilities\Scripts\python_package_updater.py"
Searching external projects in C:\Slicer\SuperBuild
Validate external projects

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python-real.exe -m pip install --upgrade pip
Package            Version         Latest   Type
------------------ --------------- -------- -----
certifi            2022.12.7       2023.5.7 wheel
charset-normalizer 3.1.0           3.2.0    wheel
Deprecated         1.2.13          1.2.14   wheel
numpy              1.24.2          1.25.1   wheel
packaging          23.0            23.1     wheel
Pillow             9.4.0           10.0.0   wheel
pip                23.0.1          23.1.2   wheel
pydicom            2.3.1           2.4.1    wheel
PyGithub           1.58.0          1.59.0   wheel
PyJWT              2.6.0           2.7.0    wheel
pyparsing          3.0.9           3.1.0    wheel
requests           2.28.2          2.31.0   wheel
scipy              1.10.1          1.11.1   wheel
setuptools         67.5.1          68.0.0   wheel
SimpleITK          2.2.0rc2.dev368 2.2.1    wheel
urllib3            1.26.14         2.0.3    wheel
wheel              0.38.4          0.40.0   wheel

  certifi==2023.5.7 --hash=sha256:c6c2e98f5c7869efca1f8916fed228dd91539f9f1b444c314c06eef02980c716
  # Hashes correspond to the following packages:
  #  - charset_normalizer-3.2.0-cp39-cp39-macosx_10_9_universal2.whl
  #  - charset_normalizer-3.2.0-cp39-cp39-macosx_10_9_x86_64.whl
  #  - charset_normalizer-3.2.0-cp39-cp39-macosx_11_0_arm64.whl
  #  - charset_normalizer-3.2.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - charset_normalizer-3.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - charset_normalizer-3.2.0-cp39-cp39-musllinux_1_1_aarch64.whl
  #  - charset_normalizer-3.2.0-cp39-cp39-musllinux_1_1_x86_64.whl
  #  - charset_normalizer-3.2.0-cp39-cp39-win_amd64.whl
  #  - charset_normalizer-3.2.0-py3-none-any.whl
  charset-normalizer==3.2.0 --hash=sha256:855eafa5d5a2034b4621c74925d89c5efef61418570e5ef9b37717d9c796419c \
                            --hash=sha256:203f0c8871d5a7987be20c72442488a0b8cfd0f43b7973771640fc593f56321f \
                            --hash=sha256:e857a2232ba53ae940d3456f7533ce6ca98b81917d47adc3c7fd55dad8fab858 \
                            --hash=sha256:5e86d77b090dbddbe78867a0275cb4df08ea195e660f1f7f13435a4649e954e5 \
                            --hash=sha256:8700f06d0ce6f128de3ccdbc1acaea1ee264d2caa9ca05daaf492fde7c2a7200 \
                            --hash=sha256:c1c76a1743432b4b60ab3358c937a3fe1341c828ae6194108a94c69028247f22 \
                            --hash=sha256:1249cbbf3d3b04902ff081ffbb33ce3377fa6e4c7356f759f3cd076cc138d020 \
                            --hash=sha256:7095f6fbfaa55defb6b733cfeb14efaae7a29f0b59d8cf213be4e7ca0b857b80 \
                            --hash=sha256:8e098148dd37b4ce3baca71fb394c81dc5d9c7728c95df695d2dca218edf40e6
  Deprecated==1.2.14 --hash=sha256:6fac8b097794a90302bdbb17b9b815e732d3c4720583ff1b198499d78470466c
  # Hashes correspond to the following packages:
  #  - numpy-1.25.1-cp39-cp39-macosx_10_9_x86_64.whl
  #  - numpy-1.25.1-cp39-cp39-macosx_11_0_arm64.whl
  #  - numpy-1.25.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - numpy-1.25.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - numpy-1.25.1-cp39-cp39-musllinux_1_1_x86_64.whl
  #  - numpy-1.25.1-cp39-cp39-win_amd64.whl
  numpy==1.25.1 --hash=sha256:3d7abcdd85aea3e6cdddb59af2350c7ab1ed764397f8eec97a038ad244d2d105 \
                --hash=sha256:1a180429394f81c7933634ae49b37b472d343cccb5bb0c4a575ac8bbc433722f \
                --hash=sha256:d412c1697c3853c6fc3cb9751b4915859c7afe6a277c2bf00acf287d56c4e625 \
                --hash=sha256:20e1266411120a4f16fad8efa8e0454d21d00b8c7cee5b5ccad7565d95eb42dd \
                --hash=sha256:f76aebc3358ade9eacf9bc2bb8ae589863a4f911611694103af05346637df1b7 \
                --hash=sha256:1d5d3c68e443c90b38fdf8ef40e60e2538a27548b39b12b73132456847f4b631
  packaging==23.1 --hash=sha256:994793af429502c4ea2ebf6bf664629d07c1a9fe974af92966e4b8d2df7edc61
  # Hashes correspond to the following packages:
  #  - Pillow-10.0.0-cp39-cp39-macosx_10_10_x86_64.whl
  #  - Pillow-10.0.0-cp39-cp39-macosx_11_0_arm64.whl
  #  - Pillow-10.0.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - Pillow-10.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - Pillow-10.0.0-cp39-cp39-manylinux_2_28_aarch64.whl
  #  - Pillow-10.0.0-cp39-cp39-manylinux_2_28_x86_64.whl
  #  - Pillow-10.0.0-cp39-cp39-musllinux_1_1_aarch64.whl
  #  - Pillow-10.0.0-cp39-cp39-musllinux_1_1_x86_64.whl
  #  - Pillow-10.0.0-cp39-cp39-win_amd64.whl
  Pillow==10.0.0 --hash=sha256:9211e7ad69d7c9401cfc0e23d49b69ca65ddd898976d660a2fa5904e3d7a9baa \
                 --hash=sha256:faaf07ea35355b01a35cb442dd950d8f1bb5b040a7787791a535de13db15ed90 \
                 --hash=sha256:c9f72a021fbb792ce98306ffb0c348b3c9cb967dce0f12a49aa4c3d3fdefa967 \
                 --hash=sha256:9f7c16705f44e0504a3a2a14197c1f0b32a95731d251777dcb060aa83022cb2d \
                 --hash=sha256:76edb0a1fa2b4745fb0c99fb9fb98f8b180a1bbceb8be49b087e0b21867e77d3 \
                 --hash=sha256:368ab3dfb5f49e312231b6f27b8820c823652b7cd29cfbd34090565a015e99ba \
                 --hash=sha256:608bfdee0d57cf297d32bcbb3c728dc1da0907519d1784962c5f0c68bb93e5a3 \
                 --hash=sha256:5c6e3df6bdd396749bafd45314871b3d0af81ff935b2d188385e970052091017 \
                 --hash=sha256:7be600823e4c8631b74e4a0d38384c73f680e6105a7d3c6824fcf226c178c7e6
  pip==23.1.2 --hash=sha256:3ef6ac33239e4027d9a5598a381b9d30880a1477e50039db2eac6e8a8f6d1b18
  pydicom==2.4.1 --hash=sha256:301cbf8bf2cca95643ccf678f5b0cfecfd15974cd27e199f0856c44694852c0e
  PyGithub==1.59.0 --hash=sha256:126bdbae72087d8d038b113aab6b059b4553cb59348e3024bb1a1cae406ace9e
  PyJWT==2.7.0 --hash=sha256:ba2b425b15ad5ef12f200dc67dd56af4e26de2331f965c5439994dad075876e1
  pyparsing==3.1.0 --hash=sha256:d554a96d1a7d3ddaf7183104485bc19fd80543ad6ac5bdb6426719d766fb06c1
  requests==2.31.0 --hash=sha256:58cd2187c01e70e6e26505bca751777aa9f2ee0b7f4300988b709f44e013003f
  # Hashes correspond to the following packages:
  #  - scipy-1.11.1-cp39-cp39-macosx_10_9_x86_64.whl
  #  - scipy-1.11.1-cp39-cp39-macosx_12_0_arm64.whl
  #  - scipy-1.11.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - scipy-1.11.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - scipy-1.11.1-cp39-cp39-musllinux_1_1_x86_64.whl
  #  - scipy-1.11.1-cp39-cp39-win_amd64.whl
  scipy==1.11.1 --hash=sha256:39154437654260a52871dfde852adf1b93b1d1bc5dc0ffa70068f16ec0be2624 \
                --hash=sha256:b588311875c58d1acd4ef17c983b9f1ab5391755a47c3d70b6bd503a45bfaf71 \
                --hash=sha256:d51565560565a0307ed06fa0ec4c6f21ff094947d4844d6068ed04400c72d0c3 \
                --hash=sha256:b41a0f322b4eb51b078cb3441e950ad661ede490c3aca66edef66f4b37ab1877 \
                --hash=sha256:396fae3f8c12ad14c5f3eb40499fd06a6fef8393a6baa352a652ecd51e74e029 \
                --hash=sha256:be8c962a821957fdde8c4044efdab7a140c13294997a407eaee777acf63cbf0c
  setuptools==68.0.0 --hash=sha256:11e52c67415a381d10d6b462ced9cfb97066179f0e871399e006c4ab101fc85f
  # Hashes correspond to the following packages:
  #  - SimpleITK-2.2.1-cp39-cp39-macosx_10_9_x86_64.whl
  #  - SimpleITK-2.2.1-cp39-cp39-macosx_11_0_arm64.whl
  #  - SimpleITK-2.2.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - SimpleITK-2.2.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - SimpleITK-2.2.1-cp39-cp39-win_amd64.whl
  SimpleITK==2.2.1 --hash=sha256:e032bb2e54b96ce426187f07ce5dd9733077b18005399f6fbbcd4765b386299f \
                   --hash=sha256:3ffec97db30f923788f4e19b5a6e708d68afcce8f89cb54d7c976bd099b9a580 \
                   --hash=sha256:d6f58cdf90dbd0b84be68e0b46545c92f28c650d86e9f24acb91ad1c27416357 \
                   --hash=sha256:9b90dfd94cba0b068bacddaf2550d96df2683df830b9ee71cd9440e64c701196 \
                   --hash=sha256:7e20bbc467a8fff15978fee34a97c851ec3d0caed2d01929f600a13a0ff2f955
  urllib3==2.0.3 --hash=sha256:48e7fafa40319d358848e1bc6809b208340fafe2096f1725d05d67443d0483d1
  wheel==0.40.0 --hash=sha256:d236b20e7cb522daf2390fa84c55eea81c5c30190f90f29ae2ca1ad8355bf247
```

- numpy 1.25.0 removed support for Nose.
- As of PyGithub 1.58.1, it now requires the cryptography dependency

Changes to note with the numpy version update from 1.24 to 1.25 are the following:
- https://numpy.org/doc/stable/release/1.25.0-notes.html#deprecations
- https://numpy.org/doc/stable/release/1.25.0-notes.html#expired-deprecations

Changes to note with the scipy version update from 1.10 to 1.11 are the following:
- https://scipy.github.io/devdocs/release/1.11.0-notes.html#deprecated-features
- https://scipy.github.io/devdocs/release/1.11.0-notes.html#expired-deprecations

Since `scipy` is not directly used in Slicer core, we may have to update extensions to account for changes.

Additionally re https://github.com/Slicer/Slicer/pull/6590#issuecomment-1282762511, on macOS, some of the dependent libraries shipped with scipy have changed
```
Directory: scipy-1.10.1-cp39-cp39-macosx_10_9_x86_64\scipy\.dylibs
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         3/6/2023  8:54 PM         313744 libgcc_s.1.dylib
-a----         3/6/2023  8:54 PM        1588608 libgfortran.3.dylib
-a----         3/6/2023  8:54 PM       66118352 libopenblas.0.dylib
-a----         3/6/2023  8:54 PM         301952 libquadmath.0.dylib

Directory: scipy-1.11.1-cp39-cp39-macosx_10_9_x86_64\scipy\.dylibs
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         6/28/2023  10:42 PM         126416 libgcc_s.1.1.dylib
-a----         6/28/2023  10:42 PM        6786304 libgfortran.5.dylib
-a----         6/28/2023  10:42 PM       66689840 libopenblas.0.dylib
-a----         6/28/2023  10:42 PM         352704 libquadmath.0.dylib
```

## Testing Results:
Windows
- [X] Build ✔️  
- [X] Tests ✔️

### CODE REVIEW

**Comment by jcfr** [comment]
Changes to note with the urllib3 version update from `1.26.14` to `2.0.3` are the following:
* https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html
* https://urllib3.readthedocs.io/en/stable/changelog.html

**Comment by jamesobutler** [comment]
> numpy 1.25.0 removed support for Nose.

The removal of `nose` since it is no longer a dependency of `numpy` has resulted in the following test failure. This is the only direct usage of `nose` in Slicer core.

https://github.com/Slicer/Slicer/blob/84d5c8dea9fefb2ab562dd6fb65bdad22b48da30/Applications/SlicerApp/Testing/Python/DWMRIMultishellIOTests.py#L104

**Comment by jcfr** [comment]
>  removal of `nose` [...] has resulted in the following test failure

This should be addressed in:
* https://github.com/Slicer/Slicer/pull/7052

**Comment by jamesobutler** [comment]
@jcfr Although this is superbuild update, how is the "Build Slicer" status check supposed to pass since it is a required status check? I'm surprised that it is sitting in a "Waiting..." state as well.

**Comment by jcfr** [comment]
Topic re-based :heavy_check_mark:
Windows build :heavy_check_mark: (@jamesobutler)
Linux build :heavy_check_mark: (@jcfr)

**Review by jcfr — APPROVED** [review]
Let's monitor how macOS behave in the next round of preview builds.

**Pull request merged**
