### PR TITLE
fix docs for dataframeFromMarkups

### PR DESCRIPTION
**Pull request by fbordignon**

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Good catch, thank you.

**Review by lassoan — CHANGES_REQUESTED** [review]
Looks good, except the commit message must start with `DOC: `. Could you please update that?

**Comment by fbordignon** [comment]
ok, sorry. I've edited this online at github. Fixed now. Thanks!

**Comment by jamesobutler** [comment]
Commit check failed because it needs to be the following `DOC:fix...` -> `DOC: Fix...`. A space between the prefix and the text after the prefix being capitalized.

**Review by lassoan — APPROVED** [review]

**Pull request merged**
