### PR TITLE
ENH: Update SlicerExecutionModel version

### PR DESCRIPTION
**Pull request by bpaniagua**
```
git shortlog 983d2112ec431af20cafa49ca6cf7bd1a777869a..62d0121dbb0fb057ebbd7c9ab84520accacec8bc --no-merges
Jean-Christophe Fillion-Robin (3):
      gitignore: Add CMakeLists.txt.user
      docker: Associate build-time metadata with the image
      README: Add docker badges

Johan Andruejol (1):
      ENH: GenerateCLP: Include jsoncpp include dirs in UseGenerateCLP.cmake.in

Stephen Aylward (1):
      WARN: Rename isPresent variables to avoid hidden local variable
```

### CODE REVIEW

**Comment by bpaniagua** [comment]
@jcfr Could you please have a look into this PR? Thanks

**Comment by jcfr** [comment]
Looks good.

Please, after amending the commit (see below), consider integrating using:

```
git svn dcommit
```

Nitpick:

```
git shortlog 983d2112ec431af20cafa49ca6cf7bd1a777869a..62d0121dbb0fb057ebbd7c9ab84520accacec8bc --no-merges
```

->

```
git shortlog 983d211..62d0121 --no-merges
```

**Comment by bpaniagua** [comment]
@jcfr I amended the commit. Does all look good?

**Comment by jcfr** [comment]
Thanks. Looks great :+1:

**Comment by bpaniagua** [comment]
This change was pushed 
http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25493

**Pull request closed without merging**
