### PR TITLE
ENH: add support for Scanco file format

### PR DESCRIPTION
**Pull request by dzenanz**
This file format is frequently used in small animal CT imaging.

### CODE REVIEW

**Review by jcfr — COMMENTED** [review]
Thanks for the patch. Could you update the documentation ? See https://slicer.readthedocs.io/en/latest/user_guide/data_loading_and_saving.html#supported-data-formats

**Comment by dzenanz** [comment]
Doc update added.

**Comment by lassoan** [comment]
Thank you! It seems that this module can read/write a couple of more file extensions:

https://github.com/KitwareMedical/ITKIOScanco/blob/a913b8736e53901edef3be2529d1eacdb3e5d88b/src/itkScancoImageIO.cxx#L53-L56

Is there a specific reason for just adding .isq to Slicer?

**Comment by dzenanz** [comment]
The other formats are less well supported, and I don't have testing data for them. So I would rather not advertised them as "supported".

**Review by lassoan — APPROVED** [review]
Thank you, it looks good to me.

**Comment by dzenanz** [comment]
Thank you for merging, and quickly too.

**Pull request merged**
