### PR TITLE
4398 fix bzip2 release debug error

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
This should fix https://issues.slicer.org/view.php?id=4398

See also https://discourse.slicer.org/t/slicer-debug-mode-buid-error-in-2017-07-23-version-on-windows-due-to-bzip2/751/3

@lassoan  After you confirm it addresses the issue on your workstation, I will integrate :+1:

**Comment by lassoan** [comment]
Thank you, the build was successful! (I did not start from a clean build, now I start a build from scratch in both debug and release)

**Comment by jcfr** [comment]
Great. Thanks for the feedback.

I will plan to integrate at 10pm unless the builds fail.

**Comment by jcfr** [comment]
Integrated in [r26174](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26174)

**Pull request closed without merging**
