### PR TITLE
Improve volume rendering presets

### PR DESCRIPTION
**Pull request by lassoan**
Improve appearance of volume rendering preset selector and add micro-CT presets. Icons are now 2x higher resolution (so they don't look small or blurred anymore on high-resolution screens), larger, and labeled.

Before: (small icons, no text)

image

With changes in this pull request: (large, sharp icons, labelled)

image

Some of the existing presets don't seem to be very useful to me and we may consider removing in the future, but I did not want to do too many changes in one pull request.

### CODE REVIEW

**Comment by lassoan** [comment]
@muratmaga This pull requests adds the 3 presets in SlicerMorph as MicroCT-bone-LDR, MicroCT-bone-HDR, MicroCT-mouse. LDR/HDR = low/high dynamic range.

I was not sure about the mouse preset. Is if for micro-CT? Is it for a specific mouse dataset or we can specify a broader application area and choose a name that better reflects that? Should it be just Micro-CT-bone-LDR2?

The preset names like `MicroCT-bone-LDR` are a bit too long and so truncated. Should we use `uCT-bone-LDR` instead?

Instead LDR/HDR (which may be misintepreted as low-dose-rate/high-dose-rate, and a bit long), should we use other acronyms, such as `NR`/`WR` (narrow/wide range), `LB`/`HB` (low/high bit depth)? I wanted to avoid the 8-bit/16-bit as it might be too technical, but maybe using that (`8b`/`16b`) could work, too. Any other ideas?

**Review by pieper — DISMISSED** [review]
LGTM 👍

**Review by jamesobutler — COMMENTED** [review]
Can we make sure the visible labeling is unique? In the provide screenshot of the changes there are multiple presets labeled as "CT-Coronary-..."

**Comment by lassoan** [comment]
> Can we make sure the visible labeling is unique? In the provided screenshot of the changes there are multiple presets where the visible text is "CT-Coronary-..."

It would be nice, but for that we would need to change the preset name, which would be a little bit risky (some extensions may look up the preset by name). A better solution could be to separate the preset ID (or name) from the displayed label. This is also needed for internationalization, but we don't have a design yet for translating MRML/logic content.

Since this is already an improvement (previously there was no label at all), you can see the complete label when you hover over a preset, and you can also distinguish presets by appearance (difference between presets variants is mainly the color tone), I would incline not to hold up this pull request, but get back to this when we implement translation of VR preset names.

**Comment by lassoan** [comment]
> Is reducing the text size label or adjusting the spacing of the grid possible so that the preset name isn't cut off? Currently there is elided text resulting in multiple labels of "CT-Coronary...".

Probably it is possible to disable eliding, but that would mean lots of wasted space (the longest name would increase the size of every item).

We could increase the icon size to avoid truncated text on some displays in some languages, but it would be very hard to prevent this from happening in all environments.

Reducing point size of the text is not a sustainable option (we cannot reduce the font size whenever the space is tight).

**Comment by jamesobutler** [comment]
My only brainstorm idea for the display of the presets would be like what is done for the Color table selection where the icons are displayed to the left of the text in a single vertical column list. Then this accommodates longer names without having to create abbreviations that may be misinterpreted or run into text elide issues after only ~12 characters.
image

**Comment by muratmaga** [comment]
> Instead LDR/HDR (which may be misintepreted as low-dose-rate/high-dose-rate, and a bit long), should we use other acronyms, such as `NR`/`WR` (narrow/wide range), `LB`/`HB` (low/high bit depth)? I wanted to avoid the 8-bit/16-bit as it might be too technical, but maybe using that (`8b`/`16b`) could work, too. Any other ideas?

I personally think 8bit/16bit is more straightforward than LDR/HDR but either way is fine.

**Comment by jcfr** [comment]
> in multiple labels of "CT-Coronary...".

Since a tooltip is displayed with the fullname, I think the proposed solution is an improvement and worth the tradeoff. Especially considering no text is being displayed in the current version.

**Review by jcfr — APPROVED** [review]
In addition of this great improvement, would it be possible to update [developer_guide/modules/volumerendering](https://slicer.readthedocs.io/en/latest/developer_guide/modules/volumerendering.html#examples) by:
* briefly describing `presets.xml`
* explain how to re-generate the thumbnail (may be by linking to an entry in the script repository?)

Related feature requests:
* https://github.com/Slicer/Slicer/issues/5206
* https://github.com/Slicer/Slicer/issues/6305

**Comment by lassoan** [comment]
OK, we can use the 8bit and 16bit in the preset name. I will add 8 and 16 to the icon to avoid the need to replace the icon for different languages.

**Comment by lassoan** [comment]
@muratmaga can you comment the mouse preset? See my questions above.

**Comment by muratmaga** [comment]
> I was not sure about the mouse preset. Is if for micro-CT? Is it for a specific mouse dataset or we can specify a broader application area and choose a name that better reflects that? Should it be just Micro-CT-bone-LDR2?

Sorry I missed this. It is for microCT too. it is just a steeper jump than the other 8 bit image, and tries to render the teeth more white than the rest of the specimen. it should be applicable to other microCT scans of bones too. Micro-CT-bone-LDR2 is fine. Or Micro-CT-skull-8bit...

**Comment by lassoan** [comment]
Thanks for all the reviews and feedbacks. I've added a note about changing VR preset labels to https://github.com/Slicer/Slicer/issues/6647#issuecomment-1373094102.

**Pull request merged**
