### PR TITLE
ENH: Updated the git tag for ITK

### PR DESCRIPTION
**Pull request by sumedhasingla**
$ git shortlog 7db7b60..16df9b6 --no-merges

Sumedha Singla (1):
            ENH: Updated the git tag for the ITK-Minimal-Path external module.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the update :+1: 

For sake of consistency, consider fixing the commit message following this guideline: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Versioning#Project_fork

**Comment by jcfr** [comment]
@msmolens  Let me know what you think of http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Versioning#Project_fork

I also wonder if we could find a better home or reference it from the developer faq ...

**Comment by msmolens** [comment]
@jcfr Looks good. The only thing that is unclear is the line:

> If the copied log or message reference a sha1 the project ...

I'm okay with where that information is located on the wiki; I was able to discover it from the main Developer page on the first try ("Build system... > Versioning")! Great job on the reorganization.

**Comment by jcfr** [comment]
Thanksk @msmolens  I tweaked it. Let me know what you think.

> was able to discover it from the main Developer page on the first try ("Build system... > Versioning")! Great job on the reorganization.

:tada:

**Comment by sumedhasingla** [comment]
@jcfr Can you please merge the pull request.

**Comment by jcfr** [comment]
Integrated in [25198](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25198)

Side comments:

There is also this section in the style guide, i just updated it to be more coherent and link to the Versionning/Project fork one: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Style_Guide#Importing_changes_from_external_project.2Frepository

@sumedhasingla  I just added an other [Caveats](http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Versioning#Caveats), basically prefer the form `ENH: Update ITK to <action verb>` instead of `ENH: Updated the git tag for ITK`.

Tense should also be imperative.

**Pull request closed without merging**
