### PR TITLE
ENH: Build SlicerApp-real.exe as a console application to enable console output

### PR DESCRIPTION
**Pull request by lassoan**
If SlicerApp-real.exe is built as a console application then it is possible to capture and redirect its output (to files, display, any other software), and test outputs also become visible on dashboard builds.

If the launcher is still built as a Windows GUI application then no command console is displayed when Slicer is started.

Added instructions (in Docs\developer_guide\debugging\overview.md) for accessing the console output when launcher is a Windows GUI application.

re #2934

### CODE REVIEW

**Comment by lassoan** [comment]
After this is integrated, the AppLauncher could be updated to detect if a console is available (using [AttachConsole](https://docs.microsoft.com/en-us/windows/console/attachconsole)) and if that's the case then write output to is (using [WriteConsoleOutput](https://docs.microsoft.com/en-us/windows/console/writeconsoleoutput)). This would make Slicer.exe fully behave as a console application when a console is available but would not create a console when Slicer.exe is started from GUI.

**Comment by pieper** [comment]
Sounds like really nice behavior.

**Comment by lassoan** [comment]
@jcfr if you don't have any objections then I'll merge this tomorrow.

**Review by sjh26 — APPROVED** [review]
🦖

**Comment by lassoan** [comment]
@sjh26 thanks for the review, I'll merge it now.

**Pull request merged**
