### PR TITLE
BUG: Fix color legend visibility on non-standard slice views

### PR DESCRIPTION
**Pull request by MichaelColonel**
Possible fix for issue #6827. Some minor bugs can be still present.

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
Thanks a lot for working on this. Your fix was very useful in showing what went wrong and a potential way to address the problem. However, I've found that a simpler fix could be to ensure that the slice logic is available by the time the displayable manager is initialized. I've pushed that fix on your branch. It would be great if you could give it some testing to see if it fixes all color legend initialization issues related to layout switching and if it does not introduce any regressions.

If everything works well then we'll have to squash the commits and merge.

**Comment by MichaelColonel** [comment]
Everything works correctly except one general workflow pattern when color legend isn't visible: Select Layout -> Load Volume -> Create Color Legend -> Select other layout with more slice views -> Add volume to an any newly added slice.

``` python
# Start Slicer so that on startup it is the Four-Up Layout
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutFourUpView)

import SampleData
sampleDataLogic = SampleData.SampleDataLogic()
mrHead = sampleDataLogic.downloadMRHead()

clDisplayNode = slicer.modules.colors.logic().AddDefaultColorLegendDisplayNode(mrHead)
clDisplayNode.SetVisibility(True)


slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutThreeOverThreeView)

for color in ["Red+", "Yellow+"]:
  slicer.app.layoutManager().sliceWidget(color).sliceLogic().GetSliceCompositeNode().SetForegroundVolumeID(mrHead.GetID())
```
Screenshot1

If delete a color legend and recreate it again, the color legend displayed as it should.

``` python
# Start Slicer so that on startup it is the Four-Up Layout
slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutFourUpView)

import SampleData
sampleDataLogic = SampleData.SampleDataLogic()
mrHead = sampleDataLogic.downloadMRHead()

clDisplayNode = slicer.modules.colors.logic().AddDefaultColorLegendDisplayNode(mrHead)
clDisplayNode.SetVisibility(True)


slicer.app.layoutManager().setLayout(slicer.vtkMRMLLayoutNode.SlicerLayoutThreeOverThreeView)

for color in ["Red+", "Yellow+"]:
  slicer.app.layoutManager().sliceWidget(color).sliceLogic().GetSliceCompositeNode().SetForegroundVolumeID(mrHead.GetID())


clDisplayNode.GetScene().RemoveNode(clDisplayNode)
clDisplayNode = slicer.modules.colors.logic().AddDefaultColorLegendDisplayNode(mrHead)
clDisplayNode.SetVisibility(True)
```
Screenshot2

**Comment by jamesobutler** [comment]
@lassoan I can confirm that your current changes fixed the situation I described in #6827. I also can replicate the issue that @MichaelColonel observed in the above comment. Do you know what is going wrong in this situation?

**Comment by MichaelColonel** [comment]
After some additional tests and debugging the main problem remains. The `SliceCompositeNode` is invalid and color legend actor is updated earlier than non-standard slice composite node were added to the scene.

**Comment by MichaelColonel** [comment]
I've update this PR a little, so when one set all manually, Slicer shows color legend for non-standard views correctly.
It doesn't work from the script though.
So for the script rule of thumb should be:
1. Setup slice layout;
2. Everything else.

**Comment by lassoan** [comment]
> updated earlier than non-standard slice composite node were added to the scene.

Would observing "node added" events solve the issue? We could update the display pipeline when we detect that a composite node is added to the scene.

**Comment by MichaelColonel** [comment]
> Would observing "node added" events solve the issue?

I will try it later.

I've made some minor changes, and now color legend should be displayed correctly in 3DSlicer, except execution from the script.

**Comment by MichaelColonel** [comment]
> We could update the display pipeline when we detect that a composite node is added to the scene.

How it can be done, i mean the pipeline update? Another question. What event is invoked when volume node is added for removed from the SliceCompositeNode foreground or background?

**Review by jamesobutler — APPROVED** [review]
I can confirm the current changes in this PR
- Fix the issue that the script provided in https://github.com/Slicer/Slicer/issues/6827#issue-1582742933 previously caused
- The issue described in https://github.com/Slicer/Slicer/pull/6836#issuecomment-1447957273 still exists.

@lassoan Since the current changes fix my original issue, I think it would be good to integrate these changes as part of continuous improvement. It is better to have some fix than no fix. It appears questions still arise on how to address the second issue that still exists here. A new GitHub issue can be generated for this remaining work or you can issue a change if you see an obvious set of next steps.

**Pull request merged**
