### PR TITLE
BUG: Fixed SlicerApp-real.exe.exe filename on Windows

### PR DESCRIPTION
**Pull request by lassoan**
Removed the double .exe extensions from the main application name.
Before the fix: SlicerApp-real.exe.exe
After the fix: SlicerApp-real.exe

### CODE REVIEW

**Comment by jcfr** [comment]
:+1:  Good catch. Thanks for the fix.

Before integrating to svn, could you also add the following text to the commit message:

```
This commit fixes a regression introduced in r24024 (ENH: Add
slicerMacroBuildAppLibrary and slicerMacroBuildApplication) where
it was wrongly assumed that specifying executable extension when
setting the OUTPUT_NAME target property was required.
```

**Comment by lassoan** [comment]
updated commit message as requested

**Comment by jcfr** [comment]
:+1:  Feel free to `git svn dcommit`

**Comment by lassoan** [comment]
git-svn does not work on my computer, I would need to copy the change manually to SVN

**Comment by jcfr** [comment]
Integrated in [r24206](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24206)

As a side note, extending git interface with `hub` makes it very easy to cherry pick commit from a pull request. See https://hub.github.com/ 

For example I just did:

```
$ git cherry-pick https://github.com/lassoan/Slicer/commit/136d20f10027e2ef169ec4c063c49cc2c7994c48
[...]
$ git log
[...] 
$ git svn dcommit --add-author-from
[...]
```

**Pull request closed without merging**
