### PR TITLE
Stop subject hierarchy node duplication

### PR DESCRIPTION
**Pull request by cpinter**
Implementation of subject hierarchy 2.0. In a nutshell, what it offers in addition to the current subject hierarchy is:
- Considerably increased speed due to the single subject hierarchy node (instead of duplicate SH node for each data node)
- It is enabled by default, because it does not clutter the MRML scene and there are no special mechanisms to support other hierarchies (no pop-up window when entering the module)
- Support of model and annotation hierarchies in subject hierarchy (subject hierarchy shows the same tree that the Models module shows, and it is handled the same way (atlases, drag&drop, show/hide, etc.)
- Improved drag&drop: re-ordering of items (and restoring the order correctly on complete update), drag&drop to empty area reparents to the scene
- Expand and collapsed states of the items are preserved, and restored when reconstructing the hierarchy
- Subject hierarchy combobox showing a drop-down tree is implemented. It can be added in the modules instead of a simple MRML node selector. This, besides allowing an easier overview of the data, makes it possible to differentiate between nodes that have the same name but belong to different patient or study
- More versatile filtering options in the tree and combobox (name, attribute, level)
- More control over the subject hierarchy Qt model in general, more room for further improvements

Extended information about it can be found on the labs page
https://www.slicer.org/wiki/Documentation/Labs/SubjectHierarchy

### CODE REVIEW

**Comment by cpinter** [comment]
This time I’m not sure if one commit is the way to go, because there are so many changes, but also there are 56 commits in the pull request. Suggestions are welcome.

**Comment by pieper** [comment]
I built and did some quick testing - LGTM

**Comment by jcfr** [comment]
Keeping the commit history makes sense. Before integrating, could you try to generate a package look like CircleCI is red because it fails to package.

**Comment by lassoan** [comment]
56 commits seems quite a lot to me. It would be difficult to decipher these commits for writing release notes or understand what was developed. Would you be able to squash them into one or few commits with a good summary in the commit comment?

**Comment by cpinter** [comment]
@lassoan Yes the idea is that I make one or a few more commits (this is why I said that 56 is a lot). I can go with one, because it's hard to group commits without breaking the order (the WIP ones and the bugfixes should go in one, but they are mixed).
One commit then?

**Comment by cpinter** [comment]
@jcfr Packaging failed. I'll try to fix it asap.

14>  CPack: - Install project: Slicer
14>  CMake Error at C:/e/ScR/Slicer-build/Modules/Loadable/SubjectHierarchy/Widgets/Python/cmake_install.cmake:37 (message):
14>    ABSOLUTE path INSTALL DESTINATION forbidden (by caller):
14>    C:/e/ScR/Slicer-build/./lib/Slicer-4.7/qt-scripted-modules/SubjectHierarchyPlugins/SubjectHierarchyPlugins
14>  Call Stack (most recent call first):
14>    C:/e/ScR/Slicer-build/Modules/Loadable/SubjectHierarchy/Widgets/cmake_install.cmake:68 (include)
14>    C:/e/ScR/Slicer-build/Modules/Loadable/SubjectHierarchy/cmake_install.cmake:57 (include)
14>    C:/e/ScR/Slicer-build/Modules/Loadable/cmake_install.cmake:37 (include)
14>    C:/e/ScR/Slicer-build/Modules/cmake_install.cmake:32 (include)
14>    C:/e/ScR/Slicer-build/cmake_install.cmake:42 (include)
14>
14>
14>EXEC : CPack error : Error when generating package: Slicer
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "setlocal
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: cd C:\e\ScR\Slicer-build
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: C:
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: "C:\Program Files\CMake\bin\cpack.exe" -C Release --config ./CPackConfig.cmake
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmEnd
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmErrorLevel
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: exit /b %1
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmDone
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code 1.

**Comment by jcfr** [comment]
> decipher these commits for writing release notes 

I suggest we introduce a `CHANGES.rst` file that would be updated each time a feature or fix is introduced.
Format would be similar to https://github.com/scikit-build/scikit-build/blob/master/CHANGES.rst

> or understand what was developed

Ideally, each commit would not break the compilation of the project.

Since that is not feasible:

* keeping commit like `ENH: Removed unused OwnerPluginChanged event from SH ` makes sense
* WIP commits should probably be squashed -- re-ordering is fine  (`git rebase --interactive` is useful for this)

It is a balancing act. A single commit with 116 files being modified is also hard to understand.

**Comment by jcfr** [comment]
> Packaging failed. I'll try to fix it asap

Thanks

**Comment by cpinter** [comment]
Packaging has been fixed. The files are deployed in the right places both when building and installing.

**Comment by jcfr** [comment]
> Packaging has been fixed. The files are deployed in the right places both when building and installing.

CircleCI should allows to confirm that :smile:

**Comment by cpinter** [comment]
Anyway we installed the package and tried it out, it worked on Windows.

**Comment by agirault** [comment]
Looking forward to it 👍

**Comment by cpinter** [comment]
I created an integration branch with the squashed commits:
https://github.com/cpinter/Slicer/commits/subject-hierarchy-2-integration

@jcfr @lassoan @pieper @agirault @johan.andruejol Can I ask everyone to please not commit in the next hour or so until I finish integration? I'll add a comment when I'm done. Thanks a lot!

**Comment by jcfr** [comment]
> Can I ask everyone to please not commit in the next hour or so until I finish integration?

Sounds good.

**Comment by pieper** [comment]
Yes, no problem - thanks for moving this through the process.

**Comment by cpinter** [comment]
Integration is done. The source tree looks fine too. Let's hope everything is alright!

**Comment by lassoan** [comment]
Thank you Csaba, nice job! Looking forward to using this.

**Comment by jcfr** [comment]
Closing this PR. Associated changes have been integrated.

**Pull request closed without merging**
