### PR TITLE
Fix transform tests removing dynamic cast

### PR DESCRIPTION
**Pull request by jcfr**
This PR fixes regressions introduced by InsightSoftwareConsortium/ITK@d1e9fe2 (BUG: Ensure Transform IO factories are  registered once.) and integrated in r24836 (ENH: Update ITKv4 to v4.9.0 release branch).

Following this ITK commit, the ITKIO transform libraries are build as shared and dynamic_cast can NOT be used with templated classes that are instantiated in a translation unit different than the one where they are defined. It will work only if the classes are explicitly instantiated and exported.

To workaround the issue, code that was relying on `dynamic_cast` is updated to (1) ensure the objects are of the right type doing string comparison and (2) then use `static_cast` instead of `dynamic_cast`.

To summarize, the following tests that started to [fail on Ubuntu since January 8th](http://slicer.cdash.org/viewTest.php?buildid=750644&onlyfailed) will now pass:

```
EMSegCL_RunSetEverything
EMSegCL_Task_BRAINS_MRIHumanBrain_scalartype_float_very_small
EMSegCL_Task_BRAINS_MRIHumanBrain_scalartype_uint_very_small
EMSegCL_Task_HumanEye_BRAINS_small
EMSegCL_Task_MRIHumanBrain_BRAINS_small
EMSegCL_Task_MRIHumanBrainExp_BRAINS_small
EMSegCL_Task_MRIHumanBrainFullParcellation_BRAINS_small
EMSegCL_Task_MRIHumanBrainParcellation_BRAINS_small
EMSegCL_Task_NonHumanPrimate_BRAINS_small

ResampleScalarVectorDWIVolumeBSplineInterpolationTest
ResampleScalarVectorDWIVolumeBSplineWSInterpolationTest
ResampleScalarVectorDWIVolumeRotationAndAffineTest
ResampleScalarVectorDWIVolumeRotationNNTest

ResampleDTIVolumeRotationNNTest
ResampleDTIVolume2RigidTransformsLinearTest
ResampleDTIVolumeBSplineWSInterpolationTest
ResampleDTIVolumeBSplineInterpolationTest

vtkSlicerTransformLogicTest1
vtkMRMLNonlinearTransformNodeTest1
```

The tests `EMSeg_SlicerCommonInterfaceTestGeneral` and `EMSegCL_Task_MRIHumanBrain_2CH`
are failing because of issue with `N4ITKBiasFieldCorrection`. This is tracked in issue
[#4130](http://na-mic.org/Mantis/view.php?id=4130).

Test `vtkMRMLFiberBundleNodeTest1` failure is tracked in issue [#4129](http://na-mic.org/Mantis/view.php?id=4129).

Cc: @thewtex @fbudin69500 @lassoan @pieper @hjmjohnson

### CODE REVIEW

**Comment by jcfr** [comment]
I suspect _issues_ with `N4ITKBiasFieldCorrection` are side effected of InsightSoftwareConsortium/ITK@51c2ff5 or InsightSoftwareConsortium/ITK@d0f5914

**Comment by thewtex** [comment]
Well done! LGTM.

Ping @ntustison re: N4ITKBiasFieldCorrection issues.

**Comment by ntustison** [comment]
From what I can tell, this issue should've been fixed with https://github.com/InsightSoftwareConsortium/ITK/commit/be66cfa7e396491a5da7fc8da4ff384cf26138bc.

**Comment by thewtex** [comment]
@ntustison Thanks for the note!  That commit had not been merged to the release branch. I just merged it to the release branch for the 4.9.0 release.

**Comment by jcfr** [comment]
@thewtex @ntustison  I confirm that InsightSoftwareConsortium/ITK@be66cfa addresses the problem. Thanks for the quick turnaround. :fireworks:

**Comment by jcfr** [comment]
Integrated in [r24883](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24883)

**Pull request closed without merging**
