### PR TITLE
STYLE: Remove VTKv5 support

### PR DESCRIPTION
**Pull request by jcfr**
As discussed during the developer hangout of 2015-03-31, this commit
removes support for VTKv5.

Most of the h/cxx files have been updated automatically using the
script "slicer_remove_vtk5_support.py" [1]. See below.

The remaining of h/cxx, python and CMake files have been updated
manually.

slicer_remove_vtk5_support.py:
```
cd ~/Project/Slicer
~/Download/slicer_remove_vtk5_support.py $(ack -l VTK_MAJOR_VERSION)
```

[1] https://gist.github.com/jcfr/91d2f5d07c2a36320e48

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @Slicer/community

**Comment by naucoin** [comment]
Will take a look at it this afternoon!

**Comment by jcfr** [comment]
Great. Thanks

**Comment by pieper** [comment]
This is great, it significantly cleans up the code.

**Comment by naucoin** [comment]
Builds, works from the GUI and a selection of my favourite tests pass. Looks good to me!

**Comment by hjmjohnson** [comment]
I support all efforts to make it easier to maintain!

Hans

**Comment by jcfr** [comment]
Thanks for the review. Integrated in [r24801](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24801)

**Pull request closed without merging**
