### PR TITLE
Prepare for itk future

### PR DESCRIPTION
**Pull request by hjmjohnson**
Remove compiler warnings from Slicer.

### CODE REVIEW

**Comment by jcfr** [comment]
12567b4 `COMP: Remove useless compile time array as NULL` integrated as [r24616](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24616) to [r24620](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24620)

**Comment by jcfr** [comment]
85736e8 `BUG: Incorrect truncation to integer` integrated in [r24621](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24621)

**Comment by jcfr** [comment]
@hjmjohnson Since I will be travelling next week, I will integrate your patched when I return (after Oct 18th). 

In the mean time, @thewtex could you review commit 8bdf606 ?

**Comment by thewtex** [comment]
Overall looks good to me.  I made a few comments on some additions that are suspicious.  Cheers to @hjmjohnson for adding ITK_OVERRIDE in the first place -- it can be pretty useful :-).

**Comment by jcfr** [comment]
Closing since 8bdf606 has been integrated as of [r24669](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24669)

**Pull request closed without merging**
