### PR TITLE
ENH: Use the latest vtkImageReslice filter instead of vtkImageResliceMask

### PR DESCRIPTION
**Pull request by lassoan**
Features:
* Performance optimization: about 2x speed increase in slice rendering speed when the volume is linearly transformed (e.g., transformed MRHead refresh rate 25fps -> 50fps)
* Thick slices, MIP, DRR, etc. display modes are available (no GUI yet, but already can be enabled using Python), see the code samples below

Implementation:
* Convert composite transform to simple linear filter before setting it in the reslice filter (because vtkImageResliceMask can do some additional optimizations if it gets a simple linear transform)
* Use the latest vtkImageReslice filter instead of vtkImageResliceMask:
** mask output of vtkImageReslice is a stencil, therefore slice processing pipeline is simplified: vtkImageCast filter is not needed anymore and the more efficient vtkImageStencil is used instead of vtkImageMathematics
** custom vtkImageResliceMask class is removed: no need to maintain it any longer, etc.

Thick slice:

sliceNode = slicer.mrmlScene.GetNodeByID('vtkMRMLSliceNodeRed')
appLogic = slicer.app.applicationLogic()
sliceLogic = appLogic.GetSliceLogic(sliceNode)
sliceLayerLogic = sliceLogic.GetBackgroundLayer()
reslice = sliceLayerLogic.GetReslice()
reslice.SetSlabModeToMean()
reslice.SetSlabNumberOfSlices(10)
reslice.SetSlabSliceSpacingFraction(0.3)
sliceNode.Modified()

Maximum intensity projection (MIP):

sliceNode = slicer.mrmlScene.GetNodeByID('vtkMRMLSliceNodeRed')
appLogic = slicer.app.applicationLogic()
sliceLogic = appLogic.GetSliceLogic(sliceNode)
sliceLayerLogic = sliceLogic.GetBackgroundLayer()
reslice = sliceLayerLogic.GetReslice()
reslice.SetSlabModeToMax()
reslice.SetSlabNumberOfSlices(600)
reslice.SetSlabSliceSpacingFraction(0.5)
sliceNode.Modified()

### CODE REVIEW

**Comment by pieper** [comment]
I built this branch.  Seems to be mostly working - slick!

But when I download the MRHead sample data I get this message at every reslice operation (e.g. dragging the slider)

Warning: In /Users/pieper/slicer4/latest/Slicer-superbuild/VTKv6/Common/ExecutionModel/vtkAlgorithm.cxx, line 1421
vtkImageStencil (0x7fec2610c670): Attempt to get connection index 2 for input port 0, which has 1 connections.

**Comment by lassoan** [comment]
There was a bug in checking if background mask was specified which caused the warning.
I've reviewed stencil usage in all volume display node classes, fixed this bug and made some simplifications. It would be great if you could test it again, preferably with DWI/DTI volumes, too (I've only tested scalar, label, and vector volume types).

**Comment by pieper** [comment]
Looks like it works great!  I didn't notice any problems with dwi/dti.  +1 for committing to trunk.

**Comment by lassoan** [comment]
Thanks for testing, Steve!

Anyone else planning to test it?

Can I integrate it?

**Comment by pieper** [comment]
+1 for integrating

**Comment by lassoan** [comment]
OK. If there are no more feedbacks till Monday then I commit this to the trunk.

**Comment by lassoan** [comment]
Integration is postponed until VTK 6.2 / OpenGL2 developments integration is completed.

**Comment by lassoan** [comment]
@jcfr What is the status of the VTK 6.2 transition? As soon as things look stable I would like to integrate this pull request. Thanks!

**Comment by pieper** [comment]
Still some instability some best to hold off for a few more days.  Or
revert the vtk if it cannot be stabilized easily.

**Comment by jcfr** [comment]
:+1:  Works great.

@lassoan Do you also confirm it compiles with VTKv5 or should I do a test build ?

**Comment by lassoan** [comment]
I did not pay attention to maintain VTK5 compatibility, so it may or may not compile with VTK5.

I thought VTK5 support was only for the time we transition to VTK6.

**Comment by pieper** [comment]
I would think we can safely remove support for vtk5 now.  I don't think
anyone is relying on it for new development.  Even if we don't yet have a
patch that removes all the ifdefs and vtk version checking we can accept
this patch even if it only works in vtk6.

**Comment by lassoan** [comment]
Guys, merge conflicts appeared due to the delay in merging this! Please merge this before it gets even more complicated to do it.

**Comment by jcfr** [comment]
Already identified this conflict, it is due to the changes of Nicole. 

This will be integrated as soon I checked it build with VTK5. It is still a requirement for us for some project.

**Comment by lassoan** [comment]
Thanks!

**Comment by jcfr** [comment]
Integrated in [r23942](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23942), [r23943](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23943) and [r23944](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23944)

**Comment by jcfr** [comment]
@lassoan Thanks for your contribution :8ball:

**Comment by lassoan** [comment]
Thanks for testing&integrating

**Comment by jcfr** [comment]
@lassoan I just noticed that test `vtkMRMLSliceLogicTest2_fixed.nrrd` was displaying some warning. Do you think you could have a quick look ? Thanks

```
[...]
125: vtkMRMLScalarVolumeDisplayNode::pipeline updated: 0.000349045 fps: 2864.96
125: ERROR: In /home/jchris/Projects/Slicer-2-SuperBuild-Debug/VTKv6/Common/ExecutionModel/vtkDemandDrivenPipeline.cxx, line 810
125: vtkCompositeDataPipeline (0x2cadda0): Input for connection index 0 on input port index 0 for algorithm vtkImageCast(0x2cabb40) is of type vtkImageStencilData, but a vtkImageData is required.
125: 
125: vtkMRMLScalarVolumeDisplayNode::window updated: 0.000169039 fps: 5915.8
125: ERROR: In /home/jchris/Projects/Slicer-2-SuperBuild-Debug/VTKv6/Common/ExecutionModel/vtkDemandDrivenPipeline.cxx, line 810
125: vtkCompositeDataPipeline (0x2cadda0): Input for connection index 0 on input port index 0 for algorithm vtkImageCast(0x2cabb40) is of type vtkImageStencilData, but a vtkImageData is required.
125: 
125: vtkMRMLScalarVolumeDisplayNode::threshold updated: 0.000144958 fps: 6898.53
125: ERROR: In /home/jchris/Projects/Slicer-2-SuperBuild-Debug/VTKv6/Common/ExecutionModel/vtkDemandDrivenPipeline.cxx, line 810
125: vtkCompositeDataPipeline (0x2cadda0): Input for connection index 0 on input port index 0 for algorithm vtkImageCast(0x2cabb40) is of type vtkImageStencilData, but a vtkImageData is required.
125: 
125: vtkMRMLScalarVolumeDisplayNode::alpha updated: 8.79765e-05 fps: 11366.7
1/1 Test #125: vtkMRMLSliceLogicTest2_fixed.nrrd ...   Passed    0.99 sec

```

**Comment by lassoan** [comment]
OK. I'll commit a patch soon.

**Comment by jcfr** [comment]
Thanks

On Thu, Feb 5, 2015 at 10:41 AM, Andras Lasso <notifications@github.com>
wrote:

> OK. I'll commit a patch soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/228#issuecomment-73067181>.
>



-- 
+1 919 869 8849

**Comment by lassoan** [comment]
The test is fixed in rev 23964

**Comment by jcfr** [comment]
Great. Mercii.
Jc

On Thu, Feb 5, 2015 at 4:22 PM, Andras Lasso <notifications@github.com>
wrote:

> The test is fixed in rev 23964
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/Slicer/pull/228#issuecomment-73131562>.
>



-- 
+1 919 869 8849

**Pull request closed without merging**
