### PR TITLE
Update itk and sem

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @thewtex

**Comment by thewtex** [comment]
+1 Will test...

**Comment by thewtex** [comment]
There is an issue with the N4 bias correction filter.  I am working on a patch...

**Comment by jcfr** [comment]
Sounds good. Thanks for testing and thanks for working on a patch :+1:

**Comment by jcfr** [comment]
@thewtex Thanks again for testing and updating ITK to ensure backward compatibility :+1: 

Integrated in [r25026](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25026) and [r25027](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25027)

**Pull request closed without merging**
