### PR TITLE
ENH: update MultiVolumeImporter hash

### PR DESCRIPTION
**Pull request by fedorov**
Updated MultiVolumeImporter plugin is improved to handle certain types of 4D
Cardiac CT.

Thanks to @lassoan for identifying the use case and contributing the patch.

### CODE REVIEW

**Comment by jcfr** [comment]
Building locally. Planning on integrating shortly.

@fedorov Should this be integrated today or wait after the release ?

**Comment by fedorov** [comment]
It is a very small change, and I can't see how it can break anything (nothing in the core depends on it), so I would say integrating now would be good and painless. It's just the last 2 commits from here https://github.com/fedorov/MultiVolumeImporter/commits/master

**Comment by jcfr** [comment]
Thanks for the note

Integrated in [r25422](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25422)

There are a small warning when opening the module, I wonder if this is a symptom of something more important .., 

```
PythonQt: QObject::connect() signal 'mrmlSceneChanged(vtkMRMLScene*)' does not exist on qMRMLNodeComboBox
```

**Comment by fedorov** [comment]
It is probably this line, the purpose of which I don't know at this point.

https://github.com/fedorov/MultiVolumeImporter/blob/master/MultiVolumeImporter.py#L84

I don't think it is important.

**Pull request closed without merging**
