### PR TITLE
Support new-style classes for scripted modules/widgets; use VTKObservationMixin in EditorWidget

### PR DESCRIPTION
**Pull request by msmolens**
This change makes EditorWidget use VTKObservationMixin to simplify managing observers, as suggested in https://github.com/Slicer/Slicer/pull/346#issuecomment-141474443.

To support using VTKObservationMixin with EditorWidget, this change also adds support for writing scripted module and widget classes as new-style Python classes.

### CODE REVIEW

**Comment by pieper** [comment]
LGTM, thanks!

**Comment by jcfr** [comment]
:+1: LGTM

**Comment by jcfr** [comment]
In commit 2735447, make sure to reference these two issues:

http://www.na-mic.org/Bug/view.php?id=2994
http://www.na-mic.org/Bug/view.php?id=1890

... and mark them as resolved afterward :smile:

**Comment by msmolens** [comment]
:+1: Integrated in [r24569](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24569) and [r24570](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24570)

**Pull request closed without merging**
