### PR TITLE
BUG: Restore support for writing CLI output as .fcsv files

### PR DESCRIPTION
**Pull request by jcfr**
This commit resolves errors when writing Markup nodes set as CLI output of type `point` to `.fcsv` files. It reintroduces support for the `.fcsv` format, ensuring compatibility similar to the fix in commit 889d98ebda ("BUG: Fix writing markups input for CLI modules", 2021-02-01).

Example error:

```
[VTK] vtkMRMLMarkupsJsonStorageNode::ReadDataInternal: Error: Error parsing the file '/tmp/Slicer-jcfr/BJDHB_vtkMRMLMarkupsFiducialNodeB.fcsv'
[VTK] vtkMRMLStorageNode::ReadData: Failed to read node F (vtkMRMLMarkupsFiducialNode1) from filename='/tmp/Slicer-jcfr/BJDHB_vtkMRMLMarkupsFiducialNodeB.fcsv'
```

Reported-by: @dzenanz

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
The fix works for me!

**Comment by dzenanz** [comment]
@sjh26 @lassoan can this be merged?

**Comment by lassoan** [comment]
We would like to phase out the .fcsv file format, but it is OK to keep supporting it for a little longer.

**Comment by jcfr** [comment]
Thanks @lassoan and @dzenanz for the review :pray:

**Pull request merged**
