### PR TITLE
COMP: Update python packages to latest

### PR DESCRIPTION
**Pull request by jamesobutler**
Python packages were last checked for updates in mid-November 2021 and these version updates were integrated in https://github.com/Slicer/Slicer/commit/34e48e8aef5dad19ec8a955d6f48a1940846e3f3 committed on Jan. 25th 2022. Outdated python packages were discovered and updated using the python_package_updater.py script in the Slicer repo and then dependencies new/conflicting were manually reviewed. 

A build on Windows was run without any build issues.

```powershell
PS C:\S5R\python-install\bin> ./PythonSlicer "C:\Users\JamesButler\Documents\GitHub\Slicer\Utilities\Scripts\python_package_updater.py"
Package            Version   Latest    Type
------------------ --------- --------- -----
certifi            2021.5.30 2021.10.8 wheel
charset-normalizer 2.0.6     2.0.10    wheel
dicomweb-client    0.53.0    0.54.4    wheel
gitdb              4.0.7     4.0.9     wheel
GitPython          3.1.18    3.1.26    wheel
idna               3.2       3.3       wheel
numpy              1.21.4    1.22.1    wheel
packaging          21.0      21.3      wheel
Pillow             8.4.0     9.0.0     wheel
PyGithub           1.54.1    1.55      wheel
PyJWT              1.7.1     2.3.0     wheel
pyparsing          2.4.7     3.0.7     wheel
requests           2.26.0    2.27.1    wheel
scipy              1.7.2     1.7.3     wheel
setuptools         58.5.3    60.5.0    wheel
smmap              4.0.0     5.0.0     wheel
typing-extensions  3.10.0.2  4.0.1     wheel
urllib3            1.26.7    1.26.8    wheel
wheel              0.37.0    0.37.1    wheel
wrapt              1.12.1    1.13.3    wheel

  certifi==2021.10.8 --hash=sha256:d62a0163eb4c2344ac042ab2bdf75399a71a2d8c7d47eac2e2ee91b9d6339569
  charset-normalizer==2.0.10 --hash=sha256:cb957888737fc0bbcd78e3df769addb41fd1ff8cf950dc9e7ad7793f1bf44455
  dicomweb-client==0.54.4 --hash=sha256:397cb05982258fde33bd059efecd74893350826f9fe71f36a9500e98baf6f96d
  gitdb==4.0.9 --hash=sha256:8033ad4e853066ba6ca92050b9df2f89301b8fc8bf7e9324d412a63f8bf1a8fd
  GitPython==3.1.26 --hash=sha256:26ac35c212d1f7b16036361ca5cff3ec66e11753a0d677fb6c48fa4e1a9dd8d6
  idna==3.3 --hash=sha256:84d9dd047ffa80596e0f246e2eab0b391788b0503584e8945f2368256d2735ff
  # Hashes correspond to the following packages:
  #  - numpy-1.22.1-cp39-cp39-macosx_10_9_x86_64.whl
  #  - numpy-1.22.1-cp39-cp39-macosx_11_0_arm64.whl
  #  - numpy-1.22.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - numpy-1.22.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - numpy-1.22.1-cp39-cp39-win_amd64.whl
  numpy==1.22.1 --hash=sha256:bcd19dab43b852b03868796f533b5f5561e6c0e3048415e675bec8d2e9d286c1 \
                --hash=sha256:78bfbdf809fc236490e7e65715bbd98377b122f329457fffde206299e163e7f3 \
                --hash=sha256:c51124df17f012c3b757380782ae46eee85213a3215e51477e559739f57d9bf6 \
                --hash=sha256:88d54b7b516f0ca38a69590557814de2dd638d7d4ed04864826acaac5ebb8f01 \
                --hash=sha256:4ac4d7c9f8ea2a79d721ebfcce81705fc3cd61a10b731354f1049eb8c99521e8
  packaging==21.3 --hash=sha256:ef103e05f519cdc783ae24ea4e2e0f508a9c99b2d4969652eed6a2e1ea5bd522
  # Hashes correspond to the following packages:
  #  - Pillow-9.0.0-cp39-cp39-macosx_10_10_x86_64.whl
  #  - Pillow-9.0.0-cp39-cp39-macosx_11_0_arm64.whl
  #  - Pillow-9.0.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - Pillow-9.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - Pillow-9.0.0-cp39-cp39-win_amd64.whl
  Pillow==9.0.0 --hash=sha256:c2067b3bb0781f14059b112c9da5a91c80a600a97915b4f48b37f197895dd925 \
                --hash=sha256:2d16b6196fb7a54aff6b5e3ecd00f7c0bab1b56eee39214b2b223a9d938c50af \
                --hash=sha256:98cb63ca63cb61f594511c06218ab4394bf80388b3d66cd61d0b1f63ee0ea69f \
                --hash=sha256:3586e12d874ce2f1bc875a3ffba98732ebb12e18fb6d97be482bd62b56803281 \
                --hash=sha256:6579f9ba84a3d4f1807c4aab4be06f373017fc65fff43498885ac50a9b47a553
  PyGithub==1.55 --hash=sha256:2caf0054ea079b71e539741ae56c5a95e073b81fa472ce222e81667381b9601b
  PyJWT==2.3.0 --hash=sha256:e0c4bb8d9f0af0c7f5b1ec4c5036309617d03d56932877f2f7a0beeb5318322f
  pyparsing==3.0.7 --hash=sha256:a6c06a88f252e6c322f65faf8f418b16213b51bdfaece0524c1c1bc30c63c484
  requests==2.27.1 --hash=sha256:f22fa1e554c9ddfd16e6e41ac79759e17be9e492b3587efa038054674760e72d
  # Hashes correspond to the following packages:
  #  - scipy-1.7.3-1-cp39-cp39-macosx_12_0_arm64.whl
  #  - scipy-1.7.3-cp39-cp39-macosx_10_9_x86_64.whl
  #  - scipy-1.7.3-cp39-cp39-macosx_12_0_arm64.whl
  #  - scipy-1.7.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - scipy-1.7.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - scipy-1.7.3-cp39-cp39-win_amd64.whl
  scipy==1.7.3 --hash=sha256:b78a35c5c74d336f42f44106174b9851c783184a85a3fe3e68857259b37b9ffb \
               --hash=sha256:eef93a446114ac0193a7b714ce67659db80caf940f3232bad63f4c7a81bc18df \
               --hash=sha256:eb326658f9b73c07081300daba90a8746543b5ea177184daed26528273157294 \
               --hash=sha256:edad1cf5b2ce1912c4d8ddad20e11d333165552aba262c882e28c78bbc09dbf6 \
               --hash=sha256:5d1cc2c19afe3b5a546ede7e6a44ce1ff52e443d12b231823268019f608b9b12 \
               --hash=sha256:3f78181a153fa21c018d346f595edd648344751d7f03ab94b398be2ad083ed3e
  setuptools==60.5.0 --hash=sha256:68eb94073fc486091447fcb0501efd6560a0e5a1839ba249e5ff3c4c93f05f90
  smmap==5.0.0 --hash=sha256:2aba19d6a040e78d8b09de5c57e96207b09ed71d8e55ce0959eeee6c8e190d94
  typing-extensions==4.0.1 --hash=sha256:7f001e5ac290a0c0401508864c7ec868be4e701886d5b573a9528ed3973d9d3b
  urllib3==1.26.8 --hash=sha256:000ca7f471a233c2251c6c7023ee85305721bfdf18621ebff4fd17a8653427ed
  wheel==0.37.1 --hash=sha256:4bdcd7d840138086126cd09254dc6195fb4fc6f01c050a1d7236f2630db1d22a
  # Hashes correspond to the following packages:
  #  - wrapt-1.13.3-cp39-cp39-macosx_10_9_x86_64.whl
  #  - wrapt-1.13.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
  #  - wrapt-1.13.3-cp39-cp39-musllinux_1_1_x86_64.whl
  #  - wrapt-1.13.3-cp39-cp39-win_amd64.whl
  wrapt==1.13.3 --hash=sha256:981da26722bebb9247a0601e2922cedf8bb7a600e89c852d063313102de6f2cb \
                --hash=sha256:25b1b1d5df495d82be1c9d2fad408f7ce5ca8a38085e2da41bb63c914baadff7 \
                --hash=sha256:865c0b50003616f05858b22174c40ffc27a38e67359fa1495605f96125f76640 \
                --hash=sha256:81bd7c90d28a4b2e1df135bfbd7c23aee3050078ca6441bead44c42483f9ebfb
```

- typing-extensions is not required for latest `GitPython` when using Python 3.8 or newer
- Did not upgrade `PyGithub` to 1.55 because it introduces a new dependency `PyNaCl` that only has wheels for the Windows platform for the Python 3.6 version. Continuing to stay with `PyGithub` 1.54.1 means we must continue to use `PyJWT`<2.

### CODE REVIEW

**Comment by pieper** [comment]
I'm thinking we should hold off a day on this one so we can see what changing the core python does and do this as a second step.  I'll approve it anyway so it's ready to go.

**Review by pieper — APPROVED** [review]
@jcfr should also have a look of course.

**Comment by jamesobutler** [comment]
Due to the big jump from Python 3.6 to Python 3.9, package updates were already included in https://github.com/Slicer/Slicer/commit/34e48e8aef5dad19ec8a955d6f48a1940846e3f3 as we had been pinned to lower versions for Python 3.6, and newer versions were required to use Python 3.9. This PR just further updates the package versions to latest as the recently merged Python 3.9 PR only had updates through mid-November.

**Comment by pieper** [comment]
Okay, I take your comment to mean that it will be better to test the 3.9 update with this merged as well, so in that case I will merge.

**Comment by jcfr** [comment]
Thanks James.

Since we are actively working on updating python, catching issues earlier would be great.

Before integrating, the major version of package like dicomweb-client has been updated, could you look if this is introducing some breaking changes.

**Comment by jamesobutler** [comment]
I am building and running tests this evening. I'll post here if I find any issues with updates like `dicomweb-client` from 0.53.0 to 0.54.4. From my quick review of the release notes, nothing seemed major in this seemingly "minor" not "major" version update.

**Comment by pieper** [comment]
I wouldn't expect the dicomweb-client to break anything except the DICOMwebBrowser extension and even that's [a little in flux anyway](https://github.com/lassoan/SlicerDICOMwebBrowser/pull/7) so no real danger of breaking the build there.

**Pull request merged**
