### PR TITLE
ENH: Addition of ctk_cli

### PR DESCRIPTION
**Pull request by fbudin69500**
ctk_cli [1] is a command line parsing python package that parses
arguments the same way SlicerExecutionModel does.
Using ctk_cli allows in Python scripts allows to have the same
user interface in Python or in C++.

[1] https://github.com/commontk/ctk-cli

### CODE REVIEW

**Comment by pieper** [comment]
Sounds cool - can you add a short example?

**Comment by fbudin69500** [comment]
@pieper Sure. Do you have any preference where the example should go?

**Comment by fbudin69500** [comment]
@pieper : I added an example in the extension examples. Let me know if that seems reasonable.

**Comment by pieper** [comment]
Yes, that makes sense - thanks!

**Comment by jcfr** [comment]
Thanks for the patch.

Nitpick:  In 80a5a9b, instead of modifying the files in Extensions/Testing. Could you:
* Add a type of modules in https://github.com/Slicer/Slicer/tree/master/Utilities/Templates/Modules
* Update the module [SlicerGenerateExtensionTemplates](https://github.com/Slicer/Slicer/blob/90211eb32fd8f6c2cf5d6c1104760216869e417e/CMake/SlicerExtensionTemplatesGenerator.cmake#L84)
* Build the target `SlicerGenerateExtensionTemplates`

Thanks
Jc

**Comment by jcfr** [comment]
Closing. Superseded by #497

**Pull request closed without merging**
