### PR TITLE
BUG: Fix bug in vtkMRMLIGTLTrackingDataBundleNode::GetTransformNode()…

### PR DESCRIPTION
**Pull request by tokjun**
The new GitTag will fix the bug reported in http://www.na-mic.org/Bug/view.php?id=4011

### CODE REVIEW

**Comment by jcfr** [comment]
Hi Junichi,
If not done by other core do vs, i ll apply your patch next week when back
from vacation.
Thanks
Jc

**Comment by fedorov** [comment]
I can integrate, just need to look up how to give the authorship credit to Junichi

**Comment by fedorov** [comment]
Integrated in r24369 = ca9bdbef055a9b038db85c6845b63e90784d6968

**Comment by tokjun** [comment]
Thanks, Andriy!

**Comment by jcfr** [comment]
Integrated in [r24369](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24369)

**Pull request closed without merging**
