### PR TITLE
ENH: Display thumbnails in SampleData module

### PR DESCRIPTION
**Pull request by lassoan**
It makes the module nicer and the button easier to hit.
sampledata-thumbnails

### CODE REVIEW

**Comment by lassoan** [comment]
@ihnorton - Probably you could make much nicer thumbnails for the DTI/DWI volumes. You can either attach images here or replace them after the PR is merged.

**Comment by lassoan** [comment]
Thumbnails were generate using ScreenCapture module (single step + capture all views option). Note that view controllers are hidden when capture all views option is enabled, which makes the capture much simpler and nicer (no colored bars).

**Comment by pieper** [comment]
LGTM - very nice.

**Comment by jcfr** [comment]
Niceee :+1:

**Comment by jcfr** [comment]
As a side note, the CircleCI bot fails way to often ... we will look into transitioning to CircleCI 2.0 which natively integrate with docker.

**Comment by lassoan** [comment]
Merged.
https://github.com/Slicer/Slicer/commit/471c00b3b643d7ebc1cd58226d3e232ad637b94a

**Pull request closed without merging**
