### PR TITLE
ENH: Generalize Editor "propagationMode" to support arbitrary set of lay...

### PR DESCRIPTION
**Pull request by jcfr**
...ers

This commit makes the Layer enum introduced in the r24106 public and uses
the Layer enum value to set the editor "propagationMode" value.

### CODE REVIEW

**Comment by jcfr** [comment]
@mehrtash @fedorov @pieper Let me know what you think of this. I think it nicely generalized how the propagation mode can be set.

**Comment by fedorov** [comment]
looks great to me

**Comment by mehrtash** [comment]
Looks fine to me. Thanks. :+1:

**Comment by pieper** [comment]
+1 and thanks!

**Comment by jcfr** [comment]
Thanks for the reviews.

@fedorov I changed `AllLayer` to `AllLayers`

Integrated in [r24128](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24128)

**Comment by fedorov** [comment]
Thanks JC!

**Pull request closed without merging**
