### PR TITLE
ENH: Add OSSF scorecard action to quantify open-source health

### PR DESCRIPTION
**Pull request by jamesobutler**
This adds the OSSF scorecard action (https://github.com/ossf/scorecard-action) to display open-source health. 

Some security engineering groups have requested that open-source repositories should display their OSSF score. Adding this GitHub action will help fulfill their request. [`numpy`](https://github.com/numpy/numpy#readme) is a major open source repo that has adopted the OSSF score and present the badge on their readme. `numpy`'s full scorecard https://securityscorecards.dev/viewer/?uri=github.com/numpy/numpy reports a 7.5 score.

As of right now the Slicer OSSF score is a 5.4 for my fork specifically (this will be slightly different for the Slicer upstream as there are protected branches in the upstream which will give a higher score). You may be able to see the score reported on my branch https://securityscorecards.dev/viewer/?uri=github.com/jamesobutler/Slicer.

### CODE REVIEW

**Review by pieper — APPROVED** [review]
Sounds reasonable to me.  Do others want to comment before we merge?

**Review by jcfr — APPROVED** [review]
This makes sense, and moving forward we should definitely introduce more badges in the README :ok_hand:

The badge currently associated with the README renders like this:

| | | 
|--|--|
| image | image |

Since the contributed GitHub action has been tested independently in https://securityscorecards.dev/viewer/?uri=github.com/jamesobutler/Slicer, integrating makes sense.

**Comment by jcfr** [comment]
Associated GitHub workflow completed :white_check_mark: 

| https://github.com/Slicer/Slicer/actions/runs/6005904413/job/16289500870 |
|--|
| image |

**Comment by jcfr** [comment]
And score card renders as expected :heavy_check_mark: 

| https://securityscorecards.dev/viewer/?uri=github.com/Slicer/Slicer |
|--| 
| image |

**Pull request merged**
