### PR TITLE
ENH: Make ctk ErrorLogWidget dockable

### PR DESCRIPTION
**Pull request by Punzo**
ref https://discourse.slicer.org/t/log-window-cannot-be-hidden-in-enviroments-with-no-windows-manager/29633

@pieper @lassoan @jamesobutler can you please review? thanks!

### CODE REVIEW

**Comment by Punzo** [comment]
I broke CTRL+0 action, I will add a commit

**Review by lassoan — COMMENTED** [review]
Thank you this works very nicely.

I'm just wondering if we should make it work the same way as the Python console, i.e., hitting Ctrl-0 should toggle the window instead of bringing it to the top. For me it would make it much easier to quickly peek at the log window (currently I can bring it up by Ctrl-0 but then I need to use the mouse to close it).

@pieper @jcfr Do you agree that we should change the behavior of Ctrl-0 to toggle the log window instead of always showing it (to be consistent with  the Python console and Module panel)?

**Comment by Punzo** [comment]
@lassoan fixed the action/shortcut in https://github.com/Slicer/Slicer/pull/7059/commits/7d8d9ce323e1092dd136374a19da1c753fe50b60

**Comment by lassoan** [comment]
@Punzo This looks very nice. I have only one usability concern: docking the the log window to the bottom by default leads to a relatively narrow window. I can only see a few list entries and about 10 lines of log:

image

Docking to the side looks good:

image

We should either log to the side by default, but even better, it would be nice if we changed the layout so that if the log window is docked to the top or bottom, its layout would switch to horizontal:

image

It could be implemented by using a grid layout and adding a "layoutDirection" property to the ctkErrorLogWidget that is updated when the dock location is changed; or maybe even better, a ctkFlowLayout could be used to automatically switch between horizontal/vertical layout depending on the shape of the window.

**Comment by pieper** [comment]
+1 for making the keyboard shortcut toggle the window.

👍 for making the layout nicer too

**Comment by Punzo** [comment]
@lassoan @pieper I have applied the feedback, see:
https://github.com/commontk/CTK/pull/1100
https://github.com/Slicer/Slicer/pull/7059/commits/5ce1bbd18316e3e05b4cc35afa0aaae6567dafe9
https://github.com/Slicer/Slicer/pull/7059/commits/d7ff16bd4b24cc07d6fc46a6b4512ceba17544a9

**Review by lassoan — APPROVED** [review]
I've tested it and made tweaked the behavior a bit more (the "new error" notification is dismissed now when the user interacts with the log window; the log window is raised to the top when shown; etc.) and it all looks good to me now.

Build fails due to the required CTK update.

**Pull request merged**
