### PR TITLE
COMP: Disabling git protocol by default

### PR DESCRIPTION
**Pull request by RafaelPalomar**
Github has disabled the unauthenticatd `git protocol by default
(see https://github.blog/2021-09-01-improving-git-protocol-security-github). By
default, the Slicer superbuild uses the git protocol for a number of
repositories hosted in Github.

This makes the `https` protocol the default protocol so the default
configuration will be able to clone external dependencies from Github.

### CODE REVIEW

**Comment by pieper** [comment]
We could look through these places too:

```
git grep git://
CMake/PreventInSourceBuilds.cmake:    message("# git clone git://github.com/${PROJECT_NAME}/${PROJECT_NAME}.git # or download & unpack the source tarball")
CMake/SlicerExtensionCPack.cmake:      string(REPLACE "git@" "git://" ${EXTENSION_NAME}_WC_READONLY_URL ${${EXTENSION_NAME}_WC_READONLY_URL})
Docs/developer_guide/build_instructions/linux.md:git clone git://github.com/Slicer/Slicer.git
Docs/developer_guide/build_instructions/macos.md:git clone git://github.com/Slicer/Slicer.git
Docs/developer_guide/extensions.md:    git remote add origin git://github.com/<username>/MyExtension
Extensions/CMake/SlicerExtensionsDashboardScript.TEMPLATE.cmake:dashboard_set(EXTENSIONS_INDEX_GIT_REPOSITORY "git://github.com/Slicer/ExtensionsIndex.git")
Extensions/CMake/SlicerFunctionExtractExtensionDescription.cmake:  set(expected_SCMURL "git://github.com/jcfr/SlicerToKiwiExporter.git")
Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake:    EXTENSION_WC_ROOT "git://github.com/jcfr/SlicerToKiwiExporter.git"
Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake:    EXTENSION_WC_URL "git://github.com/jcfr/SlicerToKiwiExporter.git"
Extensions/CMake/Testing/SlicerExtensionBuildSystemTest.py:        scmurl git://github.com/Slicer/ExtensionThatDoNotExists
Extensions/CMake/Testing/SlicerExtensionBuildSystemTest.py:set(EXTENSIONS_INDEX_GIT_REPOSITORY git://github.com/jcfr/ExtensionsIndex.git)
Extensions/CMake/Testing/extension_description_with_depends.s4ext:scmurl git://github.com/jcfr/SlicerToKiwiExporter.git
Extensions/CMake/Testing/extension_description_without_depends.s4ext:scmurl git://github.com/jcfr/SlicerToKiwiExporter.git
Utilities/Scripts/SlicerWizard/ExtensionDescription.py:      return url.replace(":", "/").replace("git@", "git://")
```

Also the s4ext files should be checked.

**Comment by RafaelPalomar** [comment]
@jcfr, could you have a look at the CircleCI error? [CircleCI build error](https://circleci.com/gh/Slicer/Slicer/2587?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

It looks like the`slicer/slicer-base` image needs an update for this. Is that something I can do myself?

**Comment by RafaelPalomar** [comment]
> Also the s4ext files should be checked.

@pieper What are the s4ext files?

**Comment by jamesobutler** [comment]
S4ext are the configuration files for build extensions. There may be a few templates in this repo, but they are mostly over at https://github.com/Slicer/ExtensionsIndex.

**Comment by lassoan** [comment]
Merged in https://github.com/Slicer/Slicer/commit/99578c69edb147c9d0b517270803e30851fa7660 and https://github.com/Slicer/Slicer/commit/fb404815fead08199e394064fb7e406d65941f59.

As discussed during the Slicer weekly meeting, the CMake variable is kept, it was just set to disabled by default. We could go further and replace the CMake `option()` by an `if(NOT DEFINED ...) set (...) endif()` construct (to prevent the `${SUPERBUILD_TOPLEVEL_PROJECT}_USE_GIT_PROTOCOL` option appearing in CMake GUI), but that would have required a bit more testing and I wanted to get this in before the 10pm nightly build cutoff time.

@RafaelPalomar I would have pushed the version after the finishing touches back to this branch and merge from here, but it seems that you keep disabling the option that allows maintainers to push to your branch. This slows things down (as it is hard to get some changes done just by submitting review comments; and creating a separate branch and creating a new pull request for the pull request in your fork just complicates things too much) or results in merge requests that appear to be abandoned instead of merged. Therefore, unless you have specific concerns then please allow maintainers to push to the pull request branch in the future.

**Comment by lassoan** [comment]
I've also updated the extensions index (master and 4.11 branches) to use https://github.com instead of git://github.com.

**Comment by RafaelPalomar** [comment]
> @RafaelPalomar I would have pushed the version after the finishing touches back to this branch and merge from here, but it seems that you keep disabling the option that allows maintainers to push to your branch. This slows things down (as it is hard to get some changes done just by submitting review comments; and creating a separate branch and creating a new pull request for the pull request in your fork just complicates things too much) or results in merge requests that appear to be abandoned instead of merged. Therefore, unless you have specific concerns then please allow maintainers to push to the pull request branch in the future.

Thanks @lassoan, I wasn't aware of this. I'll fix it for next time.

**Pull request closed without merging**
