### PR TITLE
Fix FindGit for CMake 3.4rc01.

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the fix.

Out of curiosity, do you have more details on the error fix by this commit ? Is there a change in the latest CMake rc that is causing trouble ?

**Comment by thewtex** [comment]
The use of GIT_VERSION_STRING in ExternalProject.cmake was added to upstream in b04c38159 and 7c5b6ed5c.  But, Slicer's FindGit diverges from upstream's.

**Comment by msmolens** [comment]
Also, the comments in CMake bug [15791](https://cmake.org/Bug/view.php?id=15791) give more details.

**Comment by jcfr** [comment]
Commit 5e2ede3 integrated in [r24629](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24629)

**Comment by jcfr** [comment]
Integrated in [r24631](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24631)

Thanks @thewtex and @msmolens

**Pull request closed without merging**
