### PR TITLE
COMP: Update python packages to latest

### PR DESCRIPTION
**Pull request by jamesobutler**
it's been about 3 months since python packages were last updated. Python packages were last updated on July 21st 2022. This PR updates python packages to their latest versions. This type of update is something I usually do on about a quarterly cadence (every 3 months).

Note that SimpleITK isn't being updated here as we build it from source rather than using the provided whl on pypi. VTK is also not updated as we use build VTK and its python wrapping as well from source rather than installing from whl.

```
PS C:\Users\butlej30383\AppData\Local\NA-MIC\Slicer 5.1.0-2022-10-15\bin> ./PythonSlicer.exe "C:\Slicer\Utilities\Scripts\python_package_updater.py"
Searching external projects in C:\Slicer\SuperBuild
Package            Version         Latest    Type
------------------ --------------- --------- -----
certifi            2022.6.15       2022.9.24 wheel
charset-normalizer 2.1.0           2.1.1     wheel
dicomweb-client    0.56.2          0.57.1    wheel
GitPython          3.1.27          3.1.29    wheel
idna               3.3             3.4       wheel
numpy              1.23.1          1.23.4    wheel
pip                22.2            22.3      wheel
PyGithub           1.55            1.56      wheel
PyJWT              2.4.0           2.5.0     wheel
scipy              1.8.1           1.9.2     wheel
setuptools         63.2.0          65.5.0    wheel
SimpleITK          2.2.0rc2.dev367 2.2.0     wheel
urllib3            1.26.10         1.26.12   wheel
vtk                9.1.20220125    9.2.2     wheel

[notice] A new release of pip available: 22.2 -> 22.3
[notice] To update, run: python-real.exe -m pip install --upgrade pip

  certifi==2022.9.24 --hash=sha256:90c1a32f1d68f940488354e36370f6cca89f0f106db09518524c88d6ed83f382
  charset-normalizer==2.1.1 --hash=sha256:83e9a75d1911279afd89352c68b45348559d1fc0506b054b346651b5e7fee29f
  dicomweb-client==0.57.1 --hash=sha256:191f39a06ac5b256ec0c160e6a9c54c9af0d8256eea1d5cb39781939381e3969
  GitPython==3.1.29 --hash=sha256:41eea0deec2deea139b459ac03656f0dd28fc4a3387240ec1d3c259a2c47850f
  idna==3.4 --hash=sha256:90b77e79eaa3eba6de819a0c442c0b4ceefc341a7a2ab77d7562bf49f425c5c2
  # Hashes correspond to the following packages:
  #  - numpy-1.23.4-cp39-cp39-macosx_10_9_x86_64.whl
  #  - numpy-1.23.4-cp39-cp39-macosx_11_0_arm64.whl
  #  - numpy-1.23.4-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - numpy-1.23.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - numpy-1.23.4-cp39-cp39-win_amd64.whl
  numpy==1.23.4 --hash=sha256:c67b833dbccefe97cdd3f52798d430b9d3430396af7cdb2a0c32954c3ef73894 \
                --hash=sha256:f76025acc8e2114bb664294a07ede0727aa75d63a06d2fae96bf29a81747e4a7 \
                --hash=sha256:12ac457b63ec8ded85d85c1e17d85efd3c2b0967ca39560b307a35a6703a4735 \
                --hash=sha256:95de7dc7dc47a312f6feddd3da2500826defdccbc41608d0031276a24181a2c0 \
                --hash=sha256:f260da502d7441a45695199b4e7fd8ca87db659ba1c78f2bbf31f934fe76ae0e
  pip==22.3 --hash=sha256:1daab4b8d3b97d1d763caeb01a4640a2250a0ea899e257b1e44b9eded91e15ab
  PyGithub==1.56 --hash=sha256:d15f13d82165306da8a68aefc0f848a6f6432d5febbff13b60a94758ce3ef8b5
  PyJWT==2.5.0 --hash=sha256:8d82e7087868e94dd8d7d418e5088ce64f7daab4b36db654cbaedb46f9d1ca80
  # Hashes correspond to the following packages:
  #  - scipy-1.9.2-cp39-cp39-macosx_10_9_x86_64.whl
  #  - scipy-1.9.2-cp39-cp39-macosx_12_0_arm64.whl
  #  - scipy-1.9.2-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - scipy-1.9.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - scipy-1.9.2-cp39-cp39-win_amd64.whl
  scipy==1.9.2 --hash=sha256:1e3b23a82867018cd26255dc951789a7c567921622073e1113755866f1eae928 \
               --hash=sha256:82e8bfb352aa9dce9a0ffe81f4c369a2c87c85533519441686f59f21d8c09697 \
               --hash=sha256:61b95283529712101bfb7c87faf94cb86ed9e64de079509edfe107e5cfa55733 \
               --hash=sha256:8c8c29703202c39d699b0d6b164bde5501c212005f20abf46ae322b9307c8a41 \
               --hash=sha256:7b2608b3141c257d01ae772e23b3de9e04d27344e6b68a890883795229cb7191
  setuptools==65.5.0 --hash=sha256:f62ea9da9ed6289bfe868cd6845968a2c854d1427f8548d52cae02a42b4f0356
  # Hashes correspond to the following packages:
  #  - SimpleITK-2.2.0-cp39-cp39-macosx_10_9_x86_64.whl
  #  - SimpleITK-2.2.0-cp39-cp39-macosx_11_0_arm64.whl
  #  - SimpleITK-2.2.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
  #  - SimpleITK-2.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  #  - SimpleITK-2.2.0-cp39-cp39-win_amd64.whl
  SimpleITK==2.2.0 --hash=sha256:160a5e2743ab16b1fe201766ec3aed9587a19dcce534953736d4af7a77216628 \
                   --hash=sha256:a712f4b205a0c2bbd9bfbefbe27f83ad892904f6cf9e165644dec0fb2320c508 \
                   --hash=sha256:dc82050f78bfed95af20683a10bb2a0caf8c3c798aa2ccd43099f338baa2ec55 \
                   --hash=sha256:ffaa51d88a75048bc759f6147c87695987914764ac411095f63c0d4ebde2365b \
                   --hash=sha256:b607f118b061744a7dcf656ccd93245029c312318df7fd88063356287784fbc8
  urllib3==1.26.12 --hash=sha256:b930dd878d5a8afb066a637fbb35144fe7901e3b209d1cd4f524bd0e9deee997
```

### CODE REVIEW

**Comment by jamesobutler** [comment]
I'm currently building and testing on Windows and will report back the results here once complete.

**Comment by jamesobutler** [comment]
My clean build on Windows was successful. When I ran tests the ones that are already failing on the [factory preview build](https://slicer.cdash.org/viewTest.php?onlyfailed&buildid=2830495) were the same ones that I observed. So everything looks good here on Windows.
```
1>The following tests FAILED:
1>	 36 - vtkMRMLDisplayableNodeTest1 (Failed)
1>	154 - vtkMRMLCameraDisplayableManagerTest1 (Failed)
1>	602 - py_nomainwindow_test_sitkUtils (Failed)
```

**Review by jcfr — APPROVED** [review]

**Comment by jcfr** [comment]
Remaining tasks:
* [ ] Check status of local linux build
* [ ] Review changelog associated with dicomweb-client (rational: minor update)
* [ ] Confirm that libraries shipped along side scipy and numpy remains compatible with targeted macOS version (10.13)
* [ ]

**Comment by jcfr** [comment]
The version `0.57` of dicomweb-client introduces the following breaking changes:

* Constructor of `DICOMfileClient` now accepts a URL with `file` scheme rather than a filesystem path
* Parameter `base_dir` of constructor of `DICOMfileClient` has been renamed to `url`
* Schema of SQLite database underlying `DICOMfileClient` has changed

Source: https://github.com/herrmannlab/dicomweb-client/releases/tag/v0.57.0

Since `DICOMfileClient` is not used in [Slicer](https://github.com/Slicer/Slicer), including the updates should not be an issue.

**Comment by jcfr** [comment]
Backward compatible changes introduced with the scipy version update from `1.8.1` to `1.9.2` are the following:
* https://docs.scipy.org/doc/scipy/release.1.9.0.html#deprecated-features
* https://docs.scipy.org/doc/scipy/release.1.9.0.html#expired-deprecations
* https://docs.scipy.org/doc/scipy/release.1.9.0.html#backwards-incompatible-changes

Since `scipy` is not directly use in Slicer core, we may have to update extensions to account for changes. If any, related issues will be tracked in https://github.com/Slicer/Slicer/issues/6587

**Comment by jcfr** [comment]
Additionally, on macOS, the dependent libraries shipped with scipy remain the same:

image

**Pull request merged**
