### PR TITLE
ENH: update ScalarVolumePlugin to not attempt loading DICOM SEG

### PR DESCRIPTION
**Pull request by fedorov**
DICOM Segmentation IOD cannot be loaded using any of the loaders included
in the core Slicer application. Do not attempt to load it and mislead the
user with the failure message. Log error to recommend the user should install
QuantitativeReporting extension that can properly handle this type of object.

For the reference, see discussion in https://discourse.slicer.org/t/segmentation-storage-1-2-840-10008-5-1-4-1-1-66-4/4274/12?u=fedorov.

### CODE REVIEW

**Comment by pieper** [comment]
Yes, makes sense to me. 👍

**Comment by fedorov** [comment]
Thank you Steve! Could you merge it? I lost my svn login credentials, and not sure how to recover (or whether it is worth the effort).

**Comment by jcfr** [comment]
@fedorov  I can also integrate if you would like. 

> I lost my svn login credentials, and not sure how to recover

You can provide your new credential here: https://www.kitware.com/Admin/SendPassword.cgi 
Add me as a reference

**Comment by fedorov** [comment]
> I can also integrate if you would like

Yes, please do - thank you!

> You can provide your new credential here

Do we have any specifics on the GitHub migration? Do you anticipate I will need those credentials for an extended period of time?

**Comment by cpinter** [comment]
Once we're at it - could we do the same for RT? We get lots of "Cannot load XY as scalar volume" error messages for RT as well.

**Comment by fedorov** [comment]
> could we do the same for RT

Absolutely - feel free to update the PR! 

But I do not know if it will be handled the same way. ScalarVolume gets confused by SEG, since SEG has PixelData. RT does not, so I would expect it not to be attempted for loading anyway already, with the standard plugins.

**Comment by cpinter** [comment]
Dose volumes do have pixel data. Once this is merged I'll create another PR

**Comment by jcfr** [comment]
> Do we have any specifics on the GitHub migration? Do you anticipate I will need those credentials for an extended period of time?

@fedorov Since the focus is currently on Python 3 transition, I anticipate we will be using `svn dcommit` a little longer.

**Comment by fedorov** [comment]
@jcfr Ok, thanks - I submitted the form.

**Comment by fedorov** [comment]
Would it be possible for one of the [3D Slicer benevolent dictators for life](https://slicer.readthedocs.io/en/latest/developer_guide/contributing.html#benevolent-dictators-for-life) to exercise their privilege and merge this PR? I am unable to do this. I requested SVN write access 3 days ago, but never heard back. This is a rather trivial fix that was reviewed and approved 7 days ago.

**Comment by jcfr** [comment]
I will take care of it now.

> I requested SVN write access 3 days ago

And will follow up on this.

**Comment by jcfr** [comment]
Integrated in [r27964](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=27964)

**Comment by fedorov** [comment]
Thanks a lot @jcfr!

**Pull request closed without merging**
