### PR TITLE
BUG: Fix Python site packages location detection.

### PR DESCRIPTION
**Pull request by thewtex**
This path is used to add WrapITK.pth so ITK's Python wrapping can be used from
the build tree.

The current code only works when Slicer_USE_ITKPython is turned ON with an
existing build tree. With a fresh build tree, Slicer's Python is not available
at the initial configure. This patch delays the site package path
detection to after ITK has been built, which is after Python has been built.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the patch.

In order to be able to create the ITKPython extension, we should either remove or make the installation in the `site-packages` optional adding an option.

Indeed, the ITKPython extension will simply run the CMake install command associated with the `<WRAP_ITK_INSTALL_COMPONENT_IDENTIFIER>Runtime`  (`<WRAP_ITK_INSTALL_COMPONENT_IDENTIFIER>RuntimeLibraries`) specifying where the the files should be installed.

If we would like to have the option to easily use ITKPython from a build tree, the files should be installed in directory different from `site-packages` and then ensure the Slicer launcher extend the `PYTHONPATH`. All the machinery is here to allow this.  To help me understand, could you copy here the content of the current `WrapITK.pth`.

**Comment by thewtex** [comment]
@jcfr Thanks fro the review.

I believe @vovythevov has a WIP patch for the installation.  To install the Python libraries into a different location than the site-packages location of the Python executable, the variable PY_SITE_PACKAGES_PATH passed into ITK could be set to something else, then PYTHONPATH given that directory.

The current WrapITK.pth Linux content is:

```
# Python pth file to add WrapITK's path to sys.path.
/home/matt/bin/Slicer-GCC-MinSizeRel/ITKv4-build/Wrapping/Generators/Python
/home/matt/bin/Slicer-GCC-MinSizeRel/ITKv4-build/lib
```

I see CTK ExternalProject, for example, is using `${proj}_PYTHONPATH_LAUNCHER_BUILD`. Should this be set to the location of WrapITK.pth?

**Comment by jcfr** [comment]
> `${proj}_PYTHONPATH_LAUNCHER_BUILD`. Should this be set to the location of `WrapITK.pth`

Yeahh.

> @vovythevov has a WIP patch for the installation.

Indeed, here is a recap of what we have / what we need:

### High level 

The Slicer Branch `ITKIPython` of @vovythevov [integrates all patches and tweaked](https://github.com/Slicer/Slicer/compare/master...vovythevov:ITKPython) so far:
 * it integrates all Slicer ITK wrapping changes so far.
 * if means that the commit from **this** PR (#402) is also included in @vovythevov branch.
 * it has its `External_ITKv4.cmake`:
  * updated to point to [vovythevov/ITK@slicer-v4.8.2-2015-11-2-42732c1-external-module-support](https://github.com/vovythevov/ITK/tree/slicer-v4.8.2-2015-11-2-42732c1-external-module-support)
  * which includes the [following changes](https://github.com/Slicer/ITK/compare/slicer-v4.8.2-2015-10-23-38095f7...vovythevov:slicer-v4.8.2-2015-11-2-42732c1-external-module-support) not yet integrated in the Slicer/ITK fork.

The current behaviour of the branch is the following:

1.  **build time**: thanks to the ITKv4 external project command `ITKv4_INSTALL_COMMAND`, `WrapITK.pth` will be installed into `site-packages` directory `/path/to/Slicer-SuperBuild/python-install/lib/python2.7/site-packages`

2. **install time**: thanks to the `WIPPPP` commit of @vovythevov (8da7542d73d9), python wrapping libraries and files associated with these components: 
 1. `${WRAP_ITK_INSTALL_COMPONENT_IDENTIFIER}Development`
 2. `${WRAP_ITK_INSTALL_COMPONENT_IDENTIFIER}Runtime` 
 3. `${WRAP_ITK_INSTALL_COMPONENT_IDENTIFIER}RuntimeLibraries` 

 will be install in the following relative directories:
  * `${PY_SITE_PACKAGES_PATH}`:
    * `itkConfig.py` 
    * `WrapITKBuildOptionsPython.py`
    * `${python_modules}`
    * `${WRAPPER_LIBRARY_NAME}.py`
  * `${PY_SITE_PACKAGES_PATH}/Configuration`:
    * `WrapITKBuildOptionsConfig.py`
    * `${WRAPPER_LIBRARY_NAME}Config.py` 
  * `${PY_SITE_PACKAGES_PATH}/itk`:
    * `${init_file}`
    * `${python_file}`

All the files listed above are associated with the component `Runtime` thanks to macro `WRAP_ITK_PYTHON_BINDINGS_INSTALL` defined [here](https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/Generators/Python/CMakeLists.txt#L62-L67).

## Next steps

* [ ] ITK: Associate files currently installed in `Configuration` to `Development`

* [ ] ITK: Rename macro `WRAP_ITK_INSTALL` to `WRAP_ITK_INSTALL_DEVELOPMENT` and change component to `Development`. See details below.

* [ ] Slicer: At build time, ITKPython files should be installed outside of `site-packages`. See `ITKv4_INSTALL_COMMAND`. It means that in `External_ITKv4.cmake`, `PY_SITE_PACKAGES_PATH` should be set to something like `${proj}-install-wrapping`. Consider setting a variable named `Slicer_ITK_PY_SITE_PACKAGES_PATH` to `${proj}-install-wrapping`.

 * [ ] Remove the code using `detect_site_packages_path.py` it is not needed for Slicer. 

* [ ] Slicer: In a build tree, the launcher settings should have a `PYTHONPATH` entry pointing to the location of `WrapITK.pth`. See `${proj}_PYTHONPATH_LAUNCHER_BUILD`. Consider using `Slicer_ITK_PY_SITE_PACKAGES_PATH` here.

* [ ] Slicer: Rename option `Slicer_USE_ITKPython` to `Slicer_BUILD_ITKPython`

* [ ] Slicer: Add a Slicer option named `Slicer_PACKAGE_ITKPython` (depending on `Slicer_BUILD_ITKPython`). If enabled, the ITK python files will be packages using the installed rules specified in the `WIPPPP` commit of @vovythevov (8da7542d73d9).



### More details / Discussion

* Variables `python_modules`, `init_file` and `python_file` will be set for each wrapped ITK modules (for example `ITKFilteringImageGrid`, ...). The variable `WRAPPER_LIBRARY_NAME` will contain the wrapped module name being installed.

* Questions for @thewtex: Generally, should we install files in ${PY_SITE_PACKAGES_PATH}/Configuration using component name `Runtime/RuntimeLibraries` ? Are these files only needed to build/wrap modules ?

* Macro `WRAP_ITK_INSTALL` defined [here](https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/ConfigureWrapping.cmake#L116-L121) is not used to install Python wrapping files:

```
$ ack -i "WRAP_ITK_INSTALL\("
Generators/SwigInterface/CMakeLists.txt
361:  WRAP_ITK_INSTALL("/Configuration/Typedefs" "${mdx_file}")
445:  WRAP_ITK_INSTALL("/Configuration/Typedefs/" "${idx_file}")

Generators/Doc/CMakeLists.txt
47:        WRAP_ITK_INSTALL(/Doc/man3 "${page}")

Generators/Tcl/CMakeLists.txt
24:  WRAP_ITK_INSTALL(/Configuration/Generators/Tcl CMakeLists.txt)
25:  WRAP_ITK_INSTALL(/Configuration/Generators/Tcl main_module_ext.i.in)
26:  WRAP_ITK_INSTALL(/Configuration/Generators/Tcl module_ext.i.in)
```
* Questions for @thewtex:

 * Currently the macro `` is associated with `Runtime` (`RuntimeLibraries` in your latest patch), should this be changed to `Development` ? It seems all the files (`SwigInterface`, `Doc`, `*.in`) are needed only to develop ITK modules supporting wrapping.
 * May the macro could be renamed to `WRAP_ITK_INSTALL_DEVELOPMENT` ?

* Macro `WRAP_ITK_BINDINGS_INSTALL` defined [here](https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/ConfigureWrapping.cmake#L127-L132) is not used for Python wrapping either:

```
$ ack -i "WRAP_ITK_BINDINGS_INSTALL\("
Generators/Tcl/CMakeLists.txt
111:  WRAP_ITK_BINDINGS_INSTALL("/Tcl" "${tcl_file}")
350:    WRAP_ITK_BINDINGS_INSTALL(/Tcl "${ITK_WRAP_TCL_BINARY_DIR}/InstallOnly/itkwish_wont_find_me_here/pkgIndex.tcl")

Generators/Java/CMakeLists.txt
222:    WRAP_ITK_BINDINGS_INSTALL(/Java ${java_jar_file_path})
```

* The latest patch of @thewtex not yet integrated in the Slicer/ITK fork remove the need to deal with the `Runtime` component to install wrapping. Instead all runtime support files will be associated with `RuntimeLibraries` component. See [here](http://review.source.kitware.com/#/c/20346/1..2/Wrapping/ConfigureWrapping.cmake), [here](http://review.source.kitware.com/#/c/20346/1..2/Wrapping/Generators/Explicit/CMakeLists.txt), [here](http://review.source.kitware.com/#/c/20346/1..2/Wrapping/Generators/Python/CMakeLists.txt) and [here](http://review.source.kitware.com/#/c/20346/1..2/Wrapping/Generators/Tcl/CMakeLists.txt)

**Comment by thewtex** [comment]
@jcfr Thanks for the great outline!


All SwigInterface *.i, *.in development files should be removed in this patch:

  http://review.source.kitware.com/#/c/20333/

The .mdx and .idx files are needed at runtime. These files define content and dependencies between the different wrapping modules. They could be used by all the wrapping languages, so they are installed into Configuration/Typedefs.

The Doc, Tcl, Java Generators are currently are not functional, but they may be moved to a per-language package location, too when functional.  I will check to see if these Tcl WRAP_ITK_INSTALL calls should be removed in http://review.source.kitware.com/#/c/20333.

So, the first and second check boxes should not be necessary.


A clarification on the install layout: the _${WRAPPER_LIBRARY_NAME}.py and ${WRAPPER_LIBRARY_NAME}.so files should be installed into the itk/ package.


I will start working on the forth check box -- set up the build PYTHONPATH configuration.


Thanks!

**Comment by jcfr** [comment]
> the first and second check boxes should not be necessary.

All set. Box checked.

> The .mdx and .idx files are needed at runtime

Makes sense. How does the python modules find these files. Is it by relative location ? 

>  `_${WRAPPER_LIBRARY_NAME}.py` and `${WRAPPER_LIBRARY_NAME}.so` files should be installed into the `itk/`

Good point. It is indeed the case for the libraries (*.so). See [here](https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/Generators/Python/CMakeLists.txt#L439-L442)

That said, it seems it is not case for:

* `${python_modules}` . See [here](https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/Generators/Python/CMakeLists.txt#L206)

* `${WRAPPER_LIBRARY_NAME}.py`. See [here](https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/Generators/Python/CMakeLists.txt#L378)

Should these also be installed to `${PY_SITE_PACKAGES_PATH}/itk` ?


> I will start working on the forth check box -- set up the build PYTHONPATH configuration.

Great

**Comment by thewtex** [comment]
On Sat, Nov 7, 2015 at 3:52 PM, Jean-Christophe Fillion-Robin <
notifications@github.com> wrote:

> the first and second check boxes should not be necessary.
>
> All set. Box checked.
>
Thanks!


> The .mdx and .idx files are needed at runtime
>
> Makes sense. How does the python modules find these files. Is it by
> relative location ?
>

The loading functionality is implemented in itkBase.py:


https://github.com/InsightSoftwareConsortium/ITK/blob/f7575d8836277ac532f1ec425821531e2de242fe/Wrapping/Generators/Python/itkBase.py

This in turn depends on paths defined in itkConfig.py:


https://github.com/InsightSoftwareConsortium/ITK/blob/f7575d8836277ac532f1ec425821531e2de242fe/Wrapping/Generators/Python/itkConfig.py.in

I will do some further testing to ensure that these work with the install
tree location.



> _${WRAPPER_LIBRARY_NAME}.py and ${WRAPPER_LIBRARY_NAME}.so files should
> be installed into the itk/
>
> Good point. It is indeed the case for the libraries (*.so). See here
> <https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/Generators/Python/CMakeLists.txt#L439-L442>
>
> That said, it seems it is not case for:
>
>    -
>
>    ${python_modules} . See here
>    <https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/Generators/Python/CMakeLists.txt#L206>
>    -
>
>    ${WRAPPER_LIBRARY_NAME}.py. See here
>    <https://github.com/vovythevov/ITK/blob/bc77835d68ee71b286dacd28fe0272e4ff626233/Wrapping/Generators/Python/CMakeLists.txt#L378>
>
> Should these also be installed to ${PY_SITE_PACKAGES_PATH}/itk ?
>
The modules could be directly be loaded by importing these modules directly
per the comments here:


https://github.com/InsightSoftwareConsortium/ITK/blob/f7575d8836277ac532f1ec425821531e2de242fe/Wrapping/Generators/Python/CMakeLists.txt#L383-L385

Given that there are so many modules, though, we may want to remove this
feature.  Then again, this will break backwards compatibility.  I will
discuss more in the Gerrit change.





> I will start working on the forth check box -- set up the build PYTHONPATH
> configuration.
>
> Great
>
I will update this pull request when it is ready...

**Comment by thewtex** [comment]
@vovythevov Yes, good catch. I suspect that it still should work, though, but 'import itk' does not succeed.  @jcfr Any ideas?

**Comment by thewtex** [comment]
I have discovered `--launcher-dump-environment`, and I see some ITK paths -- will investigate further...

**Comment by thewtex** [comment]
@vovythevov @jcfr The latest pushed patch, which uses PYTHONPATH in the launcher, works with Linux!

**Comment by vovythevov** [comment]
@jcrf, @matt I updated my branches to use http://review.source.kitware.com/#/c/20346/ and the above change: 90f299c and will try to build with that.

**Comment by jcfr** [comment]
@vovythevov  Thanks

The changes to ITK have been integrated to the Slicer/ITK fork. See [r24716](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24716)

Remaining steps are the finalization of this pull request (#402) to confirm the installation outside and within Slicer package works.

Great team work :smile:

**Comment by jcfr** [comment]
Latest topic here: https://github.com/jcfr/Slicer/tree/2015-11-10-ITKPython

Still need to include http://review.source.kitware.com/#/c/20380/

**Comment by thewtex** [comment]
This branch:

  https://github.com/jcfr/Slicer/tree/2015-11-10-ITKPython

looks good to me.

Following integration, and updates to ITK, I will rebase this branch:

  https://github.com/thewtex/Slicer/tree/ITKPython

This branch adds ITKVtkGlue support to Slicer, which is very important for ITK use in Slicer for both C++ and Python.

**Comment by jcfr** [comment]
Topic `2015-11-10-ITKPython` has been integrated in [r24892](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24892) -> [r24895](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24895) :fireworks:

**Comment by thewtex** [comment]
Thanks!

**Pull request closed without merging**
