### PR TITLE
ENH: Fix 3943 and other enhancements for slice view annotaitons

### PR DESCRIPTION
**Pull request by mehrtash**
* Fixed #3943 [1] by replacing DICOM study date and study time with series date and series time.
* Moved slice view annotations settings gear from Data Probe small widget (main  screen) to the Data probe module in order to preserve more screen real estate for the module uis.
* Fixed problem with color scalarbar range labels.
* Added an option to change format of color scalarbar range label and save the user settings in application settings.
* Change ruler text font size and family according to other text annotations.

[1] http://na-mic.org/Mantis/view.php?id=3943

### CODE REVIEW

**Comment by fedorov** [comment]
Excellent, thanks a lot Alireza!

**Comment by jcfr** [comment]
I rebased the topic and also added a fix for the `py_nomainwindow_qSlicerDataProbeModuleGenericTest`. See https://github.com/jcfr/Slicer/compare/3943-update-slice-view-annotations

That said, there are some issue with the gear push button integrated in the DataProbe. It is not clickable and located at the wrong location. It is possible and I didn't resolve the conflict adequately when rebasing.

@mehrtash Would be great if you could have a look.

 See screenshot below. 

3943-update-slice-view-annotations_issue_with_pushbutton

**Comment by fedorov** [comment]
I think the idea was that this gear button should have disappeared. Is this right Alireza?

**Comment by mehrtash** [comment]
Yes, It would only show up in the data probe module located at the
menu>modules>....

**Comment by jcfr** [comment]
I most likely screw something while rebasing. 

@mehrtash  Would appreciate if you could you check ?  Thanks

**Comment by mehrtash** [comment]
Sure. Thanks for reviewing. I'll check it and will get back to you.

**Comment by jcfr** [comment]
Waiting a the topic is rebased, I am closing this PR.

**Comment by jcfr** [comment]
As a side note, a convenience enum has now been added to `vtkCornerAnnotation`. 

From python, it is now possible to use:
* `vtkCornerAnnotation.UpperLeft`
* `vtkCornerAnnotation.UpperRight`
* `vtkCornerAnnotation.LowerLeft`
* `vtkCornerAnnotation.LowerRight`

See Slicer/VTK@923c48ab40e44a8d63af52637e76033b810935db

**Comment by fedorov** [comment]
@mehrtash can you confirm you are working on the updated pull request?

**Comment by mehrtash** [comment]
Yes, I will make a new pull request soon.

Alireza

**Comment by mehrtash** [comment]
New pull request: https://github.com/Slicer/Slicer/pull/235

**Pull request closed without merging**
