### PR TITLE
STYLE: Simplify Main.cxx introducing (pre|post)InitializeApplication function

### PR DESCRIPTION
**Pull request by jcfr**
This allows to remove duplicated code from Slicer-based application and
streamline the associated maintenance.

### CODE REVIEW

**Comment by jcfr** [comment]
Since both style and main window are instantiated instantiated in the
methods at different time , this is why. There are also independent
objects.

I will look at the python issue.

**Comment by lassoan** [comment]
It is just highly unusual to sneak in a constructor by using a templated method to create an object inside. Normally you just create the object outside and pass it to the method as an argument.

**Comment by jcfr** [comment]
Agreed and thanks for the review. I am updating the approach.

**Comment by jcfr** [comment]
> Why can't we create the object outside and pass it to the method as an argument?

The rational was to create the object only when needed. 

This means that when Slicer is executed with `--no-main-window`, or any other command that do not required the main windows (eg `--help`, ...), it is not instantiated.

Since the Style is lightweight, I moved it as parameter.

I will investigate if there is an overhead of always creating the main window even if not needed

**Comment by lassoan** [comment]
Thank you, it looks good.

**Comment by jcfr** [comment]
Closing. Integrated in [r26964](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26964) and [r26965](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26965)

**Pull request closed without merging**
