### PR TITLE
ENH: Add interactive slice intersections widget

### PR DESCRIPTION
**Pull request by cpinter**
If "Interaction" flag is enabled then slice intersections can be drag-and-dropped in slice views.

Re #5544

Co-authored-by: Andras Lasso <lasso@queensu.ca>
Co-authored-by: Csaba Pinter <pinter.csaba@gmail.com>

Continuation of https://github.com/Slicer/Slicer/pull/6008

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
I'm finished with the updates and it seems to work now. Please test.

**Comment by cpinter** [comment]
Thanks a lot @lassoan . Building now.

**Comment by cpinter** [comment]
@lassoan It seems to work fine with all the use cases and combinations I'm aware of. Thank you so much for your work on this!

**Comment by cpinter** [comment]
Thank you for the merge!

**Pull request merged**
