### PR TITLE
DOC: Fix typo in `License.txt`

### PR DESCRIPTION
**Pull request by RafaelPalomar**
This fixes a small typo on the `License.txt` file. This closes Slicer/Slicer#7056

### CODE REVIEW

**Comment by jcfr** [comment]
For reference, here are the prior updates to the license:
* https://github.com/Slicer/Slicer/commits/main/License.txt

**Comment by jcfr** [comment]
To avoid updating the license file, it was included to the list of file to ignore in `.github/workflows/codespell.yml`. 

That said, I don't see any reason for not moving forward. Historically we have fixed typo. See  https://github.com/Slicer/Slicer/commit/ced0ab6d84996f5f802d4cd7b36b334c8083f676

If we move forward with this, the following file will  have to be updated:

https://github.com/Slicer/Slicer/blob/d1385c51350f9565cec8e3b12fc08ba05bc473c1/.github/workflows/codespell.yml#L15

cc: @lassoan @pieper

**Review by jcfr — APPROVED** [review]

**Comment by jcfr** [comment]
I also suggest to add the following at the end of the commit message:

```
Co-authored-by: luzpaz <luzpaz@users.noreply.github.com>
```

**Review by jcfr — CHANGES_REQUESTED** [review]
Consider adding missing `Co-authored-by: `

**Comment by lassoan** [comment]
This is a trivial typo, so I don't see any potential issue with changing the license file to fix this.

**Pull request merged**
